### ISSUE TITLE
ngx-translate is not working  in *ngfor

### ISSUE THREAD

**Issue by kumaresan-subramani** [ngx-translate/core#1011]
## Current behavior
ngx-translate is not working in ng-for

## Expected behavior
it has to work

## Minimal reproduction of the problem with instructions
if i use like below it won't work:

`<e-column *ngFor="let a of array"
        field="ImplantationDate"
        headerText="{{ a | translate }}">
      </e-column>`
where arry valyue is
array = ['one,'two,'three'];

**but if i use one value it is working fine**
`<e-column
        field="ImplantationDate"
        headerText="{{ a | translate}}">
      </e-column>`

## sample
  download this sample and run below commands

1. npm i
2. ng serve

sample:  [http://www.syncfusion.com/downloads/support/directtrac/general/ze/SAMPLE_FOR_SYNCFUSION-1886628965](http://www.syncfusion.com/downloads/support/directtrac/general/ze/SAMPLE_FOR_SYNCFUSION-1886628965)

## Environment

"@ngx-translate/core": "10.0.1",
 "@ngx-translate/http-loader": "3.0.1",
"ngx-bootstrap": "2.0.5",
 "ngx-infinite-scroll": "6.0.0",
Angular version: 6.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kumaresan-subramani** [comment]
Hi 
Any update on this?

**Comment by kumaresan-subramani** [comment]
Hello,
is there anybody working on this organization????

**Comment by insomnia1337** [comment]
bump
