### ISSUE TITLE
I can not install the ngx-translate/core, here is my error message. Any one could you pls help out?

### ISSUE THREAD

**Issue by chenheng0910** [ngx-translate/core#1029]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@ngx-translate/core@11.x',
1 verbose cli   '--save' ]
2 info using npm@6.7.0
3 info using node@v10.15.0
4 verbose npm-session 0ea176e0740b966d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.npmjs.com/package/@ngx-translate/core 170ms (from cache)
8 silly fetchPackageMetaData error for @ngx-translate/core@11.x Unexpected token < in JSON at position 1 while parsing near '
8 silly fetchPackageMetaData <!doctype html>
8 silly fetchPackageMetaData <htm...'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 2152ms
11 verbose stack SyntaxError: Unexpected token < in JSON at position 1 while parsing near '
11 verbose stack <!doctype html>
11 verbose stack <htm...'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose cwd /Users/chenheng/thaiLandProject-DRC
13 verbose Darwin 18.2.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@ngx-translate/core@11.x" "--save"
15 verbose node v10.15.0
16 verbose npm  v6.7.0
17 error Unexpected token < in JSON at position 1 while parsing near '
17 error <!doctype html>
17 error <htm...'
18 verbose exit [ 1, true ]

**Comment by tashoecraft** [comment]
There is so little info here to actually help you, if you could create a fresh project in stackblitz that replicates then some assistance could be provided. My guess is you haven't set something up correctly regarding versions between npm/node/angular/ngx-translate, or something about this line
```
or Unexpected token < in JSON at position 1 while parsing near
```
Something is trying to reference a json file and it's getting an html file, which will error for obvious reasons. I don't believe this has anything to do with ngx-translate, consider checking with stackoverflow.
