### ISSUE TITLE
Need to import it in every component?

### ISSUE THREAD

**Issue by Civile** [ngx-translate/core#1047]
I'm pretty new to angular 2. I find it boring to have to import the translate service into each component where i use it (almost everywhere). There is a way to import the TranslateService only once and make it usable for every components?

I mean this
`import {TranslateService} from '@ngx-translate/core';`

**Comment by Civile** [comment]
Solved it just using the pipe (it wasn't working before)

**Comment by Kiokol** [comment]
Can you explain more?

**Comment by Civile** [comment]
You should create an angular pipe and import that pipe it into a shared module
