### ISSUE TITLE
Support Angular 8

### ISSUE THREAD

**Issue by launcelot66** [ngx-translate/core#1084]
in v8 core-js was removed as i saw, so can u remove it from package.json dependencies?
after migrate my project (big) maby will see something else

**Comment by ocombe** [comment]
The only peer dependencies are "@angular/core": ">=7.0.0" and "rxjs": ">=6.3.0", core-js is only used for testing and building the library, but is not required to use it.
Since the version required for Angular is ">=7.0.0", it should work with v8 as well

**Comment by paddyfink** [comment]
currently the library is not working with angular 8. Is there any workarounds other than downgrading angular?

**Comment by ocombe** [comment]
@paddyfink it is working with v8, see: https://stackblitz.com/edit/github-47bavg?file=package.json

**Comment by ocombe** [comment]
Yes that's because of how semver works, `>=7.0.0` will work with `9.0.0` but not `9.0.0-next.3`, you can try it here: https://semver.npmjs.com/
