### ISSUE TITLE
IMPORTANT: Unable to guarantee load of translations before initialisation of app

### ISSUE THREAD

**Issue by jpike88** [ngx-translate/core#1086]
```
const providers: Provider[] = [
	{ provide: APP_INITIALIZER, useFactory: initialise, deps: [TranslateService], multi: true }
];

function initialise(translate: TranslateService) {
     return async () => {
           await translate.setDefaultLang('en-AU');
	  await translate.use('en-AU');
     }
}
```

But when my first component loads, I see some calls using ```instant``` that aren't being translated. I know they work that way, but why aren't my translations being loaded in my APP_INITIALIZER call? I'm awaiting them, shouldn't this work?

**Comment by matte00** [comment]
Me too. Any ideas? Is there an event when translation file is loaded from http backend?

**Comment by jpike88** [comment]
the trick is this:

```

export function initialise(translate: TranslateService) {
	return async () => {
		return new Promise(resolve => {
			translate.onLangChange.subscribe(() => {
				resolve();
			});
		});
	};
}


const providers: Provider[] = [
	{ provide: APP_INITIALIZER, useFactory: initialise, deps: [TranslateService], multi: true }
];
```

Poor design IMO, but that's how it works

**Comment by biesbjerg** [comment]
I haven't tested this, but `setDefaultLang()` returns `void` and not a promise and `use()` returns an `Observable`, so I think you'd need to convert that to a promise first.

Try something along the lines of this:

```typescript
import { from } 'rxjs';

export function loadTranslations(translateService: TranslateService) {
	return () => from(translateService.use('en-AU));
}

const providers: Provider[] = [
	{ provide: APP_INITIALIZER, useFactory: loadTranslations, deps: [TranslateService], multi: true }
];
```

**Comment by jpike88** [comment]
whoops, amended my last comment with a bit more code... there's loads more happening there, I cut out too much.

I found translate.onLangChange was the only way I could guarantee that the language was loaded, it seems to work with that arrangement
