### ISSUE TITLE
Upgrade to Angular 8

### ISSUE THREAD

**Issue by riede** [ngx-translate/core#1104]
At the moment ngx-translate does not support Angular 8 offically. Please upgrade the package.

**Comment by ocombe** [comment]
It works fine with v8. What do you mean by does not support v8 officially?

**Comment by riede** [comment]
In the documentation there is no hint that it works with Angular 8 and the package.json refers also to Angular 7 dependencies. 

That’s why I created this issue.

**Comment by ocombe** [comment]
The package.json says ">= 7" which includes v8
I'll update the readme
