### ISSUE TITLE
interpolation string in translation key does not work

### ISSUE THREAD

**Issue by smasam** [ngx-translate/core#1108]
Hi,

I want to maintain translation key as descriptive text where the translation key and translation value will be same strings in english as this
{
 "Hi! how are you" : "Hi! how are you"
}

but looks like the text is not getting translated if it has interpolation this way

<span>{{ 'Hello {{ name }}' | translate: { name: 'Srinivas' } }}</span>
Since there is interpolation string {{name}} I have to escape this inorder for this to work
this way
`<span>{{ 'Hello \{\{ name \}\}' | translate: { name: 'Srinivas' } }}</span>`, but this causes the key to have escape string, when searching for issue in ngx-translate I found a similar issue which was already resolved, so I tried implementing that but still it does not work

https://github.com/ngx-translate/core/issues/707

I changed the tempalte string to 

<span>{{ 'Hello { name }' | translate: { name: 'Kim' } }}</span>

expecting the key and value in the en.json locale bundle to be of following form

{
"Hello { name }" : "Hello { name }"
}
but even this does not work, I change the value to double curly braces it works, but thats not expected as the translations team is expected to look at the key and perform translation, which mean they would use single open and close brace same as the key in the translated text.

**Comment by dsnoeck** [comment]
Hi @smasam,
I have the same setup as you, so if you provide a working plunkr I could help.
In the meantime, make sure that this translation is part of what is returned by your `TranslateLoader`.

To work around this issue, I'm also trying to develop a custom `MissingTranslationHandler`. So it will also work by default, when no translation have been created.

**Comment by dsnoeck** [comment]
So, if you want to have translation with parameters working if no translation is provided for the default language, you can implement this `MissingTranslationHandler`:
See: https://github.com/ngx-translate/core/blob/master/README.md#how-to-handle-missing-translations

Basically, I have copy past the `TranslateDefaultParser` and just update the regex to match placeholder in `{}` instead of `{{}}`
```
import { MissingTranslationHandler, MissingTranslationHandlerParams, TranslateParser } from '@ngx-translate/core';

export class MyMissingTranslationHandler implements MissingTranslationHandler {
  templateMatcher: RegExp = /{\s?([^{}\s]*)\s?}/g;

  constructor(private translateParser: TranslateParser) {}

  handle(params: MissingTranslationHandlerParams) {
    return this.translateParser.interpolate((param) => {
      return params.key.replace(this.templateMatcher, (substring: string, b: string) => {
        const r = this.translateParser.getValue(param, b);
        return (typeof r !== 'undefined' && r !== null) ? r : substring;
      });
    }, params.interpolateParams);
  }
}

```

**Comment by ocombe** [comment]
you could just do something like that: `{{ 'Hello ' + name | translate: { name: 'Srinivas' } }}` and it should work just fine
