### ISSUE TITLE
how to  translate in ts file

### ISSUE THREAD

**Issue by vrushabh583** [ngx-translate/core#1110]
tree.component.html:
 
*ngIf="node.SpaceType !== 'building' && node.SpaceType !== 'portfolio' && node.SpaceType !== 'meter' && node.SpaceType !== 'facility' && node.SpaceType !== 'floor' && node.SpaceType !== 'points'  else test">{{'abc.'+ node?.Name|translate}}</span> 
<ng-template #test>{{node?.Name}}</ng-template>
<span *ngIf="node.SpaceType === 'points'" class="point-gripper-icon"></span>
 </span>

In html file I have applied for ngif to translate which is translating  but I want to write a translate code in ts file and use that in html. How can I ???

i have a two conditions ..                                                                                                                        1) i want to translate when commodity == 'Weather' or 'electricity' or 'steam'.                                    2) i want to translate when spacetype !== 'building' or 'portfolio' or 'meter' or 'points'

**Comment by DenisSemionov** [comment]
This should be on stackoverflow, not in this repository, I suggest you to close this.
