### ISSUE TITLE
High CPU usage when I use the ngx-translate.

### ISSUE THREAD

**Issue by rassokhina-e** [ngx-translate/core#1134]
I have noticed something on my laptop on Chrome over the past few days where a tab starts taking up more CPU if I leave it open for a while. I use ngx-translate. The task manager showed that tab taking up most of the CPU. When I closed the tab, it stopped. For example it 30% the CPU usage, but when I try to turn off the ngx-translate library I see 5% the CPU usage. How I can reduce the CPU usage and continue to use the ngx-translate?

**Comment by PsychoPflanze** [comment]
Can you reproduce that? The issue might come from change detection and etc.

**Comment by rassokhina-e** [comment]
Yes, sure. I’ve done the record for profiling the page for good understanding performance. I've gone through an analyze the results and tried to measure how poor the page's performance and tried to figure out causes. Below an FPS chart, I see the CPU chart. The colors in the CPU chart correspond to the colors in the Summary tab, so the first color is yellow - the scripting process, the second is grey - the system process, and the Idle process. The fact that the CPU chart is full of color means that the CPU was maxed out during the recording. We see repeating tasks every 4 milliseconds but If we research any yellow task separately we will see the main processes as a reaction of `detectChanges` on translation the page. If go deep to the root of the issue I see functions from the `TranslateDirective` such as `ngAfterViewChecked` and the `checkNodes` function which works every 4 milliseconds. So the following functions which work after that are `updateValue` , `getValue`, `setContent`, etc. It gives the pressure on CPU usage.
<img width="1680" alt="1" src="https://user-images.githubusercontent.com/31901584/67459190-a64e4d00-f640-11e9-94f7-2d52ad2532bc.png">
<img width="502" alt="2" src="https://user-images.githubusercontent.com/31901584/67459230-bbc37700-f640-11e9-8c4b-313638ef59b2.png">
<img width="1025" alt="3" src="https://user-images.githubusercontent.com/31901584/67459480-5ae86e80-f641-11e9-834d-5b432f8d3fba.png">
![4](https://user-images.githubusercontent.com/31901584/67459498-620f7c80-f641-11e9-9643-83a508b6f2d4.jpeg)

**Comment by PsychoPflanze** [comment]
This makes total sense, everytime change detection is run it also needs to check the translation. Why is it that it runs change detection so often though? As far as i know, ngx-translate does not trigger change detection, unless you are executing `translate.use` (Are you maybe executing `translate.use` a lot?). Try using onPush change detection or see why your change detection is run so often. Also, check your 100 warnings you have :D

**Comment by PsychoPflanze** [comment]
This is a fully translated page, and change detection is run maybe a few times. You may be causing a lot of change detection in your code.
![Screenshot_1](https://user-images.githubusercontent.com/15183853/67485957-605aae80-f66b-11e9-964a-171a218be7fe.png)

**Comment by rassokhina-e** [comment]
Hey:D Also you noticed about ChangeDetectionStrategy.OnPush but I have several subscribers, which required time for starting my project, so I can't use OnPush. But in images above, I show a lot of tasks that were created by Angular for the `ngx-translate` lib. Currently, this is a mystery to me.

**Comment by PsychoPflanze** [comment]
The tasks created for ngx-translate are only created because change detection is run. You can see that by looking at a clean project on stackblitz. ngx-translate will not translate existing elements unless change detection is run. Your performance issues come from the fact that change detection is run a lot

**Comment by PsychoPflanze** [comment]
As you can see, the task flow is from top to bottom, meaning the top task causes the tasks below to be run. And ngx-translate is at the far bottom meaning something else is causing ngx-translate to run. Or to say it better, something is causing change detection to be run, which then runs ngx-translate

**Comment by rassokhina-e** [comment]
Thanks, man! I'll try to check.
