### ISSUE TITLE
Warning: requires a peer of @angular/core@>=7.0.0 on Angular 9.0.0-rc.1

### ISSUE THREAD

**Issue by dorje42** [ngx-translate/core#1140]
I use Angular 9.0.0-rc.1 and get this warnings, if I install ngx-translate/core:

`npm WARN @ngx-translate/core@11.0.1 requires a peer of @angular/core@>=7.0.0 but none is installed. You must install peer dependencies yourself.
`

**Comment by greenchapter** [comment]
I got the some problems with `ng update` on a project with angular version `8.2.14`. I think some should lift `ngx-translate`

**Comment by ocombe** [comment]
It's only an issue until the final release: npm doesn't consider beta/rc versions as valid semver numbers, that's why it's issuing a warning for the peer dependency.
Only v9.0.0 gets released, everything will be fine.

**Comment by greenchapter** [comment]
ehm @ocombe no, that's not the right solution to wait for `v9.0.0`. The right way is do define the right peer decencies.

See your `package.json` 

```
  "peerDependencies": {
    "@angular/core": ">=7.0.0",
    "rxjs": ">=6.3.0"
  }
```
Why are you go on Version `v7.0.0` and not to `v8.2.14`?

**Comment by ocombe** [comment]
Because it works with v7, why change it?! Using 8.2.4 wouldn't fix the peer dependency issue with v9 rc
