### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by dankerk** [ngx-translate/core#1150]
Hi there,

Will you be upgrading/supporting Angular 9 or is this project kinda dead (last release was a year ago)?
If so, is there a  timeline for it?
Thanks a lot!

**Comment by ocombe** [comment]
Hello, yes there will be a new release for v9. It should be around the release of Angular v9 (early January).

**Comment by dankerk** [comment]
That's good to hear, thanks.

**Comment by RogierKonings** [comment]
Angular 9 has been released, but no new version of ngx-translate. Do you know the timelines?

**Comment by ocombe** [comment]
Well I've released v12 a week ago (and a few patches since then), it's currently at 12.1.1: https://github.com/ngx-translate/core/releases
