### ISSUE TITLE
ngx-translate在ts中中英文切换不了？

### ISSUE THREAD

**Issue by Faine-LHL** [ngx-translate/core#1158]
具体情况如下：```this.name = this.translate.instant('TimeoutLogoutTips')```
页面加载时将国际化赋给一个变量，通过ngx-translate国际化时，在html中通过管道的方式能够正常国际化，在ts中就是不行？？？
网上有说通过全局监听语言变化事件来处理，但是代价太大
`this.translate.onLangChange.subscribe((event: TranslationChangeEvent) => {
      this.name = this.translate.instant('TimeoutLogoutTips')
      console.log(this.name)
    })`
请问道友们有什么好的处理方式吗，在线等

**Comment by ocombe** [comment]
Sorry I don't speak Chinese, can you translate your post in english please?

**Comment by Faine-LHL** [comment]
When you click to switch between Chinese and English, NGX translate can switch normally in HTML, but in TS, the page must be refreshed before switching.
The cost of modification is too high if the following methods are adopted:
`this.translate.onLangChange.subscribe((event: TranslationChangeEvent) => { 
      this.name = this.translate.instant('TimeoutLogoutTips') 
      console.log(this.name) 
})`
Is there any good solution in TS？
