### ISSUE TITLE
Installation of @ngx-translate/core also installs “semantic-release” (since version 12.1.0)

### ISSUE THREAD

**Issue by voorproever** [ngx-translate/core#1171]
## Current behavior

The `@ngx-translate/core` package seems to depend on `semantic-release` since v12.1.0:

  * https://www.npmjs.com/package/@ngx-translate/core/v/12.1.0?activeTab=dependencies
  * https://www.npmjs.com/package/@ngx-translate/core/v/12.0.0?activeTab=dependencies

## Expected behavior

No installation of `semantic-release` since it’s a `devDependency`.

## Minimal reproduction of the problem with instructions

```
npm install @ngx-translate/core
less package-lock.json
```

**Comment by ocombe** [comment]
Thanks, good catch! It'll be fixed in the next version (I won't release a new version just for that)

**Comment by ViceIce** [comment]
Shouldn't it be a dependency on the root package.json?

**Comment by ViceIce** [comment]
or install wirhout adding to package.json at all?

btw: latest [semantic-release](https://www.npmjs.com/package/semantic-release) is **v17.0.3** and you are using **v8.2.3**

**Comment by ocombe** [comment]
As long as it works, I'm reluctant to change the setup since it does
releases automatically and it works fine 😁

**Comment by nicolashenry** [comment]
@ocombe Is it released? I still have it installed with @ngx-translate/core 12.1.1 : 
![image](https://user-images.githubusercontent.com/139160/75351158-f451b680-58a7-11ea-98f3-e7e6f759c8ca.png)

**Comment by demisx** [comment]
Same issue here. The latest version still installs `semantic-release@8.2.3` and generates warnings in Angular 9 when the latter tries to compile all npm dependencies as esm2015. Please remove it from the dependencies, since it's not a requirement to run your app code.

**Comment by ocombe** [comment]
Can you try 12.1.2 please? Hopefully it should be fixed for good now

**Comment by nicolashenry** [comment]
Seems fixed, thanks!

**Comment by demisx** [comment]
Yep, it's fixed. Thank you @ocombe 🙏
