### ISSUE TITLE
always adds a white space at the beginning

### ISSUE THREAD

**Issue by Sunny41** [ngx-translate/core#1206]
I am developing a multi language app with Ionic 4 and recently upgraded to Ionic 5 which doesn't make any difference to the behaviour of the plugin.

The texts are being translated and the plugin overall works fine but there is one thing that grinds my gears. the plugin always adds a white space infront of the text. I haven't any whitespaces in the html nor in the tranlsation .json...

{{'Hello' | translate}} translates to " Hallo".

This happens on all platforms and with ionic serve in the browser (tried chrome and firefox, which is obsolete since I want to deploy on android and ios).

I hope you have a guess what it could be. :)

ionic info: 
   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.0
   @angular-devkit/schematics    : 9.1.0
   @angular/cli                  : 9.1.0
   @ionic/angular-toolkit        : 2.0.0

plugin version: 
      "@ngx-translate/core": "^11.0.1",
      "@ngx-translate/http-loader": "^4.0.0"

**Comment by Sunny41** [comment]
Ok I found the issue. The Compiler diesn't recognize the indent of the html row. 
```<div class="intro">{{'Hello'|translate}}</div>```
translates perfectly.
Otherwise 
```
<div class="intro">
    {{'User.card.intro'|translate}}
</div>
```
doesn't. 
And this only works if the translated text is in a <div> inside <ion-content>

**Comment by exitlol** [comment]
This is a big issues since youcan have rules defined regarding line-length and auto formatting.
I am facing this issue now, that everyones' auto fromat breaks some translations since not every label is equally long.

This leads to the error described by @Sunny41 This needs some fix because you cannot format template differently for each translated line.
