### ISSUE TITLE
.po files loader linked in readme.md is unmantained

### ISSUE THREAD

**Issue by UnGaucho** [ngx-translate/core#1221]
Seems that [the po loader](https://github.com/biesbjerg/ngx-translate-po-http-loader/issues/22) linked in the readme has gone unmantained for a while. 

It's missing critical updates and has pull requests that have been pending for a while.

There is a fork currently mantained
https://github.com/fjnr-inc/ngx-translate-po-http-loader

Would a pull request be welcome so that we can update the readme?

**Comment by ocombe** [comment]
yes, that would be great, thanks
