### ISSUE TITLE
typesafe translation file 

### ISSUE THREAD

**Issue by georgy-alarcon** [ngx-translate/core#1223]
Hi, it's my first time with ngx-translate.
someone know a method to type-safe the translation file?

i work in a project and use ngx-translate for the internalization.

Example 

**Html**
```
<div>{{car.model | translate}}</div>
or
<div translate>car.model</div>
``` 
en.json

```
{
  "car":  {
       "model": "xxxx"
  }
}
```

there are anyway to have a warming or error if i write `car.mod` instead `car.model` ? 

exist a method to resolve this problem? or there are best practices to reduce this problem? 

what should I do? if the project become bigger and also the path to arrive at the translation, because it becomes easier to make mistake.

**Comment by parloti** [comment]
Hello, @georgy99 I may have an answer to your question, but questions are best asked at https://stackoverflow.com/ with the following tag: typescript, ngx-translate.
