### ISSUE TITLE
Add compatibility with Angular 10

### ISSUE THREAD

**Issue by PapaNappa** [ngx-translate/core#1225]
## Current behavior
When updating an Angular 9 application to Angular 10 (`ng update @angular/core @angular/cli`), the following error message appears:

```
                  Package "@ngx-translate/core" has an incompatible peer dependency to "tslib" (requires "^1.10.0", would install "2.0.0").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

## Expected behavior
I should first update ngx-translate to a supported version and then updgrade should go smoothly.

## How do you think that we should fix this?
Update ngx-translate/core itself to Angular 10 so a compatible package.json is generated and a compatible tslib version is used.
It also seems that `tslib` moved from being a 'peerDependency' to being a 'dependency' with Angular 10.

## Minimal reproduction of the problem with instructions
I can create a short script later on if requested.

## Environment

<pre><code>
ngx-translate version: 12.1.2
Angular version: 10.0.0

</code></pre>

**Comment by ocombe** [comment]
Thanks for the report, v13 is out for Angular v10!
