### ISSUE TITLE
Duplicate Translation When Element Has Content

### ISSUE THREAD

**Issue by backwards-rat-race** [ngx-translate/core#1240]
Hi,

When I have the translate attribute on a HTML element and that element also has text content;

`<div translate="login.title">Login Screen</div>`

The produced HTML is as so (the translation of 'login.title' is 'Login Title')

`<div _ngcontent-itw-c12="" translate="login.title" ng-reflect-translate="login.title">Login TitleLogin Title</div>`

Where it has the translation twice in the innerHTML. I've looked and notice there is a unit test for this situation which is passing, so I'm not sure what I'm doing wrong. I've create a repository here that replicates the issue here - https://github.com/backwards-rat-race/duplicate-translate-issue/blob/master/src/app/app.component.html

**Comment by russ-p** [comment]
Hmmm...

``<div [translate]="'login.title'">Login Screen</div>``

works

**Comment by backwards-rat-race** [comment]
Thanks. That resolves the issue.
