### ISSUE TITLE
Possible "phishing" / "hijacking" attempt on NPM

### ISSUE THREAD

**Issue by cice** [ngx-translate/core#1292]
![image](https://user-images.githubusercontent.com/143797/109150084-a85e7980-7768-11eb-9bda-436d22fd01f5.png)
i just discovered t his package on npmjs.com, which was published 5 hours ago and just contains `lol` as description. 
i'm gonna download it and check what it's about, if it contains something malicious, but i thought you should be aware of it.

**Comment by cice** [comment]
well it tries to read the /etc/shadow of course

https://unpkg.com/browse/ngx-translate@99.19.7/run.js

**Comment by ocombe** [comment]
Thank you for the report, I've contacted npm to report it, we'll see what they can do.

**Comment by cice** [comment]
hey i just checked, and it was finally removed by npm 🎉  https://www.npmjs.com/package/ngx-translate
