### ISSUE TITLE
Angular 13: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Mawi137** [ngx-translate/core#1346]
After updating to @ngx-translate/core@14.0.0, I keep getting this error in my jest tests (application itself works fine):
```
C:\dev\prj\Angular13Test\node_modules\@ngx-translate\core\fesm2015\ngx-translate-core.mjs:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as i0 from '@angular/core';
                                                                                                                                           ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { Component } from '@angular/core';
    > 2 | import {TranslateService} from '@ngx-translate/core';
        | ^
      3 |
      4 | @Component({
      5 |   selector: 'app-root',

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/app/app.component.ts:2:1)
```
Any idea what the issue might be? 
I also created a simple new Angular project, added ngx-translate + jest and added the `TranslateService` in the constructor of the `AppComponent`. It has the same issue.

**Comment by ocombe** [comment]
You will hav to update to the new version of jest angular preset (currently it's  11.0.0.rc2) as angular libs are now ESM only

**Comment by Mawi137** [comment]
I'm using `"@angular-builders/jest": "^13.0.0-beta.1"` which uses jest-angular-preset, They use 11.0.0.rc1 at the moment, but 11.0.0.rc2 has the same issue.

**Comment by Mawi137** [comment]
Apparently this module needs to be excluded in jest using `transformIgnorePatterns` as explained here:  https://github.com/thymikee/jest-preset-angular/issues/1149#issuecomment-963506942.

**Comment by ocombe** [comment]
Great, I'll try to add a note about that
