### ISSUE TITLE
Compile this package with "compilationMode": "partial", so the onus of `full` Ivy is left to when we build the full application 

### ISSUE THREAD

**Issue by un33k** [ngx-translate/core#1349]
I use NX mono repo for many large enterprise application.  NX has the best practice of encouraging non-ivy builds for publishable library.  That is great, as Ivy kicks in at application level, and with all data (code-signature) still available, it can make the best decisions in its static complication analysis.

With that said, I do have an internal i18n module that utilizes `ngx-translate/code`, and it worked great till the v13 release which is ivy only.  

## Current behavior
A `publishable` library that relies on `ngx-translate/*` and has decided to use "enableIvy": false or "compilationMode": "partial" would fail to locate the `translate` pipe on compilation after upgrading to v13 of this package.

## Expected behavior
V13 should not be a breaking change, Ivy flag of a publishable library as per Angular's V13 instruction can be set to ` "compilationMode": "partial"`. 

## How do you think that we should fix this?
Enable the ` "compilationMode": "partial"` on the builds, so the full Ivy compilation is postponed to when we compile the full application. 

## Minimal reproduction of the problem with instructions
Add `@fullerstack/ngx-i18n@0.0.4` to your project, enable it and try to compile the application.

https://www.npmjs.com/package/@fullerstack/ngx-i18n

## Environment

 "@ngx-translate/core": "14.0.0",
 "@ngx-translate/http-loader": "7.0.0",
 "@angular/core": "13.0.2",

Browser:
- [ x] Chrome (desktop) version 95

 
For Tooling issues:
- Node version: v14.17.0
- Platform:  Mac

Others:
vscode

**Comment by ocombe** [comment]
The Angular team recommends to publish ivy only libs from v13, the goal is to remove ngcc as it takes time and ressources.
If you wish you can still use v12.x, since I'm not adding new features and just maintaining the lib so that it still works, there is no other difference for now (and probably for the foreseeable future).

**Comment by un33k** [comment]
I think even for the version < 14, it would be best if you add "compilationMode": "partial", to satisfy the projects that progress forward alongside angular. 

```
// Works
application <- publishableMode ("enableIvy": false") <- ngx-translate ("enableIvy": false") 
```

```
// Broken
application <- publishableMode ("compilationMode": "partial") <- ngx-translate ("enableIvy": false")
```

```
// Broken
application <- publishableMode ("compilationMode": "partial") <- ngx-translate ("enableIvy": true")
```
