### ISSUE TITLE
Sharing pages on social media

### ISSUE THREAD

**Issue by rbalet** [ngx-translate/core#1352]
_I know this library is on low maintenance mode and that we should migrate to the angular library._  

I tried to share the page on social media and saw that the text weren't being translate. Does somebody have a fix for that ?

**Comment by EOussama** [comment]
What do you mean?

**Comment by rbalet** [comment]
I was testing my links for Facebook there https://developers.facebook.com/tools/debug/ and it wasn't translated.

 But I had to wait around 1 week till [rendertron](https://github.com/GoogleChrome/rendertron) did his works.
 
Sorry for the useless issue, I'm closing it
