### ISSUE TITLE
issue while translating "default"

### ISSUE THREAD

**Issue by SaravananManickam220592** [ngx-translate/core#1388]
when i try to translate the word "default" using pipe this is what happens , I have also given the code snippet used below:

**Current behavior :**

I used a custom loader as below : 

export class LazyTranslateLoader implements TranslateLoader {
  getTranslation(lang: string): Observable<any> {
    return from(import(`../assets/i18n/${lang}.json`));
  }
}

and I load it in the translate module root as below : 

  TranslateModule.forRoot(
      {
        loader : {
          provide: TranslateLoader,
          useClass: LazyTranslateLoader,
        }
      }
    ) 

when i try to use the pipe and translate the word "default". it is returning me the whole json file instead of just the word 
<h1>{{ "default" | translate }} </h1>

it is rendered as [object object] which is the whole json file.

**Expected Behaviour :**

it should return just default

**Comment by dhutaryan** [comment]
Have the same issue

**Comment by dananaprey** [comment]
Faced same issue, any updates?

**Comment by CodeAndWeb** [comment]
I've added some tests to reproduce this issue - but there does not seem to be anything strange.
Neither when using the translate pipe, nor the service directly using instant. Also tried setting translations directly or using a loader.

Please create some tests that can reproduce the issue.

**Comment by dananaprey** [comment]
I tried to make a clean application, the bug is not reproduced there, but at work there is a bug, that is, something around is influencing, I’d like to understand what

Maybe there are suggestions as to what could have an effect?

**Comment by dananaprey** [comment]
@CodeAndWeb I tried to make a clean application, the bug is not reproduced there, but at work there is a bug, that is, something around is influencing, I’d like to understand what

Maybe there are suggestions as to what could have an effect?
