### ISSUE TITLE
NgxTranslate Support for Standalone?

### ISSUE THREAD

**Issue by ksrae** [ngx-translate/core#1398]
The app I created with standalone components.

The issue is setting ngx-translate not working.

Here is my code:

`
// main.ts
export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

bootstrapApplication(AppComponent, {
  providers: [
    importProvidersFrom([
      HttpClientModule,
      TranslateModule.forRoot({
        loader: {
          provide: TranslateLoader,
          useFactory: createTranslateLoader,
          deps: [HttpClient]
        }
      }),
    ]),
    provideRouter(
      AppRoutes,
      withPreloading(PreloadAllModules),
      withDebugTracing()
    )
  ]
}).catch(
  err => console.error(err)
);
`

If I build this code. I got a following error:

`
./src/main.ts:9:0-75 - Error: Module not found: Error: Package path ./lib/translate.loader is not exported from package C:\workspace\samples\angular-samples\standalone-sample\node_modules\@ngx-translate\core (see exports field in C:\workspace\samples\angular-samples\standalone-sample\node_modules\@ngx-translate\core\package.json)

× Failed to compile.
`

How to use ngx-translate on standalone application. Please let me know if anyone knows. 

Thanks,

**Comment by tutkli** [comment]
You need to import providers from the TranslateModule. 
```ts
bootstrapApplication(AppComponent, {
    providers: [
        ...
        importProvidersFrom(HttpClientModule), // or provideHttpClient() in Angular v15
        importProvidersFrom(TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: createTranslateLoader,
                deps: [HttpClient]
           }
        }),
    ]
})
```

**Comment by ksrae** [comment]
I made two things wrong.
First thing was import link of TranslateLoader was long. 
It was `import { TranslateLoader } from @ngx-translate/core/lib/translate/loader'. 
The link should be imported from '@ngx-translate/core'

Second thing was I missed importing TranslateModule into the standalone component.


`
@Component({
   standalone: true,
   ...
   imports: [
      CommonModule,
      TranslateModule
   ]
})
`

Thanks for help @tutkli .

**Comment by Un1xCr3wR0x** [comment]
../../app.component.html:2:11 - error NG8004: No pipe found with name 'translate'.

{{"APP" | translate}}

any fix for this please ?

**Comment by Un1xCr3wR0x** [comment]
@ksrae , @tutkli hello guys currently iam doing everything u saying but iam getting 
```
Error: ../../app.component.html:2:11 - error NG8004: No pipe found with name 'translate'.
```

**Comment by alessanndro-prencipe-enginius** [comment]
> TranslateLoader

did you importend TranslateModule in your component?

**Comment by Un1xCr3wR0x** [comment]
yeah but it didnt work 
when i import the module i got this error 
main.ts:6 NullInjectorError: R3InjectorError(Standalone[AppComponent])[LocalizationService -> LocalizationService -> TranslateService -> TranslateStore -> TranslateStore]: 
  NullInjectorError: No provider for TranslateStore!
    at NullInjector.get (core.mjs:8771:27)
    at R3Injector.get (core.mjs:9200:33)
    at R3Injector.get (core.mjs:9200:33)
    at injectInjectorOnly (core.mjs:652:33)
    at Module.ɵɵinject (core.mjs:656:60)
    at Object.TranslateService_Factory [as factory] (ngx-translate-core.mjs:18:84)
    at R3Injector.hydrate (core.mjs:9301:35)
    at R3Injector.get (core.mjs:9189:33)
    at injectInjectorOnly (core.mjs:652:33)
    at Module.ɵɵinject (core.mjs:656:60)
    
    here is my component 
    ```
    import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { LoadingService } from './core/services/loading/loading.service';
import { LocalizationService } from './core/services/localization/localization.service';
import { TranslateModule } from '@ngx-translate/core';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet,TranslateModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'angular-standalone-progressive';

  constructor(
    public loadingService: LoadingService,
    private localizationService: LocalizationService
  ) {}

  ngOnInit() {
    this.localizationService.init();
  }
}

    ```

**Comment by Un1xCr3wR0x** [comment]
![image](https://github.com/ngx-translate/core/assets/139376647/65efd689-ca51-45a0-b905-86270023a8db)
component loads inside the angular material dialog 
any idea why ?

**Comment by mersal-developing** [comment]
Error: ../../app.component.html:2:11 - error NG8004: No pipe found with name 'translate'.


me also got the same error

**Comment by github-sadegh** [comment]
I have same problem for standalone components. What can I do?

**Comment by anurag-navsoft** [comment]
> @ksrae , @tutkli hello guys currently iam doing everything u saying but iam getting
> 
> ```
> Error: ../../app.component.html:2:11 - error NG8004: No pipe found with name 'translate'.
> ```
> 
> here is my app.config.ts
> 
> ```
> import { ApplicationConfig, ErrorHandler } from '@angular/core';
> import { provideRouter } from '@angular/router';
> 
> import { routes } from './app.routes';
> import {
>   HttpClient,
>   HttpClientModule,
>   provideHttpClient,
>   withInterceptors,
> } from '@angular/common/http';
> import { importProvidersFrom } from '@angular/core';
> import { httpInter } from './core/interceptors/http/http.interceptor';
> import { ErrorService } from './core/services/error-handler/error-handler.service';
> import { provideAnimations } from '@angular/platform-browser/animations';
> import { MatSnackBar } from '@angular/material/snack-bar';
> import { TranslateHttpLoader } from '@ngx-translate/http-loader';
> import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
> 
> export function createTranslateLoader(http: HttpClient) {
>   return new TranslateHttpLoader(http, './assets/i18n/', '.json');
> }
> export const appConfig: ApplicationConfig = {
>   providers: [
>     provideRouter(routes),
>     provideHttpClient(withInterceptors([httpInter])),
>     {
>       provide: ErrorHandler,
>       useClass: ErrorService,
>     },
>     provideAnimations(),
>     MatSnackBar,
>     importProvidersFrom(HttpClientModule),
>     importProvidersFrom(
>       TranslateModule.forChild({
>         loader: {
>           provide: TranslateLoader,
>           useFactory: createTranslateLoader,
>           deps: [HttpClient],
>         },
>       })
>     ),
>   ],
> };
> ```



> import { TranslateService,TranslateModule } from '@ngx-translate/core'; @component({ selector: 'app-root', standalone: true, imports: [CommonModule, RouterOutlet,TranslateModule], templateUrl: './app.component.html', styleUrls: ['./app.component.scss'], })
> 
> export class AppComponent { constructor(private translateService : TranslateService){ this.translateService.setDefaultLang('es'); const browserLang:any = this.translateService.getBrowserLang(); this.translateService.use(browserLang);} }

i fixed the issue by this code

**Comment by WodenWang820118** [comment]
The provide solution above help me complete the refactor to bootstrap the app with standalone component. Here is another snippet from my usecase, but some comments added.
```
import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import {
  provideRouter,
  withEnabledBlockingInitialNavigation,
} from '@angular/router';
import { HttpClient, provideHttpClient } from '@angular/common/http';
import { environment } from '../environments/environment.prod';
import { appRoutes } from './app.routes';
import { provideFirebaseApp, initializeApp } from '@angular/fire/app';
import { getFirestore, provideFirestore } from '@angular/fire/firestore';
import { provideAnimations } from '@angular/platform-browser/animations';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

// AoT requires an exported function for factories
export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http);
}

export const appConfig: ApplicationConfig = {
  providers: [
    provideAnimations(), // required
    provideHttpClient(), // required
    provideRouter(appRoutes, withEnabledBlockingInitialNavigation()), // if routers are used
    importProvidersFrom(
      provideFirebaseApp(() => initializeApp(environment.firebase))
    ), // optional, firebase
    importProvidersFrom(provideFirestore(() => getFirestore())), // optional, firestore
    importProvidersFrom(
      TranslateModule.forRoot({
        loader: {
          provide: TranslateLoader,
          useFactory: HttpLoaderFactory,
          deps: [HttpClient],
        }, // required for translation
      })
    ),
  ],
};

```

**Comment by DiegoOrdonezBecerril** [comment]
It's work for me in a whole standalone app:

in main.ts you should import providers

`export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}`

`const translateModuleConfig:  TranslateModuleConfig = { defaultLanguage: 'es', loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpClient]
    }
};`

`importProvidersFrom(BrowserModule, TranslateModule.forRoot(translateModuleConfig) ),`

in every standalone component.ts you should import TranslateModule like this

`imports: [TranslateModule]`

**Comment by sa-bangash** [comment]
i want to lazy load translation where i want to load on each standalone component but it not even call the factory
`import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import {
  IonButton,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonBackButton,
  IonButtons,
  IonInput,
  IonItem,
  IonLabel,
} from '@ionic/angular/standalone';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import { Observable, defer, from } from 'rxjs';

class LanguageTranslateLoader implements TranslateLoader {
  public getTranslation(lang: string): Observable<any> {
    return defer(() => from(this.getJson(lang)));
  }

  private async getJson(lang: string) {
    return await import(`./i18n/${lang}.json`);
  }
}

export function trnaslationLoaderFactory(http: HttpClient) {
  return new LanguageTranslateLoader();
}
@Component({
  selector: 'app-mobile-number',
  templateUrl: './mobile-number.page.html',
  styleUrls: ['./mobile-number.page.scss'],
  standalone: true,
  providers: [
    {
      provide: TranslateLoader,
      useFactory: trnaslationLoaderFactory,
    },
  ],
  imports: [
    IonButton,
    IonHeader,
    IonToolbar,
    IonTitle,
    IonContent,
    IonBackButton,
    IonButtons,
    IonInput,
    IonItem,
    IonLabel,
    RouterModule,
    TranslateModule
  ],
})
export class MobileNumberPage {}
`

**Comment by zazics** [comment]
@sa-bangash did you solve it ? I have same problem to lazy load translations for a standalone component.

**Comment by sa-bangash** [comment]
> @sa-bangash did you solve it ? I have same problem to lazy load translations for a standalone component.

no but i just change my mind as i am working ionic so i don't need to lazy load it but i split the into file
<img width="573" alt="image" src="https://github.com/ngx-translate/core/assets/29809885/d8a39266-5059-4281-a7df-0fa1fb9d43c9">
