### ISSUE TITLE
Missing LICENSE file in published package

### ISSUE THREAD

**Issue by tkegelmann** [ngx-translate/core#1423]
## Current behavior
The published package contains the entry `"license": "SEE LICENSE IN LICENSE"` its `package.json`, however the `LICENSE` file itself is not included. 

## Expected behavior
The `LICENSE` file should be included in the package.
Optionally, the `license` property in the `package.json` should be changed from `SEE LICENSE IN LICENSE` to `MIT` because that matches the assigned SPDX identifier of the `LICENSE` file of this repository.

## Environment

<pre><code>
ngx-translate version: 15.0.0
Angular version: 16.0.2

For Tooling issues:
- Node version: 18.14.0
- Platform:  Linux
</code></pre>

**Comment by tkegelmann** [comment]
Might be related to #1418

**Comment by ocombe** [comment]
yes, the licence has not changed

**Comment by LeChasseur** [comment]
Merci beaucoup!

**Comment by ropotvs** [comment]
We are using Qodana, and our License Audit is not passed, because of `"license": "SEE LICENSE IN LICENSE"` that is set in `package.json`. @ocombe , can you please update the `package.json` file, with `"license": "MIT"` ? 
For `@ngx-translate/core` and `@ngx-translate/http-loader`

**Comment by CodeAndWeb** [comment]
You can switch to @codeandweb/ngx-translate - it contains the proper license file and gets updates and fixes.

**Comment by CodeAndWeb** [comment]
Fixed in v16. https://ngx-translate.org/getting-started/migration-guide/
