### ISSUE TITLE
Noticed some movement, is there a chance for support to get back?

### ISSUE THREAD

**Issue by liesahead** [ngx-translate/core#1429]
We're planning to switch to another library as this one is abandoned and loading separate translations for modules never worked.

Noticed couple commits recently. Is there a chance you're planning to start supporting this library again? @ocombe 

![image](https://github.com/ngx-translate/core/assets/32300784/82d003c4-0031-40f3-ac86-fb2ff02f8865)

**Comment by ocombe** [comment]
Hello, not really, I'm just making sure it still works but I'm not adding new features or anything. I don't really get anything out of it as I don't use it anymore and OSS doesn't pay and takes a lot of time 🙂
There are still a lot of downloads for the lib (741 112 weekly downloads according to npm), and it doesn't seem to go down... so keeping it alive is great for the community, but that's about it.
If it works like it is for you then great, but if you have issues then switching to another lib is a good idea.
