### ISSUE TITLE
Cannot calibrate ngx-translate in a private Angular Library

### ISSUE THREAD

**Issue by Lightk3ira** [ngx-translate/core#1430]
Good afternoon. I am using your ngx-translate package in my Angular / Ionic application. I have used it before in these applications without issue however one project I am working on requires me to build an angular Library to use for reusability between multiple projects. I added translations for the library in my main assets/i8n folder (I would assume I want one specifically for the library but didnt see the right way to do that) and I import the TranslateModule into each library feature module. However for some reason I keep getting the error About 'No pipe found with name 'TRANSLATE'.' and I am at a loss.

Console Error when running `ng build my-library`
![image](https://github.com/ngx-translate/core/assets/8987009/31239454-361f-4550-a1dc-f4a301b28d1e)

Legal Module
![image](https://github.com/ngx-translate/core/assets/8987009/8f58759a-194b-43c4-b0e6-5423d56e4f26)

Public-api File
![image](https://github.com/ngx-translate/core/assets/8987009/f5465e8c-8e8a-440f-8069-b143f7959f77)

Package.json
![image](https://github.com/ngx-translate/core/assets/8987009/cac003a4-e2db-443b-99c5-9de1b5c51c7d)

**Comment by ArcosBinary** [comment]
@Lightk3ira can you provide your solution anyway? I seem to have a very similar issue. ;-)
