### ISSUE TITLE
Keep getting type errors

### ISSUE THREAD

**Issue by abizit** [ngx-translate/core#1432]
Error: node_modules/@ngx-translate/core/dist/lib/translate.directive.d.ts:26:102 - error TS2344: Type '{ translate: { alias: "translate"; required: false; }; translateParams: { alias: "translateParams"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
[ng]   Property '"translate"' is incompatible with index signature.
[ng]     Type '{ alias: "translate"; required: false; }' is not assignable to type 'string'.
[ng] 
[ng] 26     static ɵdir: i0.ɵɵDirectiveDeclaration<TranslateDirective, "[translate],[ngx-translate]", never, { "translate": { "alias": "translate"; "required": false; }; "translateParams": { "alias": "translateParams"; "required": false; }; }, {}, never, never, false, never>;
[ng]

**Comment by MaJaHa95** [comment]
I got the exact same error (and ended up on this issue!), until I realized I was using Angular 15 with the latest @ngx-translate/core.

Check the [compatibility table](https://github.com/ngx-translate/core#installation), and you'll find that the latest only supports Angular16+.

Easy fix for me:

```
npm install --save @ngx-translate/core@14 @ngx-translate/http-loader@7
```

**Comment by santhosh-natarajan** [comment]
@MaJaHa95 It's working fine for me also, Thanks

**Comment by digeomel** [comment]
I am using Angular 15.2.4 with @ngx-translate/core 14 and @ngx-translate/http-loader@7 and I'm still getting this error!
Any ideas?
