### ISSUE TITLE
missing MIT license in resulting package.json 

### ISSUE THREAD

**Issue by mn-42** [ngx-translate/core#1443]
## Current behavior
the resulting package.json contains as license info:

`"license": "SEE LICENSE IN LICENSE",`

license checker is failing when using the current version of this lib with error:

`Package "@ngx-translate/core@15.0.0" is licensed under "Custom: LICENSE" which is not permitted by the --onlyAllow flag. Exiting.`

## Expected behavior
should contain "MIT" as before angular 16

`"license": "MIT",`

## How do you think that we should fix this?

add the license info to the component.json

## Minimal reproduction of the problem with instructions
use the lib and check the resulting package.json in the node_modules directory.

For Tooling issues:
- Node version: v18.12.1
- Platform:  Mac, Linux, Windows

Others:
as license checker we use:

    "license-checker-rseidelsohn": "^4.2.6",

**Comment by zinnchen** [comment]
same for me using [davglass license-checker](https://github.com/davglass/license-checker)

**Comment by Kevin-Terblanche** [comment]
I am having the same problem is there any solution for this as yet? we are also using the [davglass license-checker](https://github.com/davglass/license-checker) some updates on this would be helpful

**Comment by CodeAndWeb** [comment]
Fixed in v16
