### ISSUE TITLE
Issue in Angular 16

### ISSUE THREAD

**Issue by slash851** [ngx-translate/core#1446]
## Current behavior

erroring with:

Error: node_modules/@ngx-translate/core/dist/lib/translate.directive.d.ts:25:102 - error TS2344: Type '{ translate: { alias: "translate"; required: false; }; translateParams: { alias: "translateParams"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"translate"' is incompatible with index signature.
    Type '{ alias: "translate"; required: false; }' is not assignable to type 'string'.

## Expected behavior

should compile

## How do you think that we should fix this?

correct type is required

## Minimal reproduction of the problem with instructions

simple yarn add library and run on empty project as in documentation. error will apear on compilation

## Environment

<pre><code>
ngx-translate version: X.Y.Z
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 20.5.1  
- Platform: Ubuntu 23.04 

Others:

</code></pre>

**Comment by digeomel** [comment]
Why was this closed? What is the solution? We're having the same issue.
