### ISSUE TITLE
How to use ngx-translate in Angular 17, Knowing that AppModule is not implemented?

### ISSUE THREAD

**Issue by red1code** [ngx-translate/core#1459]
## Environment

<pre><code>
ngx-translate version: X.Y.Z
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by inunotaisho** [comment]
This one needs major attention because if it's not dealt with, I'm gonna have to look for a new translator package

**Comment by shahmaulik1991** [comment]
import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';
import { provideAnimations } from '@angular/platform-browser/animations';
import { HttpBackend, HttpClient, HttpClientModule, provideHttpClient } from '@angular/common/http';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

export const provideTranslation = () => ({
  defaultLanguage: 'en',
  loader: {
    provide: TranslateLoader,
    useFactory: HttpLoaderFactory,
    deps: [HttpClient],
  },
});

export function HttpLoaderFactory(http: HttpClient) {
  return  new  TranslateHttpLoader(http, './assets/i18n/', '.json');
}
export const appConfig: ApplicationConfig = {
  providers: [provideRouter(routes),provideAnimations(),provideHttpClient(),importProvidersFrom(HttpClientModule), importProvidersFrom([TranslateModule.forRoot(provideTranslation())
  ]),],
  
};

//home.ts
import { TranslateModule, TranslateService } from '@ngx-translate/core';


@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, RouterModule, ViewallschemeComponent,LibrariesModule,TranslateModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent implements OnInit {
constructor(
    public translate: TranslateService
  ) {
  }

  ngOnInit(): void {
    this.translate.setDefaultLang('en');
    }
}

//Home Html
<div class="w-100 title-name">{{'login.title' | translate }}</div>

**Comment by panagiotisbellias** [comment]
> //app.config.ts import { ApplicationConfig, importProvidersFrom } from '@angular/core'; import { provideRouter } from '@angular/router';
> 
> import { routes } from './app.routes'; import { provideAnimations } from '@angular/platform-browser/animations'; import { HttpBackend, HttpClient, HttpClientModule, provideHttpClient } from '@angular/common/http'; import { TranslateLoader, TranslateModule } from '@ngx-translate/core'; import { TranslateHttpLoader } from '@ngx-translate/http-loader';
> 
> export const provideTranslation = () => ({ defaultLanguage: 'en', loader: { provide: TranslateLoader, useFactory: HttpLoaderFactory, deps: [HttpClient], }, });
> 
> export function HttpLoaderFactory(http: HttpClient) { return new TranslateHttpLoader(http, './assets/i18n/', '.json'); } export const appConfig: ApplicationConfig = { providers: [provideRouter(routes),provideAnimations(),provideHttpClient(),importProvidersFrom(HttpClientModule), importProvidersFrom([TranslateModule.forRoot(provideTranslation()) ]),],
> 
> };
> 
> //home.ts import { TranslateModule, TranslateService } from '@ngx-translate/core';
> 
> @component({ selector: 'app-home', standalone: true, imports: [CommonModule, RouterModule, ViewallschemeComponent,LibrariesModule,TranslateModule], templateUrl: './home.component.html', styleUrl: './home.component.scss' }) export class HomeComponent implements OnInit { constructor( public translate: TranslateService ) { }
> 
> ngOnInit(): void { this.translate.setDefaultLang('en'); //hi,ta,fr any language } }
> 
> //Home Html
> {{'login.title' | translate }}
> //json file like (assets/i18n/en.json)

Worked perfectly for me in Angular v18, thanks!

**Comment by CodeAndWeb** [comment]
v16 fixes this issue. See https://ngx-translate.org/getting-started/migration-guide/
