### ISSUE TITLE
Angular 17 SSR. Standalone implementation - NullInjectorError: No provider for _TranslatePipe!

### ISSUE THREAD

**Issue by logicappsource** [ngx-translate/core#1465]
## Current behavior
![Screenshot 2023-12-27 at 16 08 50](https://github.com/ngx-translate/core/assets/14986750/e13a26e3-812a-4430-a033-b6672e1e59c0)
Hi amazing devs, please help, I get NullINjectionError I dont understand, since I provide this at root lvl of the application bootstrap startup?

## Expected behavior
I cant get translations to be loaded in standalone components, 

## How do you think that we should fix this?
My component standalone: 
![Screenshot 2023-12-27 at 16 10 43](https://github.com/ngx-translate/core/assets/14986750/9efe7653-04b4-4987-8ffa-7faf8d7af8e5)

## Minimal reproduction of the problem with instructions
My app.config.ts: 
![Screenshot 2023-12-27 at 16 13 21](https://github.com/ngx-translate/core/assets/14986750/7d928ee9-bcca-4e3c-81ce-85d134ae86fc)

In my 
## Environment - Packages 
<pre><code>
   "@ngx-translate/core": "^15.0.0",
    "@ngx-translate/http-loader": "^8.0.0",
    "@angular/core": "^17.0.0",

Others:

</code></pre>

**Comment by dharma-code-chris** [comment]
Have a look at this article too https://medium.com/@k4kunal/exploring-ngx-translate-support-in-angular-17-transitioning-to-standalone-components-c19324c56ce5
