### ISSUE TITLE
ngx-translate.com is pointing another website

### ISSUE THREAD

**Issue by muratcorlu** [ngx-translate/core#1477]
Here is what I get when I open the website:

<img width="1610" alt="image" src="https://github.com/ngx-translate/core/assets/127687/f41f0d2b-0829-4e18-8690-900c7f74a79f">

**Comment by ocombe** [comment]
Yeah I know, I removed the link from the organization. I didn't make sense to pay for the domain as it's not really useful. But thanks for the heads up.

**Comment by muratcorlu** [comment]
Then I think it's better to remove URL from everywhere, include repository description.

<img width="323" alt="image" src="https://github.com/ngx-translate/core/assets/127687/be14c2bd-b7a7-4b66-ac88-977c84c491d3">

**Comment by ocombe** [comment]
ah yes, thanks, I missed that one
