### ISSUE TITLE
Angular 18 Support SSR

### ISSUE THREAD

**Issue by aparzi** [ngx-translate/core#1483]
Is translation supported for Angular 18 SSR?

**Comment by cskiwi** [comment]
It seems to work. however for me it renders the translations on server side, then when the client loads it in it re loads the translations, causing a small flicker.

Might be my configuration

**Comment by aparzi** [comment]
Hi @cskiwi,
It seems to work for me too. Flickering effect should it could depend hydration process of Angular.

**Comment by cskiwi** [comment]
Indeed was some configuration on my part. all is resolved now

**Comment by KariNarhi28** [comment]
@cskiwi Could you at least share that fix for others too?

I am suffering from that flickering too.

**Comment by aparzi** [comment]
Hi @KariNarhi28,
can you share the code? Because flickering effect depends on Hydration process of Angular. I don't think that an issue of ngx-translate

**Comment by cskiwi** [comment]
@KariNarhi28  and @aparzi. it's hard to narrow down the exact fix because it didn't bother me that much and did some other changes first and eventually it was resolved.

If I would guess it would have been one of the following changes:

I had my own Transtion Module that intializes everything with a `.forRoot(config)`. I removed that and switched to:
```ts
export const appConfig: ApplicationConfig = {
  providers: [
    provideHttpClient(withFetch(), withInterceptorsFromDi()),
    importProvidersFrom(
      TranslateModule.forRoot(
        provideTranslation({
          api: `/api/v1/translate/i18n/`,
        }),
      ),
    )
  ]
}
```
with the following provider:
```ts
export const provideTranslation = (config: ITranslateConfig) => ({
  defaultLanguage: 'en',
  useDefaultLang: true,
  loader: {
    provide: TranslateLoader,
    useFactory: (http: HttpClient, baseUrl: string) =>
      new TranslateHttpLoader(http, baseUrl + config.api, ''),
    deps: [HttpClient, BASE_URL],
  },
});
```
I also moved my languageIntializer to the privders in the app.config.ts.
However none of these should have impact this

**Comment by aparzi** [comment]
@cskiwi you should add provideClientHydration() in app.module. More informations in this guide: https://angular.dev/guide/hydration.

<img width="771" alt="Screenshot 2024-07-30 alle 11 44 36" src="https://github.com/user-attachments/assets/f8919c78-dec3-4879-a28d-1a2799edbf41">

**Comment by cskiwi** [comment]
@aparzi  it is there :) i just didn't copy all my providers. Thanks for spotting that!

**Comment by therepo90** [comment]
This is what i did
```
export function HttpLoaderFactory(http: HttpClient, platformId: any): TranslateHttpLoader {
  console.log('Loading asset json lol');
  let baseUrl;
  if(isPlatformBrowser(platformId)){
    baseUrl = './';
  }else{
    baseUrl = environment.baseUrl || 'http://localhost';
  } 
  return new TranslateHttpLoader(http, `${baseUrl}/assets/i18n/`, '.json')
}

```
