### ISSUE TITLE
Updated documentation covering Angular 18

### ISSUE THREAD

**Issue by CodeAndWeb** [ngx-translate/core#1488]
## Angular 17, 18+

The [new documentation](https://ngx-translate.org/) now covers installation on 
Angular 18+ and is divided into smaller, more readable sections, making it 
easier to digest than this big README. It also documents the additional 
interfaces and explains how to develop custom plugins.
    
New documentation: **https://ngx-translate.org/**

In addition to that, a getting started tutorial is available here:  
[How to Translate Your Angular App with NGX-Translate](https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-angular-app-with-ngx-translate)

This [Demo project](https://github.com/CodeAndWeb/ngx-translate-demo) 
contains 3 simple example projects for Standalone components, NgModules, and 
how to use the message format compiler. The branches contain the same 
projects for older Angular versions.

**Comment by Judimax** [comment]
Greetings are you part of the ngx-transalate team are you planning to take over the project from combe?

**Comment by CodeAndWeb** [comment]
I currently have some additional privileges, such as handling tickets on the project: https://github.com/orgs/ngx-translate/people.

However, there isn't a formal "team" structure in place. We've never had meetings to discuss project direction, decision-making, or processes.

I'd like to take over the project since we have the resources to maintain ngx-translate in the long term and keep the library active. I proposed this two years ago, but the offer was declined. I tried reaching out to Olivier again last week, but I haven't received any response—neither via email nor on social media.

If I don't hear back from him soon, the only option may be to fork the project, although this seems questionable. It doesn’t make sense to essentially create a new library and start from scratch.

**Comment by Judimax** [comment]
essentialy what we have done is when we dont hear back from the maintainter we put our our organization in front of it @windmillcode/[PACKAGE NAME] you might as well do the same . I know that you have enough resources but if there is any collaboration, promotion or help we can provide let me know

**Comment by CodeAndWeb** [comment]
I've meanwhile forked the project:

@codeandweb/ngx-translate
@codeandweb/http-loader

The current work in progress is available as a beta version on npm.

**Comment by Judimax** [comment]
Greetings our organization's library depends on ngx-translate would like to collaborate especially on testing issues  .Even promote by writing articles https://windmillcode.github.io/Windmillcode-Angular-CDK-Docs/
you can setup time to connect https://windmillcode.com/contact

**Comment by segux** [comment]
Can you make fork public? Probably all should go migration to your new npm package and all issues will be open at that place

**Comment by CodeAndWeb** [comment]
It's already available. I've released V16 of my fork last week. This migration guide explains how to switch to my fork and also explains the benefits of doing so:

https://ngx-translate.org/getting-started/migration-guide/

**Comment by woppa684** [comment]
If all goes well, this should be arranged, soon see https://github.com/ngx-translate/core/issues/783#issuecomment-2440849415

**Comment by CodeAndWeb** [comment]
Got permissions by Olivier to publish updates here...

**Comment by alvaro-junqueira-axa** [comment]
> ## Angular 17, 18+
> The [new documentation](https://ngx-translate.org/) now covers installation on Angular 18+ and is divided into smaller, more readable sections, making it easier to digest than this big README. It also documents the additional interfaces and explains how to develop custom plugins.
> 
> New documentation: **https://ngx-translate.org/**
> 
> In addition to that, a getting started tutorial is available here: [How to Translate Your Angular App with NGX-Translate](https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-angular-app-with-ngx-translate)
> 
> This [Demo project](https://github.com/CodeAndWeb/ngx-translate-demo) contains 3 simple example projects for Standalone components, NgModules, and how to use the message format compiler. The branches contain the same projects for older Angular versions.

Hi @CodeAndWeb 
The new documentation looks very nice and clear, thanks for your work =)

The actual `README.md` file will be updated as well (maybe with the content removed and a link to the new docs)
There I still can see the recommendation to the version core@15 and http-loader@8 of the libraries and there's no usage of the Standalone methods (that are already covered in the new docs)

In the Demo project pointed out in your issue above, there's no usage of the the Standalone way as well.
From my point of view, clean the readme file and just keep the right links will be better than try to keep both updated =)
