### ISSUE TITLE
Cannot disable browser translation

### ISSUE THREAD

**Issue by jerryzhao0423** [ngx-translate/core#1492]
## Current behavior

`translate=no` is a global standard html attribute which can help prevent the dom to be translated by browser. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate. 

However, ngx-translate use translate as a directive name. As a result, `<div translate='no'>{'Home' |  translate}</div>` will give me a  'no' on UI.

## Expected behavior

`<div translate='no'>{'Home' |  translate}</div>` will show 'Home' on UI and disable the browser to translate Home.

## How do you think that we should fix this?

Add ability to disable directive usage or change directive name.

## Environment

<pre><code>
ngx-translate version: 15.0.0
Angular version: 16.2.0

Browser:
- [x] Chrome (desktop) version 129.0.6668.101
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by CodeAndWeb** [comment]
You can set it globally on the **index.html** in your **src** folder:

~~~html
<!doctype html>
<html lang="en" translate="no">
<head>
...
~~~

**Comment by carlosjeurissen** [comment]
@CodeAndWeb Thanks for your additional info! Not all scenarios can be solved by statically setting the translate attribute. In the case of browser extension content scripts, setting it dynamically is the only possible way.

However, changing the translate attribute dynamically with a browser extension causes interference with ngx-translate.

For example, setting translate to false as such:
```js
document.documentElement.translate = false;
```

Will cause ngx-translate to set the documentElement innerText to "no". Example extension:
https://github.com/carlosjeurissen/webext-tech-demo-extensions/tree/main/issues/content-script-translate-attribute/sample-extension

Example website:
https://files.dreamhost.com/

Is there a recommend way to dynamically set the translate attribute while preventing the translate behaviour from ngx-translate to be triggered? Could ngx-translate potentially exclude the values "no" and "yes"?
