### ISSUE TITLE
Make it easier to find the v16 migration guide

### ISSUE THREAD

**Issue by json-derulo** [ngx-translate/core#1497]
It is great to see that there is some movement in the project, and that a new major version is out! However, I had a hard time finding the changelog for v16. I eventually found it in the [new documentation](https://ngx-translate.org/getting-started/migration-guide/), but it took me quite some time. I would suggest the following changes to make it easier accessible:

1. Create a [GitHub release](https://github.com/ngx-translate/core/releases) and add a link there
2. Add a link in the README, section "Angular 16, 17, 18+"

**Comment by CodeAndWeb** [comment]
Updated :-)

P.S. Great pseudonym -  _json-derulo_ - 🤣
