### ISSUE TITLE
feat(wiki): link to the edition of the new wiki

### ISSUE THREAD

**Issue by rbalet** [ngx-translate/core#1499]
## Current behavior
I have found some little issues on [the wiki](https://ngx-translate.org/getting-started/migration-guide/) and would have liked to update it. 

_Additional issue: the GitHub icon link to the former library_  

## Expected behavior
Sadly, the upper GitHub button does not link to the wiki Github page
![image](https://github.com/user-attachments/assets/708bf801-529c-4df0-be27-87bf12eff23f)

## What is the motivation / use case for changing the behaviour?
Being able to easily send wiki change pull requests

## How do you think that we should implement this?
The Github button could be linked to the wiki. 

Even better, it a link to the page himself could be linked at the bottom of a page.

**Comment by rbalet** [comment]
@CodeAndWeb FYI :)

**Comment by CodeAndWeb** [comment]
The GitHub link now points to this repo.
Each page now has an "Edit" button at the end - which directly opens the matching page for editing.
