### ISSUE TITLE
Typo in installation guide

### ISSUE THREAD

**Issue by mihailmotorkin** [ngx-translate/core#1500]
Found a typo that cost me a lot of time to figure out. In installation guide in the[ Standalone Component](https://ngx-translate.org/getting-started/translation-files/#standalone-components) section TranslationService is said to be imported, although it's really TranslateService that needs to be imported. 

Hope this can help some other newbies in Angular like your humble servant.

Keep up the good work! 

Yours truly, 
Michael
![ngx-translate](https://github.com/user-attachments/assets/cb86c44e-7226-4efe-83db-db1a074bfff4)

**Comment by CodeAndWeb** [comment]
Thanks for reporting this... fixed!
