### ISSUE TITLE
Lazy Load Multiple Translation Files

### ISSUE THREAD

**Issue by voi99** [ngx-translate/core#1502]
Hi @CodeAndWeb 

I just wanted to say a huge thanks for stepping in to maintain ngx-translate. I really appreciate all the time and effort you’re putting into keeping this library going!

Question:
As my project grows and the translation files become larger, I was wondering if there’s an option to load multiple translation files. I came across this blog [https://medium.com/@redin.gaetan/angular-multi-translation-files-7116239d915b]

I’ve successfully managed to load multiple files using this loader. However, the issue is that all files are eagerly loaded. Is there a way to load them dynamically/lazy, for instance, only when a specific route is accessed?

**Comment by CodeAndWeb** [comment]
Thanks ;-)

I am closing this one for now - it's practically identical with https://github.com/ngx-translate/core/issues/1501
