### ISSUE TITLE
New injection token replacing USE_STORE has a typo in ISOALTE_TRANSLATE_SERVICE

### ISSUE THREAD

**Issue by sopelt** [ngx-translate/core#1505]
## Current behavior
We just stumbled over the rename from `USE_STORE` to `ISOALTE_TRANSLATE_SERVICE` in https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/src/public-api.ts#L13 and noticed that there is a typo in the new value as the [commit comment mentions the correct spelling](https://github.com/ngx-translate/core/commit/e5f0ad957dd4a23db51a145cdff41cf449b0d45a).

## Expected behavior
The token should be named `ISOLATE_TRANSLATE_SERVICE`.

## Environment

<pre><code>
ngx-translate version: 16.0.3

**Comment by CodeAndWeb** [comment]
Thanks for reporting the issue. Fixed.

**Comment by sopelt** [comment]
Thanks for the swift action!

**Comment by CodeAndWeb** [comment]
Easy fix ;-)
But I won't make a release for that now.
