### ISSUE TITLE
Incorrect error context: ng2-translate.js:41

### ISSUE THREAD

**Issue by Richie765** [ngx-translate/core#274]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I'm using ng2-translate within a Meteor app. Sometimes I get error messages within the wrong context, for example:

```
ng2-translate.js:41 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

ng2-translate.js:41 Uncaught TypeError: Cannot read property 'remove' of null
ViewController.dismiss @ ng2-translate.js:41
ToastCmp.dismiss @ ng2-translate.js:41
(anonymous function) @ ng2-translate.js:41
ZoneDelegate.invokeTask @ ng2-translate.js:41
Zone.runTask @ ng2-translate.js:41
ZoneTask.invoke @ ng2-translate.js:41
```

Those errors are unrelated to ng2-translate but it shows 'ng2-translate.js:41' all over the place. It seems to happen only with errors that are from a callback somewhere, but I can't reproduce it inside my own callbacks.

Any idea how to get proper error context? It's hard to fix bugs this way.

**Please tell us about your environment:**
- **ng2-translate version:** 3.1.0
- **Angular version:** 2.0.1
- **Language:** [TypeScript]

**Comment by ocombe** [comment]
I ship the source maps within the bundle, it should give you a better sense of where the error comes from if you setup your project to use source maps

**Comment by ocombe** [comment]
Closing this, let me know if you need it to be reopened.
