### ISSUE TITLE
Handle localization file missing

### ISSUE THREAD

**Issue by urffin** [ngx-translate/core#282]
**I'm submitting a ...**  (check one with "x")

```
[ x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

When localization json file missed in console write http error 404, but i can't catch this error in my code

**Expected/desired behavior**

Catch this error in code.

**Reproduction of the problem**

http://plnkr.co/edit/ls8XiZIt4UqEwyQAD8an?p=preview

**What is the expected behavior?**

go into observable catch function.

**What is the motivation / use case for changing the behavior?**
I need it for resolving my route. For example: domain.com/en/welcome.

**Please tell us about your environment:**
- **ng2-translate version:** 3.1.2 
- **Angular version:** 2.1.0
- **Browser:** all
- **Language:** TypeScript 2.0.3

**Comment by un33k** [comment]
It took a while to debug a case where the json file was invalid.  It would be great if we have a way to catch that scenario as well.

**Comment by abennouna** [comment]
An workaround approach would be:
```
    // Set the default language for translation strings.
    let defaultLanguage = 'en';
    this.translate.setDefaultLang(defaultLanguage);

    // Detect user language.
    let browserLang = this.translate.getBrowserLang();

    // Try first to load the I18N JSON file for the detected language
    return new Promise((resolve, reject) => {
      this.http.get(`../assets/i18n/${browserLang}.json`)
        .catch((error: any) => {
          // I18N File failed to load, fall back to English
          this.translate.use(defaultLanguage);
          resolve(true);

          return Observable.throw(error);
        })
        .subscribe((data) => {
          // I18N File loaded successfully, we can proceed
          this.translate.use(browserLang);
          resolve(true);
        });
    });
```

**Comment by urffin** [comment]
@abennouna, but in this case json file should be loaded manually, just for checking exists.

**Comment by ocombe** [comment]
It depends what starts the loading of the translations, if it's a pipe then you won't be able to catch that error...
If it's "use" then it returns an observable and you can use `catch` on it. Same thing for `get`.

**Comment by urffin** [comment]
@ocombe, but you can see in plunkr above, that i not go to `catch` after `use`. and not show in console output log. 

So 

> If it's use then it returns an observable and you can use catch on it.

Seems wrong. Or possibly i use catch in wrong way?

**Comment by SamVerschueren** [comment]
The problem is that you aren't subscribing to the observable. But even with subscribing this doesn't work. Don't have time to dive deeper now though.

```js
translate.use('en').subscribe({
  error: err => {
    console.log('error', err)
  }
});
```

**Comment by urffin** [comment]
@SamVerschueren, but loading started without subscribing, so why we need indeed sbuscribe instead catch?

**Comment by ocombe** [comment]
it's a shared observable, internally there's a subscribe to make the request, but if you subscribe as well you should get the returned value.
Maybe it's because of the share operator that the exceptions aren't propagated? I need to make some tests

**Comment by SamVerschueren** [comment]
@urffin What @ocombe said. Also, you're making a new subscription so you have to call `subscribe` again.

**Comment by SamVerschueren** [comment]
@ocombe Might be because we aren't catching the error [at this point](https://github.com/ngx-translate/core/blob/master/src/translate.service.ts#L190-L193). Not sure though.
