### ISSUE TITLE
Multiple values in translation

### ISSUE THREAD

**Issue by pndewit** [ngx-translate/core#334]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

Not sure whether this is already implemented and (probably) not documented or if this is a feature request.

You were probably already expecting this one, I'd like to supply multiple params to the pipe. Is there a similar way to do this like it is done now with only a single parameter: `{{'value' | translate:param}}` (e.g. `{{'value' | translate:param1:param2:...}}`)?

A workaround for now would be:
```{{'value' | translate:'{param:"\'+param1+\'", otherparam:"\'+param2+\'"}'}}```

Plunker:
http://plnkr.co/edit/mwE3PCTo7PTlMgH7ljIQ?p=preview

Thanks.

EDIT:
`{{'value' | translate:param1:param2:...}}`
Would require the order to be correct which could result into unexpected behaviour. Maybe this is not the way to go. Maybe it would be better to do some research into why this is not working: `{{'value' | translate:{param: param1, otherparam: param2}}}`.

**Comment by ocombe** [comment]
Yes using an object with multiple keys is the way to go for now.
The pipes in Angular support multiple parameters, but I'm only using the first one for now: https://github.com/ocombe/ng2-translate/blob/master/src/translate.pipe.ts#L90

If you want to make a PR to support more than one, you can :)

**Comment by aidanmischke** [comment]
This syntax worked fine for me:
`{{ 'value' | translate: { 'param': param1, 'otherparam': param2 } }}`

**Comment by pndewit** [comment]
@ocombe Must have been due to another commit. Got to love it when an issue solves itself 👍 
@aidanmischke The quotes around each param name didn't work for me, but moving them to the entire object did: `{{ 'value' | translate: '{ param: param1, otherparam: param2 }' }}`
