### ISSUE TITLE
New name for the library

### ISSUE THREAD

**Issue by ocombe** [ngx-translate/core#335]
This library has been named ng2-translate as an obvious reference to angular-translate (for Angular 1), but it is now growing as an independent project with new features.
Also Angular 2 is now called Angular (with Angular 1 being AngularJS), so the name ng2 is gonna be obsolete soon.

Which is why this library needs a new name. I've secured the npm username `i18n`, and I would like to release future versions on npm under `@i18n/...` (for example `@i18n/core`), so I'm thinking about renaming this angular-i18n or something like that, but I'm opened to other ideas (preferably with i18n in the name, but not necessary).

Why distribute this under a namespace on npm? Because I'd like to release new optional addons (new loaders, tools, ...) and I want everything under the same namespace (so that I can name these new libs the way I want).
Also this is following the `@angular` philosophy.

Do you guys have ideas or remarks on the subject ?

**Comment by Meligy** [comment]
For npm, @i18n/ng-translate.

If I may make a remark though, I don't feel like it's a good idea to claim `@i18n` though. Reminds me of [the `standard` package](https://www.gurustop.net/blog/2016/01/15/you-dont-claim-standardjs) (don't even get me started!).

So, maybe `@ng-translate/core`?

**Comment by mhartington** [comment]
Agree with @Meligy on the name of `@i18n`, maybe `@ng-i18n/core` instead?

**Comment by ocombe** [comment]
Ahah yeah, maybe i18n is a bad idea.
That being said I might one day make this library in vanilla js with addons for different frameworks (I'm not doing that for now, but that's a possibility).

`@ng-translate` is out of the question because it's too much like angular-translate.
`@ng-i18n` is a better idea yes.

**Comment by michaelbromley** [comment]
I'd agree with the sentiments re using the plain `i18n` name. 

To make the name generic (not coupled to Angular) there are only a few obvious terms - "i18n", "translate" etc. - BUT another approach could be to come up with a related-yet-distinct name, like what Babel did when renaming from "6to5". Plenty of well-known libs have names with no direct reference to the task they perform - moment.js, reveal.js for example.

As a side note: remember this: https://github.com/michaelbromley/ng2-pagination/issues/9 ? ;)

**Comment by orgbx** [comment]
Dropping `ng-polyglot` there (Something related to the [Rosetta Stone](https://www.wikiwand.com/en/Rosetta_Stone) would be even cooler 😄 )

**Comment by ocombe** [comment]
Yeah :D
I'm all for a distinct name (like babel - which would be a cool name for this lib by the way), but I haven't been able to find one that I like... naming things is the one of the hardest thing to do :)

**Comment by ocombe** [comment]
my bad, there is a library by that name, and it's about translations :D https://www.npmjs.com/package/t7e
damn it !

**Comment by codef0rmer** [comment]
@ocombe how about `angular-locale`

**Comment by NicoTuxx** [comment]
@ocombe what about something composed with 'Rosetta' ?
angular-multilingual ?

**Comment by SamVerschueren** [comment]
Or translate `translate` to some other language and maybe you come up with a cool name :).

https://translate.google.com/#en/no/translate

**Comment by ocombe** [comment]
Trad (short fort traduction = translation in french)?

**Comment by SamVerschueren** [comment]
Yeah, looks good for me!

**Comment by orgbx** [comment]
I actually did that translate `translate` to all languages yesterday :)
How about `transangular` (for tranlate angular with a "transatlantic" connotation but has a bit of that expertsexchange issue 😝)?
There seems to be a library dot js for every frigging word I think of!

**Comment by ocombe** [comment]
Let's make a little summary of the propositions that I like so far (namespace: lib name - module name):
- `@i18n`: i18n [for Angular] - i18nModule
- `@t7e`: Translate - TranslateModule
- `@???` (@trad is taken): Trad - TradModule
- `@polyglot`: Polyglot - PolyglotModule

My favorite so far are the two first

**Comment by NicoTuxx** [comment]
Your library is more a multilingual system than a "translate" system, so it look obvious that the most logical names in your selection are 'polyglot' and 'i18n'.
That would make more sense in my opinion.

**Comment by vai** [comment]
How about `li**ng**ua` ? You'd get to be able to use it as the namespace later then too.

cref. [wikitionary](https://en.wiktionary.org/wiki/lingua#Latin)

**Comment by ocombe** [comment]
Hey good idea, I like it :)

**Comment by HoltMansfield** [comment]
lingua++

**Comment by ocombe** [comment]
So after a few weeks and 3 twitter polls, I've decided that the new name will either be `ngx-i18n` or `ngx-translate`.

Think about how it will affect the directives / pipes as well.

With `ngx-i18n` the directive and pipe will be `ngxI18n`. I won't use `i18n` alone because of the official i18n directive. Also it's a pretty common name and that might cause problems. It's nice because it's short, but I really don't like how it comes out in camel-case, the `i` is hard to differenciate from the letter `L`...

With `ngx-translate` I can either change them to `ngxTranslate` or keep using the current `translate`. It's a bit more text to write, but it's closer (or similar) to the actual implementation, and it's easier to writer/remember I think.

Any preference?

**Comment by SamVerschueren** [comment]
For me personally, `ngx-translate` is the best choice.

**Comment by Meligy** [comment]
`ngxTranslate` should work just fine.

**Comment by juristr** [comment]
`ngx-translate` I'd say. Altho I don't dislike `ngx-i18n` as well 🙂

**Comment by bgies** [comment]
ngx-translate... numbers are more difficult to type...

**Comment by pinpointpanda** [comment]
Man, I'm glad I found this thread :) I just spent about half an hour on Google trying to work out what the difference was between ng2-translate and ngx-translate.
In my defense, it's been a long day :)

I guess this kind of thing is becoming more common in libraries now with AngularJS -> Angular 2 -> Angular.

**Comment by juristr** [comment]
@pinpointpanda Yes, here are the official branding guidelines: https://angular.io/presskit.html
