### ISSUE TITLE
Enable html template usage with the directive

### ISSUE THREAD

**Issue by NicoTuxx** [ngx-translate/core#354]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
a html template like : `"EXAMPLE": "<p>This is an example !</p><p>Look at this !</p>"` won't be rendered as html if used with the directive.

This : 
`<div template>EXAMPLE</div>`

Now render like this for the user : 
`<p>This is an example !</p><p>Look at this !</p> (plain text)`

**Expected/desired behavior**
Make html renderable by the directive.

This : 
`"EXAMPLE": "<p>This is an example !</p><p>Look at this !</p>"`
`<div template>EXAMPLE</div>`

Would render like this for the user : 
```
This is an example !
Look at this !
```

**Please tell us about your environment:**

* **ng2-translate version:**4.2.0

**Comment by ocombe** [comment]
It's not possible with the current directive, and it would probably require a different directive altogether to enable it. But you can have the exact same behavior with the pipe:

```html
<div [innerHTML]="'HELLO' | translate"></div>
```

**Comment by renehamburger** [comment]
In some cases it may be necessary to sanitize the html content before it's added to the DOM. This may be the case if the interpolation variables contain user-created content or if the translation string itself can be edited by outsiders, e.g., external translators.

Here's a directive that sanitizes the html

```ts
import { Directive, ElementRef, Input, OnChanges, Sanitizer, SecurityContext,
  SimpleChanges } from '@angular/core';

// Sets the element's innerHTML to a sanitized version of [safeHtml]
@Directive({ selector: '[safeHtml]' })
export class HtmlDirective implements OnChanges {
  @Input() safeHtml: string;

  constructor(private elementRef: ElementRef, private sanitizer: Sanitizer) {}

  ngOnChanges(changes: SimpleChanges): any {
    if ('safeHtml' in changes) {
      this.elementRef.nativeElement.innerHTML =
        this.sanitizer.sanitize(SecurityContext.HTML, this.safeHtml);
    }
  }
}
```
to be used exactly the same way as `innerHTML`:
```html
  <div [safeHtml]="'HELLO' | translate"></div>
```

```

**Comment by ocombe** [comment]
Perfect, closing this, let me know if you need it to be reopened.

**Comment by JLIVE101** [comment]
When translations is changed the innerHTML isnt re rendered

**Comment by manuman94** [comment]
Yes! It was feeling that I was the only one experiencing this issue @JLIVE101. I need the HTML translations to be refreshed when language changes. Is there any way to achieve this?

**Comment by elgerm** [comment]
> When translations is changed the innerHTML isnt re rendered, is there a fix for this?

create a setter on the input() and run the changes from there
