### ISSUE TITLE
`TranslateService.get()` ignores interpolateParams, if returned result is object

### ISSUE THREAD

**Issue by unlight** [ngx-translate/core#357]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
`TranslateService.get()` ignores interpolateParams, if returned result is object.

**Expected/desired behavior**
`TranslateService.get()` should not ignore interpolateParams, if result is object.

**Please tell us about your environment:**

* **ng2-translate version:** 4.2.0

* **Angular version:** 2.1.0

http://plnkr.co/edit/GtzZweCGDavJeArRxLtw?p=preview

**Comment by ocombe** [comment]
Can you give me an example ? A plunkr would be the best

**Comment by unlight** [comment]
http://plnkr.co/edit/GtzZweCGDavJeArRxLtw?p=preview

**Comment by deeg** [comment]
This might be related to the PR I just put out #412.

My argument would be it should never be returning objects for translations anyways, only keys. In your example now it would just return the key as a missing translation.

**Comment by danielang** [comment]
The easiest way to solve this issue is to stringify the object to JSON and do the replace operation on that string.

translate.parser.js:19
```js
      if (!params) {
        return expr;
      } else {
        if (typeof expr === 'string') {
          return expr.replace(this.templateMatcher, function (substring, b) {
            var r = _this.getValue(params, b);
            return isDefined(r) ? r : substring;
          });
        } else {
          var jsonString = JSON.stringify(expr);

          jsonString = jsonString.replace(this.templateMatcher, function (substring, b) {
            var r = _this.getValue(params, b);
            return isDefined(r) ? r : substring;
          });

          return JSON.parse(jsonString);
        }
      }
```
The string replace function should be wrapped in his own function to avoid duplicate code.
Should I create a PR?

**Comment by ocombe** [comment]
Hello, I'm closing & locking this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
