### ISSUE TITLE
Error while importing the package in SystemJS

### ISSUE THREAD

**Issue by cbeldacap** [ngx-translate/core#359]
**I'm submitting a ...**
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I'm using SystemJS and when I import ng2-translate as it appears on the README (.../bundles) the app throws an error.

**Expected/desired behavior**
Everything should be imported from the `bundles` folder, but finally I had to imported like that:
```
'ng2-translate': 'node_modules/ng2-translate/bundles/ng2-translate.umd.js'
```

**Reproduction of the problem**
I don't know if it is related with the problem, but setting up the configuration as it says the README, nothing works. No errors, but no results neither (trying to use i18n with the pipe option).

```
<h2 class="text-center">{{'LOGIN.TITLE' | translate}}</h2>
```

**What is the motivation / use case for changing the behavior?**
Does not work for me as the README tells.

**Please tell us about your environment:**

* **ng2-translate version:** 4.2.0

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** Chrome 54.0.2840.99 
 
* **Language:** TypeScript 2.0.3

**Comment by SamVerschueren** [comment]
You're right, that is incorrect.

**Comment by cbeldacap** [comment]
@SamVerschueren thnx for the quick feed-back. But even so, as it appears in README does not work for me. And I'm setting it up in `app.module` and initializing it in `app.component.ts`, but I think the app does never load the `.json` files. What the path here is looking for?
```
TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: (http: Http) => new TranslateStaticLoader(http, 'i18n', '.json'),
            deps: [Http]
})
```

I have a folder `/i18n` at the same level of `app.component.ts`

thnx in advance

**Comment by SamVerschueren** [comment]
The easiest thing to debug that is looking in the network tab of the developer tools. Most of the time, this is due to the fact that those `.json` files aren't being copied over to the `dist` directory.

**Comment by SamVerschueren** [comment]
Could you share the issue? Might be nice for other people experiencing the same thing.

**Comment by cbeldacap** [comment]
I could find no solution. It might be something wrong with my project, so I'm trying so make a trial evolving the example of "systemjs".

**Comment by rsaenen** [comment]
I added ng2-translate to [Angular Quickstart](https://angular.io/docs/ts/latest/quickstart.html) and had the following error:
```bash
home:27 Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://sf-a.dev/app/ui/home/home.component.js:12:23)
	    at eval (http://sf-a.dev/app/ui/home/home.component.js:30:4)
	    at eval (http://sf-a.dev/app/ui/home/home.component.js:31:3)
	    at eval (<anonymous>)
	Evaluating http://sf-a.dev/node_modules/ng2-translate
```
This was my system.config.js:
```bash
paths: {
      // paths serve as alias
      'npm:': 'node_modules/',
      'unpkg:': 'https://unpkg.com/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',
      'ng2-translate': 'npm:ng2-translate/', (or 'npm:ng2-translate/bundles')
      ...
```
However, it work with 'unpkg:ng2-translate'. I changed to ''ng2-translate': 'npm:ng2-translate/bundles/ng2-translate.umd.js' and I had no more error.    
    
I hope this will help.

**Comment by cbeldacap** [comment]
I've finally discovered what my issue was caused by. I've had a HTTP interceptor to simulate a back-end in my project, so every HTTP operation was passing through it, even those dedicated to extract i18n values from .json files. That is why I could never get results.

Now it works perfectly and superfast.

thnx for feed-back and help

**Comment by sajeetharan** [comment]
@cbeldacap  do you have the link? i am also having the same issue

**Comment by SamVerschueren** [comment]
@sajeetharan What issue are you experiencing? Have you read https://github.com/ngx-translate/core/issues/359#issuecomment-267318337?

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
