### ISSUE TITLE
useMessageFormatInterpolation possible?

### ISSUE THREAD

**Issue by Itrulia** [ngx-translate/core#372]
Is there an option like useMessageFormatInterpolation from ng-translate for angular 1?

**Comment by ocombe** [comment]
Not yet, but there is something like that in Angular: https://angular.io/docs/ts/latest/api/common/index/I18nPluralPipe-pipe.html
It'd be nice to use it or do something similar

**Comment by Itrulia** [comment]
Damn... We have all the translations in message format already :/

**Comment by ocombe** [comment]
Well, you can make a PR to improve the parser, or you can write your own implementation of the parser to use instead of the default one :)

**Comment by Itrulia** [comment]
Ill see what I can do on the weekend :)

**Comment by Itrulia** [comment]
```
import {Pipe, PipeTransform, Injectable} from "@angular/core";
declare var Translation: any;
declare var MessageFormat: any;

@Injectable()
@Pipe({name: "translate"})
export class TranslatePipe implements PipeTransform {
    private messageformat: any;

    constructor() {
        this.messageformat = new MessageFormat(Translation.language);
    }

    transform(value: string, args: Object): string {
        const data = Translation.data[value] ? Translation.data[value] : value;
        return this.messageformat.compile(data)(args);
    }
}
```
For reference :)

This one works standalone and should be easy to implement (uses https://messageformat.github.io/)

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
