### ISSUE TITLE
No directive present in 2.5

### ISSUE THREAD

**Issue by mmikeyy** [ngx-translate/core#375]
**I'm submitting a ...**  (check one with "x")
```
[* ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
install 2.5.0 and directive "translate" does nothing. If I look in the code in the node_module directory, the word 'directive' is not even present anywhere.

**Expected/desired behavior**
well... I would have expected this to work.

Note that ng2-translate 2.3.1 works fine. I was interested in the 'translate' directive and couldn't install 2.4.x as it would cause all sorts of problems. So I took the ts file for the directive from Github , fixed the imports and all was ok.

I just saw that 2.5 came out and seemed to have the problems I had been having with 2.4.1 fixed, so I tried to install it. The errors are gone. The pipe works. But the directive is nowhere to be found.

I added the directive to my project using the ts sources on github. **The problem now is that the directive accesses translateService.getParsedResult, which is private**.

The directive finally works if one modifies the translate service and changes the getParsedResult method to public.

**Please tell us about your environment:**

* **ng2-translate version:** x.x.x
2.5.0
* **Angular version:** 2.0.0-rc.X
 2.4.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 chrome (latest)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
ts

**Comment by ocombe** [comment]
Hello,

sorry but the directive was added in version 4.1.0: https://github.com/ocombe/ng2-translate/releases/tag/v4.1.0

If you want to use it, just update the library.

Unless you're talking about 5.0.0 when you say 2.5.0 ?
