### ISSUE TITLE
How to resolve this issue / * UNMET PEER DEPENDENCY @angular/core@^2.0.0 --- UNMET PEER DEPENDENCY @angular/http@^2.0.0 └── ng2-translate@5.0.0 

### ISSUE THREAD

**Issue by balr404** [ngx-translate/core#399]
Could you please guide me how to resolve the issue 

├── UNMET PEER DEPENDENCY @angular/core@^2.0.0
├── UNMET PEER DEPENDENCY @angular/http@^2.0.0
└── ng2-translate@5.0.0 

npm WARN enoent ENOENT: no such file or directory, open '/Users/package.json'
npm WARN ng2-translate@5.0.0 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN ng2-translate@5.0.0 requires a peer of @angular/http@^2.0.0 but none was installed.

**Comment by ocombe** [comment]
Hello,
It's pretty self explanatory: you should install @angular/core@^2.0.0 & @angular/http@^2.0.0 by yourself to make the library work.

**Comment by andrashatvani** [comment]
But this is a restriction as I currently use 2.2 and want to upgrade to 2.4 - any hints?

**Comment by ocombe** [comment]
What do you mean by this is a restriction? 2.2 and 2.4 both satisfy ^2.0.0 (notice the `^` which means superior to)

**Comment by andrashatvani** [comment]
This is what I assumed, too, but still get this error

**Comment by ocombe** [comment]
Are you using npm 2.x? It doesn't handle peer dependencies well

**Comment by andrashatvani** [comment]
No, 3.3.12

**Comment by andrashatvani** [comment]
@balr404 I think you were in the wrong folder /Users, and not in the project folder.

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
