### ISSUE TITLE
Automatic generation of translation keys

### ISSUE THREAD

**Issue by cdparra** [ngx-translate/core#401]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[X] feature request
```

**Current behavior**
For each new string, developers have to manually add the string to the locale files

**Expected/desired behavior**
For each new string included in a partial (e.g., each new use of the angular translate directive or service), automatically add the new string to the default language locale file

**What is the motivation / use case for changing the behavior?**
To facilitate the translation workflow

**Comment by ocombe** [comment]
Hi, you can already use this cli tool for that: https://www.npmjs.com/package/@biesbjerg/ng2-translate-extract

**Comment by cdparra** [comment]
Interesting, I will try that out. Thanks!

**Comment by Chuvisco88** [comment]
@cdparra I used the ng2-translate-extract as well, works like a charm. So if this solves your issue, can you close it? :)
