### ISSUE TITLE
[suggestion] add language direction 

### ISSUE THREAD

**Issue by AsimNet** [ngx-translate/core#405]
Hello,

thanks for your effort guys..

I'm currently trying to support RTL languages and i'm using this plugin. Is there a method to get the direction of the selected language (RTL OR LTR)?. I suggest to pass a parameter with selected language that determine the direction, so we can use it to update the UI.

how we update the UI?, execute this code inside app.component.ts constructor:
`this.platform.setDir('rtl', true);`

thanks

**Comment by ocombe** [comment]
Closing this issue because it's a duplicate of https://github.com/ngx-translate/core/issues/374
