### ISSUE TITLE
An issue with loading JSON (language resource) files when the angular-cli build is used

### ISSUE THREAD

**Issue by manumqln** [ngx-translate/core#413]
I found an issue with loading JSON (language resource) files when the angular-cli build is used and the whole application is put under a subfolder and base href is changed. Currently, `404 Not Found `error is displayed since the library tries to access the file from (`<domain>/assets/i18n/en.json`) instead of the (`<domain>/subfolder/assets/i18n/en.json`) even though the base href is updated accordingly. The application works fine if I put it in the root folder.

In my opinion, the library should try to prepend the base href in all cases. Just a suggestion. Looking forward to resolving it.

Thanks in advance.

**Comment by SamVerschueren** [comment]
@ocombe Would we be able to inject [APP_BASE_HREF](https://angular.io/docs/ts/latest/api/common/index/APP_BASE_HREF-let.html) somewhere in order to prefix the path with that value?

**Comment by julianpoemp** [comment]
i got this issue, too. How can this be fixed?

**Comment by raemounz** [comment]
May I know how you were able to make it work? For my case, I followed the documentation however nothing happens, no error at all.

**Comment by julianpoemp** [comment]
in app.module.ts make sure that you use this HttpLoaderFactory function:
````
export function HttpLoaderFactory(http: Http) {
	return new TranslateHttpLoader(http, "./assets/i18n/", ".json");
}
````
that fixed this issue for me.

**Comment by raemounz** [comment]
i have the following inside my AppModule
`export function HttpLoaderFactory(http: Http) {
  return new TranslateHttpLoader(http, "./assets/i18n/", ".json");
}`
`  imports: [
    BrowserModule,
    HttpModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [Http]
      }
    })
  ],`
inside app.component.ts, I have the following:
`  constructor(translate: TranslateService) {
    translate.setDefaultLang('en-US');
    translate.use('en-US');
  }
`
and i have the file src/assets/i18n/en-US.json

is there anything I did wrong?

**Comment by julianpoemp** [comment]
I'm not sure, but did you try just "en" instead of "en-US"?

**Comment by raemounz** [comment]
I also tried just "en" for both the config and the filename, but still nothing happens.  Could it be because I'm using some MockBackend?  But I don't know if it has any relation.

**Comment by julianpoemp** [comment]
what's the output of your web console? Are you sure that you have followed the instructions exactly and the file exists in path "src/assets/i18n/en.json"?
Do you use the translate pipe properly? For example (assuming your en.json contains this):
````
{
 "continue": "Continue",
"generals": {"test":"Test"}
}
````
you have to insert this in your template:
````
<p>{{"continue" | translate}}</p>
or
<p>{{"generals.test"}}</p>
````
I don't know MockBackend, sorry.

**Comment by angryanatole** [comment]
I have the same issue here. I'm not sure why, but it searches files from my domain, not the app folder.
I'm using it with Angular CLI, if it matters.

**Comment by lchimaru** [comment]
I had the same issue, but changing `      "assets": [
        "assets",
        "favicon.ico"
      ],` to `      "assets": [
        "assets/",
        "favicon.ico"
      ],` helped me solved it.

**Comment by ac3ju** [comment]
Did you solved it ?

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.

If you need an example with the CLI, see https://github.com/ngx-translate/example

**Comment by hackerunet** [comment]
Sorry to reopen this, I'm using angular 6 and I have this issue, this is the output error 
```
Successfully synced application br.com.westsat.rastreamento on device emulator-5554.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR {
JS:   "headers": {
JS:     "normalizedNames": {},
JS:     "lazyUpdate": null,
JS:     "headers": {}
JS:   },
JS:   "status": 404,
JS:   "statusText": "ERROR",
JS:   "url": "/data/data/br.com.westsat.rastreamento/files/app/i18n/pt.json",
JS:   "ok": false,
JS:   "name": "HttpErrorResponse",
JS:   "message": "Http failure response for /data/data/br.com.westsat.rastreamento/files/app/i18n/pt.json: 404 ERROR",
JS:   "error": "Not Found"
JS: }
JS: ERROR {
JS:   "headers": {
JS:     "normalizedNames": {},
JS:     "lazyUpdate": null,
JS:     "headers": {}
JS:   },
JS:   "status": 404,
JS:   "statusText": "ERROR",
JS:   "url": "/data/data/br.com.westsat.rastreamento/files/app/i18n/pt.json",
JS:   "ok": false,
JS:   "name": "HttpErrorResponse",
JS:   "message": "Http failure response for /data/data/com.domain.mob/files/app/i18n/pt.json: 404 ERROR",
JS:   "error": "Not Found"
JS: }
```
My NS project doesn't have the structure sugested to place something in assets, I don't have that folder and If I place my json files in /app/i18n I get this error, or in /i18n/ I also got this error, my NS version is 4.2 and rxjs is also 6
this is my app.module.ts
```
import { NgModule, NgModuleFactoryLoader, NO_ERRORS_SCHEMA } from "@angular/core";
import {BrowserModule} from '@angular/platform-browser';
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { NativeScriptUISideDrawerModule } from "nativescript-ui-sidedrawer/angular";
import { NativeScriptHttpClientModule } from "nativescript-angular/http-client";
import { NativeScriptFormsModule } from "nativescript-angular/forms";
import { HttpClientModule, HttpClient, HTTP_INTERCEPTORS } from "@angular/common/http";
import { AuthenticationInterceptor } from "./shared/interceptors/authentication.interceptor";
import {TranslateModule, TranslateLoader} from '@ngx-translate/core';
import {TranslateHttpLoader} from '@ngx-translate/http-loader';

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

import { LoginComponent } from "./login/login.component";
import { MenuComponent } from "./menu/menu.component";

import { UtilsService } from "~/shared/services/utils.service";
import { APIService } from "~/core/api.service";
import { Configuration } from "~/core/configuration";
// AoT requires an exported function for factories
export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(http, "/i18n/", ".json");
}
// Maps
@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        AppRoutingModule,
        BrowserModule,
        HttpClientModule,
        NativeScriptModule,
        NativeScriptFormsModule,
        NativeScriptUISideDrawerModule,
        NativeScriptHttpClientModule,
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: HttpLoaderFactory,
                deps: [HttpClient]
            }
        })
    ],
    declarations: [
        AppComponent, LoginComponent, MenuComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ],
    providers: [UtilsService, Configuration, APIService, {
        provide: HTTP_INTERCEPTORS,
        useClass: AuthenticationInterceptor,
        multi: true
    }]
})
export class AppModule { }
```
I'm a desperate man!!

**Comment by cikcoh** [comment]
HI, i have question, sometimes the server is down and json file failed to fetch. so i have a tryagain() function in components tryin to load whatever needed api again including fetching json file again in that function too. how do i call this function in componets? can anyone help me?
export function HttpLoaderFactory(http: Http) {
	return new TranslateHttpLoader(http, "./assets/i18n/", ".json");
}

**Comment by Justicea83** [comment]
// Copy assets to out dir. Add your own globs as needed.
        new CopyWebpackPlugin(
            [
                { from: { glob: "assets/**" } },
                { from: { glob: "fonts/**" } },
                { from: { glob: "i18n/*.json" } },
                { from: { glob: "**/*.jpg" } },
                { from: { glob: "**/*.png" } },
            ],
            { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] },
        ),

This { from: { glob: "i18n/*.json" } }, makes sure all the i18n JSON files are copied to bundle.

**Comment by udhayaganesh85** [comment]
try this 2 option..it worked for me

export const environment = {
  production: true,
  appRootPrefix: '/<<Your project name>>'
};

export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}
