### ISSUE TITLE
[feature request] use ngx-translate in nodejs

### ISSUE THREAD

**Issue by atiertant** [ngx-translate/core#414]
we would like to use ngx-translate on nodejs server to generate internationalized pdf on server, is it possible to use ngx-translate on server side with nodejs?

**Comment by SamVerschueren** [comment]
Why aren't you looking for a node specific solution? Like [i18n-node](https://github.com/mashpie/i18n-node) for instance? `ngx-translate` is, like the name suggests, an Angular library. So as long as you aren't rendering your pdf content with Angular, I don't think this library can be of much help for you.

**Comment by ocombe** [comment]
If you're looking to use it with angular universal (server side) then yes it works

**Comment by atiertant** [comment]
just would like to share the same translations file beetween angular client side and server side

**Comment by ocombe** [comment]
You'll have to provide a loader for the server side that works with nodejs, like this one: https://gist.github.com/ocombe/593d21598d988bf6a8609ba5fc00b67e
And use your usual loader client-side

**Comment by atiertant** [comment]
yes but how to instanciate ngx-translate out of angular in node?

**Comment by ocombe** [comment]
ah that's not possible, it only works if you use Angular Universal on the server side

**Comment by atiertant** [comment]
is there a node specific module fully compatible with ngx-translate format ?

**Comment by SamVerschueren** [comment]
Not that we're aware of. The most used/famous one in node-land is probably [i18n](https://github.com/mashpie/i18n-node). You might be able to configure it to behave the same way but I'm not sure about it.

**Comment by Xalbi** [comment]
> is there a node specific module fully compatible with ngx-translate format ?
@atiertant 
Hello, am looking for the same thing, did you find something.
thnx
