### ISSUE TITLE
The pipe doesn't work with IE

### ISSUE THREAD

**Issue by Naouf3l** [ngx-translate/core#415]
Hi,

I'm using the ng2-translate pipe, it works good with any browser except internet explorer.
I have nothing in the browser console.

If anyone knows something about this issue, please help!

thank you guys! 

* **ng2-translate version:** 5.0.0

* **Angular version:** 2.4.3-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by rtyx** [comment]
Happens to me too. Any idea we it might be happening?
