### ISSUE TITLE
angular 2 translate on ionic2 + TS behaves differently depending amount of arguments

### ISSUE THREAD

**Issue by tryadelion** [ngx-translate/core#418]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ X] support request => check the FAQ and search github for a similar issue before submitting
[ X] feature request
```

**Current behavior**

When executing code with different arguments, the library returns different results based on them, althought that is never stated on the documentation. examples:

**When using 2 arguments, it will return an array:**

```js
this.translate.get(['appname','loading']).subscribe((translation: [string]) => {
      SpinnerDialog.show(translation[0],translation[1],false);
    });
```

**When using 1 argument, it will return an object based on the return type params (that's ok):**
```js
this.translate.get('appname').subscribe((translation: string) => {
      SpinnerDialog.show(translation,"",false);
    });
```
**when using 3 arguments, it will return an object ( this is wrong, should return an array instead, right')**
```js
this.translate.get(['appname','unable_complete','ok']).subscribe((translation: [string]) => {
          console.log(translation);
          let translationLet : any =  translation;
          console.log(JSON.stringify(translationLet));
          let alert = this.alertCtrl.create({
            title: translationLet.appname,
            subTitle: translationLet.incorrect_credentials,
            buttons: [translationLet.ok]
          });
          alert.present();
        });
```

**Expected/desired behavior**
There's no need to change the behaviour of it, **BUT**, it should be mandatory to **Write in the documentation how it exactly works** so nobody gets stuck for over a quarter of a day guessing why the array position [0] will return undefined always.

**Comment by SamVerschueren** [comment]
Can you create a plunkr for that behavior because I'm not seeing it. When using an Array of keys, it should always return an object. Either when using 1, 2, 3 or more values.

**Comment by tryadelion** [comment]
I am unable to reproduce it, might be due to a forced upgrade of almost every plugin i did this morning for a push to prod.Still,  wouldn't it make sense that when providing a collection, the output also be in a collection? anyway, the object with properties return value is not properly documented **or i  might have missed it**. For sure the angular 1 version returned an array.

**Comment by ocombe** [comment]
it might indeed be missing in the documentation, also there's a PR to change this behavior in some cases: https://github.com/ngx-translate/core/pull/412
I haven't had time to take a deep look at this yet

**Comment by tryadelion** [comment]
Checked again, can't reproduce. 

the section to perfectionate is 4. , currently only shows default 1-param behaviour.

> 4. Use the service, the pipe or the directive:
> 
> You can either use the TranslateService, the TranslatePipe or the TranslateDirective to get your translation values.
> 
> With the service, it looks like this:
> 
> translate.get('HELLO', {value: 'world'}).subscribe((res: string) => {
>     console.log(res);
>     //=> 'hello world'
> });

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
