### ISSUE TITLE
Soft hyphen / wbr-tag  handling

### ISSUE THREAD

**Issue by kontza** [ngx-translate/core#419]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
Soft hyphen in translated text is rendered out as-is. E.g. I have a translated string: "Video&shy;lähetykset". The example is in Finnish, where we have compound words abound. Therefore there is a need for controlling the break point of the word. Anyway, on the page, it is rendered such that the `&shy;` is visible. Then I tried `<wbr>`, with the same result, the tag is rendered as part of the string.

**Expected/desired behavior**
The translation would be rendered without the `&shy;` or `<wbr>` being visible.

**Reproduction of the problem**
http://plnkr.co/edit/Q6U7d7Ssv4ducAcLlgrW

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
The documentation states that we can use HTML tags within translations.

**Please tell us about your environment:**

* **ng2-translate version:** 5.0.0

* **Angular version:** 2.2.1
 
* **Browser:** [Chrome 56.0.2924.87 | Android 5.0 Web View ] 
 
* **Language:** [TypeScript 2.0.9]

**Comment by SamVerschueren** [comment]
Have a look at the docs on how to render html https://github.com/ngx-translate/core#5-use-html-tags

**Comment by kontza** [comment]
RTFM, I should've read few lines further :)
Thanks for the tip.
