### ISSUE TITLE
"No provider for TranslateService" error unit test with universal-cli

### ISSUE THREAD

**Issue by phatpham9** [ngx-translate/core#420]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Test specs**

![](https://cloud.githubusercontent.com/assets/3795964/22727609/5fffc872-ee0c-11e6-80dd-30debce69707.png)

**Error output**

![](https://cloud.githubusercontent.com/assets/3795964/22727573/247889d8-ee0c-11e6-85fb-5a323ebc835d.png)

**Please tell us about your environment:**

* **ng2-translate version:** 4.2.0
* **Angular version:** 2.2.3
* **Language:** TypeScript 2.0.3

**Comment by ocombe** [comment]
Hello, you have to call "forRoot" when you import the module so that it creates an instance of the service: `TranslateModule.forRoot()`.

**Comment by phatpham9** [comment]
I tried to add `.forRoot()` but it still does not work.
![](https://cloud.githubusercontent.com/assets/3795964/22728857/b7648bb0-ee12-11e6-8637-afd6b59d952d.png)

Same error
![](https://cloud.githubusercontent.com/assets/3795964/22728869/c1599a3e-ee12-11e6-936c-474dba71f497.png)

**Comment by ocombe** [comment]
You probably need to import it in the two testing modules that you're creating

**Comment by phatpham9** [comment]
Removed other module but don't know why it's still the same.
![](https://cloud.githubusercontent.com/assets/3795964/22729362/0261acfe-ee15-11e6-821e-6b7ca9815223.png)

**Comment by ocombe** [comment]
No idea either then :-/

**Comment by martinop** [comment]
I have a similar problem with Angular Universal using this lib, the problem is the server side rendering, If I import this lib inside the module of server i get an alert of Md5 get cookie or something.. because this lib use a own http module and Universal use other. Aswell I import using the isBrowser condition but get the error of "No provider for translate service" because we import the service but obviously dont have a Module

**Comment by ocombe** [comment]
The HttpModule is no longer part of the core in the version 6.

**Comment by martinop** [comment]
Yep, i know that but in the version 6 when import the Translate Module in the Shared Module I get:
Unexpected value 'TranslateModule' imported by the module 'SharedModule'

**Comment by phatpham9** [comment]
My bad. I forgot to import TranslateModule in its parent testing module. Close this issue.

**Comment by pmandapuram** [comment]
import this one into your spec file **import {} from 'jasmine';**
