### ISSUE TITLE
"Unexpected value 'TranslateModule' imported by the module 'SharedModule'" Universal Starter

### ISSUE THREAD

**Issue by martinop** [ngx-translate/core#422]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```
![screen shot 2017-02-08 at 10 19 21 am](https://cloud.githubusercontent.com/assets/10482079/22741006/2159835c-ede8-11e6-8413-831495e9ad05.png)

**Please tell us about your environment:**

* **ng2-translate version:** 6.0.0-beta.1

* **Angular version:** 2.4.6

**Comment by markelarizaga** [comment]
I'm getting a similar issue. I'm trying to use ngx-translate in Universal Starter but I'm getting:
`Unexpected value '[object Object]' imported by the module 'MainModule'`

In node.module.ts I import TranslateModule:
`import { TranslateModule, TranslateLoader } from '@ngx-translate/core';`

And I add the Module to the imports: 
`import {Observable} from "rxjs/Observable";
let fs = require('fs');
export class TranslateUniversalLoader implements TranslateLoader {
  public getTranslation(lang: string): Observable<any> {
    return Observable.create(observer => {
      observer.next(JSON.parse(fs.readFileSync(`i18n/${lang}.json`, 'utf8')));
      observer.complete();
    });
  }
}

@NgModule({
  bootstrap: [ AppComponent ],
  imports: [
    UniversalModule,
    FormsModule,
    RouterModule.forRoot([], { useHash: false }),
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useClass: TranslateUniversalLoader
      }
    }),
    AppModule
  ],
`

I omit the rest for brevity. If I don't include TranslateModule in the list of imports everything runs fine, but just including it causes the error mentioned above. I have been digging in the internals a bit and I would say that for some reason Angular is not recognizing TranslateModule as en ngModule, but I don't want to talk to loud before having a better understanding of this.

**Environment:**
- ngx-translate version: 6.0.0
- Angular version: 2.4.5
- Angular 2 universal: 2.1.0-rc.1

Any clue?

**Comment by markelarizaga** [comment]
I achieved to make this work finally.
The good way for me was to use ng2-translate instead of ngx-translate along with the angular and universal versions I mentioned in my last comment.

**Comment by thebarada** [comment]
I solve it just add @ngx- to **includeClientPackages** 

like in this repo https://github.com/angular/universal-starter/blob/master/webpack.config.ts#L88

**Comment by markelarizaga** [comment]
@thebarada It worked for me too, thanks!

**Comment by premiumwd** [comment]
@markelarizaga cant have service side code for client side render.
