### ISSUE TITLE
How to setup to test translate pipe in template?

### ISSUE THREAD

**Issue by phatpham9** [ngx-translate/core#429]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

Please help!

**Comment by SamVerschueren** [comment]
Please let us know what you've tried before asking questions because at this point, the only thing I can say is, read the [documentation](https://github.com/ngx-translate/core#usage).

**Comment by phatpham9** [comment]
This is my test spec:
![](https://cloud.githubusercontent.com/assets/3795964/22967758/558cc87a-f39a-11e6-9ca7-d327efec0347.png)

This is my template:
![](https://cloud.githubusercontent.com/assets/3795964/22967700/2ae44850-f39a-11e6-99c0-8e0faa82739b.png)

This is the error message:
![](https://cloud.githubusercontent.com/assets/3795964/22967677/0ef0f9b8-f39a-11e6-857b-f7bf85b38e56.png)

Thank you.

**Comment by ocombe** [comment]
Hu that weird, it looks like the import and forRoot definition are correct, I don't know why you get this error :(

**Comment by phatpham9** [comment]
@ocombe I'm new to jasmine. Don't know if I miss anything.

**Comment by ocombe** [comment]
I'm not sure why you use two beforeEach ? But other than that it seems correct

Wait, are you using version 6 or 5? The error message let me thinks that you installed version 5 but are using the configuration of version 6?

**Comment by phatpham9** [comment]
@ocombe I'm using ng2-translate 4.2.0 and angular 2.2.3. Anything wrong with it?

**Comment by ocombe** [comment]
Nothing except that the documentation is not the same. Use this one: https://github.com/ngx-translate/core/blob/fb02ca5920aae405048ebab50e09db67d5bf12a2/README.md
And especially the import is different for the forRoot method.

**Comment by phatpham9** [comment]
Ah it works but it seems the pipe does not work correctly in the template.
![](https://cloud.githubusercontent.com/assets/3795964/22969726/1ed1d48a-f3a2-11e6-97e5-1cad0485b23b.png)
![](https://cloud.githubusercontent.com/assets/3795964/22969743/2ed97374-f3a2-11e6-8ca1-90e21bca39c4.png)

**Comment by phatpham9** [comment]
@ocombe the pipe does not work in the template. Do I need to provide anything else to the testing module?

**Comment by ocombe** [comment]
yes, you need to initiate the translate service with "use" (either in the component, or in the tests) so that it knows which lang to load

**Comment by phatpham9** [comment]
@ocombe Could you please guide me how to do it in the tests?

**Comment by ocombe** [comment]
```ts
let injector = getTestBed();
let translate = injector.get(TranslateService);
translate.use('en');
```

**Comment by phatpham9** [comment]
@ocombe thank you so much I did it. Close the topic now.
