### ISSUE TITLE
Language bundle is loaded twice if default and used lang are the same

### ISSUE THREAD

**Issue by chpasha** [ngx-translate/core#432]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ x ] feature request
```

**Current behavior**
the following code causes the same bundle to load twice if fallback and current languages are the same
translate.setDefaultLang(defaultLang);
...get current lang from cookie/storage/etc
translate.use(currentLang); 
if currentLang is the same as defaultLang we can see that the requested bundle is loaded twice. 

**Expected/desired behavior**
I'm not sure that there are no side effects but does it make sense to avoid loading the same bundle again if it coincides with fallback language? So the use method could do everything including language change event emit, but do not loaded any bundles again.

**Comment by SamVerschueren** [comment]
I swear I saw this coming by a week or so ago, so it's a duplicate. Just can't find it for now :). Keeping it open though.

**Comment by dhardtke** [comment]
https://github.com/ngx-translate/core/issues/397#issuecomment-275368243

**Comment by ocombe** [comment]
Yes, this is a duplicate, closing it
