### ISSUE TITLE
Getting 404 Not Found for translation files.

### ISSUE THREAD

**Issue by elliotwesoff** [ngx-translate/core#433]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Receiving this error message in console output:
EXCEPTION: Response with status: 404 Not Found for URL: /assets/i18n/en-us.json

**Expected/desired behavior**
No error message

**Reproduction of the problem**
I've followed the readme exactly and have been struggling for a few hours to get this working.  Using the translate.setTranslations method works, but using the HTTP loader does not.

**What is the expected behavior?**
Translation files are loaded properly.

**What is the motivation / use case for changing the behavior?**
Doesn't work.

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.0

* **Angular version:** 2.4.0
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by SamVerschueren** [comment]
It looks like the tool you are using to build your application doesn't copy your translation files. Make sure the file `en-us.json` exists in the directory `assets/i18n`. If not, make sure you copy them over to the `dist` directory.

**Comment by elliotwesoff** [comment]
Sorry, I just figured it out.  The InMemoryWebApiModule was intercepting the HTTP loader's request.  Thanks for the quick reply!

**Comment by LeHoanVu** [comment]
how to fix ?

**Comment by elliotwesoff** [comment]
@LeHoanVu if you're using the InMemoryWebApiModule for mock network requests, you'll need to remove it.  In my case I ended up writing my own static loader to ensure that everything is loaded before attempting to process translation keys.

**Comment by dgroh** [comment]
Having the same issues. Files are in the dist folder, but I still get 404. Probably because of the base href="/app" ?

**Comment by mike1130694** [comment]
Elliot. Is it possible that you share some more information regarding your static loader? I'm new to angular and found exactly this problem. My application is running perfectly but if I add the InMemoryWebApiModule in the app.module like this "InMemoryWebApiModule.forRoot(InMemoryDataService)," i get an error that my json translations files are not found.

I would truly appreciate your help with this.

**Comment by elliotwesoff** [comment]
Hey @mike1130694 , I unfortunately cannot share any code with you as I'm legally not allowed and the repository is private. I can tell you though that you add a reference to your synchronous loader class in the app module, where you would normally import the TranslateModule. For the synchronous loader class, it's simply an Observable that resolves immediately, and inside you load the translation json file. I'm pretty new to Angular myself so I know how tricky it can be. However, Angular 4 now includes a translation library which may be easier to implement than a synchronous loader for this module.  Check it out here: https://angular.io/guide/i18n
