### ISSUE TITLE
Setup for non-root modules

### ISSUE THREAD

**Issue by jsprds** [ngx-translate/core#434]
Hi I'm currently experimenting with this package for one of my projects. I'm building stand alone components wrapped by different modules which can be included in different apps. Some of these modules have some translatable content so I'm looking for a solution to provide the translations in the most efficient way.

Is it possible to use a fresh instance of ngx-translate for each component-module so I can provide the component with his translations? 

I followed the `shared module` approach and ended with something like this:

```
// app.module.ts (this is the app)
...
export function HttpLoaderFactory(http: Http) {
    return new TranslateHttpLoader(http);
}
...
@NgModule({
    ...
    imports: [
        ...
        HelloWorldModule,
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: translateLoaderFactory,
                deps: [Http]
            }
        })
        ...
    ]
    ...
})
...
```

```
// hello-world.module.ts (this the component module and will be loaded in the app module through npm)
...
export function HttpLoaderFactory(http: Http) {
    return new TranslateHttpLoader(http, 'assets/i18n/helloworld');
}
...
@NgModule({
    ...
    imports: [
        ...
        TranslateModule.forChild({
            loader: {
                provide: TranslateLoader,
                useFactory: translateLoaderFactory,
                deps: [Http]
            }
        })
        ...
    ]
    ...
})
...
```

The translation file for `HelloWorldModule` is not loaded so I guess I'm missing something? 
Is what I'm trying to do possible? I can provide translations for the `HelloWorld module` through the translation file included by the `app component` but that's not ideal for my situation, the Component module can't be separated from his translations.

Image of the architecture:
![test](http://i.imgur.com/uKc3aFt.jpg)

**Comment by dhardtke** [comment]
Probably related to #425?
