### ISSUE TITLE
In version 6, there is an error showing while trying to import http-loader in the app.module.ts

### ISSUE THREAD

**Issue by manumqln** [ngx-translate/core#437]
Are you sure you are exporting `TranslateHttpLoader`? I could not find any in the source code and it shows error 'cannot find module' when I am trying to import it. Can you please check?

Thanks in advance.

**Comment by manumqln** [comment]
Managed to resolve it finally. 

I had to install http-loader for this which was not mentioned in the docs.

**Comment by anphu7492** [comment]
I got the same error. For those who trying to fix it: https://www.npmjs.com/package/@ngx-translate/http-loader

**Comment by jongunter** [comment]
Should this issue should be re-opened until the docs get fixed?
