### ISSUE TITLE
Directive approach does not work

### ISSUE THREAD

**Issue by stevermeister** [ngx-translate/core#439]
**I'm submitting a ...** 

[ x ] bug report
[ ] support request 
[ ] feature request

**Current behavior**
Directive approach
```<span [translate]="HELLO'"></span> ```
does not update the text when I switch to another language.
http://stackoverflow.com/questions/42349738/ngx-translate-pipe-vs-directive

plunker - https://plnkr.co/edit/PykLBrZGI1jz7Imsnzz6?p=preview

**Comment by Verurteilt** [comment]
Pretty weird, I think this problem could be related to the checkNodes function inside the directive, anyway, if you change your code to this one, it works:

`<h2 translate>HOME.TITLE</h2>`

**Comment by stevermeister** [comment]
I know about the option
```<h2 translate>HOME.TITLE</h2>```

but actually the idea, why I want to use exactly *directive* approach is I still want to keep original text in template, i.e.:

```<span [translate]="HELLO'">Hello Dear User</span>```

**Comment by xtgrant** [comment]
Hi @stevermeister 
I'm having the same issue. When using directive as attribute with value,
<span [translate]="HELLO'"></span>
will not work because the checkNodes function only queues elements with text length > 0.
Because <span> has no text length, the checkNodes method will not go into the for loop.

If you add a space in the <span> </span>, it will work.
The space gives <span> a length of 1 and it goes into the loop.

This is in fact a bug.

**Comment by stevermeister** [comment]
@xtgrant 

you probably did not get my point, I have more than space in between:

    <span [translate]="HELLO'">Hello Dear User</span>

**Comment by xtgrant** [comment]
Oh, if this code sample is from your actual code, then it's your syntax. you are missing single quote before the HELLO.
`<span [translate]="'HELLO'">`

**Comment by stevermeister** [comment]
I provided a plunker with exact code, you can check there. Quotes are on their place

**Comment by xtgrant** [comment]
Found this:
https://github.com/ngx-translate/core/issues/355

Yea looks like there its trust issues from parent binding when implementing [directive]="" notation.
https://angular.io/docs/ts/latest/guide/attribute-directives.html#!#why-input

Please read this portion. @input allows the properties to be trusted references.

**Comment by stevermeister** [comment]
yes,  #355 looks similar.

it should do the check 
https://github.com/ngx-translate/core/blob/master/src/translate.directive.ts#L85

I think I need to dive in code myself, otherwise I'll never get an answer here  :)

**Comment by sGerli** [comment]
I'm having the same issue with directive, they aren't updating.

**Comment by f1ssl** [comment]
Had the same problem, but 

<span [translate]>HELLO</span>

did it for me.

But i think this is not the total solution. Will there be a bugfix concerning this issue?

**Comment by stevermeister** [comment]
ideally I would like to have response from @ocombe for this issue

**Comment by ocombe** [comment]
Seems like a bug to me: when the key is forced it doesn't detect changes because the key is always the same...
We should always set `node.lastKey = null;` when `forceUpdate` is true in the `checkNodes` method for the directive
