### ISSUE TITLE
Translate message from server

### ISSUE THREAD

**Issue by kresogalic8** [ngx-translate/core#440]
Hello guys, is there any possibility to translate content from the server, here's my example. I have something like this sweetalert('Success', res.content.msg, 'success'); and I want to translate res.content.msg. Any solution for that?

```
saveGroup() {
      this._api.send(urlValues.addAdminGroup, 'Post', this.groupForm.value).subscribe(
        res => {
          sweetalert('Success', res.content.msg, 'success');
          this._router.navigate(['./administrators']);
        },
        err => sweetalert('Error', err.content.msg, 'error')
      )
    }
```

**Comment by SamVerschueren** [comment]
By injecting the service and use `get` or`instant` https://github.com/ngx-translate/core#4-use-the-service-the-pipe-or-the-directive

**Comment by kresogalic8** [comment]
Can you please give me an example based on my code?

**Comment by SamVerschueren** [comment]
```js
    constructor(private translate: TranslateService) { }

    saveGroup() {
      this._api.send(urlValues.addAdminGroup, 'Post', this.groupForm.value).subscribe(
        res => {
          sweetalert('Success', this.translate.instant(res.content.msg), 'success');
          this._router.navigate(['./administrators']);
        },
        err => sweetalert('Error', err.content.msg, 'error')
      )
    }
```

**Comment by kresogalic8** [comment]
One more question. How can I translate hard coded values like 'Success'? Can I also use instant? Can you please write me that also? You will help me a lot with this solution? Thanks in advance

**Comment by SamVerschueren** [comment]
Yes totally, it's the exact same way.

```js
sweetalert(this.translate.instant('success'), this.translate.instant(res.content.msg), 'success');
```

**Comment by kresogalic8** [comment]
Thank you @SamVerschueren. I really appreciate your answer.
