### ISSUE TITLE
Single json file

### ISSUE THREAD

**Issue by elmartino** [ngx-translate/core#443]
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

HI!

Is there a possibility to load and use only one single custom json object for the translations over http?
the structure of the json object returned by the webservice looks like:

```
en
  word: translation
  word2: translation
nl
  word: translation
  word2: translation
```

Thanks in advance!

Regards,
Martin

**Comment by SamVerschueren** [comment]
Just wondering why you would want that? That means that if one language is 1MB in size, you will ship 3MB of data to your end-users if you offer 3 different languages.

**Comment by elmartino** [comment]
I'm working on the migration of the frontend of an application. This is how it's done right now and how the data get's received from the backend

**Comment by deeg** [comment]
You could probably already achieve this if you wanted to, although I haven't tried.

Take a look at the [translation service methods](https://github.com/ngx-translate/core#methods) for setTranslation.

You could probably just get ahold of the JSON file and manually set the translations yourself in JS.

**Comment by picard31** [comment]
@elmartino , are there news ?

I'm in the same situation as you from several days, but can't find an effective solution.

**Comment by dgresko** [comment]
@elmartino , Did you find a solution for this?
