### ISSUE TITLE
Duplicate requests when using use & setDefaultLang

### ISSUE THREAD

**Issue by deeg** [ngx-translate/core#447]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

* Load the [plunker example from the home page](https://plnkr.co/edit/01UjWY3TKfP6pgwXKuEa?p=preview)
* Notice en.json file is fetched twice (see the network tab)
    * This has to do with the following two lines fetching en.json:

``` 
translate.setDefaultLang('en');
translate.use(browserLang.match(/en|fr/) ? browserLang : 'en');
```

**Expected/desired behavior**

The en.json file should only load once. I know you can wait for .use to complete by subscribing to it and calling setDefaultLang file after, but I was wondering if you wanted to take a different approach in the library:

* When the library starts to fetch a translation file, do not fetch any more until that is complete.

I can look into putting out a PR for this, but wanted to see your thoughts before I started. Is this something that should be handled by the lib, or should the user be the one to make sure you aren't calling setDefault and use at the same time for the same language?

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.0

* **Angular version:** 2.4.8

**Comment by SamVerschueren** [comment]
duplicate https://github.com/ngx-translate/core/issues/397#issuecomment-275368243

**Comment by deeg** [comment]
Sorry about that, I did try searching too!

**Comment by SamVerschueren** [comment]
No problem :)
