### ISSUE TITLE
Core documentation link broken

### ISSUE THREAD

**Issue by dexygen** [ngx-translate/core#451]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Core documentation link (http://core.ngx-translate.com/) on home page results in a "not found".  Perhaps it should be linked to https://github.com/ngx-translate/core/blob/master/README.md instead

**Comment by ocombe** [comment]
Thanks you're right, do you want to make a PR on this file https://github.com/ngx-translate/ngx-translate-website/blob/master/src/app/components/app.component.ts ? Or I can make the change otherwise.
