### ISSUE TITLE
MissingTranslationHandler is never called

### ISSUE THREAD

**Issue by amirduran** [ngx-translate/core#452]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
MissingTranslationHandler is never called even though the translation doesn't exist

**Expected/desired behavior**
MyCustomMissingTranslationHandler should be called when translation doesn't exist in translation JSON array.

**Reproduction of the problem**
First I implemented my custom MissingTranslationHandler
```
import {MissingTranslationHandlerParams, MissingTranslationHandler} from "ng2-translate/src/translate.service";

export class MyCustomMissingTranslationHandler implements MissingTranslationHandler {
    handle(params: MissingTranslationHandlerParams) {
        console.log("Missing translation");
        console.log(params);
    }
}
```
In my main AppModule I have registered missingTranslation handler like this: 

```
TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: (store: Store<any>) => new StoreTranslateLoader(store),
            missingTranslationHandler: {provide: MissingTranslationHandler, useClass: MyCustomMissingTranslationHandler},
            deps: [Store]
        }),
```

In my template file I want to translate the string which doesn't exist:

`{{"halllou yeah" | translate}} `

Console logs in MyCustomMissingTranslationHandler are never printed in console.

**What is the expected behavior?**
Console logs from my MyCustomMissingTranslationHandler should be printed in console

**What is the motivation / use case for changing the behavior?**
We could easily extend MissingTranslationHandler to send and API request every time when we encounter untranslated word.

**Please tell us about your environment:**

* **ngx-translate version:** >=4.0.0 <5.0.0

* **Angular version:** 2.x.x
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by chrillewoodz** [comment]
Try with something that would actually be a valid json property, like `hallo_yeah`.

**Comment by sangecz** [comment]
mine MissingTrans. handler also not being called at all

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
