### ISSUE TITLE
Translateloader.getTranslation observable not beeing observed?

### ISSUE THREAD

**Issue by nbijl-worthit** [ngx-translate/core#453]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I created a implementation of the TranslateLoader. This loaders get the translations from a json file , and from a remote api. When the getTranslations method return a observable, the first value I send to it is the json file, the second is the response from the api. 

Somehow the second value is never displayed on the page.

**Expected/desired behavior**
When a observable is defined as the return value of a method, I expect it to handle multiple values. I had a look in your code, and tried to remove the .take(1) calls but that made no difference. 

This is my implementation of the TranslateLoader.getTranslations:
```typescript 
getTranslation(lang: string): Observable<any> {
        return new Observable(observer => {
            observer.next(i18nTexts[lang]);
            this.apiService.getTranslations(lang).subscribe(
                (response: Response) => {
                    const corrections = response.json() as Object;
                    observer.next(Object.assign(Object.assign({}, i18nTexts[lang]), corrections));
                },
                (error: Error) => {
                    observer.next(i18nTexts[lang]);
                });
        });
    }
```

**Please tell us about your environment:**
"dependencies": {
        "@angular/common": "^2.4.9",
        "@angular/compiler": "^2.4.9",
        "@angular/core": "^2.4.9",
        "@angular/forms": "^2.4.9",
        "@angular/http": "^2.4.9",
        "@angular/platform-browser": "^2.4.9",
        "@angular/platform-browser-dynamic": "^2.4.9",
        "@angular/router": "^3.4.9",
        "core-js": "^2.4.1",
        "ng2-translate": "^5.0.0",
        "rxjs": "^5.2.0",
        "ts-helpers": "^1.1.1",
        "zone.js": "^0.7.6"
    },

* **Browser:** [all]

Let me know if this is a know issue or if there is something else I can try

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
