### ISSUE TITLE
setTranslation with shouldMerge throws out old translations when combined with lazy loading

### ISSUE THREAD

**Issue by Delta388** [ngx-translate/core#454]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

My setup: I use lazy loading to load separate modules, every module has its own version of a custom loader loading some translations specific to the module when they are loaded, this works fine and the different instances share translations as intended (they are not isolated)

But I also have additional translations to be loaded deeper into a module, for this I load the translation, then use "setTranslation" with shouldMerge=true to add the translations to the current ones.

When I do this, the whole thing behaves very oddly, it merges the new translations with the one from the lazy loaded version of the custom loader, but the originally loaded translations are dropped.

**Expected/desired behavior**

setTranslation with shouldMerge = true shouldn't drop already loaded resources

**Reproduction of the problem**
http://plnkr.co/edit/aNfjJyfP1aLjSAItXeps

Simple setup with a lazy loaded module and another component loading additional translations. As you can see in the AdditionalComponent, the translation loaded by the lazy loaded module ("TEST") and the additionally loaded translation ("ADD") are still available after I call setTranslation, but the original one ("TITLE") is gone.
 
* **ngx-translate version:** 6.0.0

* **Angular version:** 2.4.8
 
* **Browser:** Chrome 56.0.2924.87 ]

**Comment by sebelga** [comment]
I am seeing the same behavior.
I first load a "common" translation file in my forRoot.
Then I go to a lazyloaded module that loads its translation file in a forChild.
But the "common" translation file never get loaded...

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
