### ISSUE TITLE
Allow deep cloning

### ISSUE THREAD

**Issue by jlberrocal** [ngx-translate/core#456]
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
If you try to merge an object with deep keys, the Object.assign is replacing since the second level, this indeed is the expected behavior of that method, you can check the MDN documentation about Object.assign

**Expected/desired behavior**
Allow deep cloning

**What is the expected behavior?**
I solved my problem using jQuery.extend in recursive mode, however it could be nice that this library will handle it by it's own, and not use Object.assign or maybe add other parameter for recursive mode

**Comment by unsafecode** [comment]
+1 Experienced the same, and it was kind of tricky to debug. Would be nice to support deep merge, since we're talking about plain JSON and not complex JS objects.

**Comment by unsafecode** [comment]
This looks nice and tiny enough to be embed, IMHO:
https://github.com/KyleAMathews/deepmerge

**Comment by jlberrocal** [comment]
Yes, you are right @unsafecode the problem is that it seems that @ocombe is far of this project for a time

**Comment by ocombe** [comment]
aye, sorry guys, got a lot of stuff on my plate while working for the core team :)

**Comment by jlberrocal** [comment]
@ocombe could you please add this feature, i already made the PR actually i'm stuck because of this

**Comment by ocombe** [comment]
Yeah I'll try to work on this tonight after my work :)

**Comment by jlberrocal** [comment]
wow excellent thanks, i really appreciate it
