### ISSUE TITLE
Directive within ngPlural fails

### ISSUE THREAD

**Issue by Waitak** [ngx-translate/core#457]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

I'm attempting to do:

    <span [ngPlural]="form.controls.items.length">
      <template ngPluralCase="=0">{{'ITEM.PLURAL_ZERO'|translate}}</template>
      <template ngPluralCase="=1">{{'ITEM.PLURAL_ONE'|translate}}</template>
      <template ngPluralCase="other" translate [translateParams]="{count: form.controls.items.length}">ITEM.PLURAL_OTHER</template>
    </span>

where the translations are defined as:

    {
        "ITEM": {
            "PLURAL_ZERO": "No items",
            "PLURAL_ONE": "One item",
            "PLURAL_OTHER": "{count} items"
        }
    }

**Expected/desired behavior**

I expect the same behavior with the directive as with the pipe. The pipe works, the directive doesn't.

**Reproduction of the problem**

The behavior is illustrated here:

http://plnkr.co/edit/NqCrSco4P7kaPpbZLMCE

**What is the expected behavior?**

As above

**What is the motivation / use case for changing the behavior?**

Using translate with plurals.

**Comment by victorlevasseur** [comment]
I think the directive doesn't work with ng-container and ng-template/template tags.

**Comment by ocombe** [comment]
No it doesn't, it manipulates the DOM (which honestly is probably not a very good idea). The pipe is a safer bet.
