### ISSUE TITLE
Translate not working for ionic date-time.

### ISSUE THREAD

**Issue by rashedshaon** [ngx-translate/core#458]
**I want to translate ionic date-time.**  

**ionic usually works like following code to translate date-time**

`<ion-datetime displayFormat="DDDD MMM D, YYYY" [(ngModel)]="myDate" monthNames="janeiro, fevereiro, march, ..." ></ion-datetime>`

I'm using **monthNames="{{ 'MONTHS' | translate }}" or [monthNames]="'MONTHS' | translate"** as translation rules of ng2-translate but its not work just showing an error Cannot read property 'length' of undefined.

in en.json file I use
```
{
"MONTHS": "Janua,Febru,Mar,Apr,May,June,Jul,Augus,September,October,November,December"
}
```

If there are any other solution please answer.

**Comment by antoine92190** [comment]
Try adding a space after each comma:

"Janua, Febru, Mar, Apr, May, June, Jul, Augus, September, October, November, December"

**Comment by sebrojas14** [comment]
Someone?

**Comment by mikifus** [comment]
Hi,

Despite I am quite new using ionic, I found a solution to this issue, hope it helps someone.

In html use:
`[monthNames]="months_names"`

Then in ts:
`this.months_names = this.translate.instant("MONTHS");`
