### ISSUE TITLE
Suppress interpolation if no value is found

### ISSUE THREAD

**Issue by TylerDev6** [ngx-translate/core#461]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x ] feature request
```

**Current behavior**
interpolation will not be parsed if params object is null

**Expected/desired behavior**
hide interpolation tokens if params object is not supplied

**What is the motivation / use case for changing the behavior?**
In some cases we are using data from the server or user-entered values as interpolation keys so these are fetched asynchronously. The pipe detects when the value has changed but until then it displays the ugly braces on the screen.... maybe this is a good option to add as a flag.

**Comment by n0daft** [comment]
Don't know your state on this but I just ran into the same problem and came up with a temporary solution using a pipe with ternary operator in interpolation params:

```
<mat-card-title>{{'your.translation.key' | translate: {number: customer ? customer.number : ''} }}</mat-card-title>
```

This way the translation logic is still only in the template and the ugly braces in case of null value disappear in favor of the empty string.

Hope this helps.

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
