### ISSUE TITLE
Can't get current language with translate.getBrowserLang(), it always return the same value

### ISSUE THREAD

**Issue by justforuse** [ngx-translate/core#463]
I want to get current language with `this.translate.getBrowserLang()` , but it always return 'en', but the app's language actually changed, here is the plunkr 
https://plnkr.co/edit/JEXgj8WcISYGtDg75VoR?p=preview ,and this is from the demo plunkr

here is my version:
```
"@ngx-translate/core": "^6.0.0",
"@ngx-translate/http-loader": "^0.0.3",
```

**Comment by ocombe** [comment]
Like its name suggests, `getBrowserLang` returns the lang of the **browser**.
If you want the lang setup for your application use `this.translate.currentLang`.

**Comment by justforuse** [comment]
@ocombe Sorry, my bad, I didn't notice it and thought it is the same with angular-translate, which use $translate.use() to get current language.
Thanks a lot.

**Comment by guntram** [comment]
.getBrowserLang() returns the FIRST default browser language.
I just changed my chrome from "de" to "en"...ok...working.
I wanted to change back to "de", but the german language was gone in the chrome settings, so i added it again and set it as the default browser language.
After all of that, the .getBrowserLang() still returns "en", because my "de" setting was the last of three ["en-us", "en", "de"], and the .getBrowserLang() only returns the first browser language, but NOT the one which is set as the default language.

**Comment by NiklasA** [comment]
Hi,

I can reproduce the issue described by Guntram. Could anyone please review this issue?

![image](https://cloud.githubusercontent.com/assets/5022295/26784268/082b7810-49fd-11e7-8993-012b2504f52d.png)

`.getBrowserLang()` will return english, but my Chrome is configured with german as preferred language.

Thanks in advance.
Niklas

**Comment by vinmontes** [comment]
@NiklasA and others.  I had the same issue.  This is how I solve it.  

Lets look at your screen shot, you notice that English is the first language on your list.  Well for some reason even if you select Deutsch as your browser language your  .getBrowserLang(); picks up the first language on that list which is English (see your screenshot) Deutsch is your second on your list.

You have to move Deutsch to the top of the list AND also make it your browser language in order for it to work.

**Comment by richflee** [comment]
@vinmontes How does this work with IE (particularly IE11) though? I've added languages to IE11 and shifted them to the top of my preferred languages, yet getBrowserLang() always returns 'en' as the language.

**Comment by rbirkgit** [comment]
getBrowserLang() doesn't seem to work with IE11. It always returns 'en' for me.

**Comment by tatsujb** [comment]
`this.translate.currentLang` is always undefined for me.
