### ISSUE TITLE
Get Translated value in html

### ISSUE THREAD

**Issue by TeodorKolev** [ngx-translate/core#467]
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```
Am I able to get translated value in html. Example:
```
<select required [(ngModel)]="model.type">
    <option *ngFor="let type of types" [value]="type">{{type | translate}}</option>
</select>
```
and Component:
```
constructor() {
        this.types = ['TYPES.CAR', 'TYPES.TRUCK']
}
```
This will return selected value as "TYPES.CAR". My target is ti return selected value in english > "Car", no matter what lang I have selected it. Something sort of:

```
<select required [(ngModel)]="model.type | translated in english...">
    <option *ngFor="let type of types" [value]="type">{{type | translate}}</option>
</select>
```

**Comment by SamVerschueren** [comment]
What about this?

```html
<select required [(ngModel)]="model.type">
    <option *ngFor="let type of types" value="{{type | translate}}">{{type | translate}}</option>
</select>
```

**Comment by TeodorKolev** [comment]
Nope, because I don't want in my database selected properties in all languages.

**Comment by SamVerschueren** [comment]
So what's wrong with this?

```html
<select required [(ngModel)]="model.type">
    <option *ngFor="let type of types" [value]="type">{{type | translate}}</option>
</select>
```

`model.type` is the type from the database/server with the value `TYPES.CARE` and will select `TYPES.CAR` from the option list which will render the translated value, hence the `{{type | translate}}`.

If you have a plunkr example that shows what you want, please share because I don't see any problem right now.

**Comment by TeodorKolev** [comment]
Because if it is translate to Chinese I will get some Chinese record as return. I do not want to do that. To get word "Car" in Chinese.

**Comment by SamVerschueren** [comment]
But what I suggested doesn't give you `Car` in chinese in the database. If gives you `TYPES.CAR` in the database but renders `Bla` (`Car` in chinese ;)) in the dropdown. Might be missing something here though, not sure :p.

**Comment by TeodorKolev** [comment]
But when selected I got for example: "TYPES.CAR", I want to get from return not TYPES.CAR but this translated in Enlish, which is "Car"

**Comment by lobnazakaria** [comment]
were you able to translate several different text in an array using ngFor ??
i want to translate several text but i don't know how to use translate pipe 
i would like help please
