### ISSUE TITLE
Update external documentation to point to renamed package

### ISSUE THREAD

**Issue by jaufgang** [ngx-translate/core#470]
It seems that this package is a newer/renamed version of ng2-translate.

I would suggest ensuring that the old ng2-translate npm page  https://www.npmjs.com/package/ng2-translate be updated to let people know that the newest version has a different name and pointing them in the right direction.

Also would be a good idea to ensure that the ionic 2 docs (https://ionicframework.com/docs/v2/resources/ng2-translate/) get updated as well

**Comment by ocombe** [comment]
The url for the old package redirects here. The old package doesn't support the new versions of Angular, I'm confident that they will find this one whenever they need to update.
