### ISSUE TITLE
ng2-translate problem in unit test Jasmine

### ISSUE THREAD

**Issue by AhmedHadjTaieb** [ngx-translate/core#471]
**Reproduction of the problem**
I am using karma with Jasmine for unit testing my component of Angular 2 but when I open karma server in testing and open pages tested ng2-translate don't charging attributes references in json.
I find this problem just in unit test but when I start my project in dev mode all attributes have good charging from json.

***My code in the pictures :***
![capture d ecran 2017-03-18 a 17 15 18](https://cloud.githubusercontent.com/assets/22799068/24074013/774512c2-0c01-11e7-8514-e1b286dcb660.jpg)

**My environment:**

* **ng2-translate version:** 5.0.0

* **Angular version:** 2.4.8
* **Angular/cli version:** 1.0.0-rc.0
* **karma version:**  1.5.0
* **jasmine version:** 2.5.38
* **Browser:** Chrome

***Without Testing :***
![capture d ecran 2017-03-18 a 17 21 18](https://cloud.githubusercontent.com/assets/22799068/24074014/774a81bc-0c01-11e7-85f8-114331530171.jpg)
***With Testing in Karma :***
![capture d ecran 2017-03-18 a 17 19 45](https://cloud.githubusercontent.com/assets/22799068/24074015/774b770c-0c01-11e7-9d8f-31b64b765b63.jpg)

**Comment by ocombe** [comment]
Did you call .use() somewhere in your testing app? (like in a component that's you're testing)
if not then that's why it's not loading the json

**Comment by AhmedHadjTaieb** [comment]
@ocombe Yes, I do this in the first component but not in the same component testing because it will be redundance code when I call other component use ng2-translate , also I think if user change language in the first page and change the route to another page (component) the language will be changed or it's not logical... I search for another solution when the testing component work with here own ng2-translate just for testing...I hope you interstrand me.

**Comment by mmarimuthu** [comment]
were you able to resolve the issue ? if so, please explain.

**Comment by AhmedHadjTaieb** [comment]
@mmarimuthu sorry but problem not resolved 😢 ... If you have any other solution tell me 😃

**Comment by bankimatglobant** [comment]
Please let me know if anyone able to resolve the problem.

**Comment by IevhenIkonnykov** [comment]
Hello guys. Perhaps it is too late and not what you really want, but I had a similar problem. I needed to test a component that uses translation, but the TranslateService is used in a parent component. To test my component I had to substitute TranslateHttpLoader by my own like the following:
1. Inside **TestBed.configureTestingModule**:

```
imports: [
        TranslateModule.forRoot({
          loader: {
            provide: TranslateLoader,
            useClass: TranslateCustomLoader
          }
        })
      ]
```

2. **TranslateCustomLoader** itself:

```
import {TranslateLoader} from "@ngx-translate/core";
import {Observable} from "rxjs";

declare let readJSON: any;

export class TranslateCustomLoader implements TranslateLoader {
  getTranslation(lang: string): Observable<any> {
    if (lang=="ru"){
      let ru = readJSON('assets/i18n/ru.json');
      return Observable.of(ru);
    }
    let en = readJSON('assets/i18n/en.json');
    return Observable.of(en);
  }
}
```

3. **readJSON** function (file **read-json.js**):

```
var readJSON = function (url) {
  url = readJSON.base + url;

  var xhr = new XMLHttpRequest();
  var json = null;

  xhr.open("GET", url, false);

  xhr.onload = function (e) {
    if (xhr.status === 200) {
      json = JSON.parse(xhr.responseText);
    }

    else {
      console.error('readJSON', url, xhr.statusText);
    }
  };

  xhr.onerror = function (e) {
    console.error('readJSON', url, xhr.statusText);
  };

  xhr.send(null);
  return json;
};

readJSON.base = '';

try {
  if (exports) {
    exports.readJSON = readJSON;
  }
}

catch (error) {
  //exports not available so not loaded by require
}
```

4. Make appropriate changes in **karma.conf.js** (include file with readJSON function and *.json files with translations):

```
files: [
      './src/assets/scripts/read-json.js',
      {pattern: './src/test.ts', watched: false},
      {pattern: './src/assets/i18n/*.json', included: false}
    ]
```

5. Inside of **descibe** declare a service:

`let translateService: TranslateService;`

and inject it before each test:

```
beforeEach(inject([TranslateService], (service) => {
    translateService = service;
    translateService.use('en');
  }));
```

this forces TranslateService to load translations and also you can change language in your test.

I hope it will be useful for someone. Good luck!

**Comment by linux-nerd** [comment]
@IevhenIkonnykov You are a savior. The solution worked for me!!

**Comment by IevhenIkonnykov** [comment]
@linux-nerd It seems like you have different matchers that cover the same files. I am not sure, but perhaps it would be right to check you matchers or make them more precise. To be honest I do not have a real solution for your problem. When you fix it would be great to share your solution. Actually I do not have anything like that in my tests. Good luck.

**Comment by bobrosoft** [comment]
Just run into testing of the component which uses ngx-translate. I don't think it matters for unit tests to have correct translation displayed in the component, you're usually testing functionality, not translation itself (which makes no sense almost and can lead to broken tests over time when translation changes). So using only bare `TranslateModule.forRoot()` in TestBed imports is pretty fine imho.

**Comment by beyerleinf** [comment]
After following the guide by  @IevhenIkonnykov I get the error ```No provider for TranslateService!```
Any idea?

**Comment by xmeng1** [comment]
@IevhenIkonnykov thanks for your solution, it works. By the way, just be careful the path of the file.
```
export class TranslateCustomLoader implements TranslateLoader {
  getTranslation(lang: string): Observable<any> {
    if (lang === 'zh-CN') {
      const zhCN = readJSON('../../assets/i18n/zh-CN.json');
      return Observable.of(zhCN);
    }
    const en = readJSON('../../assets/i18n/EN.json');
    return Observable.of(en);
  }
}
```
this path should be the relative path to file with the class defined.

**Comment by govindarajkp** [comment]
In Angualr5 getting error   ReferenceError: inject is not defined

**Comment by IevhenIkonnykov** [comment]
Just checked my tests in Angular 5.2.6 and they work as before. Perhaps there is another problem that you experience.

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.

You can find an example of unit test with this lib here: https://github.com/ngx-translate/example/blob/master/src/app/app.component.spec.ts

I'm accepting PRs to add more complex tests.

**Comment by JerinJ** [comment]
@ocombe 

While writing unit test case for translate, Even though we are able to test multi-lingual support, still branch completion is not 100%, it lagging on `browser language get call` negative case.

Please find the screenshot attached.
![image](https://user-images.githubusercontent.com/2240674/74329678-4548b180-4db6-11ea-88a2-3c8c3c5d483b.png)

We tried the spec available in the example provided, it too has not covered the branch
https://github.com/ngx-translate/example/blob/master/src/app/app.component.spec.ts

We also tried to send mock data using spyon
`spyOn(translate, 'getBrowserLang').and.returnValue('de');`

Can anybody help us here!!!!

**Comment by ocombe** [comment]
This case is only happening in some old versions of IE, it should never occur in a normal scenario.
You know that you don't need 100% coverage, right?
But if you really *need* it, then you could set `window.navigator.languages`, `window.navigator.language`, `window.navigator.browserLanguage` AND `window.navigator.userLanguage` to `null`

**Comment by JerinJ** [comment]
@ocombe 
Currently we are in start of the project, thus we are trying to cover as much as possible from every corner. 

We are working with Google Chrome Version 80.0, still facing the issue.

We tried to change the browser language via `window.navigator` but as `languages` is read-only it not allowing to reset it.

Please find the attached screenshot for the ref.

![image](https://user-images.githubusercontent.com/2240674/74331707-411e9300-4dba-11ea-8315-624b5485dddf.png)

**Comment by ocombe** [comment]
you need to do `(window as any).navigator.languages = null;`

**Comment by JerinJ** [comment]
Even though we are able to change it, but karma-jasmine is bit smarter. :-;

![image](https://user-images.githubusercontent.com/2240674/74332144-239df900-4dbb-11ea-82e5-ebea00e1f822.png)

**Comment by ocombe** [comment]
Well too bad then...
But I don't understand why `spyOn(translate, 'getBrowserLang').and.returnValue('de');` doesn't work

**Comment by JerinJ** [comment]
@ocombe 

Got a workaround to make branch cover uptill 100%.

Raised PR for the same: [Pull Request](https://github.com/ngx-translate/example/pull/6)
