### ISSUE TITLE
Question regarding making a library

### ISSUE THREAD

**Issue by rahul0923** [ngx-translate/core#473]
Hi Oliver,
First thanks for sharing this library. Very useful, clean and simple. I wanted to get your advice of creating a library for some of my angular modules. I looked at this link https://medium.com/@OCombe/how-to-publish-a-library-for-angular-2-on-npm-5f48cdabf435#.4pow4qrpc and wanted to confirm if this is still relavant or is there any other process that I should follow?

Thanks,
Rahul

**Comment by ocombe** [comment]
Hello,

it can still be used, but it's a bit outdated.
You should probably look at this article from Minko Gechev http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/
And take a look at that starter: https://github.com/preboot/angular-library-seed

**Comment by rahul0923** [comment]
Thanks very much Oliver!!

Regards,
Rahul
