### ISSUE TITLE
Catching Missing Translation File Error

### ISSUE THREAD

**Issue by ting-yun-career** [ngx-translate/core#474]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When translation file is missing, a console log is thrown reporting file not found error.

**Expected/desired behavior**
I want to be able to catch this error and process this in a callback handler.

**Reproduction of the problem**
http://plnkr.co/edit/ftorfSr6MSksHL93LLbN?p=preview,
Here I set the translate.use('Martian') to fetch a non-existing language file. If you pull up the console log you will see martian.json not found error.

**What is the expected behavior?**
I tried to use try... catch and .catch() on translate.use() but both failed. the try ... catch doesn't catch the thrown error. I tried to .catch() it but output doesn't make any sense to me. Running out of ideas.

**What is the motivation / use case for changing the behavior?**
To keep console.log clean.

**Please tell us about your environment:**
Mac OS Yosemite

* **ngx-translate version:** x.x.x
from packages.json:
    "@ngx-translate/core": "6.0.0",
    "@ngx-translate/http-loader": "0.0.3",

* **Angular version:** 2.x.x
2.4.8
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Test in Chrome only so far

**Comment by moarsel** [comment]
I also had this problem. The temporary workaround was to use `translate.getTranslation()` instead, which doesn't swallow the error.
