### ISSUE TITLE
String is fallback to default lang for a second under slow network

### ISSUE THREAD

**Issue by kennch** [ngx-translate/core#479]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When the network is slow (by setting chrome's network throttling), the page is rendered with default language first, and then quickly switched to desired language.

For example, the default language is EN, and the desired language is same as browser (CN here). When the network is slow, the page is shown as EN first, and then auto switched to CN in a second.

**Expected/desired behavior**
Show the desired language without switching under slow network

**ngx-translate version:** 6.0.1

**Angular version:** 2.x.x & 4.0.0
```typescript
export class AppComponent implements OnInit {
  private _defaultLang: string;
  private _browserLang: string;

  constructor(private _translate: TranslateService) { }

  ngOnInit() {
    this._defaultLang = 'en-us';
    this._browserLang = this._translate.getBrowserCultureLang().toLocaleLowerCase();

    this._translate.setDefaultLang(this._defaultLang);
    this._translate.use(this._browserLang);
  }
}
```

Thanks.

**Comment by CodeAndWeb** [comment]
1) You don't have a language set. 
2) You set the default - which gets loaded - and since nothing else is set becomes the visible language
3) You switch to the browser language - which gets loaded and displayed

Try switching `.use()` and `.setDefaultLang()`.
