### ISSUE TITLE
Cannot find name 'TranslateStaticLoader'.

### ISSUE THREAD

**Issue by Debananda** [ngx-translate/core#482]
Not able to call http services to get the translation sources

**Current behavior**
Cannot find name 'TranslateStaticLoader'.

**Expected/desired behavior**
'TranslateStaticLoader' shall be there to load translation sources from service calls.

ngx-translate version:** 6.0.1
Angular version:**4

**Comment by ocombe** [comment]
`TranslateStaticLoader` doesn't exist in version 6.x anymore, it has been replaced by `TranslateHttpLoader` (you will need to install the npm module `@ngx-translate/http-loader`): https://github.com/ngx-translate/http-loader
