### ISSUE TITLE
ng build -prod errors in ng4

### ISSUE THREAD

**Issue by qiushuiqs** [ngx-translate/core#484]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When I running `ng serve -prod` or `ng build -prod` via angular-cli, errors occurs 

> ERROR in .../src/$$_gendir/app/app.component.ngfactory.ts (1,1): Property 'translate' does not exist on type

It is running well on development mode.

**Reproduction of the problem**
Dont know how to setup the ng4 env in the plunker

**app.component.ts**
```
export class AppComponent implements OnInit {
    public supportedLangs;

    constructor(private _translate: TranslateService) {
        this._translate.addLangs(["en", "zh"]);
        this._translate.setDefaultLang('en');

        let browserLang = this._translate.getBrowserLang();
        this._translate.use(browserLang.match(/en|zh/) ? browserLang : 'en');
        this.supportedLangs = { en: 'English', zh: '中文' }
    }

    ngOnInit() {
    }
}
```

**Please tell us about your environment:**

* **ngx-translate version:** ^6.0.1

* **Angular version:** 4.0.0
 
Thanks!!

**Comment by SamVerschueren** [comment]
Would be happy to look into it if you are able to reproduce this in a GitHub repository.
