### ISSUE TITLE
Problem with TranslateService in Pipe

### ISSUE THREAD

**Issue by phatpham9** [ngx-translate/core#485]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I'm creating a new pipe that uses translate service inside. Code below:

```javascript
export class TimeRemainingPipe implements PipeTransform {
    constructor(private translateService: TranslateService) {}
    transform(input: any, args?: any): any {
        return this.translateService.get('TEST').subscribe(res => res);
    }
}
```

When I use that pipe in the template, what I got is always `[object]` string. I think the problem is `observable/subscriber` but I don't know how to solve it.

Please help! Thank you very much.

**Comment by NKjoep** [comment]
@phatpham9  I think you should try to return a new observable which is *complete* when the translateService has done.

More or like you'd do with promises. Look here maybe it helps http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html

**Comment by phatpham9** [comment]
@NKjoep thanks for your reply. I've read it but still don't know how to do it :(.

Please help me to replace this code `return this.translateService.get('TEST').subscribe(res => res);` with returning new observable. Thanks a lot.

**Comment by NKjoep** [comment]
@phatpham9 have you tried with the example I wrote in the prev comment? :) the full code would be:

```js

export class TimeRemainingPipe implements PipeTransform {
    constructor(private translateService: TranslateService) {}
    transform(input: any, args?: any): any {
        return Observable.create((observer) => {
              this.translateService.get('TEST').subscribe((inputTranslated) => {
                    observer.next(inputTranslated);
                    observer.complete();
              });
       });
    }
}

```

**Comment by phatpham9** [comment]
Sorry @NKjoep I didn't see your edit in the previous comment. I just tried and the output still the same.

**Comment by phatpham9** [comment]
problem solved. the code is below

```javascript
@Pipe({
    name: 'timeRemaining',
    pure: false
})
export class TimeRemainingPipe implements PipeTransform {
    private result;

    constructor(private translateService: TranslateService) {}

    transform(input: any, args?: any): any {
        this.translateService.get('TEST').subscribe(res => this.result = res);
        return this.result;
    }
}
```

any thanks @NKjoep :)
