### ISSUE TITLE
Sending params to a nested JSON object

### ISSUE THREAD

**Issue by kgaspar** [ngx-translate/core#486]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When using the TranslateService to fetch the translation value from a nested JSON object, the additional param is not inserted in the translation.

**Reproduction of the problem**
Im using the TranslateService to get the translation value from a nested JSON file:

```Javascript        
    private showBatteryAlert(batteryValue: string){
        let batteryWarningTranslation;

        this.translateService.get('BatteryWarningAlert', {battery: batteryValue})
        .subscribe(
            value => batteryWarningTranslation = value
        );

        let alert = this.alertCtrl.create({
          title: batteryWarningTranslation.title,
          subTitle: batteryWarningTranslation.message,
          buttons: ['OK']
        });
        alert.present();
    }
```

The example nested JSON object:

```Javascript        
"BatteryWarningAlert":{
    "title": "Battery Warning",
    "message": "Your battery is at {{battery}}%. Connect your battery to a charger."
},
```
**_Example_**
If the batteryValue is for example a string "15", The batteryWarningTranslation.message would be:
 _Your battery is at {{battery}}%. Connect your battery to a charger._
instead of:
_Your battery is at 15%. Connect your battery to a charger._

I am using this in combination with Ionic 2

* **ngx-translate version:** 5.0.0
* **Angular version:** 2.2.1

**Comment by NodeJoSe** [comment]
@kgaspar im having the same issue, did you find a solution?

**Comment by NodeJoSe** [comment]
just found the solutions on [stackoverflow](https://stackoverflow.com/questions/46025829/angular-translate-service-interpolate-params-in-nested-json)

This is how you do it: 

```
this.translateService.get([
    'BatteryWarningAlert.title',
    'BatteryWarningAlert.message'
  ], {
    battery: batteryValue
  })
  .subscribe(value => {
    let alert = this.alertCtrl.create({
      title: value['BatteryWarningAlert.title'],
      subTitle: value['BatteryWarningAlert.message'],
      buttons: ['OK']
    }).present();
  });
```
