### ISSUE TITLE
When using @angular/router and accessing a component by its route url, the `get` never fires the Observable

### ISSUE THREAD

**Issue by ljean** [ngx-translate/core#490]
**I'm submitting a ...** 
```
[x] bug report 
[x] support request
[ ] feature request
```

**Current behavior**
When using `@angular/router` and accessing a component by its route url,  In `ngOnInit` the `get` method of the `Translation` service doesn't call the Observable  

Notes : 
* The text in templates translated with pipe is correct
* This just occurs on the first load of the page. When accessing the page after clicking a link, for example, everything is Ok.

**Expected/desired behavior**
 the `get` method of the `Translation`service should call the Observable  

**Reproduction of the problem**

I've try to make a code showing the problem here even if it is not possible to reproduce on plunker because it is not possible to run the page by providing the route URL. 

http://plnkr.co/edit/66Ne3Fnm8gDvSZDUoSUH?p=preview

If you click the 'CLICK ME' button, you will see that the `MyComponent` is loaded and injected in the page and the text is translated (even if I don't provide any translation, the `get` calls my Observable).

```
 --TEXT-- 
```

This is correct

If you could access the `MyComponent` directly from url at http://plnkr.co/edit/66Ne3Fnm8gDvSZDUoSUH/my-route (but unfortunately this is not AFAIK possible with plunker) you would see `MyComponent` loaded but the text would be  

```
--DEFAULT-- 
```

In this case, when component is directly loaded from a route/url the `get` method of the `Translation`service doesn't call the Observable  

**Please tell us about your environment:**

* **ngx-translate version:** 
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",

* **Angular version:** 4.0.0
 
* **Browser:** [all ]

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
