### ISSUE TITLE
UNPET MEER DEPENDENCY - @angular/common, core, http/ 2.3.0 -> 4.0.1

### ISSUE THREAD

**Issue by brada1703** [ngx-translate/core#491]
**I'm submitting a ...**  (check one with "x")
[X] bug report => check the FAQ and search github for a similar issue or PR before submitting

**Current behavior**

using "npm install @ngx-translate/core --save" I get the following error:

"
├── UNMET PEER DEPENDENCY @angular/common@4.0.1
├── UNMET PEER DEPENDENCY @angular/core@4.0.1
├── UNMET PEER DEPENDENCY @angular/http@4.0.1
├── @ngx-translate/core@6.0.1 
└── UNMET PEER DEPENDENCY tslint@5.0.0

npm WARN @angular/material@2.0.0-beta.2 requires a peer of @angular/core@^2.3.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.2 requires a peer of @angular/common@^2.3.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.2 requires a peer of @angular/http@^2.3.0 but none was installed.
npm WARN codelyzer@3.0.0-beta.4 requires a peer of tslint@^4.0.0 but none was installed.
"

**Expected/desired behavior** -> ngx-translate should allow angular 4

**Reproduction of the problem** -> See current behavior above

**What is the motivation / use case for changing the behavior?** -> so it works with angular 4

* **ngx-translate version:** 6.0.1

* **Angular version:** 4.0.1

**Comment by ocombe** [comment]
The peer dependency for ngx translate is `"@angular/core": ">=2.0.0"`.
The messages that you have don't come from ngx-translate but from angular material and codelyzer (for tslint).

**Comment by ocombe** [comment]
If you need the current version of material before the release you can use `npm install angular/material2-builds --save`, it's the nightly build.

**Comment by brada1703** [comment]
- Will the library work even with these errors? 
- Or would you suggest that I install @angular/core@^2.3.0, @angular/common@^2.3.0, @angular/http@^2.3.0, and tslint@^4.0.0 for the library to work? 
- Is it possible to have both @angular/core@^2.3.0 and @angular/core@^4.0.1 as dependencies?

Thanks!

**Comment by ocombe** [comment]
Angular material should work. v4 only deprecates things, the worst case scenario will be some warnings in the console that you're using deprecated things.
ngx translate works with v4 for sure (I'm testing the lib on v4).
You cannot have both v2 and v4 @angular/core, it would most likely break your build.

If you see that material really doesn't work with v4, you should probably install the last build that I linked above and wait for the new release that should come out shortly.

**Comment by brada1703** [comment]
Ok, Thanks Olivier! 👍
