### ISSUE TITLE
how to get user's browser or preferred language

### ISSUE THREAD

**Issue by louisdoe** [ngx-translate/core#493]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
With ionic 1 I was using this code to get the user's Preferred Language

```
navigator.globalization.getPreferredLanguage(function (language) {
                            this.translateService.use((language.value).split('-')[0]).then(function (data) {
                        }
```

**Expected/desired behavior**
Now I need to do the same with ionic 2, but I get this error if I use  `navigator.globalization`:
```
Typescript Error
Property 'globalization' does not exist on type 'Navigator'.
```

**Please tell us about your environment:**
$ ionic info

Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.4.0
Xcode version: Not installed

* **ngx-translate version:** last

* **Angular version:**  2.4.8
 
* **Browser:** Chromium 56

**Comment by Kr0n092** [comment]
Have you tried `navigator.language` ?

**Comment by malounna** [comment]
You should try the plugin cordova-plugin-globalization as explained here [https://ionicframework.com/docs/native/globalization/](url)

**Comment by trentclowater** [comment]
Since you're using Ionic 2, another alternative would be to use `Platform.lang()`.

**Comment by louisdoe** [comment]
I have tried navigator.language and I get errors.

Indeed @malounna, I installed the globalization plugin and it seems to work.

@trentclowater it seems that Platform.lang() returns the languages of the app and not the preferred language of the device, doesn't it ?
