### ISSUE TITLE
Can't use dots in default strings

### ISSUE THREAD

**Issue by amineparis** [ngx-translate/core#494]
I use default strings in English. Using dots extracts nested objects with indexes.
Eg: Using` <span translate>Loading ...</span>` produces
```
 "Loading ": {
		"0": {
			"0": {
				"0": ""
			}
		}
	},
```

How to handle this issue ?

**Comment by lkmkr** [comment]
If you are using @biesbjerg/ngx-translate-extract, use the json instead namespaced-json output format.
`--format, -f                Output format
          [string] [choices: "json", "namespaced-json", "pot"] [default: "json"]`

**Comment by CodeAndWeb** [comment]
That's not a "default string". It's a key that uses nested translations...
