### ISSUE TITLE
Translation of html element attributes

### ISSUE THREAD

**Issue by izub** [ngx-translate/core#496]
Is there any support for the translation of html element attributes (e.g. alt, title, placeholder)?
This is supported out of the box by Angular i18n.  See [Add i18n-... translation attributes](https://angular.io/docs/ts/latest/cookbook/i18n.html#!#translate-attributes).

To me, this is quite an important feature, especially for proper accessibility support.

`<img src="image.jpg" alt="This should be translatable" title="So should this">`
`<input placeholder="Some default text that should be translatable">`

**Comment by ocombe** [comment]
You can use bindings on attributes like this:
`<img src="image.jpg" [attr.alt]="'key' | translate">` or like this:
`<input placeholder="{{'key' | translate}}">`

I recommend the first one which will only set the value once it's available.

**Comment by idomiralin** [comment]
Could you please help me regarding this issue:

https://stackoverflow.com/questions/55646825/translate-attribute-values-with-ngx-translate-angular

**Comment by idomiralin** [comment]
I am trying to use ngx-translate for attribute values like p-messages text, p-column header, p-tabPanel header

<p-message text="text"></p-message>

<p-column header="text"></p-column>

<p-tabPanel header="text">

I tried the following but it doesn't work:

<p-tabPanel header="'key' | translate">

<p-tabPanel header="{{'key' | translate}}">

<p-tabPanel [attr.header]="'key' | translate">

Is there any way to use ngx-translate for these situations?

**Comment by idomiralin** [comment]
I am trying to use ngx-translate for attribute values like p-messages text, p-column header, p-tabPanel header

<p-message text="text"></p-message>

<p-column header="text"></p-column>

<p-tabPanel header="text">

I tried the following but it doesn't work:

<p-tabPanel header="'key' | translate">

<p-tabPanel header="{{'key' | translate}}">

<p-tabPanel [attr.header]="'key' | translate">

Is there any way to use ngx-translate for these?

**Comment by idomiralin** [comment]
I am trying to use ngx-translate for attribute values like p-messages text, p-column header, p-tabPanel header

        <p-message text="text"></p-message>
        <p-column header="text"></p-column>
        <p-tabPanel header="text">

I tried the following but it doesn't work:
         <p-tabPanel header="'key' | translate">
         <p-tabPanel header="{{'key' | translate}}">
         <p-tabPanel [attr.header]="'key' | translate">

Is there any way to use ngx-translate for these?
