### ISSUE TITLE
how to use use keys as english language ?

### ISSUE THREAD

**Issue by amineparis** [ngx-translate/core#498]
I had an existing project _(in English)._

To make it available in german I kept english labels as translation keys and added a new german translation files.

```
//Example
<span translate>First name</span>
```

**Problem :**  Is their a way to tell ngx-translate to use keys for english language instead of defining each time a redundant english file that contains key=value.

**Comment by P-H-F** [comment]
You could just use 'empty' translations for English (see `i18n/en.json` in my sample).
Per default the key is shown if the translation is not found.

Example: https://plnkr.co/edit/zvfGyIAv7dHIqUhz6eqO?p=preview

**Comment by amineparis** [comment]
great TY :)
