### ISSUE TITLE
Support simple primitive type in parser

### ISSUE THREAD

**Issue by Sergejack** [ngx-translate/core#499]
**I'm submitting a ...** 
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x ] feature request
```

TranslateDefaultParser  only gets value from objects

Allow to use primitive (number, string, ...) as well

**Reproduction of the problem**
One can't use the translate pipe providing a parameter which is a simple primitive type.
old-movie-reference.component.ts:
```
x: 300;
xObjectForParsing: { somePropertyName: x };
```

old-movie-reference.component.html:
`{{ 'HowManySpartans' | translate:xObjectForParsing.somePropertyName }}`

i18n/en.json:
```
{
"HowManySpartans": "How many spartans? {{ somePropertyName }}!"
}
```

**What is the expected behavior?**
old-movie-reference.component.ts:
`x: 300;`

old-movie-reference.component.html:
`{{ 'HowManySpartans' | translate:x }}`

i18n/en.json:
```
{
"HowManySpartans": "How many spartans? {{ valueOf() }}!"
}
```

**What is the motivation / use case for changing the behavior?**
It would be neat not to have to create object to work arround this limitation

* **ngx-translate version:** 6.0.

* **Angular version:** 4.0.0
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by CodeAndWeb** [comment]
We currently prefer to keep the api as simple as possible.
We might add it if more people request this feautre.
