### ISSUE TITLE
@ngx-translate source code installation fails using npm

### ISSUE THREAD

**Issue by smozhaykin** [ngx-translate/core#500]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I can't install @ngx-translate/core and @ngx-translate/http-loader source code using with the following lines in my package.json:

```
"ngx-translate-core-src": "git+https://github.com/ngx-translate/core.git#v6.0.1",
"ngx-translate-http-loader-src": "git+https://github.com/ngx-translate/http-loader.git#v0.0.3",
```

Result:

```
npm ERR! addLocal Could not install C:\Users\RUSMOZ~1\AppData\Local\Temp\npm-12620-e05ba842\git-cache-409d7c92\6d5c832e00b0c806f55c6f4d3539358a5ee1656
7
npm ERR! addLocal Could not install C:\Users\RUSMOZ~1\AppData\Local\Temp\npm-12620-e05ba842\git-cache-62c4aec1\35b48c365e812704b818915960e95d80e0c88da
1
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rusmozhaik\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.3.0
npm ERR! npm  v4.0.5

npm ERR! No version provided in package.json
npm ERR!
```

**Expected/desired behavior**

It should be possible to install source code using npm. Version is required in package.json

**Reproduction of the problem**
Add following dependencies into package.json and try to install it:

```
"ngx-translate-core-src": "git+https://github.com/ngx-translate/core.git#v6.0.1",
"ngx-translate-http-loader-src": "git+https://github.com/ngx-translate/http-loader.git#v0.0.3",
```

**What is the expected behavior?**

Dependencies should be installed

**What is the motivation / use case for changing the behavior?**

According to [this comment](https://github.com/npm/npm/issues/7105#issuecomment-73655360):

> There are only two parameters in package.json that are absolutely required – name and version.

**Comment by ocombe** [comment]
The version number is automatically generated when I push/merge new code,
depending on the commit messages, and a new version is released. The
version number is present on npm packages when the code is submitted to
npm, it's just not present on GitHub


> "x")
>
> [x] bug report => check the FAQ and search github for a similar issue or PR before submitting
> [ ] support request => check the FAQ and search github for a similar issue before submitting
> [ ] feature request
>
> *Current *
>

**Comment by smozhaykin** [comment]
@ocombe it's clear that version number is present on the package submitted to npm. But I'm trying to implement this approach on my application. I'm using ngx-translate for localization, but looks like both @ngx-translate packages (or at least @ngx-translate/core) are not supported by closure compiler. So I need to recompile it manually (in the same way as rxjs). I've tried to download source code using npm, but it failed.

If version won't be added to the source code, please close this issue.
