### ISSUE TITLE
How to dynamically change app base url by onLangChange event

### ISSUE THREAD

**Issue by k-majick** [ngx-translate/core#502]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ x ] support request => check the FAQ and search github for a similar issue before submitting
[ x ] feature request
```

**Current behavior**

Currently the app is using two urls generated by WP REST API and exported from file app.settings.ts in a class AppSettings:
```
export class AppSettings {
  public static APP_ENDPOINT_PL() {
    return 'http://domain.pl/wp-json/'
  };
  public static APP_ENDPOINT_EN() {
    return 'http://domain.pl/en/wp-json/'
  };
}
```
The above class is used by posts.servise to fetch posts content by a proper http request:
```
...
import { AppSettings, PATHSSERVICES } from '../app.settings';
import { TranslateService, LangChangeEvent } from '@ngx-translate/core';
import { TransService } from './trans.service';
...
  private urlBase = AppSettings.APP_ENDPOINT_EN();

  public getPosts(page: any = 1): Observable<Post[]> {
    return this.http
      .get(this.urlBase + PATHSSERVICES.posts.path + `?per_page=2&page=${page}&_embed`)
      .map((res: Response) => res.json());
  }
```

**Expected/desired behavior**

Now I'd like to be able to change the base url dynamically by using translate.onLangChange event in order to show translated content of posts. So far I managed to return the right path in the console by passing it to the `PostsService.appEndpoint` method:

```
  constructor(private http: Http, public translate: TranslateService) {
    translate.onLangChange.subscribe((event: LangChangeEvent) => {
      var myLang = translate.currentLang;
      if (myLang == "en") {
        PostsService.appEndpoint = AppSettings.APP_ENDPOINT_EN();
        console.log("en", PostsService.appEndpoint, myLang);
      }
      if (myLang == "pl") {
        PostsService.appEndpoint = AppSettings.APP_ENDPOINT_PL();
        console.log("pl ", PostsService.appEndpoint, myLang);
      }
    });
  }
```
However passing the `PostsService.appEndpoint` value to `private urlBase` like this: 
`private urlBase = PostsService.appEndpoint;` returns an undefined error. I suppose that one of the reasons might be that the value is not being set before the event occurs, so I should have it set it before it does. But I'm not even sure if using onLangChange in this manner is the right approach... Any hint will be appreciated:)

**What is the motivation / use case for changing the behavior?**

Translation of posts content on a single click along with other translations preset on trans.service.

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.0

* **Angular version:** 4.0.1
 
* **Browser:** [all]

**Comment by CodeAndWeb** [comment]
Sorry for not answering... we'll try to do better in the future.
I'm closing this issue for now. Please open a new issue if this problem still persists.
