### ISSUE TITLE
how to use a package to a stand-alone angular component

### ISSUE THREAD

**Issue by DanielYKPan** [ngx-translate/core#503]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[X ] feature request
```

**Current behavior**
Currently, In order to use the translateService, **TranslateModule.forRoot()** must be in the root NgModule of my application. What if I am building a stand-alone module and I want to use this package in my module.
I mean if I am building a module and I am going to publish it to npm. Using **TranslateModule.forRoot()** in my module will work. But once people import my module into their AppModule, **TranslateModule.forRoot()** in my module might cause problem. Using forChild() in my module might seem appropriate, but using forChild() would cause problem **No provider for TranslateStore!**.

Any solutions?

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:01UjWY3TKfP6pgwXKuEa

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-translate version:** x.x.x

* **Angular version:** 2.x.x
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by TomDemulierChevret** [comment]
I'm experiencing the same issue with a shared library I'm trying to build for some of my apps.

If I import TranslateModule.forRoot() both in my AppModule and in my LibraryModule, the translations are not found for the component provided by the library, only for the one inside the App.

Any ideas ?

**Comment by DenisVuyka** [comment]
Jan 2018 already and having the same problem

**Comment by valera33** [comment]
+1
it would be nice to be able to import it not only in the root NgModule of the application. I wonder why this restriction came at all?

**Comment by ocombe** [comment]
`forRoot` and `forChild` are just helpers to automatically configure the module, providers, etc...
You can do all of that on your own if you have a very special use case, look at what those functions do: https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/src/public_api.ts
They import the module, and then define a bunch of providers.
