### ISSUE TITLE
TranslatService does not translate after upgrading to angular 4.0.1

### ISSUE THREAD

**Issue by christophearg** [ngx-translate/core#505]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
TranslateService always returns the key instead of the translation as soon as i upgraded to angular 4.0.1
Same code was ok on angular 2.4.x.
The Pipe and template are translating correctly although.

**Expected/desired behavior**
Support angular 4.0.1

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.1

* **Angular version:** 4.0.1
 
* **Browser:** [all ]

**Comment by dhardtke** [comment]
Works fine for me with Angular 4.0.1 and ngx-translate 6.0.1 in conjunction with the http-loader.

Can you post parts of your code, i.e. your modules?

**Comment by starwarslover** [comment]
I have the same issue when i subscribe from ngOnInit in my component.

**Comment by christophearg** [comment]
Don't understand why, pipe and directive are well but service does not translate. I tried instant and get methods, both failing.

**Comment by SamVerschueren** [comment]
Try creating a minimal example in plunkr or on GitHub that reproduces this issue.

**Comment by christophearg** [comment]
On this plunker the get method is ok but instant is not. The translation is loaded because it appears in the pipe; I don't understand.
https://plnkr.co/edit/IKmp2M80waZUpLWPIYnc

**Comment by SamVerschueren** [comment]
From the documentation

> `instant(key: string|Array<string>, interpolateParams?: Object): string|Object`: Gets the instant translated value of a key (or an array of keys). /!\ This method is **synchronous** and the default file loader is asynchronous. You are responsible for knowing when your translations have been loaded and it is safe to use this method. If you are not sure then you should use the `get` method instead.

So because the `comp` component is initialised immediately, at that point, the translation is not yet loaded so in that case you can only use the `get` method. Best practice is to use the pipes though, but I agree that sometimes you need the service to load a translation. For instance when you want to show a toast notification etc.

**Comment by christophearg** [comment]
My problem is to change the title of the page. I saw this in the documentation, in my project i could not reproduce the get problem in the plunkr but it appears on my real projects. I stepped into the code and it appears that the translation array is empty when i use get or instant.

**Comment by SamVerschueren** [comment]
Well yes, see the description of the `instant` method. Locally this wouldn't cause problems because loading data from your localhost is almost instant. But when you deploy your app, loading the translation file will cause a delay. So I think you will have to subscribe to the `get` method in order to fix it. Nothing we can do here I'm afraid.

**Comment by christophearg** [comment]
Is there a way to know when the translations are ready? An event or something?

**Comment by SamVerschueren** [comment]
`TranslateService.use` returns an Observable so I believe you can subscribe on that one and if it completes, the language is loaded.

**Comment by christophearg** [comment]
Ok I will try this thank you.

De : Sam Verschueren [mailto:notifications@github.com]
Envoyé : mardi 18 avril 2017 19:53
À : ngx-translate/core <core@noreply.github.com>
Cc : christophearg <christophe_argento@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [ngx-translate/core] TranslatService does not translate after upgrading to angular 4.0.1 (#505)


TranslateService.use returns an Observable so I believe you can subscribe on that one and if it completes, the language is loaded.

**Comment by starwarslover** [comment]
You can try to subscribe for translations in the onLangChange event. It worked for me

**Comment by tomriddle1234** [comment]
I am experiencing the same issue with Ionic 3 (Angular 4.0.2） + ngx 6.0.1, the get method only gives the key  rather than its value, instant gives nothing. Please see https://github.com/ngx-translate/core/issues/464

**Comment by tomriddle1234** [comment]
I solved it by removing node_modules folder and run npm install again. Was using cnpm instead of npm.
