### ISSUE TITLE
Ionic 3.01 Lazy Module : The pipe 'translate' could not be found 

### ISSUE THREAD

**Issue by pegaltier** [ngx-translate/core#506]
**I'm submitting a issue because since the updated Ionic 3.0.0 the ngx-translate cannot be used with ionic lazy loading system.

**Current behavior**
When i load the page lazy loaded i get : 
`Uncaught (in promise): Error: Template parse errors: The pipe 'translate' could not be found (" <ion-header> <ion-navbar color="primary" hideBackButton="true"> <ion-title>{{[ERROR ->]"login.title"|translate}}</ion-title> </ion-navbar> </ion-header> "): ng:///LoginModule/LoginPage.html@8:17 `

**Expected/desired behavior**

**Reproduction of the problem**
Load the webapp using : ionic serve

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.1

* **Angular version:** 4.0.0
 
* **Browser:** [all ]

**Comment by SamVerschueren** [comment]
Make sure to import `TranslateModule` in your lazy loaded module as well. Or better, add `TranslateModule` to a `SharedModule` and import that `SharedModule` to every feature module.

**Comment by pegaltier** [comment]
Hi, @SamVerschueren thanks for your reply. i have done your idea and it work in dev mode (ionic serve) but when i build for production it dosn't work. Have you tested with ionic run android --prod ?

**Comment by SamVerschueren** [comment]
Have you looked at the [AoT](https://github.com/ngx-translate/core#aot) section? If yes, provide me with a minimal reproduction case (GitHub repository for instance) and I'll see what I can do. Not much time now to dive into it myself.

**Comment by pegaltier** [comment]
Finally i have solved my problem by adding : 
```
// AoT requires an exported function for factories
export function HttpLoaderFactory(http: Http) {
 return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}
```

And drawing inspiration from : https://github.com/ngx-translate/core/issues/209

Thanks @SamVerschueren

**Comment by SamVerschueren** [comment]
Glad it worked out :)

**Comment by pegaltier** [comment]
I have experienced new problem with lazy loading using ion-tabs component.
Have you experienced this component with lazy loading ?

Thanks

**Comment by SamVerschueren** [comment]
No sorry. This is an ionic issue so please file an issue over there.

**Comment by pegaltier** [comment]
Ok i will do this, have a good day!

**Comment by pegaltier** [comment]
Finally is ok for the tabs but you must use lazy for all tab inside pager

**Comment by wushuai820** [comment]
@pegaltier Do i have the same question that will let me see your code? please

**Comment by arthursp** [comment]
I thought the IonicPageModule.forChild() function should resolve this ? 

If it's loaded in app.module.ts, why should we add it to each page lazy loaded too ?

**Comment by erperejildo** [comment]
@pegaltier I got that error but I use lazy loading for all my pages

**Comment by helios1989** [comment]
how do you load the json file in lazyloaded module?
