### ISSUE TITLE
ng2-translate 5 requires peer dependency of angular/core 2

### ISSUE THREAD

**Issue by peterennis** [ngx-translate/core#507]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
![capture053](https://cloud.githubusercontent.com/assets/140737/24894654/b08975a4-1e40-11e7-9a25-8b06c68a95fb.png)

**Expected/desired behavior**

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Update to Ionic 3 and Angular 4

* **ngx-translate version:** x.x.x

* **Angular version:** 2.x.x
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ocombe** [comment]
Hello, you should update to version 6.0.1, it will solve your problem.
