### ISSUE TITLE
Ionic 2 input cursor not show properly

### ISSUE THREAD

**Issue by ykonstant** [ngx-translate/core#508]
we use ng2-translate in ionic 2, All things goes to fine, but on input field it not shows accurate effect. As we use in simple html 
<input type="text" dir="rtl">
it shows following effect
![screen shot 2017-04-11 at 5 23 15 pm](https://cloud.githubusercontent.com/assets/24272414/24907852/83353534-1edb-11e7-8b0c-0052b7d32bb1.png)

But when we use it in ionic 2, the cursor points to front of data, effect show very bad

**Comment by ocombe** [comment]
I don't see what this has to do with ng2 translate?
