### ISSUE TITLE
Update text not working | ionic 2

### ISSUE THREAD

**Issue by VesperDev** [ngx-translate/core#515]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
|| No update text in the span ||
I have a component called ion-range, basically I want to update the text with the selected range.

` <ion-label> <span [translate]="'SHOW_TASKS_DISTANCE'">SHOW_TASKS_DISTANCE</span> </ion-label>`

` <ion-range [(ngModel)]="objFilter.distance" min="0" max="30" step="1" color="primary" (ionChange)="onRefreshText()"></ion-range>`

Inside the function I have this code

`  onRefreshText() {

    this.translate.get('SHOW_TASKS_DISTANCE',
      { 'val': this.objFilter.distance }).subscribe((res: string) => {
        console.log(res);
      });

  }`

The printed output in console does it well but does not update the text, use the set function but only update it once.
What is printed on console is this

Show Tasks in 9 km distance.
Show Tasks in 10 km distance.
Show Tasks in 11 km distance.
Show Tasks in 12 km distance.
Show Tasks in 13 km distance.
Show Tasks in 14 km distance.
Show Tasks in 15 km distance.
Show Tasks in 16 km distance.
Show Tasks in 17 km distance.
Show Tasks in 18 km distance.
Show Tasks in 19 km distance.
Show Tasks in 20 km distance.
Show Tasks in 21 km distance.
Show Tasks in 22 km distance.

This text should be updated every time I select a range but it does not :(

what am I doing wrong?

Thanks for your time

**Expected/desired behavior**
Update the text correctly from the function onRefreshText()

**Please tell us about your environment:**

* **ngx-translate version:**  "ng2-translate": "^4.0.0" | ionic

* **Angular version:**  "@angular/core": "4.0.0", | ionic2
 
* **Browser:** [Mobile Chrome XX ]

**File img:**
![captura](https://cloud.githubusercontent.com/assets/14016458/25217722/95f08118-256d-11e7-9ef0-09b7706fcb94.PNG)

**Comment by CodeAndWeb** [comment]
Your label is missing the distance {{valu}} parameter.

    <div [translate]="'HELLO'" [translateParams]="{value: 'world'}"></div>
