### ISSUE TITLE
translate.instant vs translate.get

### ISSUE THREAD

**Issue by amineparis** [ngx-translate/core#516]
which is the better instant or get ? why we need get if instant allows us to have cleaner code without a lot of ugly embedded blocks ?

**Comment by SamVerschueren** [comment]
You can find more information in this discussion over here https://github.com/ngx-translate/core/issues/505#issuecomment-294913354.

From the documentation

> `instant(key: string|Array<string>, interpolateParams?: Object): string|Object`: Gets the instant translated value of a key (or an array of keys). /!\ This method is **synchronous** and the default file loader is asynchronous. You are responsible for knowing when your translations have been loaded and it is safe to use this method. If you are not sure then you should use the `get` method instead.
