### ISSUE TITLE
safely use translate.instant()

### ISSUE THREAD

**Issue by amineparis** [ngx-translate/core#517]
is theire a way to load translations when application starts so that we can safely use` translate.instant()`

**Comment by SamVerschueren** [comment]
Load the translations via `.use()` in the ngOnInit of your AppComponent. In some cases (slow server response) you might still end up with not translate values. That's why we recommend using the pipe as much as possible. As the docs describe, that's just how instant works. Nothing we can do about it I'm afraid.

**Comment by amineparis** [comment]
I am using it in the component.ts file. the need that makes me think of instant() instead of get() is the fact as it is much code cleaner since I don't need to embedd blocks to subscription

**Comment by xtoff** [comment]
@SamVerschueren I want the same thing :) 
Something like in Angular 1: https://angular-translate.github.io/docs/#/api/pascalprecht.translate.$translate#methods_instant

**Comment by mp3por** [comment]
Me too. This is too troubles right now. Especially if you need to get multiple words. There has to be a way to load the all the translations and them use translate.instant everywhere.

**Comment by kneefer** [comment]
All you need to do (as it was partially mentioned) is to preload translations using `.use()` method. The problem is the method is async (we should wait for the result). The best way to force the application to wait for "something" to finish before it shows up is using `APP_INITIALIZER` function in your `AppModule`.

You have to add to your `AppModule`'s `providers` section following provider:
```typescript
{
      provide: APP_INITIALIZER,
      useFactory: appInitializerFactory,
      deps: [TranslateService, Injector],
      multi: true
}
```

And define factory function `appInitializerFactory`:
```typescript
export function appInitializerFactory(
  translate: TranslateService,
  injector: Injector) {

  return () => new Promise<any>((resolve: any) => {
    const locationInitialized = injector.get(LOCATION_INITIALIZED, Promise.resolve(null));
    locationInitialized.then(() => {
      const langToSet = 'en-GB'
      translate.setDefaultLang('en-US');
      translate.use(langToSet).subscribe(() => {
        console.info(`Successfully initialized '${langToSet}' language.'`);
      }, err => {
        console.error(`Problem with '${langToSet}' language initialization.'`);
      }, () => {
        resolve(null);
      });
    });
  });
}
```
Now application will wait for translations initialization before it shows up for user.

**Comment by ocombe** [comment]
Yes sorry guys, that's how instant works. If you want you want "clean" code but don't mind with the fact that it's async or not, you could try using async/await since it works in typescript 2.3 now

**Comment by outsideMyBox** [comment]
I'm interested in having several languages loaded before using instant(). Does it work if I call use() on each of the languages and then, once everything has been loaded, use use() again to choose the current language for instant()?

**Comment by micobarac** [comment]
What happens when you have a multilanguage application and you have an option to switch between languages? How do you preload a new language then (on button click), without showing the translate token instead of actual translation (Angular 1 cloak, if you remember)?

**Comment by xStarman** [comment]
Hi,
I don't know if this is the best solution but worked for me:
string "init" is any key you want

```
translate.get('init').subscribe((text:string) => {
//use instant call here
});
```

**Comment by derek90** [comment]
> Hi,
> I don't know if this is the best solution but worked for me:
> string "init" is any key you want
> 
> ```
> translate.get('init').subscribe((text:string) => {
> //use instant call here
> });
> ```

Yeah, but that's not very clean when you need to set a lot of variables (like one per 'month' for example). Look at the next example, which is not working because is using 'instant':

`    this.config.set('monthNames', [
      this.translateService.instant('_january'),
      this.translateService.instant('_february'),
      this.translateService.instant('_march'),
      this.translateService.instant('_april'),
      this.translateService.instant('_may'),
      this.translateService.instant('_june'),
      this.translateService.instant('_july'),
      this.translateService.instant('_august'),
      this.translateService.instant('_september'),
      this.translateService.instant('_october'),
      this.translateService.instant('_november'),
      this.translateService.instant('_december')
    ]);`

You will need to use a subscription for every single variable :/

**Comment by arunsaibk** [comment]
this.translate.get(this.pageTitle).subscribe((text:string) => {
          this.translate.onLangChange.subscribe((event: LangChangeEvent) => {
            title.setTitle(this.translate.instant(text))
          });
        });

**Comment by Mythrim** [comment]
But I am not able to return value inside this:
translate.get('key').subscribe((text:string) => {
  return text;
});
This is not returning any text instead returns an observable even after returning response from inside subscriber, Does any one know how to tackle this situation?

**Comment by xStarman** [comment]
Mythrim, In my answer I used get('key') just to wait until translation service starts before acessing instant, your calls must be inside the subscribe callback, or you can just call a callback inside it because subscribe are asyncronous.

**Comment by bnfrnz** [comment]
> is theire a way to load translations when application starts so that we can safely use` translate.instant()`

If you want to be sure that the translations are loaded, consider converting the Observable to a Promise and then await that before calling `instant()`:
`await this.translate.use('en').toPromise<void>();`

**Comment by andreas-aeschlimann** [comment]
You could also do something like this:

```
async doSomething(): void {

    await this.translateService.get("").toPromise();
    // It loads the translate data now, and you can now safely use instant

    const hello: string = this.translateService.instant("HELLO");
    console.log(hello);

}
```

Obviously, you could also just always use await/get in this method.

**Comment by moguzozcan** [comment]
@xStarman Thanks for your comment, It worked for me. 
@andreas-aeschlimann can we use this approach in the ngOnInit() method. Since await requires async method, it will not work on ngOnInit()? What do you think?

**Comment by andreas-aeschlimann** [comment]
It wouldn't work directly in ngOnInit I guess, but you could probably wrap it in a setTimeout() function, then it runs async.

**Comment by chibibiscuit** [comment]
@kneefer 's answer was absolute gold. I went ahead and converted it to an async function that's a little more succinct codewise, but performs the same trick. We are going to be loading in the user's language from a settings table later on, so we will be using multiple awaits inside the async function - if you wanted to have multiple things initializing asynchronously, I would recommend returning a `Promise.all()` instead.

Also - Angular gets mad if you try to set the factory as an async function, hence how I'm immediately returning an anonymous async function inside the factory. If anyone has a better example of this, I would love to learn from it!

```typescript
import { Injector, APP_INITIALIZER } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { LOCATION_INITIALIZED } from '@angular/common';

export function appInitializerFactory(translate: TranslateService, injector: Injector) {
  return async () => {
    await injector.get(LOCATION_INITIALIZED, Promise.resolve(null));

    translate.setDefaultLang('en-US');
    await translate.use('client').toPromise();
  }
}
```

**Comment by davidweining2333** [comment]
> All you need to do (as it was partially mentioned) is to preload translations using `.use()` method. The problem is the method is async (we should wait for the result). The best way to force the application to wait for "something" to finish before it shows up is using `APP_INITIALIZER` function in your `AppModule`.
> 
> You have to add following provider to your `AppModule`'s `providers` section:
> 
> ```ts
> providers: [
>   {
>     provide: APP_INITIALIZER,
>     useFactory: appInitializerFactory,
>     deps: [TranslateService, Injector],
>     multi: true
>   }
> ]
> ```
> 
> And define factory function `appInitializerFactory` upper in the same file:
> 
> ```ts
> import { Injector, APP_INITIALIZER } from '@angular/core';
> import { TranslateService } from '@ngx-translate/core';
> import { LOCATION_INITIALIZED } from '@angular/common';
> 
> export function appInitializerFactory(translate: TranslateService, injector: Injector) {
>   return () => new Promise<any>((resolve: any) => {
>     const locationInitialized = injector.get(LOCATION_INITIALIZED, Promise.resolve(null));
>     locationInitialized.then(() => {
>       const langToSet = 'en-GB'
>       translate.setDefaultLang('en-US');
>       translate.use(langToSet).subscribe(() => {
>         console.info(`Successfully initialized '${langToSet}' language.'`);
>       }, err => {
>         console.error(`Problem with '${langToSet}' language initialization.'`);
>       }, () => {
>         resolve(null);
>       });
>     });
>   });
> }
> ```
> 
> Now application will wait for translations initialization before it shows up for user.



> All you need to do (as it was partially mentioned) is to preload translations using `.use()` method. The problem is the method is async (we should wait for the result). The best way to force the application to wait for "something" to finish before it shows up is using `APP_INITIALIZER` function in your `AppModule`.
> 
> You have to add following provider to your `AppModule`'s `providers` section:
> 
> ```ts
> providers: [
>   {
>     provide: APP_INITIALIZER,
>     useFactory: appInitializerFactory,
>     deps: [TranslateService, Injector],
>     multi: true
>   }
> ]
> ```
> 
> And define factory function `appInitializerFactory` upper in the same file:
> 
> ```ts
> import { Injector, APP_INITIALIZER } from '@angular/core';
> import { TranslateService } from '@ngx-translate/core';
> import { LOCATION_INITIALIZED } from '@angular/common';
> 
> export function appInitializerFactory(translate: TranslateService, injector: Injector) {
>   return () => new Promise<any>((resolve: any) => {
>     const locationInitialized = injector.get(LOCATION_INITIALIZED, Promise.resolve(null));
>     locationInitialized.then(() => {
>       const langToSet = 'en-GB'
>       translate.setDefaultLang('en-US');
>       translate.use(langToSet).subscribe(() => {
>         console.info(`Successfully initialized '${langToSet}' language.'`);
>       }, err => {
>         console.error(`Problem with '${langToSet}' language initialization.'`);
>       }, () => {
>         resolve(null);
>       });
>     });
>   });
> }
> ```
> 
> Now application will wait for translations initialization before it shows up for user.

amazing！

**Comment by jainsamyak** [comment]
> All you need to do (as it was partially mentioned) is to preload translations using `.use()` method. The problem is the method is async (we should wait for the result). The best way to force the application to wait for "something" to finish before it shows up is using `APP_INITIALIZER` function in your `AppModule`.
> 
> You have to add following provider to your `AppModule`'s `providers` section:
> 
> ```ts
> providers: [
>   {
>     provide: APP_INITIALIZER,
>     useFactory: appInitializerFactory,
>     deps: [TranslateService, Injector],
>     multi: true
>   }
> ]
> ```
> 
> And define factory function `appInitializerFactory` upper in the same file:
> 
> ```ts
> import { Injector, APP_INITIALIZER } from '@angular/core';
> import { TranslateService } from '@ngx-translate/core';
> import { LOCATION_INITIALIZED } from '@angular/common';
> 
> export function appInitializerFactory(translate: TranslateService, injector: Injector) {
>   return () => new Promise<any>((resolve: any) => {
>     const locationInitialized = injector.get(LOCATION_INITIALIZED, Promise.resolve(null));
>     locationInitialized.then(() => {
>       const langToSet = 'en-GB'
>       translate.setDefaultLang('en-US');
>       translate.use(langToSet).subscribe(() => {
>         console.info(`Successfully initialized '${langToSet}' language.'`);
>       }, err => {
>         console.error(`Problem with '${langToSet}' language initialization.'`);
>       }, () => {
>         resolve(null);
>       });
>     });
>   });
> }
> ```
> 
> Now application will wait for translations initialization before it shows up for user.

Gold! Thanks so much for this

**Comment by coni2k** [comment]
As an addition to @kneefer's answer;

Since RxJS has a built-in `toPromise()` function that converts observables to promises, you can shorten the `appInitializerFactory` code as the following:

```
function appInitializerFactory(translateService: TranslateService) {
  return () => {
    translate.setDefaultLang('en-US');
    return translateService.use('en-US').toPromise();
  };
}
```

**Comment by TCB13** [comment]
I just changed the method signature to:

`````
export function appInitializerFactory(translateService: TranslateService): () => Promise<any> {
`````

Cause tslint.

**Comment by urosmlade** [comment]
Can instant be used in lazy loaded module?

**Comment by Clemzd** [comment]
Hello!

Thank you for all those advices.

I tried the solution suggested by @coni2k but i get a cyclic dependancy error.

I understand why but I don't know how to resolve it.

This is cause by this initialization In the `app.modules.ts`
```
TranslateModule.forRoot({
    loader: {
        provide: TranslateLoader,
        useFactory: createTranslateLoader,
        deps: [HttpClient]
    }
}),
```

In the APP_INITIALIZE provider, i tried to inject the TranslateService but I think it is not loaded at this moment. So the INITIALIZER wait for it to be ready and the TranslateModule too.

```
{
    provide: APP_INITIALIZER,
    useFactory: appInitializerFn,
    multi: true,
    deps: [TranslateService]
},

const appInitializerFn = (translateService: TranslateService) => {
    return translateService.use('fr-FR').toPromise();
};
```

**Comment by suppadeliux** [comment]
This is very confusing. I am facing the same issue. 

Sadly, I have no way to reproduce the error, because it only happens when my site is on prod.

I thought we had to use `return new TranslateHttpLoader(http, './assets/i18n/', '.json');` to be able to fetch all translations.

I havent found a proper example of using `APP_INITIALIZER`, and being able to use `TranslateHttpLoader`? 

thanks in advance if someone has an idea.

**Comment by EliseiNicolae** [comment]
**app.module.ts**

```
import { Injector, APP_INITIALIZER } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

function appInitializerFactory(translateService: TranslateService) {
    return () => {
        translateService.setDefaultLang('en');
        return translateService.use('en').toPromise();
    };
}
```

In **@NgModule** add: 
```
    providers: [
        {
            provide: APP_INITIALIZER,
            useFactory: appInitializerFactory,
            deps: [TranslateService, Injector],
            multi: true
        }
    ],
```

**Comment by dakoncic** [comment]
> **app.module.ts**
> 
> ```
> import { Injector, APP_INITIALIZER } from '@angular/core';
> import { TranslateService } from '@ngx-translate/core';
> 
> function appInitializerFactory(translateService: TranslateService) {
>     return () => {
>         return translateService.use('en').toPromise();
>     };
> }
> ```
> 
> In **@NgModule** add:
> 
> ```
> imports: [
>     ...
>         TranslateModule.forRoot({
>             defaultLanguage: 'en',
>             loader: {
>                 provide: TranslateLoader,
>                 useFactory: HttpLoaderFactory,
>                 deps: [HttpClient]
>             }
>         })
> ],
> providers: [
> {
>     provide: APP_INITIALIZER,
>     useFactory: appInitializerFactory,
>     deps: [TranslateService, Injector],
>     multi: true
> }
> ],
> ```

I can confirm this works, the only thing that was different on this date for me is:
...
useFactory: (http: HttpClient) => new TranslateHttpLoader(http, './assets/i18n/', '.json'),
...
'./assets/i18n/' ---> this might be different for you, this is location of .json file for translation, for example: en_US.json

**Comment by davyvanlaere** [comment]
The onLangChange event fires when a language is loaded. So, any rxjs subscription which includes the operator below will only fire after the translations have loaded:

`combineLatestWith(this.translateService.onLangChange)`

**Comment by YahyaRechaki** [comment]
what if we have lazy loading ? each module has it own translation files ? how we can implement the translation initialization ?

**Comment by YahyaRechaki** [comment]
I'm running with an issue where i have to translate properties that are array and objects, these objects/arrays are being initialized in ngOnInit ! I tried to do the samething with APP_INITIALIZER in each feature module but doesn't worked !

here is an example of a feature module

`

export function CreateTranslateLoader(http: HttpClient){
  return new TranslateHttpLoader(http, '../../assets/i18n/featuremodule/', '.json')
}

export function appInitializerFactory(translate: TranslateService, injector: Injector) {
  return () => new Promise<any>((resolve: any) => {
    const locationInitialized = injector.get(LOCATION_INITIALIZED, Promise.resolve(null));
    locationInitialized.then(() => {
      const langToSet = 'en'
      translate.setDefaultLang('fr');
      translate.use(langToSet).subscribe(() => {
        console.info(`Successfully initialized '${langToSet}' language.'`);
      }, err => {
        console.error(`Problem with '${langToSet}' language initialization.'`);
      }, () => {
        resolve(null);
      });
    });
  });
}

@NgModule({
  declarations: [
    ...
  ],
  imports: [
    ...
    TranslateModule.forChild({
      defaultLanguage: 'fr',
      loader: {
        provide: TranslateLoader,
        useFactory: (CreateTranslateLoader),
        deps: [ HttpClient ]
      },
      isolate: true,
    }),
  ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: appInitializerFactory,
      deps: [TranslateService, Injector],
      multi: true
    },
    ...
  ],
})
export class FeatureModule {}
`

**Comment by CraigAtInstrumental** [comment]
> **app.module.ts**
> 
> ```
> import { Injector, APP_INITIALIZER } from '@angular/core';
> import { TranslateService } from '@ngx-translate/core';
> 
> function appInitializerFactory(translateService: TranslateService) {
>     return () => {
>         return translateService.use('en').toPromise();
>     };
> }
> ```
> 
> In **@NgModule** add:
> 
> ```
> imports: [
>     ...
>         TranslateModule.forRoot({
>             defaultLanguage: 'en',
>             loader: {
>                 provide: TranslateLoader,
>                 useFactory: HttpLoaderFactory,
>                 deps: [HttpClient]
>             }
>         })
> ],
> providers: [
> {
>     provide: APP_INITIALIZER,
>     useFactory: appInitializerFactory,
>     deps: [TranslateService, Injector],
>     multi: true
> }
> ],
> ```

I'm getting an error: APP_INITIALIZER is not assignable to type "Provider" in the 'provide' line.

**Comment by davyvanlaere** [comment]
This also works, is a bit easier imo.

`  providers: [
    {
      provide: APP_INITIALIZER,
      multi: true,
      useFactory: (service: TranslateService) => () =>
        lastValueFrom(service.get('nav.home')),
      deps: [TranslateService]
    }
  ]`
