### ISSUE TITLE
Cannot read property 'getDOM' of undefined at CookieXSRFStrategy.configureRequest 

### ISSUE THREAD

**Issue by chendetong1993** [ngx-translate/core#519]
Hi,

I am using Ionic 2 with Angularjs 4. These day, I am trying to use ng-transalte module. However, it shows the error at "http" module.

```
export function HttpLoaderFactory(http: Http) {
    return new TranslateHttpLoader(http);
}
```
Uncaught (in promise): TypeError: Cannot read property 'getDOM' of undefined TypeError: Cannot read property 'getDOM' of undefined at CookieXSRFStrategy.configureRequest (http://localhost:8100/build/main.js:64707:129) at XHRBackend.createConnection (http://localhost:8100/build/main.js:64762:28) at httpRequest (http://localhost:8100/build/main.js:64919:20) at Http.request (http://localhost:8100/build/main.js:65028:34) at Http.get (http://localhost:8100/build/main.js:65042:21) at TranslateHttpLoader.getTranslation (http://localhost:8100/build/main.js:114729:26) at TranslateService.getTranslation (http://localhost:8100/build/main.js:44101:55) at TranslateService.retrieveTranslations (http://localhost:8100/build/main.js:44088:87) at TranslateService.setDefaultLang (http://localhost:8100/build/main.js:44033:28) at http://localhost:8100/build/main.js:114670:27 at t.invoke (http://localhost:8100/build/polyfills.js:3:14529) at Object.onInvoke (http://localhost:8100/build/main.js:4425:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:14469) at n.run (http://localhost:8100/build/polyfills.js:3:9741) at http://localhost:8100/build/polyfills.js:3:6774

Please, help me.

Thank you

**Comment by FelipeAmaralRodrigues** [comment]
Solved?

**Comment by junaidbinsarfraz** [comment]
Also having same issue with `@angular/http`

```
var link = 'https://mywebsite.com/myws/Login';
    var data = JSON.stringify({ username: this.username, password: this.password });

    this.http.post(link, data)
      .subscribe(data => {
        console.log(data);
      }, error => {
        console.log("Oooops!");
    });
```

Error on chrome

```
ERROR TypeError: Cannot read property 'getDOM' of undefined
    at CookieXSRFStrategy.configureRequest (xhr_backend.js:167)
    at XHRBackend.createConnection (xhr_backend.js:207)
    at httpRequest (http.js:20)
    at Http.request (http.js:120)
    at Http.post (http.js:137)
    at LoginPage.doLogin (login.ts:37)
    at Object.eval [as handleEvent] (LoginPage.html:113)
    at handleEvent (core.es5.js:11892)
    at callWithDebugContext (core.es5.js:13184)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12772)
```

**Comment by jlcasasg** [comment]
solved it?

**Comment by CodeAndWeb** [comment]
Does this issue still persist? If so can you provide more information?

**Comment by parinita88** [comment]
i have same problem.. wondering why this issue is closed without any solution threads??

**Comment by anis072** [comment]
solved it?

**Comment by junyang123** [comment]
I solved the problem by uninstalling globally installed typescript package using following command: npm uninstall -g typescript
