### ISSUE TITLE
file: '@ngx-translate/core/index.ts' not found.'

### ISSUE THREAD

**Issue by eestein** [ngx-translate/core#521]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Error being reported by VS Code:

![screen shot 2017-04-25 at 14 52 32](https://cloud.githubusercontent.com/assets/2049255/25399786/f59bab3a-29c6-11e7-80b4-0cf62d5812d2.jpg)

The provided `tsconfig` expects an index.ts file.

**Expected/desired behavior**
No errors reported

**Reproduction of the problem**
Install the library on any project and open VS Code.

This is not preventing the usage of the library, but it would be nice if it was fixed.

**Comment by marpereira** [comment]
due to typings 2.2.1 and 2.2.2.

check if workplace version is the same as VSCode version

**Comment by eestein** [comment]
@marpereira they are, both are 2.2.2.

Thanks.

**Comment by yannickadam** [comment]
Probably that tsconfig.json needs to be added to .npmignore.
In the meantime, deleting the file (tsconfig.json) manually solves the error.

**Comment by eestein** [comment]
@yannickadam thank you :)

**Comment by larssn** [comment]
#543
