### ISSUE TITLE
Can't see translations for lazy-loaded module

### ISSUE THREAD

**Issue by alcfeoh** [ngx-translate/core#522]
**I'm submitting a ...** 
```
[X] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I have a lazy loaded module that tries to load TranslateModule using a simple `TranslateModule.forChild({ })`

**Expected/desired behavior**
I would like to access the translations from the main module. This used to work when my module wasn't lazily loaded, now I only see the keys. Translations don't show up anymore.

**Reproduction of the problem**
Happens consistently to me.

**What is the expected behavior?**
Translations should be loaded.

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.1

* **Angular version:** 4.0.3
 
* **Browser:** [all  ]

**Comment by tomriddle1234** [comment]
Yeah, I got exactly same issue. Please check this issue too, https://github.com/ngx-translate/core/issues/464

**Comment by tomriddle1234** [comment]
Solved it, just remove node_modules and run npm install again fixed it for me. Cause I was using cnpm instead of npm, it was broken.

**Comment by alcfeoh** [comment]
This didn't do the trick for me. Now Angular is complaining that it can't find the `translate` pipe, though I import `TranslateModule` in both my main module and my shared module.

**Comment by alcfeoh** [comment]
After restarting my `ng serve` a couple of times, it actually works now... Really weird but problem solved, somehow.
