### ISSUE TITLE
Pipe updates value multiple times when language is changed

### ISSUE THREAD

**Issue by shedar** [ngx-translate/core#526]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

If new language is set with `translate.use()` then `onTranslation` function is called 2 or 3 times instead of single call. It means that `markForCheck` is also called multiple times, which can affect performance.

First call: `onLangChange`=> one of this lines https://github.com/ngx-translate/core/blob/master/src/translate.pipe.ts#L30-L32

Second call: `onLangChange` => https://github.com/ngx-translate/core/blob/master/src/translate.pipe.ts#L35 
I guess it's assumed as a choice between two flows. So it should be either return inside of `if(translations)` or L35 should be as `else`

Third call: occurs if language wasn't loaded before

**Expected/desired behavior**

Single update when translation is changed

**Reproduction of the problem**

1. Run http://run.plnkr.co/iei6pdkd1CCqqpmy/ (non full-screen version http://plnkr.co/edit/lVKUlVvRWy19MySndwqJ?p=preview)
2. open dev tools and put breakpoint on `this._ref.markForCheck()` of TranslatePipe
3. Refresh page

**What is the expected behavior?**

Breakpoint hit once per locale

**What is the motivation / use case for changing the behavior?**

Prevent extra checks for changes by angular because we can have a lot of translated strings on the page

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.1

* **Angular version:** 4.0.2
 
* **Browser:** all

**Comment by victorlevasseur** [comment]
In dev mode, Angular 2 does a double change check to detect potential side-effects (that are often causing troubles). So, it might be why you're seeing multiple calls (not sure tho, but it's a possibility).

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
