### ISSUE TITLE
How handle 404 error we are passing miss match path

### ISSUE THREAD

**Issue by gadelaanil** [ngx-translate/core#528]
I am directly passing non related path to translate.use(). I am getting 404 error that one is correct to me. But i want to handle that 404 error by passing another path.  Where can I retrieve  that 404 error to handle
component.ts 
this.translate.use(assets/i18n/IN/ar/ar);

issue:
GET http://localhost:4200/assets/i18n/IN/ar/ar.json 404 (Not Found)

**Comment by jlberrocal** [comment]
What about using a custom loader?

**Comment by ocombe** [comment]
Yes, a custom loader is the way to do that.
