### ISSUE TITLE
Automatic load available Langs from i18n folder

### ISSUE THREAD

**Issue by marpereira** [ngx-translate/core#533]
[ ] bug report
[x] support request
[ ] feature request

**Current behavior**
getLangs method only retrieve langs that are used or manually added.

**Expected/desired behavior**
I what that getLangs method retrieve available languages on 'default' directory.

**What is the motivation / use case for changing the behavior?**
I want to add to 'default' folder (in my case root/i18n/) files like 'pt.json', 'de.json' and app should automatically added them to getLangs array.

**Comment by ocombe** [comment]
The library works browser side, it has no idea of what is available in your folder server side.
If you use webpack, you can provide this quite easily with the `webpack.DefinePlugin` that lets you define global variable for your application (you can get a list of files from the directory and send that to your app this way).

**Comment by dev054** [comment]
Hey, @ocombe. I think @marpereira wasn't talking about **server-side**, but client-side...

**Comment by ocombe** [comment]
Which is only possible via webpack. Javascript cannot list the files from the directory of a server.

**Comment by marpereira** [comment]
@ocombe What I want to be able to put a translation file on i18n folder and the app recognize it.
