### ISSUE TITLE
Conflict with angular material2

### ISSUE THREAD

**Issue by Toub** [ngx-translate/core#536]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

When using with md-button or md-raised button from angular-material2 project, translation does not work:

```html
<a translate md-button>Hello</a>
<!-- => output "Hello" -->
```

**Expected/desired behavior**

```html
<a translate md-button>Hello</a>
<!-- => output "Bonjour" -->
```

Workaround:

```html
<a  md-button><span translate>Hello</span></a>
<!-- => output "Bonjour" -->
```

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.1

* **Angular version:** 4.1.0
 
* **Browser:** [all ]

**Comment by Toub** [comment]
It probably appends with any transclusion directive.

**Comment by jlberrocal** [comment]
@Toub why you don't use the pipe approach?

**Comment by Toub** [comment]
Do you mean?

```html
<a  md-button>{ 'Hello' | translate }</a>
```

Yes, it is an option, but it is much more verbose than:

```html
<a translate md-button>Hello</a>
```

**Comment by jlberrocal** [comment]
yes but is more precise using pipes (having in mind how pipes works) BTW i guess that both are template based so you can't use 2 template based directives in a same component (Angular behavior)

**Comment by Toub** [comment]
Ok, so I guess we can close this one as there is no way to fix it. 

Maybe just mention this behavior in the documentation?
