### ISSUE TITLE
AOT Server: Unexpected token import

### ISSUE THREAD

**Issue by mmathys** [ngx-translate/core#537]
**I'm submitting a ...**
```
[x] bug report
[ ] support request
[ ] feature request
```

**Current behavior**
When serving using `ng serve`, it works fine. However, when I launch the AOT server, I get this error:

```
> node dist/server.js

/Users/max/code/test2/node_modules/@ngx-translate/core/index.js:1
(function (exports, require, module, __filename, __dirname) { import { NgModule } from "@angular/core";
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/max/code/test2/dist/server.js:1212:18)
    at __webpack_require__ (/Users/max/code/test2/dist/server.js:20:30)
```

Relevant code ([full repo for reproduction here](https://github.com/mmathys/ngxissue)):

```javascript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { HttpModule, Http } from '@angular/http';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

import { AppComponent } from './app.component';

export { AppComponent };
export function createTranslateLoader(http: Http) {
  return new TranslateHttpLoader(http, '../assets/i18n/', '.json');
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule.withServerTransition({ appId: 'cli-universal-demo' }),
    RouterModule.forRoot([
      { path: '', loadChildren: './home/home.module#HomeModule' },
      { path: 'about', loadChildren: './about/about.module#AboutModule' },
      { path: '**', redirectTo: '', pathMatch: 'full' },
    ]),
    HttpModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [Http]
      }
    })

  ],
  exports: [AppComponent],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**Expected/desired behavior**

It should compile the same way as `ng serve`.

**Reproduction of the problem**
I'm using this starter: https://github.com/evertonrobertoauler/cli-universal-demo

Here is the full code I'm using: https://github.com/mmathys/ngxissue

* **ngx-translate version:** 6.0.1 (@ngx-translate/core), 0.0.3 (@ngx-translate/http-loader@0.0.3)

* **Angular version:** 4.1.1
 
* **Browser:** all

**Comment by yamidvo** [comment]
I have the same error

**Comment by mmathys** [comment]
@yamidvo I fixed it. See here: https://github.com/evertonrobertoauler/cli-universal-demo/issues/14#issuecomment-301125219

**Comment by premiumwd** [comment]
@mmathys what about for angular cli?

**Comment by robmeredith** [comment]
@mmathys I beleive a better solution than using webpack to transpile the package is to build the package according to Angular packaging rules in the first place.. [ng-packagr](https://github.com/dherges/ng-packagr) does just this.. I created a [fork ](https://github.com/robmeredith/core) of ngx-translate that uses this to build the package and this seems to have solved the problem.. with this I can use ngx-translate with Universal with angular-cli (as described in [this story](https://github.com/angular/angular-cli/wiki/stories-universal-rendering)) without the additional webpack phase.

@ocombe maybe [this change ](https://github.com/robmeredith/core/commit/9d1acad4bdbcd138d05acd36743b959632644d50)to the build could be done to align packaging with Angular standards?

**Comment by AnthonyNahas** [comment]
take a look to my solution (only as work around)

[https://github.com/ngx-translate/core/issues/581#issuecomment-326256510](url)

**Comment by mmathys** [comment]
@AnthonyNahas your link is broken. this one works: https://github.com/ngx-translate/core/issues/581#issuecomment-326256510
