### ISSUE TITLE
Load resources json files inside component

### ISSUE THREAD

**Issue by napcat** [ngx-translate/core#540]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**What is the motivation / use case for changing the behavior?**
I need to load the json file with the resources only when the app is already booted because I need to make a resquest to the server do some specific project informations.

At this moment I'm loading the json files like the exemples:

```
export function createTranslateLoader(http: Http) {
    return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: (createTranslateLoader),
                deps: [Http]
            }
        })
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

How can I loaded it inside a component?

**Comment by ocombe** [comment]
The translations will only be loaded when you call the `.use(lang)` method, you can call this anywhere you want.
