### ISSUE TITLE
Use in Ionic 2 : how to add downloaded external languages files ? dynamically change folder of json or use setTranslate ?

### ISSUE THREAD

**Issue by davidanquetin** [ngx-translate/core#542]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

I use nxg-translate in Ionic 2 project.

in my `app.module.ts`, i use `translateHttpLoader` : 

 ```
...
imports: [
    BrowserModule,
    HttpModule,
    IonicImageViewerModule,
    IonicModule.forRoot(MyApp, AppOptions),
    IonicAudioModule.forRoot(),
    TranslateModule.forRoot({
        loader: {
            provide: TranslateLoader,
            useFactory: createTranslateLoader,
           deps: [Http]
        }
    })
  ],
...


export function createTranslateLoader(http: Http,) {
    return new TranslateHttpLoader(http, 'assets/i18n/', '.json');
}

```

In my app, i have to download lang files from a external zip, because the client want to have the possibility to change traductions without to republish app.

So i download and unzip files, 
and when i have the json content of the lang (=`data`), i add it to the translation tools with `setTranslate` method.

` this.translate.setTranslation(lang,data);`

But when i check if the language is well added with the getTranslation method, i have an error because it does not find the file. (http request error). It is normal, my folder `assets/i18n/` is empty, 
but with the `setTranslation` method, i think that i should normally find what i had added juste before ? Or I do not use the module as expected ?

I have tried to put an empty file in assets/in18n folder (for example fr.json), to see if it could work, but it does not change anything.

If i change the url of folder in translateHttpLoader, to have exact downloaded zip content folder, it works, but the problem is that i would be able to change in function of platform (ios/android), because folder of zip is not the same in function of the OS.

**Expected/desired behavior**

My question is:
- could i change the folder of assets in function of platform, in my `createTranslateLoader` function  (or after app is initialized)
- how work  setTranslation method : does it need a minimal file in `i18n` folder to work ?
- have you an idea to improve my use of ngx-translate ?

thanks !
David

**UPDATE**

I found a solution : 
add File in dependances of my loader :  

```
imports: [
    BrowserModule,
	  HttpModule,
	    IonicImageViewerModule,
    IonicModule.forRoot(MyApp, AppOptions),
	  IonicAudioModule.forRoot(),
	  TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
       deps: [Http, File]
      }
    })

  ]
```

than use file.dataDirectory in my function : 
```
export function createTranslateLoader(http: Http, file : File ) {
   return new TranslateHttpLoader(http, file.dataDirectory+'initial/i18n/', '.json');
}
```

So with this, lang files are used from the cordova dataDirectory where zip is unziped.

If it can help someone!

**Comment by emis44** [comment]
For IOS there is the problem that file.dataDirectory is null at the moment of the definition of function createTranslateLoader in **app.module.ts** (not for android, I don't know why).

The only way i found for this problem is to re-define the loader for translation inside the platform.ready of **app.component.ts**

`
platform.ready().then(() => {
translate.currentLoader = new TranslateHttpLoader(http, file.dataDirectory+'langs/', '.json');
translate.reloadLang('en');
translate.use('en')
}
`

Here the file.dataDirectory is not null
