### ISSUE TITLE
ngx-translate can not install module on Linux/Ubantu server

### ISSUE THREAD

**Issue by ankit0606** [ngx-translate/core#544]
ngx version - 6.0.1.
http loader - 0.0.3
When I tried running npm install it works perfectly fine on Windows. It worked as expected.
But when I try to do npm install on cloud server which is Linux/Ubantu it doses not install.
The production build fails. But when I remove translate code from my code and build it again it works great. 
My environment is 
I am using angular-seed.

"@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "@angular/service-worker": "1.0.0-beta.6",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "angular2-highcharts": "^0.5.5",
    "bootstrap": "3.3.7",
    "core-js": "2.4.1",
    "intl": "1.2.5",
    "jquery": "3.1.1",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "rxjs": "5.2.0",
    "systemjs": "0.19.41",
    "zone.js": "0.8.4"
```

**Current behaviour**
Not working on Server(Linux / Ubuntu)

**Expected/Desired behaviour**
Should work on Server(Linux / Ubuntu)

**Reproduction of the problem**
Use angular-seed and ngx modules on ubuntu machine. It will reproduce the problem.

**What is the motivation/use case for changing the behaviour?**
Should work on the server to use it.

**Comment by jlberrocal** [comment]
@ankit0606 could you provide the error that you are facing?
and maybe also how the code where you are importing the module

**Comment by ankit0606** [comment]
I changed to ng2-translate and that's working fine for me now.

**Comment by jlberrocal** [comment]
great, nice to hear that
