### ISSUE TITLE
I have many forms and would like to prepare a json file for each form.

### ISSUE THREAD

**Issue by AlwaysAbhl001** [ngx-translate/core#546]
Home,About,Contact three components.

Home - i18n-en,fr json file.
Contact - i18n-en,fr json file
About - i18n-en,fr json file

need to maintain separate i18n folders for each component, How could i achieve it? Is there any in-built support for it ? 

* **ngx-translate version:** x.x.x
  "@ngx-translate/core": "^6.0.1",

**Comment by jlberrocal** [comment]
@AlwaysAbhl001 i solved that using require, here an example:
```typescript
export class UsersModule {
    constructor(translate: TranslateService) {
        let lang = CONFIG['LANGUAGES'];
        let i18n = require(`./i18n/${lang}.json`);

        translate.setTranslation(lang, i18n, true);
    }
}
```

the only problem that i had was with the shouldMerge param because object deep merge is mess in JS, however i already made a PR that solves this problem, we need to wait until @ocombe accept it

**Comment by AlwaysAbhl001** [comment]
@jlberrocal  let i18n = require(`./i18n/${lang}.json`); i need to call this at every component ?

**Comment by jlberrocal** [comment]
if you have a different i18n file per component yes, in my case i have that for every lazy loaded module (AKA route)
