### ISSUE TITLE
Error when using with angular platform server

### ISSUE THREAD

**Issue by kyue1005** [ngx-translate/core#548]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When using ngx-translate with http-loader platform server for SSR. It gives 'URLs requested via Http on the server must be absolute.'

**Expected/desired behavior**
Could be used under platform server rendering.

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.1

* **Angular version:** 4.1.3

**Comment by jlberrocal** [comment]
@kyue1005 AFAIK you will need a custom loader, that does not look like an error
