### ISSUE TITLE
Translation containing a space at the end of string failed to switch language

### ISSUE THREAD

**Issue by bentfc** [ngx-translate/core#550]
Hi,

I have added a translation that contains a space character at the end of the string. When I switch the language, the translation tag isn't translated anymore.

Here are my language files :

> fr.json
> {
>     ...
>     "FILE_NAME": "Nom du fichier: ",
>     ...
> }

> en.json
> {
>     ...
>     "FILE_NAME": "File Name: ",
>     ...
> }

I use the method "use" of the translateService.
I can easily solve the problem by removing the space character from the translation files and adding it in the html template where I use the tag 'FILE_NAME'.

**Environment:**
CentOs

* **ngx-translate version:** 
6.0.1

* **Angular version:**
4.1.3
 
* **Browser:**
Version 58.0.3029.81 (64-bit)

**Comment by CodeAndWeb** [comment]
#790, fixed with 10.0.1
