### ISSUE TITLE
Calling function 'OpaqueToken', function calls are not supported.

### ISSUE THREAD

**Issue by xmlking** [ngx-translate/core#551]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
```
ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken',
 function calls are not supported. Consider replacing the function or lambda with a reference to an 
exported function, resolving symbol USE_STORE in /xyx/node_modules/@ngx-
translate/core/src/translate.service.d.ts, resolving symbol TranslateModule.forRoot in 
/Developer/Work/iot/hub/node_modules/@ngx-translate/core/index.d.ts, resolving symbol 
AppModule in /xyz/src/app/app.module.ts, resolving symbol AppModule in 
/xyz/src/app/app.module.ts
```
**Expected/desired behavior**

ngx-translate/core should switch to Angular 4 recommended approach  

**Reproduction of the problem**
 
   

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.1

* **Angular version:** 4.2.0 RC1
 
* **Browser:** all

**Comment by ramuda** [comment]
any update on this fix? its failing for angular 5 beta

**Comment by ocombe** [comment]
I've merged it, new release inc, thanks !

**Comment by ramuda** [comment]
> I've merged it, new release inc, thanks !

:+1:
