### ISSUE TITLE
Update npm version to v6.0.1 (latest is 5.0.0)

### ISSUE THREAD

**Issue by dukearena** [ngx-translate/core#554]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

> npm install ng2-translate@latest

 will download only v5.0.0, instead Github Repo has released v6.0.1.

**Expected/desired behavior**

> npm install ng2-translate@latest

 should download v6.0.1

**What is the motivation / use case for changing the behavior?**
I need it because of Angular2 v4 compatibility.

**Comment by ocombe** [comment]
The library has been renamed ngx-translate, and is now using scopes (@ngx-translate/core, ...).
ng2-translate is no longer updated.
