### ISSUE TITLE
How to set title of a document using ngx-translate?

### ISSUE THREAD

**Issue by hegdemahesh** [ngx-translate/core#557]
How do I set page title using ngx-translate? any suggestions?

**Comment by hegdemahesh** [comment]
Used Angular title service. and it worked fine,
translate.get('page_title').subscribe((res: string) => {
      titleService.setTitle(res);
    })

**Comment by roger2hk** [comment]
The following code will update title on language change event.
```javascript
translate.onLangChange.subscribe((event: LangChangeEvent) => {
  translate.get('page_title').subscribe((res: string) => {
    titleService.setTitle(res);
  });
});
```

This issue can be closed.

**Comment by ihd2911** [comment]
Used Angular title service. and it worked fine,
translate.get('page_title').subscribe((res: string) => {
titleService.setTitle(res);
})

Not working in constructor

**Comment by heapwalker** [comment]
Here is the summarized minimal working codes (at recently angular 8 and ngx-translate 11).

```typescript
// src/app/app.component.ts

import { Title } from '@angular/platform-browser';

export class AppComponent {
  constructor(
    private titleService: Title,
    private translate: TranslateService,
  ) {
    // You might set fallback language here too
    // translate.setDefaultLang('en');

    // You might set initial language here too
    // translate.use('fr');

    translate.onLangChange.subscribe((event: LangChangeEvent) => {
      // Change page title when user changes language preference
      translate.get('page_title').subscribe((res: string) => {
        titleService.setTitle(res);
      });
    });
  }
}
```

Credits to @hegdemahesh and @roger2hk, thanks mates.
See also https://angular.io/guide/set-document-title for the `Title` service.

**Comment by sebastianmusial** [comment]
Here you can find simple package: https://github.com/ng-sm/title

**Comment by usamagamea** [comment]
I had an issue when I navigate to another component

**Comment by usamagamea** [comment]
> Here you can find simple package: https://github.com/ng-sm/title



> Here is the summarized minimal working codes (at recently angular 8 and ngx-translate 11).
> 
> ```ts
> // src/app/app.component.ts
> 
> import { Title } from '@angular/platform-browser';
> 
> export class AppComponent {
>   constructor(
>     private titleService: Title,
>     private translate: TranslateService,
>   ) {
>     // You might set fallback language here too
>     // translate.setDefaultLang('en');
> 
>     // You might set initial language here too
>     // translate.use('fr');
> 
>     translate.onLangChange.subscribe((event: LangChangeEvent) => {
>       // Change page title when user changes language preference
>       translate.get('page_title').subscribe((res: string) => {
>         titleService.setTitle(res);
>       });
>     });
>   }
> }
> ```
> 
> Credits to @hegdemahesh and @roger2hk, thanks mates. See also https://angular.io/guide/set-document-title for the `Title` service.
I had an issue when I navigate to another component

**Comment by gentoo90** [comment]
If you want the title to update both on navigating and on language change than you can implement your own [`TitleStrategy`](https://angular.dev/api/router/TitleStrategy):
```ts
import { inject, Injectable } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { RouterStateSnapshot, TitleStrategy } from '@angular/router';
import { TranslateService } from '@ngx-translate/core';
import { Subject, switchMap } from 'rxjs';

@Injectable({ providedIn: 'root' })
export class I18nTitleStrategy extends TitleStrategy {
  #titleService = inject(Title);
  #translate = inject(TranslateService);
  #titleSubject = new Subject<string>();

  constructor() {
    super();

    this.#titleSubject
      .pipe(switchMap((newTitle) => this.#translate.stream(newTitle)))
      .subscribe((newTitle) => {
        this.#titleService.setTitle(newTitle);
      });
  }

  override updateTitle(routerState: RouterStateSnapshot) {
    const newTitle = this.buildTitle(routerState);
    if (newTitle !== undefined) {
      this.#titleSubject.next(newTitle);
    }
  }
}
```
and then just put your keys in the routes titles:
```ts
export const appRoutes: Route[] = [
  {
    path: 'foo',
    title: marker('PAGES.FOO'),
    component: FooComponent,
  },
  {
    path: 'bar',
    title: marker('PAGES.BAR'),
    component: BarComponent,
  },
];
```
