### ISSUE TITLE
Error: SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by adammus95** [ngx-translate/core#558]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

`Error: SyntaxError: Unexpected token <`

I have this error after DEPLOY, local works fine.
I had problem with ngx-translate. It couldn't find @ngx-translate so finally i put:
`'@ngx-translate/core': 'node_modules/@ngx-translate/core/bundles/core.umd.js',`

into map in my systemjs.config.js

if i put `'@ngx-translate/core': 'node_modules/@ngx-translate/core/bundles'`  it won't work

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by tea-mo903** [comment]
i have a similar problem.

**Comment by tsvetan-ganev** [comment]
I would suggest you check the Network tab in the Chrome DevTools to see if the translations file was loaded correctly. My guess is that instead of the desired `.json` file the server responds with an HTML file (probably your `index.html`).

**Comment by SamVerschueren** [comment]
Yes, that's almost always the reason why it fails. Because a SPA always starts from `index.html`, if the translation files can not be found it just returns the `index.html` file. So like @tsvetan-ganev suggests, take a look in your chrome devtools to the network tab and make sure the correct path is loaded.
