### ISSUE TITLE
Error from Your Example App

### ISSUE THREAD

**Issue by rebelholic** [ngx-translate/core#560]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Hello,
After I downloaded your ionic 2 example app from this repo and ran "npm install". After that, I am trying to test with "Ionic Serve" cmd got error message like below:

![ngtrans](https://user-images.githubusercontent.com/6254876/26916593-272bc4ea-4c55-11e7-8a3b-ba45d48b9ba5.jpg)

Please fix your repo!

Cheers

**Comment by CodeAndWeb** [comment]
We've created a new example here: https://github.com/ngx-translate/ionic-example
