### ISSUE TITLE
Case Insensitive

### ISSUE THREAD

**Issue by reinhardholl** [ngx-translate/core#561]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Loading a translation is case sensitive.

**Expected/desired behavior**
Is there an option that makes this case insensitive?

**Comment by Nasicus** [comment]
I would also be interested in this.

**Comment by tsvetan-ganev** [comment]
You can simulate that behavior by using the built-in `uppercase` or `lowercase` pipes to normalize your translation keys and then pipe the output into the `translate` pipe.

Example:
`sample.component.html`
```
<p>{{ 'ToolbarTitle' | uppercase | translate }}</p>
```

`en.json`
```json
{
  "TOOLBARTITLE": "My app"
}
```

**Comment by AndreasBaumgart** [comment]
Just for curiosity, what is the reasoning behind enforcing a case-convention at all? And why uppercase in particular?

**Comment by ocombe** [comment]
it's just how json/objects work

**Comment by AndreasBaumgart** [comment]
I don't think JSON is case-insensitive. Nor are JS objects. 
```
JSON.stringify({foo: 1, FOO: 2})
>> "{"foo":1,"FOO":2}"
```

Perhaps I'm missing your point. 
Mine is: What's the obstacle of using keys like "users.userManagementHeadline"?

**Comment by ocombe** [comment]
None, you can do it

**Comment by AndreasBaumgart** [comment]
Oh damn, just realized I falled into a caching trap. Sorry, should've checked twice, but this topic lead me into believe that this was actually only working with uppercase letter.
