### ISSUE TITLE
ngx-translate/core not working as expected after build.

### ISSUE THREAD

**Issue by AlwaysAbhl001** [ngx-translate/core#563]
after my ng build - angular2

I'm just accessing index.html which is in dist folder, loaded successfully and working as expected except ngx-Translate.  json files not loading
![translate](https://user-images.githubusercontent.com/26591838/27002787-69eb461c-4e07-11e7-9cfd-5c2c96fe96d7.JPG) 

error:
XML Parsing Error: not well-formed
Location: file:///C:/../dist/assets/i18n/en.json
Line Number 1, Column 1:

**Comment by premiumwd** [comment]
@AlwaysAbhl001 can you post your scripts here so I can help you furher? server.ts, app.module.ts, etc.

**Comment by AlwaysAbhl001** [comment]
[This](https://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local ) one gave me the solution @premiumwd  thanks for your response.

**Comment by premiumwd** [comment]
@AlwaysAbhl001 Im having issues too with ngx-translate on server side.
