### ISSUE TITLE
load json from REST API

### ISSUE THREAD

**Issue by mydata** [ngx-translate/core#564]
Is there any option to load the json file . from a REST URL, to translate the page data?

* **ngx-translate version:** x.x.x

* **Angular version:** 4.1.3
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by haakotsm** [comment]
As long as you have a properly formatted json on your backend it is easy enough to do. Write your own translationloader which requests the resource through http. Take a look at how the default one is written. Fairly straight forward. The guide on the front page shows you how to provide a new loader
