### ISSUE TITLE
Use pipe within json

### ISSUE THREAD

**Issue by uxer** [ngx-translate/core#572]
This is what I would like to do:

```
{
  "_common": {
    "test": "Test"
  },
  "page": {
    "test": "{{ '_common.test' | translate }}"
  }
}
```

Is it possible?

**Comment by StefH** [comment]
I'm trying to use the same:

```js
{
    "Generic": {
        "Hello2": "Hello {{value}} !",
        "Hello": "Hello {{Generic.World | translate}} !",
        "World": "W O R L D"
    }
}
```

I tried HTML like (which does not work):
```html
<div translate [translateParams]="{value: 'Generic.World | translate'}">Generic.Hello</div>
```
or
```html
<div translate [translateParams]="{value: {{Generic.World | translate}}}">Generic.Hello</div>
```
Which throws this error:

> Parser Error: Got interpolation ({{}}) where expression was expected at column 8 in [{value: {{Generic.World | translate}}}]

**Comment by ocombe** [comment]
Translations cannot contain any angular specific code, only text and regular html.

**Comment by StefH** [comment]
@ocombe 
Then how can I do variable substitution ?

Only way is via:

> This is how you do it with the pipe:

```html
<div>{{ 'HELLO' | translate:param }}</div>
```

> And in your component define param like this:
```js
param = {value: 'world'};
```
