### ISSUE TITLE
Query: Creating a module of optionally (ngx-translate)-able components.

### ISSUE THREAD

**Issue by joewoodhouse** [ngx-translate/core#577]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```
Goal: To create a module of ***optionally*** translatable components

**Current behavior**

I am creating a module of components that I would like to be optionally translatable. My basic requirements are:

1. Components in my module will use translate pipe/directive.
2. The components will (somehow) ship with default translations (english).
3. The importer of the module should not have to (directly) import @ngx-translate if they don't want to i.e. they are only planning to deliver their product in the default language, and have no interest in overriding existing translations.
4. However should they wish to provide translations, they should be able to.

I can't see exactly how I would achieve this given my understandings of this module and ngx.

To get the default translations working within my module (to satisfy requirements 2 and 3) my module will have to import and configure the `TranslateModule`. I guess this already is the problem - if the consuming application is not going to use @ngx-translate, then my module would need to `.forRoot` where as if it is I would have to `.forChild` ?

For requirement 4 I would want/expect that my consuming application can load translations with the appropriate keys specified in my components and that the translations will happen. So for example if my component defines a `<p translate>LOGIN_BUTTON</p>` and the application loads a translation with that key, then it should be translated as such ***and*** should override the default specified within the component.

Any advice on how to set this up would be much appreciated.

**Expected/desired behavior**

To be able to provide a module of optionally translatable components to the user.

**Comment by CodeAndWeb** [comment]
Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.
I am closing the issue for now - please re-open it if the issue still persists or you still need help.
