### ISSUE TITLE
*ngFor issue

### ISSUE THREAD

**Issue by SSlippa** [ngx-translate/core#580]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[X] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

I have this code

```
<div *ngFor="let service of services">
    <span><img  [src]="service.imgPath" alt="{{ service.name }}"/></span>
    <h4>{{ service.name}}</h4>
    <p>{{ service.desc }}</p>
</div>
``` 

And .json file

```
"service":[
    { "name" : "someName1", "desc" : "someDesc1"},
    { "name" : "someName2", "desc" : "someDesc2"},
    { "name" : "someName3", "desc" : "someDesc3"}
  ]
```

How can I do translation of each service that have 2 parameters

In regular case I use {{ 'something' | translate  }} , where "something" is placed in .json file

"something" : "translation"
So how can a use it in state of ngFor? It read me an object from .json, but not array of objects that what I need in my case

* **ngx-translate version:** 7.0.0

* **Angular version:** 4.0.0
 
* **Browser:** [all]

**Comment by heihenri** [comment]
I'm also trying to achieve something similar, any suggestions?

**Comment by jonathanantoine** [comment]
Hello,

Maybe this will help you. I have a collection of "TrackerType" in availableTypes which are integer (0, 1, etc.) and I use the translate attribute which will get the translation which match the content as a key. 

` <div *ngFor="let type of availableTypes" [value]="type" translate>TrackerType_{{type}}</div>
`

With this translation files :
```
{
  "TrackerType_0": "Une valeur"
  "TrackerType_1": "Deux valeurs"
}
```

**Comment by IsDragon** [comment]
what if i have multiple object inside an object

```
{
  "TrackerType_0": "Une valeur",
  "TrackerType_1": "Deux valeurs",
    "Test1":{
          "TrackerType_0": "Une valeur"
           "TrackerType_1": "Deux valeurs"
     },
    "Test2":{
          "TrackerType_0": "Une valeur"
           "TrackerType_1": "Deux valeurs"
     }

}

**Comment by jonathanantoine** [comment]
Maybe using the dot notation works ? Did you try it ?

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.

**Comment by itwinetechnologies** [comment]
Its not fixed.

**Comment by dnsbbu** [comment]
its not fixed

**Comment by megustalafantabienfria** [comment]
I made it work with this
`<div *ngFor="let service of ('service' | translate)">
    <span><img  [src]="service.imgPath" alt="{{ service.name }}"/></span>
    <h4>{{ service.name}}</h4>
    <p>{{ service.desc }}</p>
</div>`

**Comment by dnsbbu** [comment]
> I made it work with this
> 
> ```
> <div *ngFor="let service of ('service' | translate)">
>    <span><img  [src]="service.imgPath" alt="{{ service.name }}"/></span>
>   <h4>{{ service.name}}</h4>
>   <p>{{ service.desc }}</p>
> </div>
> ```

Not working,

ERROR Error: Cannot find a differ supporting object 'service' of type 'string'. NgFor only supports binding to Iterables such as Arrays.

**Comment by megustalafantabienfria** [comment]
> 
> Not working,
> 
> ERROR Error: Cannot find a differ supporting object 'service' of type 'string'. NgFor only supports binding to Iterables such as Arrays.

That's weird... because that's how my project is working.
I'm using it like this

```
<div *ngFor="let service of ('service' | translate)">
	<p>{{service.name}}</p>
	<p>{{service.desc}}</p>
</div>
```
The json is structured like this
```
{
  "service": [
    { "name" : "someName1", "desc" : "someDesc1"},
    { "name" : "someName2", "desc" : "someDesc2"},
    { "name" : "someName3", "desc" : "someDesc3"}
  ]
}
```

**Comment by cesargomezh** [comment]
> > Not working,
> > ERROR Error: Cannot find a differ supporting object 'service' of type 'string'. NgFor only supports binding to Iterables such as Arrays.
> 
> That's weird... because that's how my project is working.
> I'm using it like this
> 
> ```
> <div *ngFor="let service of ('service' | translate)">
> 	<p>{{service.name}}</p>
> 	<p>{{service.desc}}</p>
> </div>
> ```
> The json is structured like this
> 
> ```
> {
>   "service": [
>     { "name" : "someName1", "desc" : "someDesc1"},
>     { "name" : "someName2", "desc" : "someDesc2"},
>     { "name" : "someName3", "desc" : "someDesc3"}
>   ]
> }
> ```

Nice hack bro, thank you. You saved my azz.

**Comment by kumaresan-subramani** [comment]
i am also having the same problem any solution available?

https://github.com/ngx-translate/core/issues/1011

**Comment by geramireze** [comment]
no me funciono

**Comment by SaitejaAakula** [comment]
thanks @megustalafantabienfria it works.! :)

**Comment by Amith278** [comment]
> > Not working,
> > ERROR Error: Cannot find a differ supporting object 'service' of type 'string'. NgFor only supports binding to Iterables such as Arrays.
> 
> That's weird... because that's how my project is working.
> I'm using it like this
> 
> ```
> <div *ngFor="let service of ('service' | translate)">
> 	<p>{{service.name}}</p>
> 	<p>{{service.desc}}</p>
> </div>
> ```
> 
> The json is structured like this
> 
> ```
> {
>   "service": [
>     { "name" : "someName1", "desc" : "someDesc1"},
>     { "name" : "someName2", "desc" : "someDesc2"},
>     { "name" : "someName3", "desc" : "someDesc3"}
>   ]
> }
> ```



> > Not working,
> > ERROR Error: Cannot find a differ supporting object 'service' of type 'string'. NgFor only supports binding to Iterables such as Arrays.
> 
> That's weird... because that's how my project is working.
> I'm using it like this
> 
> ```
> <div *ngFor="let service of ('service' | translate)">
> 	<p>{{service.name}}</p>
> 	<p>{{service.desc}}</p>
> </div>
> ```
> 
> The json is structured like this
> 
> ```
> {
>   "service": [
>     { "name" : "someName1", "desc" : "someDesc1"},
>     { "name" : "someName2", "desc" : "someDesc2"},
>     { "name" : "someName3", "desc" : "someDesc3"}
>   ]
> }
> ```

ngFor works fine with forRoot()
But for forChild(), we get

'ERROR Error: Cannot find a differ supporting object 'service' of type 'string'. NgFor only supports binding to Iterables such as Arrays.'

**Comment by Amith278** [comment]
I have a quick workaround. 

Using keyvalue pipe :
 <*ngFor="let data of 'analysis_service.info-swiper' | translate | keyvalue ">

            {{ data?.value | unknow: "header" }}
            
              {{ data?.value | unknow: "body" }}
            
          
  </>
  
  And using a Custom pipe to tackle the "Object Unknown" issue while accessing any value

import { Pipe, PipeTransform } from '@angular/core';
--------------------------------------------------------------------------------
@Pipe({
  name: 'unknow',
})
export class UnknowPipe implements PipeTransform {
  transform(value: any, text?: any): unknown {
    if (
      value != null &&
      value != undefined &&
      value != '' &&
      text != null &&
      text != undefined &&
      text != ''
    )
      return value[text];
    return null;
  }
}

--------------------------------------------------------------------------
