### ISSUE TITLE
Translation does not update when params passed into translate pipe OR directive has changed

### ISSUE THREAD

**Issue by kamok** [ngx-translate/core#582]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[] feature request
```

**Current behavior**
For example, if you're passing in the object `{number: 1}` into the params of the translate pipe, if the object changes, like `{number:2}`, the view won't change. I have to use a dumb hack like `this.translateService.use(this.translateService.currentLang);` to force update of the params to use the new params.

So both of these don't update automatically when the model of the params change:
`<div>{{ 'HELLO' | translate:param }}</div>`
`<div [translate]="'HELLO'" [translateParams]="{value: 'world'}"></div>`

I'm using `ng2-translate` with the latest version of Ionic.

**Comment by 0xCHERRY** [comment]
You should always pass plain objects as your parameter. Checking deeply nested objects for possible changes is not only out of scope of this package, but also expensive and time-consuming.

You can pass a pointer to the property

```js
@Input() hero: { friends: [], name: string, foo: { bar: boolean } };
```

```html
{{"whip" | translate:hero.foo.bar}}
```

The [equals utility function](https://github.com/ngx-translate/core/blob/master/src/util.ts#L18) fails if the first value in an nested object passes the test.

**Comment by 0xCHERRY** [comment]
You should always pass plain objects as your parameter. Checking deeply nested objects for possible changes is not only out of scope of this package, but also expensive and time-consuming.

You can pass a pointer to the property

```js
@Input() hero: { friends: [], name: string, foo: { bar: boolean } };
```

```html
{{"hello" | translate:hero.foo.bar}}
```

The [equals utility function](https://github.com/ngx-translate/core/blob/master/src/util.ts#L18) fails if the first value in an nested object passes the test.

**Comment by 0xCHERRY** [comment]
You should always pass plain objects as your parameter. Checking deeply nested objects for possible changes is not only out of scope of this package, but time-consuming and expensive.

You can pass a pointer to the property

```js
@Input() hero: { friends: [], name: string, foo: { bar: boolean } };
```

```html
{{"hello" | translate:hero.foo.bar}}
```

The [equals utility function](https://github.com/ngx-translate/core/blob/master/src/util.ts#L18) fails if the first value in an nested object passes the test.
