### ISSUE TITLE
Nested Keys not work on ionic

### ISSUE THREAD

**Issue by Hanzofm** [ngx-translate/core#584]
**Current behavior**
If I use nested attributes for translate it not return the value of the key
html
<span>{{'HOME.TITLE' | translate}}</span>

languaje.json
{
  "HOME": {
    "TITLE": "Hola Angular 2 con ng2-translate!"
  }
}

It render on screen 'HOME.TITLE'

If I use no nested attributes it works perfectly.

**Please tell us about your environment:**
Ionic Angular 3.5.0
@angular/common": "4.1.3"
* **ngx-translate version:** x.x.x
@ngx-translate/core": "^7.0.0",
 "@ngx-translate/http-loader": "^0.1.0"
* **Angular version:** 2.x.x
 @angular/common": "4.1.3"
* **Browser:** Chrome

**Comment by SamVerschueren** [comment]
It should work. Are you sure the correct `languaje.json` file is loaded? Check the network tab. 
What does `{{'HOME' | translate | json }}` render?

**Comment by mouhamadhassan** [comment]
hello, i have same issue, nothing is translated. only key of the words are returned and not the translation...

any idea?

**Comment by DigitalMystery** [comment]
Same thing here except I attempted with the translate.get in the component.ts.  I also only ever get the key even if I do not nest.  I do get the correct file if I change between them though @SamVerschueren 

```
translate.get("MENU.HOME").subscribe((home: string) => {
     //home ends up being MENU.HOME
});
```

ionic angular 2.2.0
ngx-translate/core": "^7.1.0"
ngx-translate/http-loader": "^0.1.0"

**Comment by DigitalMystery** [comment]
Ok... after watching the debug with the console I saw that my file just had not been loaded before the call to translate.get.  So I wrapped the translate.get with translate.use.  I suppose this is probably only an issue with the first page, but now wondering do I need to wrap everything going forward.

```
translate.use("en").subscribe((res: any) => {
     translate.get("MENU.HOME").subscribe((home: string) => {
          //loads file and is correct now with different languages.
     });
});
```

**Comment by carauzs** [comment]
Anyone having this problem, make sure to set the default language:
```
constructor(translate: TranslateService) {
     translate.setDefaultLang('en');
}
```

**Comment by CodeAndWeb** [comment]
You can find a working example here: https://github.com/ngx-translate/ionic-example
