### ISSUE TITLE
Apply translate directive to all child elements

### ISSUE THREAD

**Issue by lentschi** [ngx-translate/core#585]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[X] feature request
```

**Current behavior**
Given a translation JSON like...

```json
{"key": "translation"}
```
... the following __will__ work:

```html
<div translate>key</div>
```
-> is converted to 

```html
<div translate>translation</div>
```

However 

```html
<div translate>
  <div>key</div>
  <div>some-other-text</div>
</div>
```
obviously will __not__ be converted.

**Desired behavior**
Convert each `childElement` recursively &rarr; So the above example would be converted to:

```html
<div translate>
  <div>translation</div>
  <div>some-other-text</div>
</div>
```
Obviously this would __break current applications__ - so what I suggest is either a global configuration option to turn this on/off, or an alternate directive (such as `translate-all`).

**Reproduction of the problem**
Here's the plunkr for the reproduction of the current behavior as well as a solution using a custom directive, that I've built:
http://embed.plnkr.co/2K5nUL4iMbotCjho6Kkz/
(_Caveat:_ The custom directive is just useful for very specific applications so far - For example it currently won't work with `translateParams`)

**What is the motivation / use case for changing the behavior?**
When applying the directive on components, that replace their `innerHTML`, wrapping everything in `childElements` (such as ionic's `<ion-title />` will do), the current `translate` directive won't work.
The only alternative would be to use `<ion-title>{{'key' | translate}}</ion-title>` which is a lot harder to read IMO.

**Please tell us about your environment:**

* **ngx-translate version:** 7.0.0

* **Angular version:** 4.0.2
 
* **Browser:** all

**Comment by CodeAndWeb** [comment]
Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.

I see the point in your feature request. But as you alredy said: It will break compatiblity and
and easy solution already exists.

We can add the feature if more people ask for it.
