### ISSUE TITLE
Translations are not refreshed on page if route stays the same.

### ISSUE THREAD

**Issue by StefH** [ngx-translate/core#587]
I've created an application based on [Angular4 Webpack Starter](https://github.com/AngularClass/angular-starter).

And I'm trying to use your `http-loader` to load the translations from multiple json files.

I've multiple json files : 1 file for each page.
So the layout is:
```
/assets/i18n/
             app.json
             page1.json
             page2.json
```

The problem is that the web-application loads first (all the .js files) and the translation json files are loaded **after** the page is displayed. So the translations only happen when I switch to a new route/page. However this does not work for the main page which stays the same. (Just doing a CTRL-R)

So my questions is: how to solve this ? Like forcing a refresh, maybe by calling `instant(key: string|Array<string>, interpolateParams?: Object): string|Object` from the App.component.ts ?

**Comment by CodeAndWeb** [comment]
Sorry for not answering earlier... I guess you already solved the issue?
Please open another issue if the problem still persists.
