### ISSUE TITLE
extract fails

### ISSUE THREAD

**Issue by jjdf01** [ngx-translate/core#588]
the following does not get extracted correctly, surrounding html gets extracted:

{{ 'Messages will be sent to {{email}}.' | translate: {email: email} }}
{{ 'Messages will be sent to %%email%%.' | translate: {email: email} }}

This gets extracted correctly.
{{ 'Messages will be sent to email.' | translate: {email: email} }}

Also having issues with
`<p class="u-color--blue" translate>All your <strong>known fingerprints</strong> will be supported.</p>`
'All your' and 'will be supported'  get extracted as seperate keys.

I am pretty sure this is a regex issue. The one used in pipe.parser.js seems to work for the first issue. So i think the issue might be in abstract-template.parser.js method _extractInlineTemplate. But i am just guessing here.

**Comment by CodeAndWeb** [comment]
I assume this is an issue for https://github.com/biesbjerg/ngx-translate-extract

Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.
I am closing the issue for now - you can re-open it if the issue still persists or you still need help.
