### ISSUE TITLE
Translation binding for parents and child

### ISSUE THREAD

**Issue by kasienna** [ngx-translate/core#590]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I added translations for my project, which has multi level components (big project initially made in angularjs, now rewriting to angular). For root it seems to be working. Then, I want to load component in child module and i keep having error of **"translate" pipe could not be found**. Even though i'm trying to initiate this in the module and all the stuff. It might be my lack of angular.io understanding, but documentation for more complex project is not yet provided...

**Reproduction of the problem**
I can't reproduce a problem because the project is kinda big. However I enclose some views on the project.
File structure:
![ang4error1](https://user-images.githubusercontent.com/15572983/27869042-ef7b03bc-619e-11e7-8af8-72519c59054a.png)

Working module:
![ang4error2](https://user-images.githubusercontent.com/15572983/27869050-f5d15ee6-619e-11e7-9800-c569b6464ca1.png)

Not working module:
![ang4error3](https://user-images.githubusercontent.com/15572983/27869057-fb5b3c60-619e-11e7-88df-ace4727d1e26.png)

I made sure that Inner modules are imported. When I remove translateModule import from AuthModule, it still doesn't work.

The components, both working and not working, are angular-cli generated. Not working component template when placed in the spot of working one, starts to work. 

**Please tell us about your environment:**

* **ngx-translate version:** 7.0.0

* **Angular version:** 4.2.2
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by StefH** [comment]
I'm not 100% sure (I'm also new in using this project), but do you maybe also need to add the `TranslateModule` to the `providers` list ?

**Comment by kasienna** [comment]
Just tried it, but nothing changed. Thanks anyway!

**Comment by kasienna** [comment]
I solved it. The thing was that my component has been linked through routing and not selector. In that case, you are supposed to provide TranslateModule in the routing module.

`import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { AuthComponent } from './auth.component';
import { LoginComponent } from './components/login/login.component';
import { RegisterComponent } from './components/register/register.component';

import { TranslateModule, TranslateService, TranslatePipe, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

const routes: Routes = [
{ 
  path: 'auth',
  component: AuthComponent,
  children: [
    { path: 'signin', component: LoginComponent },
    { path: 'signup', component: RegisterComponent }
  ]
}];

@NgModule({
  declarations: [LoginComponent, RegisterComponent],
  imports: [RouterModule.forChild(routes), RouterModule.forRoot(routes), TranslateModule],
  exports: [TranslatePipe],
  providers: [TranslateModule]
})
export class AuthRoutingModule { }
`
