### ISSUE TITLE
Plunkr template is broken in IE11

### ISSUE THREAD

**Issue by adamdport** [ngx-translate/core#591]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Plunkr template for reproducing issues is broken in IE11

**Expected/desired behavior**
Plunkr template works in IE11

**Reproduction of the problem**

> If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:01UjWY3TKfP6pgwXKuEa

Visit the above starting point in IE11

**Comment by malhardeshpande12** [comment]
The error that I receive, when I run the plunkr demo link in IE11, is of "Object doesn't support property or method 'assign'". This doesn't necessarily point to broken module, but instead, this is an issue of polyfills. Object.assign is part of ES6 and hence, is not supported on IE11.

The error will go away, after adding the pollyfill for Object.assign from the MDN wiki.

**Comment by ocombe** [comment]
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.
