### ISSUE TITLE
Feature: translated description for msgctxt in .po

### ISSUE THREAD

**Issue by akhildhanuka** [ngx-translate/core#599]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x ] feature request
```

**Current behavior**
There is no way to describe the translated text for the translators. We need a new directive to have a useful description which gets populated as msgctxt under .po files.

**Expected/desired behavior**
A new directive like translate-description to expect a description to explain the text to translators.

**Please tell us about your environment:**

* **ngx-translate version:** 7.0.0

* **Angular version:** 4.0.0
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by CodeAndWeb** [comment]
Adding this information has the disadvantage that it would also be in your production code.
I think it's better to keep this outside of your source code. 

One simple solution is to add this information in an external editor. E.g. [BabelEdit](https://www.codeandweb.com/babeledit) supports comments.
