### ISSUE TITLE
when translateValue is '' (not just undefined) we should get defaultLang translations as fallback

### ISSUE THREAD

**Issue by prophetw** [ngx-translate/core#609]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
en.json
{
"KEY1":"hello"
"KEY2":"value2"
}
zh.json
{
"KEY1":"ni hao"
"KEY2":""
}
use zh as curLang
set en as default lang
translate.instant('KEY2')    //   ''

if not find the key or result === ''
typeof translateResult === undefined or translateResult === ''
then use default language to translate again and trigger the missingHandler 

**Expected/desired behavior**
use zh as curLang 
set en as default lang
translate.instant('KEY2')=value2    //   value2

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:01UjWY3TKfP6pgwXKuEa

**What is the expected behavior?**
use zh as curLang 
set en as default lang
translate.instant('KEY2')=value2    //   value2

**What is the motivation / use case for changing the behavior?**
as a develop 
we extract the en.json zh.json with value to be ''
and the tranlations come to us in 3-7 days

**Comment by CodeAndWeb** [comment]
You can try this loader from here: https://github.com/CodeAndWeb/ngx-translate-demo/blob/master/ngx-translate-demo/src/app/pruning-loader.ts

It removes all empty translations.

**Comment by carsten-ennulat** [comment]
@CodeAndWeb this file is not there anymore? how to deal this problem nowadays?

**Comment by marshal604** [comment]
@carsten-ennulat 
here
https://github.com/ngx-translate/core/issues/830#issuecomment-630221928
