### ISSUE TITLE
Incompatibility with SSR using angular/cli

### ISSUE THREAD

**Issue by feloy** [ngx-translate/core#616]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Expected/desired behavior**
ngx-translate should be usable at server-side with the method provided by the angular CLI

**Reproduction of the problem**

(https://github.com/feloy/bug-ngx-translate)

- I've created a new project with 'ng new', followed instructions to add ngx-translate.
- at this step with 'ng serve', app works correctly
- I've followed the steps to render with node, at https://github.com/angular/angular-cli/wiki/stories-universal-rendering
- ng build -aot -prod -app 1 --output-hashing=none
- node server.js

**What is the expected behavior?**
The page should be rendered

**Current behavior**
$ node server.js
```
/home/philippe/Devs/BUGS/bug-ngx-translate/node_modules/@ngx-translate/core/src/translate.pipe.js:1
(function (exports, require, module, __filename, __dirname) { import { Pipe, Injectable, ChangeDetectorRef } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.dKea (/home/philippe/Devs/BUGS/bug-ngx-translate/dist-server/main.bundle.js:1:6517)
    at r (/home/philippe/Devs/BUGS/bug-ngx-translate/dist-server/main.bundle.js:1:211)
```

**Please tell us about your environment:**
```
@angular/cli: 1.3.0-rc.3
node: 7.1.0
os: linux x64
@angular/animations: 4.3.2
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.3.0-rc.3
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2
@angular/platform-server: 4.3.2
```

* **ngx-translate version:** 7.1.0

**Comment by matthewharwood** [comment]
I think this has a problem with new commit https://github.com/angular/angular/pull/18496/commits/5db475c2c28ef1aad8fafe6087e9dab0cccb8dab

**Comment by bliitzkrieg** [comment]
I am also experiencing this issue

**Comment by kirillgroshkov** [comment]
Same here!

**Comment by AnthonyNahas** [comment]
im getting the same error

**Comment by iTwangcj** [comment]
im getting the same error

**Comment by ocombe** [comment]
This is an error from the cli, nothing that I can do from here. The issue has been reported and will be fixed for v5 most likely

**Comment by feloy** [comment]
@ocombe I close the issue
