### ISSUE TITLE
ng2-translate@5.0.0 requires a peer of @angular/core@^2.0.0 but none was installed

### ISSUE THREAD

**Issue by abidmix** [ngx-translate/core#617]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
ng2-translate@5.0.0 requires a peer of  angular @angular/core@ ^2.0.0 but none was installed

**Expected/desired behavior**
Make ng2-translate@5.0.0   require peers of   angular versions 4.X.X

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:01UjWY3TKfP6pgwXKuEa

**What is the expected behavior?**
 ng2-translate@5.0.0   should require peers of   angular versions 4.XX

**What is the motivation / use case for changing the behavior?**
Would still like t use this library after migrating to angular 4.X.X

**Please tell us about your environment:**

* **ngx-translate version:** 5.0.0

* **Angular version:** 4.3.2
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by rbarkhouse** [comment]
+1 for this, we are trying to incorporate shrinkwrap into our build process and this error is preventing us.

**Comment by abidmix** [comment]
@rbarkhouse .For now, I have  to resorted to using @ngx-translate/core which works well with angular versions 4.X,X . My imports have been changed to
`import { TranslateModule, TranslateLoader } from '@ngx-translate/core';`
from
`import {TranslateModule, TranslateStaticLoader, TranslateLoader } from 'ng2-translate';`

Hope this will help you.
