### ISSUE TITLE
Official ngx-translate plunkr demo does not work

### ISSUE THREAD

**Issue by kolkov** [ngx-translate/core#618]
Please fix it again!
![image](https://user-images.githubusercontent.com/3740898/28813061-58a5bd9e-76a0-11e7-9a12-3b9747f97a0e.png)

**Comment by kolkov** [comment]
Slightly adjusted the plunker. Perhaps a lot of excess is left, please check.
https://plnkr.co/edit/O6EYGMBBF2zp2mOOKjBG?p=preview

**Comment by matthewharwood** [comment]
What did you change? I'm not seeing the diff?

**Comment by real050280** [comment]
Skimming at it, this line has been modified.

export function HttpLoaderFactory(http: HttpClient) {
...

**Comment by ocombe** [comment]
Thanks, I've updated it
