### ISSUE TITLE
Placeholders in translation files

### ISSUE THREAD

**Issue by devbean** [ngx-translate/core#619]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```
**Current behavior**
The placeholder should be used by name. For example, 
```
{
  'Validation': [
    'Required': '{{name}} is required.'
  ]
}
```
Then we could use it as following:
```
// --
const data = { name: 'This field' };
// --
<span>{{ 'Validation.Required' | translate:data }}</span>
```
**Expected/desired behavior**
Use placeholders by numbers as following:
```
{
  'Validation': [
    'Required': '{{0}} is required.'
  ]
}
```
Then we could use it as following without instance fields in ts files:
```
// --
<span>{{ 'Validation.Required' | translate:'This field' }}</span>
```
Most other frameworks of i18n packages have such features. I think this should be added in ngx-translate.

**Comment by CodeAndWeb** [comment]
You can use `{{ 'demo.greeting' | translate:{'name':'Andreas'} }}`- which is not as compact as your suggestion - but close.
