### ISSUE TITLE
How to translate ng1 templates in a hybrid Angular app?

### ISSUE THREAD

**Issue by swandelow** [ngx-translate/core#622]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

Is there any way to handle i18n for ng1 templates using ngx-translate?

I'm running a hybrid ng1-ng2 app, using Pascal Precht's angular-translate to handle localization in the ng-1 code and ngx-translate to handle localization in the ng-2 code. 
I've checked [issue/305](https://github.com/ngx-translate/core/issues/305) but in my case **I would like to remove angular-translate from my project and only use ngx-translate.** 

I've tried removing angular-translate, doing a downgrade of `TranslateService` (registering it as `$translate` in ng1) and creating a custom filter called `translate` that use $translate to perform translation.
This works fine when the page is loaded. But it doesn't work when I change the language. Only the ng2 parts of my app get translation.

* **ngx-translate version:** 7.1.0

* **Angular version:** 2.4.5

**Comment by CodeAndWeb** [comment]
Sorry for not answering earlier... I guess you already solved the issue?
However it's hard to help you at all with the information you provided...
Please open another issue if the problem still persists.
