### ISSUE TITLE
Facing Problem with setTranslation in ngx-translate 7.0.x

### ISSUE THREAD

**Issue by erhimanshugarg** [ngx-translate/core#627]
Hi  @ocombe , 

I am using ngx-translate method setTranslate to merge the new_lang.json file into my lang.json file at runtime with some condition. I am passing 3rd Parameter of method as true (shouldMerge). 

new_lang.json file has the same json object keys as lang.json has,  but with some value changes. when my condition gets true, new_lang.json gets deep merged into lang.json and forms an updated lang.json.

Sample code -

in my app.component.ts inside ngOnInit -

translateObject.use('lang.json');

if(condition == true ) {

translateObject.use('new_lang.json').subscribe( (response: any) => { 
translateObject.seTranslate('lang.json', response, true);
}) ;

**Current behavior**

After merge when i am trying to get the json data using key (translate.get() ) method, it is picking up the new values from new_lang.json instead of updated lang.json file.

**Expected/desired behavior**
Values should be taken from lang.json instead new_lang.json

**Please tell us about your environment:**

* **ngx-translate version: 7.0.x

* **Angular version: 2.x.x
 
* **Browser: all

**Comment by erhimanshugarg** [comment]
Any help or suggestions please??

**Comment by erhimanshugarg** [comment]
++ @SamVerschueren

**Comment by jlberrocal** [comment]
you are doing things bad.
why are you doing this ```translateObject.use('new_lang.json').....

try using this code:
```typescript
constructor(translate: TranslateService) {
    let lang = CONFIG.DEFAULT_LANGUAGE;
    let i18n = require(`./i18n/${lang}.json`);

    translate.setTranslation(lang, i18n, true);
}
```

this is the solution i proposed in #411 and is the one that have been working for me

**Comment by erhimanshugarg** [comment]
@jlberrocal i want to merge a new another lang/ json file from same to folder to default lang json file based on some condition. In above example i18n will take the same lang json file what i understood. Please correct me if i am wrong.

**Comment by CodeAndWeb** [comment]
Sorry for not answering earlier... I guess you already solved the issue... Anyways...

`.use()` should be called with the language code, e.g. `.use("de")`
`.setTranslation()` is meant to be called with the language code and the translations.
