### ISSUE TITLE
How to use pipes when translating errors

### ISSUE THREAD

**Issue by mrnickel** [ngx-translate/core#628]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When formatting a dynamic form error, the translation key is output instead of proper translation.

**Expected/desired behavior**
Proper translation is displayed, not the key.

**What is the motivation / use case for changing the behavior?**
I am trying to dynamically translate a form field error. One of the benefits of the Angular FormBuilder is that you don't have to litter your HTML with conditional displays if a single field can have multiple errors.

For example, if a Code must be entered, has a min length and a max length, without dynamically displaying the error, the HTML would have numLinesOfHtmlToDisplayError * 3 more lines than is strictly necessary.

Within my component, I have a property that houses all of my validation messages:
```
  validationMessages = {
    code: {
      required: 'Customers.Add.Errors.Code.required',
      minlength: 'Customers.Add.Errors.Code.minlength',
      maxlength: 'Customers.Add.Errors.Code.maxlength'
    }
  }
```

Each of the values correspond to a key in my translation files:

```
"Customers": {
    "Add": {
      "Errors": {
        "Code": {
          "required": "Code is required.",
          "minlength": "Code must be at least 4 characters long.",
          "maxlength": "Code cannot be more than 24 characters long."
        }
      }
    }
```

Then within my component HTML:

```
<div [ngClass]="{'form-group': true, 'has-danger': formErrors.code}">
          <label for="code" class="form-control-label" translate>Customers.Add.Code</label>
          <input type="text" class="form-control" id="code" placeholder="Code" name="code" formControlName="code" required>
          <span *ngIf="formErrors.code" class="form-control-feedback">{{ formErrors.code | translate }}
          </span>
        </div>
```

So for example if I have a single character entered, I would expect to see the error: **Code must be at least 4 characters long** as defined in my en.json file, but instead it reads **Customers.Add.Errors.Code.required**

Am I missing something?

Thanks so much for your help, the ngx-translate library has been a pleasure to work with thus far.

**Please tell us about your environment:**

* **ngx-translate version:** 7.1.0

* **Angular version:** 4.3.0
 
* **Browser:** all

**Comment by CodeAndWeb** [comment]
Sorry for not answering earlier... I guess you already solved the issue...
Please open another issue if the problem still persists.

**Comment by harshals13** [comment]
@CodeAndWeb Is there a solution to this issue? I'm facing the exact same problem. Thanks.

**Comment by fromage9747** [comment]
Has anyone figured this out?

**Comment by fromage9747** [comment]
In case anyone comes past this, the problem is the selector, at least for me anyway.  I had a nested selector and I had neglected to include the root selector.  Once included, it worked beautifully.
