### ISSUE TITLE
translate text with . in the json keys

### ISSUE THREAD

**Issue by mydata** [ngx-translate/core#631]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
The translation content is loaded via http.  We have a json data similar to as following
{ "content_bundle": { "default": [{ "redirect.message": "Redirecting" }] } }

the json keys can contain '.' character
when we use the translate pipe in html as :
{{ ('content_bundle.default[0]["redirect.message"]' | translate) || defaultTitle }}

it always display as 'content_bundle.default[0]["redirect.message"]'

Note: defaultTitle : this will be hard coded in component to display default value.
**Expected/desired behavior**

the translation should display as Redirecting ( json property value)
**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:WccVZSBM0rUgq2sXSUbe

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-translate version:** 7.0.0

* **Angular version:** 4.x.x
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by iget-master** [comment]
The `dot` character is reserved to nest translations, maybe it's easiest you use an underscore instead: `redirect_message`

**Comment by cedx** [comment]
There should be an option allowing to choose the character used, like `nestedObjectDelimeter` in [ng-translate](https://angular-translate.github.io).

**Comment by CodeAndWeb** [comment]
Making it configurable adds a whole layer of complexity to ngx-translate, ngx-translate-extract and tools like [BabelEdit](https://www.codeandweb.com/babeledit) for the small convenience of using a "." instead of "-" or "_".
