### ISSUE TITLE
Spanish language not work

### ISSUE THREAD

**Issue by fredroo** [ngx-translate/core#638]
hello guys, in my project ionic 3 when call es.json show english 

someone help me

**Comment by fredroo** [comment]
follow this guide https://ionicframework.com/docs/developer-resources/ng2-translate/

**Comment by fredroo** [comment]
follow but not work, only spanish not work

**Comment by CodeAndWeb** [comment]
Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.
I am closing the issue for now - you can re-open it if the issue still persists.
