### ISSUE TITLE
Language as an URL parameter

### ISSUE THREAD

**Issue by kommad** [ngx-translate/core#639]
Hi guys,

I'm wondering if there is any possibility to set the language in the route in angular 2 
Example: 
localhost:xxx/home;lang=en      => this should give the english version.
localhost:xxx/home;lang=fr      => this should give the french version.

does anyone have any Idea ?

thanks

**Comment by sonukapoor** [comment]
@kommad Probably better to ask on StackOverflow

**Comment by Tenmak** [comment]
Seems pretty easy to me, simply get your URL parameter from the ActivatedRoute and use the Translate service to use the wanted language.
