### ISSUE TITLE
Create @Translate decorator

### ISSUE THREAD

**Issue by niccolascosta** [ngx-translate/core#645]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[X ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```
I would like to create an instance of translateService in the attribute decorator and for this I need to create an instance or grab an existing one. It's possible ?

I tried to do this but I did not succeed.

`/**
 * @Translate decorator responsável por setar a váriavel environment na propriedade anotada.
 */
import {
  MissingTranslationHandler,
  TranslateLoader,
  TranslateParser,
  TranslateService,
  USE_STORE
} from '@ngx-translate/core';
import {OpaqueToken, ReflectiveInjector} from '@angular/core';
import {TranslateStore} from '@ngx-translate/core/src/translate.store';
import {httpLoaderFactory} from '../../app.module';

export function Translate(principalKey: string, anotherKey?: string) {
  /**
   * target => instancia do qual o decorator foi colocado.
   * prop => nome do metodo/atributo/classe no qual decorator foi colocado.
   */

  return (target: any, propName: string) => {
    const descriptor = Object.getOwnPropertyDescriptor(target, propName) || {};

    const injector = ReflectiveInjector.resolveAndCreate([TranslateService, [TranslateParser,
      {provide: TranslateLoader, useFactory: (httpLoaderFactory)},
      TranslateStore,
      MissingTranslationHandler, {
        provide: USE_STORE,
        useValue: OpaqueToken
      }]]);

    const translate = injector.get(TranslateService);

    translate.get(principalKey).subscribe((model: any) => {
      if (anotherKey !== '') {
        translate.get(anotherKey, {model}).subscribe((value: any) => descriptor.value = value);
      } else {
        descriptor.value = model;
      }
    });

    Object.defineProperty(target, propName, descriptor);
  };
}
`

* **ngx-translate version:** 7.0.2

* **Angular version:** 4.0.0
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by CodeAndWeb** [comment]
Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.
I am closing the issue for now - you can re-open it if the issue still persists or you still need help.

**Comment by benkeil** [comment]
If somebody needs a working solution:

```typescript
import { Logger } from 'log4javascript';
import { TranslateService } from '@ngx-translate/core';
import { getLogger } from '../helpers/logger-helper';
import { AppModule } from '../../app.module';

const logger: Logger = getLogger('com.xxx.yyy', 'Translate');

export default function Translate(translationKey: string | Array<string>, interpolateParams?: Record<string, any>) {
  logger.debug(`@Translate ${ translationKey }`);
  return function (target: Record<string, any>, key: string | symbol) {
    const translationService = AppModule.injector.get(TranslateService);
    translationService.get(translationKey, interpolateParams)
      .subscribe((value) => {
        logger.debug(`translation for ${ translationKey }: ${ value }`);
        Object.defineProperty(target, key, {
          get: () => value,
          set: () => {
            //
          },
        });
      });
  };
}
```
