### ISSUE TITLE
Combine CustomLoader with HTTP-State-Transfer

### ISSUE THREAD

**Issue by crebuh** [ngx-translate/core#646]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```
Hi Guys, currently I'm working on an universal application. There I'm using a custom loader to read a .json-file on the server side like this:

     import { Observable } from 'rxjs/Observable';
     import { TranslateLoader } from '@ngx-translate/core';
     import { TransferState } from '../modules/transfer-state/transfer-state';
     const fs = require('fs');

     export class TranslateUniversalLoader implements TranslateLoader {
       constructor(
          private prefix: string = 'i18n',
          private suffix: string = '.json'
      ) { }

    public getTranslation(lang: string): Observable<any> {
        return Observable.create(observer => {
            observer.next(fs.readFileSync(`${this.prefix}/${lang}${this.suffix}`, 'utf8'));
            observer.complete();
        });
    }
    }

Now there is this great module called ngx-state-transfer, which will let you pass data from server to client by injecting the data as script-tag into the page. I'm already passing data which I've fetched on the server side via http down to the client.

Now I want to add this mechanism also for the loaded translation file. My concrete problem right now is I have no Idea how to integrate the transferState service into my TranslateUniversalLoader to pass the loaded json file from the server to the client.

Any ideas about that?

**Comment by peterpeterparker** [comment]
Should really the translation be passed from the server side to the frontend?

I thought a bit about it and finally I think it's kind of good to initialize ngx-translate on the client side too. My website is available in four languages and this let me offer my users a dynamic language change/switch without having to query the server, you know what I mean?

(I opened/closed an issue about this subject https://github.com/ngx-translate/core/issues/625)

I did the same as you for the server side, furthermore I added a "standard" loader in `app.module.ts`

Like:

     export function exportTranslateStaticLoader(http: HttpClient) {
        return new TranslateHttpLoader(http, './i18n/', '.json');
    }
   ...
   imports: [
       ...
       ,
    TranslateModule.forRoot({
        loader: {
          provide: TranslateLoader,
          useFactory: exportTranslateStaticLoader,
          deps: [HttpClient]
        }
      }
    ),
    ....

**Comment by crebuh** [comment]
@peterpeterparker 

yes of course ngx-translate should be initialized on the client-side too. I justed wanted to avoid that I have to fetch the json-file again. Of course when the user switches the language on the client-side (which won't happen that often) the corresponding json-file have to be loaded. so the workflow should look like this

1) Init ngx-translate on the server side
2) load json file and put its contents into the body of the side with the http-transfer-state module
3) when the client kicks in ngx-translate is initialized again
4) the loader on the client side checks if it can receive data via the http-transfer-state module if so take this data if not make an additional http call

**Comment by peterpeterparker** [comment]
@crebuh cool, good to hear we are on the same page and that you a find a solution which suits you

I just would like to add a notice to your solution. Actually transfer-state add the json content inside the rendered html page. If you have multiple translation files with a lot of translations key, the side effect could be that the html kind of gonna be heavy, maybe that could be a problem in some special situations?

**Comment by crebuh** [comment]
@peterpeterparker 

yes you are right, but I think it will still be faster than fetching with an additional http call ;)
