### ISSUE TITLE
NGX not translating

### ISSUE THREAD

**Issue by tryadelion** [ngx-translate/core#647]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

When i try to use NGX-translate on this current Ionic3 project, neither instant, nor the pipe, nor the get work, i'm always retrieving the key, and i don't know why.

![captura de pantalla 2017-09-01 a las 12 24 14](https://user-images.githubusercontent.com/3778474/29967094-3ba93abc-8f15-11e7-90f1-46966539d12d.png)

this is my log output. you can see that when i print the .use("ca") output, it prints the translated stuff, but then  i tried translating "accept", whose value should be "acceptar", and it prints the key.

ionic info output:

sh-3.2# ionic info

cli packages: (/usr/local/lib/node_modules)

    ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.0
    ios-sim           : 5.0.13
    Node              : v6.9.2
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b

ngx version

  "ngx-translate/core": "^7.2.0",
        "ngx-translate/http-loader": "^1.0.2",

angular version

"angular/common": "4.1.3",
        "angular/compiler": "4.1.3",
        "angular/compiler-cli": "4.1.3",
        "angular/core": "4.1.3",
        "angular/forms": "4.1.3",
        "angular/http": "4.1.3",
        "angular/platform-browser": "4.1.3",
        "angular/platform-browser-dynamic": "4.1.3",

**Comment by tryadelion** [comment]
Found the error.

rolled back to  "@ngx-translate/http-loader": "^0.1.0", and it worked-

**Comment by cedx** [comment]
`ngx-translate/http-loader` requires the new `HttpClient` provided by Angular 4.3+.

**Comment by tryadelion** [comment]
Ionic 3.X doesn't run over angular 4.3+ for now, is there any way to,ehm, fix this?

**Comment by ocombe** [comment]
not really, you can just use the old version until ionic updates its dependencies

**Comment by tryadelion** [comment]
what is the latest version that did work 1'00% fine with 4.1.3?

**Comment by ocombe** [comment]
v0.1.0

**Comment by tryadelion** [comment]
Thank you very much
