### ISSUE TITLE
Special chars not translated

### ISSUE THREAD

**Issue by lippomano** [ngx-translate/core#652]
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request

I have a problem with special chars like à, I see only a ?. 
Do I need to use something particular to translate the special chars?
My project is in utf-8
![cattura](https://user-images.githubusercontent.com/27501745/30054629-f7a89a04-922c-11e7-97fd-ed43386e2450.PNG)

**Comment by Namoshek** [comment]
Although it isn't really a solution to your problem as it introduces other issues, have you tried something like `<h1 [innerHtml]="'your.loca.key' | translate"></h1>`?

**Comment by CodeAndWeb** [comment]
UTF-8 in your json files should be fine.
https://github.com/CodeAndWeb/ngx-translate-demo uses German "Umlauts". 

Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.
I am closing the issue for now - you can re-open it if the issue still persists or you still need help.
