### ISSUE TITLE
7.2.1 broke our build in Angular2 project with Angular4 dependency

### ISSUE THREAD

**Issue by SebastianMetzger** [ngx-translate/core#653]
**Current behavior**
ERROR in [at-loader] node_modules/@ngx-translate/core/src/translate.service.d.ts:1:24 
    TS2305: Module '"OUR_REPOSITORY/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

**Expected/desired behavior**
Build should work 

**Reproduction of the problem**
I guess this is because the main repository still depends on Angular 2.4.10 and ngx-translate 5.0.0 and we have a dependency module that has itself already a dependency to Angular ~4.0.0 and ngx-translate ^7.10
The inner ngx-translate looks for the angular/core and resolves the 2.4.10 version instead of the 4.x.x version.

**What is the motivation / use case for changing the behavior?**
It can be fixed by hard putting the dependency to 7.2.0 in the submodule

Not sure if the issue is basically our fault and we should switch everything to Angular 4.0.0. or if the library should be resilient to such a dependency issue.

I just wanted to report it, if someone else might have the same issue.

**Comment by ocombe** [comment]
Ah yes that's my fault, I need to update the dependency and make a breaking change instead, sorry about that I'll fix it with a new release

**Comment by ocombe** [comment]
Fixed in 7.2.2! I'll release the version 8 with the new dependency to Angular 4+
