### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by aguerere** [ngx-translate/core#664]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When trying to load the demo in your website, it fails with this error in the js console:
```TypeError: "encoding" must be a valid string encoding```

**Expected/desired behavior**
The demo should load successfully.

**Reproduction of the problem**
https://embed.plnkr.co/pYo6bFPRRxVPgRR8toDt/

**What is the motivation / use case for changing the behavior?**
So that we can show it working to our boss.

**Please tell us about your environment:**
Mint 18.2, Chrome 61.0.3163.79 64-bit

**Comment by ocombe** [comment]
Hello,

where did you find this link? the correct plunkr for the demo (in the docs) is: https://plnkr.co/edit/WccVZSBM0rUgq2sXSUbe?p=preview

**Comment by ocombe** [comment]
Anyway, I just checked, it's a bug in plunkr for the embeded views, all links like "embed.plnkr.co" seem to fail, you should use the edit/preview link instead (see above)

**Comment by aguerere** [comment]
That link was found in your website a few hours ago. It seems it has been fixed already there as well. Thanks @ocombe !

**Comment by ocombe** [comment]
yes, I've updated it :)
