### ISSUE TITLE
Can not find .json path containing languages

### ISSUE THREAD

**Issue by LizanLycan** [ngx-translate/core#665]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Can not find .json path containing languages:
![image](https://user-images.githubusercontent.com/15185582/30299956-222e9696-9720-11e7-960a-160219b9959d.png)

**What is the expected behavior?**
Run like demo

**Please tell us about your environment:**
Runing on angular 4.1.3, and configuring the HttpLoader:
`export function HttpLoaderFactory(http: Http) {
    return new TranslateHttpLoader(http, "languages/", ".json");
}
`

* **ngx-translate version:** 8.0.0

* **Angular version:** 4.1.3 (configured with angular/http)
 
* **Browser:** [all ]

**Comment by yoannjauffroy** [comment]
+1

**Comment by yoannjauffroy** [comment]
Hello @LizanLycan , 
I solved the problem by modifying the angular-cli.json file : 

```
"assets": [
  "assets",
  "favicon.ico",
  "./app/demo/demo/assets" // add this line
 ]
```
In my case the json file is here : http://localhost:4200/app/demo/demo/assets/i18n/fr.json

**Comment by LizanLycan** [comment]
Ok, I will soon prove this and comment on it. Thanks @yoannjauffroy

**Comment by dave0688** [comment]
I kind of have a similar issue. It can't find the desired .json language file:

It searches in:
localhost:9000/www/i18n

but the language file is in:
localhost:9000/www/target/www/i18n

So somehow the path is wrong... This bug came with the most recent angular update I assume.

Can anybody help please?

**Comment by CodeAndWeb** [comment]
Sorry for not answering earlier...
It's hard to help with these issues without knowing your complete configuration.
I'll close this issue for now. Submit a new one it if the problem still persists.
