### ISSUE TITLE
[Ionic 3] Building with --prod. Error: Illegal state: symbol without members expected.

### ISSUE THREAD

**Issue by polcham** [ngx-translate/core#666]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] support request
[ ] feature request
```

**Current behavior**
Calling command to build the project: ionic cordova build android --prod. 
Shows:
**Error: Illegal state: symbol without members expected, but got {"filePath":"/Users/paulcham/ionic/starter/src/pages/intro/intro.ts","name":"IntroPage","members":["loader"]}.**

In my IntroPage module:
```
@NgModule({
  declarations: [
    IntroPage,
  ],
  imports: [
    IonicPageModule.forChild(IntroPage),
    TranslateModule.forChild()
  ],
  exports: [
    IntroPage
  ]
})
```

Removing TranslateModule.forChild(), will make it build successfully, so I assume the issue is related with ngx-translate. Perhaps there's a missing metadata or anything that is required by AoT. Are there anyway to bypass this for now? I'm pretty new to AoT and is stuck to this issue for days and was unable to make a successful --prod build. Thanks so much, appreciate the time and help.

**Expected/desired behavior**
Should be able to build successfully and make an .apk

**Reproduction of the problem**
Start a clean Ionic 3 project, add TranslateModule in the module of a LazyLoaded page. Call ionic cordova build android --prod.

**What is the expected behavior?**
Will not be able to build --prod successfully and show Error: Illegal state: symbol without members expected on the console.

**Please tell us about your environment:**
cli packages: (/Users/paulcham/ionic/starter/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.8
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.4.2

System:

    Node  : v8.2.1
    npm   : 5.3.0
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b

* **ngx-translate version:** ^7.0.0

* **Angular version:** 4.1.3
 
* **Browser:** [ Android X.X Web Browser | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mtshare** [comment]
+1

**Comment by flamasweb** [comment]
+1

**Comment by mtshare** [comment]
Any solution for this? I can't build my app with --prod flag!

**Comment by polcham** [comment]
I am able to fix this by setting all the other module imports to TranslateModule.forChild(). The forChild() function should be empty. You shouldn't also use forRoot().

**Comment by mtshare** [comment]
@polcham Thanks! This fixed for me! @flamasweb

**Comment by flamasweb** [comment]
@mtshare that fixed, thanks @polcham!
