### ISSUE TITLE
How to get selected language in C#

### ISSUE THREAD

**Issue by dobrinsky** [ngx-translate/core#668]
[x] support request => check the FAQ and search github for a similar issue before submitting

How can we get the selected language in C#, in a .NET Core 2 application.

Sorry for this really short question, but I do not know what to write more here...

**Comment by SamVerschueren** [comment]
C#? This is an Angular module, not a C# library.

**Comment by dobrinsky** [comment]
Yes, I know. How can we get the selected language in backend. I was saying that I am using C#

**Comment by SamVerschueren** [comment]
Listen for changes with the [`onLangChange`](https://github.com/ngx-translate/core#properties) event and send it to your backend with an API to change the user setting or something.

**Comment by dobrinsky** [comment]
Thank you very much! Sorry for the late response
