### ISSUE TITLE
interpolateParams not working when service used

### ISSUE THREAD

**Issue by callawey** [ngx-translate/core#675]
translate.get with interpolated params not using params

`
        this.translate.get('testing {{param1}}', { param1: 'test value' }).subscribe((data: string) => { _result = data; console.log(data); }, () => { return _result });
        console.log(_result);
`
this results as testing {{param1}}

it should  output 
this results as testing test value

* **ngx-translate version: 8.0.0

* **Angular version: 4.4.1
 
* **Browser:** [all]

**Comment by Gamboster** [comment]
Hello @callawey, Did you find the solution for this issue?

Could you share it? I have the same problem.

**Comment by callawey** [comment]
hi @Gamboster 

I wrote a class for translation service and inside it i use below method to handle translation

```
    getTranslationAsync(key: string | Array<string>, interpolateParams?: Object): string | any {
        var _result;
        this.translate.get(key, interpolateParams).subscribe(data => { _result = data; }, () => { return _result });
        return _result;
    }
```

and inside my components, i set it to a variable like this:

```
this.gT = (key: string, interpolateParams?: Object) => this.translationService.getTranslationAsync(key, interpolateParams);

```

after that, this works:

```
this.gT('testing {{name}}', {name: 'some name'})

```

**Comment by Gamboster** [comment]
Thank you very much for your response.
Do you know if I can do something like this ?

`let message = this.translate.instant('Maximum amount allowed is {{max}}', { max: max });`

When I run console.log(message); I get 

Maximum amount allowed is {{max}}
instead Maximum amount allowed is 35.99

I just trying to use it inside a component.

**Comment by ChrisProlls** [comment]
Same problem here ! 
`this.translationService.get(this.TRANSLATIONKEY, { reference: this.product.reference })`
with
`"TRANSLATIONKEY": "Produit {reference} ajouté à la sélection"`

And I get the translation without the param replaced ...
@Gamboster have you find any solution ?
