### ISSUE TITLE
Function 'get' should be synchronous

### ISSUE THREAD

**Issue by metatypeman** [ngx-translate/core#676]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
Now function 'get' returns Observable.
So, I can not use this function for simple translation strings for messages in js/ts code.
I can not even understand how to use this function in its current signature.

**Expected/desired behavior**
Function 'get' should return as string the translated value of a key or the key if the value was not found.

**Comment by ocombe** [comment]
If you want something synchronous, use `instant`, not `get`, but be aware that it can be undefined if translations have not been loaded yet.

**Comment by metatypeman** [comment]
Thanks you! I just did not notice this method.
