### ISSUE TITLE
Errors not propagating

### ISSUE THREAD

**Issue by chancezeus** [ngx-translate/core#684]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When setting using `translateService.use(translateService.getBrowserLang()).subscribe` it is impossible to handle errors since there is no error handler defined in the observer inside the service (see https://github.com/ReactiveX/rxjs/issues/2145 for a bug report which explains why this is the case).

**Expected/desired behavior**
The error handler of the subscriber in my code is called so I can reset the language to one of the known/working languages (or (better option) the service handles this internally resetting the current language to either the previous language or the default language).

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:WccVZSBM0rUgq2sXSUbe

http://plnkr.co/edit/lNmVAFcneFm86CwuAagP?p=preview

**What is the expected behavior?**
Alert is shown because "non_existing_language" can not be loaded

**What is the motivation / use case for changing the behavior?**
Handling dynamic loading of (future) languages from a server environment instead of only relying on locally available languages.

**Please tell us about your environment:**

* **ngx-translate version:** 8.0.0

* **Angular version:** 4.3.6
 
* **Browser:** all

**Comment by CodeAndWeb** [comment]
Duplicate: #751
