### ISSUE TITLE
Http to HttpClient

### ISSUE THREAD

**Issue by jfpcarreira** [ngx-translate/core#685]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ X ] feature request
```

**Current behavior**
ngx-translate currently only supports Http from '@angular/http' but Angular as deprecated Http and moved to HttpClient from '@angular/common/http'.

**Expected/desired behavior**
Migrate all Http references to HttpClient

**What is the motivation / use case for changing the behavior?**
Keep updated with Angular newer version

* **ngx-translate version:** 5.0.0

* **Angular version:** 4.4.3
 
* **Browser:** Chrome 61 (64 bits)

**Comment by ocombe** [comment]
Update the loader, the latest version uses HttpClient. The core has no
reference to Http, only the loader does

**Comment by jfpcarreira** [comment]
OK, I have updated the loader (`@ngx-translate/http-loader`) and I'm now able to use the HttpClient in stead. But doing this I have 2 minor problems that bother me a bit:

1. In order to use the loader I had to also add the dependency with `@ngx-translate/core`
2. I can't remove the `@angular/http` dependency. If I do it I have the following error: "ERROR in C:/Pessoal/tvpt2/client/node_modules/ng2-translate/index.d.ts (2,22): Cannot find module '@angular/http'."

**Comment by sancelot** [comment]
you can remove @angular/http reference

app.module.ts 
`
import { HttpClient, HttpClientModule } from '@angular/common/http';
import {TranslateService, TranslateModule, TranslateLoader } from '@ngx-translate/core';
import {TranslateHttpLoader} from '@ngx-translate/http-loader';



export function createTranslateLoader(http: HttpClient) {
        console.log("in createTranslateLoader");  
        return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule({
  imports: [
    BrowserModule,
    // Include it under 'imports' in your application module
    // after BrowserModule.
    HttpClientModule,
    NgbModule,
    TranslateModule.forRoot({
			loader: {
				provide: TranslateLoader,
				useFactory: (createTranslateLoader),
				deps: [HttpClient]
			}
		}),
`

**Comment by jfpcarreira** [comment]
Yes, I know, and that's what I did. But I cannot remove the dependency from my package.json. If I `npm uninstall @angular/http --save` and then run the app I have the error that I have described before. This means that you can use the ng2-translate with the loader from ngx-translate and do any reference to Http on your code, but your project will still need that dependency.
In order to have a cleaner solution ng2-translate should do a new version where they migrate all the Http to HttpClient.

**Comment by ocombe** [comment]
You need to switch to `@ngx-translate/core` because ng2-translate doesn't exist anymore.

**Comment by jfpcarreira** [comment]
Oh, ok, I didn't realised that ngx-translate was the evolution of ng2-translate. Just migrated and all works just as expected! Thanks!
