### ISSUE TITLE
Using ngx-translate with nested JSON arrays

### ISSUE THREAD

**Issue by Pomanks** [ngx-translate/core#686]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
Say you have a nested JSON array like this : 
```json
{
	"obj1": {
		"obj2": [{
			"value": "value1"
		}, {
			"value": "value2"
		}]
	}
}
```

When using it : 
```html
<span>{{ 'obj1.obj2[0].value'  | translate }}</span>
```

I returns : 
`"obj1.obj2[0].value"`

**Expected/desired behavior**
It should return the translated value : 
`"value1"`

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:WccVZSBM0rUgq2sXSUbe

**What is the expected behavior?**
See above

**What is the motivation / use case for changing the behavior?**
To simplify the json files and avoid using objects like : 
```json
{
	"obj1": {
		"nestedObj1": {
			"value": "value"
		},
                "nestedObj2": {
			"value": "value"
		}
	}
}
```

**Please tell us about your environment:**

* **ngx-translate version:** 7.2.0

* **Angular version:** 4.3.6
 
* **Browser:** all

If you have any solution I'll be happy to read it ! Maybe I'm missing something or this is just not handled (yet)..
Thanks in advance 👍

**Comment by davidmartinezros** [comment]
Hi @Pomanks,

I have the same problem.

I could load some translate json files for translate a part of the web.

But the other part of the content comes from a json array file of projects.

I put all the array in the same file of the other transate texts and I try to execute:

<span>{{ 'data[0].titol'  | translate }}</span>

But it return the value 'data[0].titol'.

If I do this code:

<span (click)="showAlert()">{{ 'data[0].titol'  | translate }}</span>

...

public showAlert() {
      this.translate.get("data").subscribe(
        key => {
          window.alert(key);
        }
      );
}

It return an array of objects, so the data is loaded, but I don't know to access it.

Any solution?

Thanks in advanced,

David

**Comment by ambermishra1988** [comment]
{



  "news": {
    "label": "news"
  },
  "page": [{
    "home": [{
      "menu": {
        "topLevel": [{
            "newsLabel": "News",
            "newsUri": "https://qoinPro.com/news",
            "subLevel": [{
              "linkLabel": "News Sub level",
              "linkUri": "https://qoinPro.com/sub-news"
            }, {
              "linkLabel": "News Sub level",
              "linkUri": "https://qoinPro.com/sub-news"
            }]
          },
          {
            "coinsLabel": "COINS",
            "coinsUri": "https://qoinPro.com/news",
            "subLevel": [{
              "linkLabel": "News Sub level",
              "linkUri": "https://qoinPro.com/sub-news"
            }, {
              "linkLabel": "News Sub level",
              "linkUri": "https://qoinPro.com/sub-news"
            }]
          },
          {
            "atmsLabel": "ATMs",
            "atmsUri": "https://qoinPro.com/news",
            "subLevel": [{
              "linkLabel": "News Sub level",
              "linkUri": "https://qoinPro.com/sub-news"
            }, {
              "linkLabel": "News Sub level",
              "linkUri": "https://qoinPro.com/sub-news"
            }]
          },
          {
            "appLabel": "APP",
            "appUri": "https://qoinPro.com/news",
            "subLevel": [{
              "linkLabel": "News Sub level",
              "linkUri": "https://qoinPro.com/sub-news"
            }, {
              "linkLabel": "News Sub level",
              "linkUri": "https://qoinPro.com/sub-news"
            }]
          },
          {
            "aboutusLabel": "ABOUT US",
            "aboutusUri": "https://qoinPro.com/news",
            "subLevel": [{
              "linkLabel": "News Sub level",
              "linkUri": "https://qoinPro.com/sub-news"
            }, {
              "linkLabel": "News Sub level",
              "linkUri": "https://qoinPro.com/sub-news"
            }]
          }
        ]
      }
    }]
  }]
}


<a routerLink="/premier-bitcoin">{{ 'page[0].home[0].menu.topLevel[0].newsLabel' | translate | json }}</a>


Not able to access value in json array but i am able to access normal nested json.

**Comment by esejuli94** [comment]
The parser already works with nested JSON array so this issue can be closed.
For whom need to know how, here goes an example:

**JSON FILE:**
```
{
  "key": [
    { "item": "value1" },
    { "item": "value2" }
  ]
}
```

**CODE:**
```
{{ 'key.0.item' | translate }} // Returns value1
{{ 'key.1.item' | translate }} // Returns value2
```

Hope it helps :)
