### ISSUE TITLE
@ngx-translate/core/src/translate.service.d.ts (1, 46): Cannot find module '@angular/core'

### ISSUE THREAD

**Issue by AlexandreMazgaj** [ngx-translate/core#691]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
my application doesn't start because this error occurs : 
@ngx-translate/core/src/translate.loader.d.ts (1,28): Cannot find module 'rxjs/Observable'.
@ngx-translate/core/src/translate.store.d.ts (1,30): Cannot find module '@angular/core'.
@ngx-translate/core/src/translate.service.d.ts (1,46): Cannot find module '@angular/core'.
@ngx-translate/core/src/translate.service.d.ts (2,28): Cannot find module 'rxjs/Observable'.
@ngx-translate/core/src/translate.directive.d.ts (1,76): Cannot find module '@angular/core'.
@ngx-translate/core/src/translate.directive.d.ts (2,30): Cannot find module 'rxjs/Subscription'.
@ngx-translate/core/src/translate.pipe.d.ts (1,75): Cannot find module '@angular/core'.
@ngx-translate/core/index.d.ts (1,47): Cannot find module '@angular/core'.

Everything was working before I added ngx-translate
**Expected/desired behavior**
 The application should work

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:WccVZSBM0rUgq2sXSUbe
I just downloaded @ngx-translate, imported the module and service in my code, and ran my application

**What is the expected behavior?**
It should work

**What is the motivation / use case for changing the behavior?**
I really need my application to work

**Please tell us about your environment:**

* **ngx-translate version:** x.x.x
 latest I guess
* **Angular version:** 2.x.x
 angular/cli : 1.4.4
 angular/core: 4.4.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by CodeAndWeb** [comment]
Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.
I am closing the issue for now - you can re-open it if the issue still persists.

**Comment by nhoctanker** [comment]
+1

**Comment by bhador1936** [comment]
+1
```ERROR in ../node_modules/@ngx-translate/core/lib/translate.directive.d.ts(1,76): error TS2307: Cannot find module '@angular/core'.
../node_modules/@ngx-translate/core/lib/translate.directive.d.ts(2,30): error TS2307: Cannot find module 'rxjs'.
../node_modules/@ngx-translate/core/lib/translate.loader.d.ts(1,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@ngx-translate/core/lib/translate.pipe.d.ts(1,75): error TS2307: Cannot find module '@angular/core'.
../node_modules/@ngx-translate/core/lib/translate.service.d.ts(1,46): error TS2307: Cannot find module '@angular/core'.
../node_modules/@ngx-translate/core/lib/translate.service.d.ts(2,28): error TS2307: Cannot find module 'rxjs'.
../node_modules/@ngx-translate/core/lib/translate.store.d.ts(1,30): error TS2307: Cannot find module '@angular/core'.
../node_modules/@ngx-translate/core/public_api.d.ts(1,47): error TS2307: Cannot find module '@angular/core'.
```

**Comment by Nandu-Chopade** [comment]
ERROR in ../node_modules/@ngx-translate/core/lib/translate.directive.d.ts(1,76): error TS2307: Cannot find module '@angular/core'.
    ../node_modules/@ngx-translate/core/lib/translate.directive.d.ts(2,30): error TS2307: Cannot find module 'rxjs'.
    ../node_modules/@ngx-translate/core/lib/translate.loader.d.ts(1,28): error TS2307: Cannot find module 'rxjs'.
    ../node_modules/@ngx-translate/core/lib/translate.pipe.d.ts(1,61): error TS2307: Cannot find module '@angular/core'.
    ../node_modules/@ngx-translate/core/lib/translate.pipe.d.ts(3,30): error TS2307: Cannot find module 'rxjs'.
    ../node_modules/@ngx-translate/core/lib/translate.service.d.ts(1,46): error TS2307: Cannot find module '@angular/core'.





I got this error after installing ngx-translator

**Comment by smartm0use** [comment]
The same here. What's wrong?
