### ISSUE TITLE
Translating both in templates and in routes

### ISSUE THREAD

**Issue by Scipionh** [ngx-translate/core#703]
I am currently building a project with translation both in the template and in the routes. I was actually thinking about using yours but I am not quite sure it would work.

What I was basically trying to do was, in the constructor of my appComponent:
```
translate.use('en').subscribe(() => {
   router.config([...])
})
```
However, I am not quite sure how it is gonna work with all my lazy modules. I tried to do `router.push `and the `router.resetConfig` in the constructor of the main component but it doesn't seem to work (I am getting route fragment undefined).

Thus what I would like to know is that is what I am trying to achieve feasible ? or should I add another module just for the router (by instance https://github.com/fulls1z3/ngx-i18n-router/tree/master/packages/@ngx-i18n-router) I just feel like I would have to duplicate quite a lot of stuff.

My other option would be to look into https://angular.io/guide/i18n but I am not quite sure it would work.

What would you guys advise me to do ?

**Comment by CodeAndWeb** [comment]
Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.
I am closing the issue for now - you can re-open it if the issue still persists or you still need help.
