### ISSUE TITLE
Translate in component

### ISSUE THREAD

**Issue by TeodorKolev** [ngx-translate/core#705]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Demo did not working:
My objects are defined in separate file and it is working great. I need to translate object in component. How can I pass it to this method?
```
translate.setTranslation('en', {
    >>>>>MESSAGES.CHECKED: '{{value}}'
});
```
object is not defined in this component. When I convert it to string, it is not working. It returns undefined. How can I handle that?

**Comment by lucasbasquerotto** [comment]
@TeodorKolev I think that is more of a syntactic problem, because you can't define an object that way in typescript/javascript. But you can do the following:

```typescript
let myObj = {};
myObj[MESSAGES.CHECKED] = '{{value}}';
translate.setTranslation('en', myObj);
```
