### ISSUE TITLE
Cannot load json file on runtime (dynamically)

### ISSUE THREAD

**Issue by eugensunic** [ngx-translate/core#711]
I'm trying to load a .json file dynamically using http.get request with the appropriate path to the .json file on the server. Problem is, with ngx-translate I load my files at build time but I want to override my previous .json file which gives the languages at runtime. 

Consider that I do not load all languages at build time. I have to access the language from another location by inputing the **full** url as stated above. So I can't just use 

`this.translate.getTranslation('en');`
Or something else because my json file does not exist yet! Untill ofcourse I call my .json via **http.get**

Can I reuse the function which I'm using in my main module? Or do I have to use something else?

```
export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, '/some/some-path/', '.json');
}

```

But instead of http I would like to pass the full url path, like for example: 

> http:/www.someone.com/file.json

Also, can I somehow rewrite this function as stated in the docs to return a observable by using http.get and providing my full URL?

```
class CustomLoader implements TranslateLoader {
    getTranslation(lang: string): Observable<any> {
        return Observable.of({KEY: 'value'});
    }
}
```
What do you suggest?

**Comment by CodeAndWeb** [comment]
Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.
I am closing the issue for now - you can re-open it if the issue still persists or you still need help.

**Comment by FlawaCLV** [comment]
@eugensunic I've manage to make it work!

But the issue now is that my template doesn't update a second time... `{{ 'KEY' | translate }}` doesn't change.

```
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import { TranslateLoader } from 'ng2-translate';
import { Subject, Observable } from 'rxjs';
import 'rxjs/operators/map';

@Injectable()
export class TranslationsLoaderService implements TranslateLoader {
    private subject = new Subject();
    private translations = {};

    constructor(private http: Http) { }

    getTranslation(lang: string) {
        // To simplify for this issue I've removed all the code that gets the observable
        // This is where the translations are defined for the 2nd time, but not updating the template...
        Observable.subscribe((translations) => {
            this.subject.next(Object.assign(this.translations, translations));
        });

        this.http.get(`https://www.website.com/translations/${lang}.json`)
            .map((res) => res.json())
            .toPromise()
            .then((translations) => {
                this.translations = translations;
                this.subject.next(this.translations);
            });

        return this.subject.asObservable();
    }
}
```

@eugensunic & @CodeAndWeb any idea ?

**Comment by CodeAndWeb** [comment]
Can you please make example on https://stackblitz.com/github/ngx-translate/example ?

**Comment by FlawaCLV** [comment]
@CodeAndWeb I managed to make it work. Actually I was using the npm package `ng2-translate`, once updated to `@ngx-translate/core` package it worked! My mistake.

**Comment by kumarmanishc** [comment]
@FlawaCLV 

Did you get it working ?
It'm also having similar requirement.

**Comment by FlawaCLV** [comment]
@kumarmanishc I stop using Angular for a long time now... My front-end dev experience is really better now that I use Vue or React to be honest.
