### ISSUE TITLE
Angular v5

### ISSUE THREAD

**Issue by marshallcool** [ngx-translate/core#713]
Bug, feature request, or proposal:

Bug

What is the expected behavior?

Work out of the box.

What is the current behavior?

Does not.

What are the steps to reproduce?

https://pp.userapi.com/c824410/v824410512/107b8/X3qrDSX8M-0.jpg

What is the use-case or motivation for changing an existing behavior?

Using the latest Angular version with ngx-translate.

Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Just replace OpaqueToken with InjectionToken.

**Comment by ocombe** [comment]
What version are you using? This lib doesn't use "OpaqueToken" since v8

**Comment by itcozum** [comment]
I'm having the same issues. I'm currently using @ngx-translate/core@^7.2.0
how do I fix this problem?

**Comment by ocombe** [comment]
Change your dependency to @ngx-translate/core@^8.0.0

**Comment by FatemeFazli** [comment]
@ocombe  thanks, you saved my day. this worked for me.

**Comment by lalitnarde-nitorinfotech** [comment]
> Change your dependency to @ngx-translate/core@^8.0.0

@ocombe , my issue with OpaqueToken is not resolved yet.

**Comment by sumegha26** [comment]
> Change your dependency to @ngx-translate/core@^8.0.0

@ocombe , my issue with OpaqueToken not resolved yet
