### ISSUE TITLE
How to use TranslateParser if we use MissingTranslationHandler

### ISSUE THREAD

**Issue by Jayanzhou** [ngx-translate/core#714]
**Current behavior**

Hi man, I have met a problem that trouble me for a long time. 

How to use TranslateParser if we use MissingTranslationHandler? 

The problem is that we have used MissingTranslationHandler to handler the common i18n translate key,

but the TranslateParser doesnot work if we need to inject variable value into MissingTranslationHandler

json file, such as blow:
```javascript
"name": "Welcome {{name}}"
```
and the result is that the variable name can not been injected.

So I donot konw how to deal with it, need your help ,thanks.

**Please tell us about your environment:**
```javascript
        "@angular/core": "4.4.4",
        "@ngx-translate/core": "6.0.1",
        "@ngx-translate/http-loader": "0.0.3",
```
 
* **Browser:** Chrome (just use chrome to test)

**Comment by Jayanzhou** [comment]
Thank for all, this issue is fixed.

If you meet the same problem, pls contact me. Hope i can help u.

**Comment by erhimanshugarg** [comment]
How did you fix??

**Comment by Jayanzhou** [comment]
@erhimanshugarg 

At the handle function of your missinghandler class which implements MissingTranslationHandler, 

you should use translateService.parser.interpolate to parser the translate key. code like blow;

```javascript
export class TranslationFailoverHandler implements MissingTranslationHandler {

    private commonTranslation = {};

    constructor(private http: Http, @Inject(LOCALE_ID) locale: string) {
       // some code here
    }

    handle(params: MissingTranslationHandlerParams): string {
        const result = params.key.split(".").reduce((pre, cur) => !!pre ? pre[cur] : null, this.commonTranslation);
// variable result is the translate key
        return !!result ? params.translateService.parser.interpolate(result, params.interpolateParams) : params.key;
    }

}
```
