### ISSUE TITLE
Error: Missing locale data for the locale "fr"

### ISSUE THREAD

**Issue by LucasBrazi06** [ngx-translate/core#717]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I upgraded from Angular 4 to 5 and got this error in the browser when using the local FR.
But it works perfectly with EN!

**Expected/desired behavior**
That it works in french as before

**Reproduction of the problem**
Just switch the local of any angular 5 project to anything but EN

**Please tell us about your environment:**

* **ngx-translate version:** x.x.x
@ngx-translate/core 8.0.0

* **Angular version:** 2.x.x
 Angular CLI: 1.5.0
Node: 6.11.5
OS: linux x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular/platform-server: 4.3.6
: 0.0.32
: 0.0.20
: 0.0.35
: 1.1.0
: 1.8.0
: 0.1.0
typescript: 2.4.2
webpack: 3.8.1

* **Browser:** 
Chrome XX | Firefox XX

**Comment by LucasBrazi06** [comment]
Works perfect !
Thanks

**Comment by milenkovic** [comment]
@ocombe what if we are using localization just for date formatting? 
We need to import all locales? And is there any easier from loading one by one?
`import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';
import localeDE from '@angular/common/locales/de';
// other locales...
registerLocaleData(localeFr);
registerLocaleData(localeDE);`

**Comment by ocombe** [comment]
No there is no easier way for now. But you can make a function to register an array of locales. You'll still need to add the imports.

**Comment by broweratcognitecdotcom** [comment]
This seems like an unfortunate workaround.

**Comment by sefo** [comment]
This is a huge issue in our project. We need to support hundreds of languages. There is no clean solution to this problem?

**Comment by ocombe** [comment]
Follow up on this issue https://github.com/angular/angular/issues/20340 we are currently reviewing our options to come up with a solution.
If you could add your use case there, it'd help

**Comment by ocombe** [comment]
Also fyi you can lazy load the locale files, see this issue: https://github.com/angular/angular/issues/20487

**Comment by soriyath** [comment]
why is it complicated?
