### ISSUE TITLE
has no exported member 'OpaqueToken' 

### ISSUE THREAD

**Issue by arsewizz** [ngx-translate/core#718]
I update my ionic application for angular5 but since then I have this problem with the library

**Comment by ocombe** [comment]
Are you using the latest version of the library? (v8.0.0)

**Comment by arsewizz** [comment]
"@ngx-translate/core": "^6.0.1"

**Comment by ocombe** [comment]
Then update to 8.0.0 and it'll be fixed.

**Comment by Nitansh44** [comment]
since v4.0.0 because it does not support type information, use `InjectionToken<?>`
