### ISSUE TITLE
OpqueToken used in ngx-translate not found in Angular 5

### ISSUE THREAD

**Issue by joselee** [ngx-translate/core#721]
**I'm submitting a ...**
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I have an private NPM library package using Angular 5 and ngx-translate. When I try to use this package in a fresh Angular CLI project and run `ng serve`, I get the following error message:

`ERROR in node_modules/@ngx-translate/core/src/translate.service.d.ts(1,24): error TS2305: Module '"C:/Users/joselee/Desktop/ng5/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.`

**Expected/desired behavior**
the project should build and run successfully

**What is the motivation / use case for changing the behavior?**
It is blocking me from building and running my application

**Please tell us about your environment:**
Windows 10
Node 6.9.1
npm 3.10.8
angular/cli: 1.5.0
angular-devkit/build-optimizer: 0.0.33
angular-devkit/core: 0.0.20
angular-devkit/schematics: 0.0.36
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.0
schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1

* **ngx-translate version:** 7.2.2

* **Angular version:** 5.0.0

**package.json dependencies:**
```
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "MY-ANGULAR5-LIBRARY": "http://127.0.0.1:8080/MY-ANGULAR5-LIBRARY.tgz",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
```

**Comment by ocombe** [comment]
If you take 5 mn to search the GitHub issues or the list of releases you'll see that you need to install version 8.0.0
It's like the 3rd or 4th issue that someone opens for that...

**Comment by SamVerschueren** [comment]
@ocombe maybe we should add a question/note to the template asking if the issue is still present in the latest version. Not sure if it would help though...

**Comment by joselee** [comment]
Sorry, I had searched on Google for a while, then the issues list as well, but I had incorrect filters on.
Anyway, I'm not sure what I am doing wrong, but the problem is still occurring for me after updating to the latest versions:

```
"@ngx-translate/core": "^8.0.0",
"@ngx-translate/http-loader": "^2.0.0",
```

Note: I've cleared my npm cache, deleted node modules, deleted yarn.lock, and re-fetched all dependencies fresh.

**Comment by ocombe** [comment]
Can you create a minimal project that reproduces the error so that I can take a look at it?

**Comment by chrillewoodz** [comment]
Noticing this problem as well when I'm on 8.0.0.
