### ISSUE TITLE
TypeError: Cannot read property 'core' of undefined at Object.setPrototypeOf.__proto__

### ISSUE THREAD

**Issue by mcattle** [ngx-translate/core#729]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[X] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Exception is raised when the application is bootstrapped.  The application still works, but this exception is blocking automated build.

Code block where exception occurs:

    (function (global, factory) {
        typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@angular/core'), require('rxjs/observable/of'), require('rxjs/Observable'), require('rxjs/operators')) :
        typeof define === 'function' && define.amd ? define(['exports', '@angular/core', 'rxjs/observable/of', 'rxjs/Observable', 'rxjs/operators'], factory) :
        (factory((global['ngx-translate'] = global['ngx-translate'] || {}, global['ngx-translate'].core = {}),global.ng.core,global.Rx.Observable,global.Rx,global.Rx.Observable.prototype));
    }(this, (function (exports,core,of,Observable,operators) { 'use strict';

Exception (as reported by Chrome):

    Uncaught TypeError: Cannot read property 'core' of undefined
        at Object.setPrototypeOf.\_\_proto\_\_ (universalModuleDefinition:5)
        at universalModuleDefinition:6

Exception (as reported in VS Code):

    Exception has occurred: TypeError
    TypeError: Cannot read property 'core' of undefined
        at Object.setPrototypeOf.\_\_proto\_\_ (http://localhost:4200/scripts.bundle.js:5:114)
        at http://localhost:4200/scripts.bundle.js:6:2

The undefined object is `global.ng`.

**Expected/desired behavior**
No exception raised.

**Please tell us about your environment:**
Windows 10, VS Code, Angular, ngx-translate, ngrx-store

* **ngx-translate version:** 9.0.0

* **Angular version:** 5.0.3
 
* **Browser:** Chrome Version 62.0.3202.94 (Official Build) (64-bit) | Microsoft Edge 41.16299.15.0

**Comment by mcattle** [comment]
Prior to the upgrade to ngx-translate 9.0.0 (from 8.0.0), we were getting an exception that was identical to [this one](https://stackoverflow.com/questions/46319990/angular-4-ngx-translate-karma-jasmin-test-cases) at the application startup.

**Comment by ocombe** [comment]
Do you have any kind of reproduction? A repo, a plunkr, a stackblitz?

**Comment by mcattle** [comment]
I'm afraid the repo is not publicly accessible.  I'm loading the library in a fairly textbook manner:

`export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(http);
}

let imports = [
    BrowserModule,
    HttpClientModule,
    TranslateModule.forRoot({
        loader: {
            provide: TranslateLoader,
            useFactory: HttpLoaderFactory,
            deps: [HttpClient]
        }
    }),
    ...
]

@NgModule({
    declarations: [
        ...
    ],
    entryComponents: [ ... ],
    imports: imports,
    providers: [
        ...
    ],
    bootstrap: [AppComponent]
})`

My tsconfig is as follows:

`{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "preserveWhitespaces": false
  }
}`

**Comment by ocombe** [comment]
if you are using the cli, are you using a version >=1.5 ?

**Comment by mcattle** [comment]
We're using 1.5.4 of the CLI.

**Comment by mcattle** [comment]
The issue was the inclusion of the following scripts in "apps" section of `.angular-cli.json`:

    "scripts": [
        "../node_modules/@ngx-translate/core/bundles/core.umd.js",
        "../node_modules/@ngx-translate/http-loader/bundles/http-loader.umd.js"
    ],

Removing those scripts removed the error.
