### ISSUE TITLE
ng-packagr with npm pack gives a Error: No provider for TranslateService!

### ISSUE THREAD

**Issue by ovione** [ngx-translate/core#730]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I developed a library with the [ng-packagr](https://github.com/dherges/ng-packagr)
I use npm pack to package the library in a tarball and then I install it in another client app.
The idea is that in my library I use ngx-translate but its in the client app where I provide the translations and the configuration of ngx-translate.
The problem is that after doing and npm pack and installing the library I have a **Error: No provider for TranslateService!**

**Expected/desired behavior**
To be able to translate in the library by configuring and providing translations in the client of the library.

**Reproduction of the problem**
I have created a  [repo](https://github.com/ovione/packagerwithtranslate) to demostrate what I'm talking about.

**Comment by dkabul** [comment]
I tried many variations in the last couple of days. The only thing thats working is to declare TranslateModule.forRoot() in the library you are trying to decouple. 

I didnt get any runtime error but the strings didnt get translated even the translation files is found

footer.module.ts
`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FooterComponent } from './footer.component';
import {TranslateModule} from '@ngx-translate/core';
import {WindowRefService} from '../service/window-ref/window-ref.service';

@NgModule({
  imports: [
    CommonModule,
    TranslateModule.forRoot()
  ],
  declarations: [FooterComponent],
  providers: [WindowRefService],
  exports: [FooterComponent]
})
export class FooterModule { }
`

app.module.ts
`
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';


import {AppComponent} from './app.component';
import {HttpClient, HttpClientModule} from '@angular/common/http';
import {TranslateLoader, TranslateModule, TranslateService} from '@ngx-translate/core';
import {TranslateHttpLoader} from '@ngx-translate/http-loader';
import {CommonModule} from '@angular/common';
import {FooterModule} from './modules/footer/footer.module';

export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/', '.json');
}

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    CommonModule,
    BrowserModule,
    HttpClientModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader) ,
        deps: [HttpClient],
      },
    }),
    FooterModule
  ],
  providers: [TranslateService],
  bootstrap: [AppComponent],
})

export class AppModule {
}
`

footer.component.html
`import {ChangeDetectionStrategy, ChangeDetectorRef, Component, OnInit} from '@angular/core';
import {WindowRefService} from '../service/window-ref/window-ref.service';
import {TranslateService} from '@ngx-translate/core';

@Component({
  selector: 'bd-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
  providers: [
  ],
})
export class FooterComponent implements OnInit {
  public statistic = 0;
  private _window: Window;
  public footermenu1: boolean;
  public footermenu2: boolean;

  constructor(windowRef: WindowRefService,
              private translateService: TranslateService) {
  }

  _statistic(): boolean {
    return !!(this.statistic && this.statistic > 0);
  }

  ngOnInit() {
  }

  scrollToTop() {
    this._window.scrollTo(0, 0);
  }

  toggleFooterMenu1() {
    return this.footermenu1 = !this.footermenu1
  }

  toggleFooterMenu2() {
    return this.footermenu2 = !this.footermenu2
  }

  ngAfterViewInit() {
    this.translateService.setDefaultLang('de');
    this.translateService.use('de');

  }

}`

**Comment by ovione** [comment]
hello DKabul

thanks for trying :)

I tried with different combinations but without any results.

Like you also said if in the library I put TranslateModule.forRoot()
it doesn't throw errors but I can't get the transalations from inside the library.
The code is put as is and not translated.

Its a pitty

cheers
Ovidio

**Comment by dkabul** [comment]
Hi Ovidio,

Im still trying to put it on the right way now. Im on the same ship. Ill give you an update if I got it right

**Comment by dkabul** [comment]
Hi Ovidio,

I really should read the official angular.io docs first. It works now with forRoot() in your shared module so the service is only injected in the shared module. With forRoot() you basically dont need to provide it in your parent app.
So now it looks like this.

footer.module.ts
```
import {ModuleWithProviders, NgModule} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FooterComponent } from './footer.component';
import {TranslateLoader, TranslateModule, TranslateService} from '@ngx-translate/core';
import {WindowRefService} from '../service/window-ref/window-ref.service';
import {TranslateHttpLoader} from '@ngx-translate/http-loader';
import {HttpClient, HttpClientModule} from '@angular/common/http';
import {BrowserModule} from '@angular/platform-browser';

export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/', '.json');
}

@NgModule({
  imports: [
    CommonModule,
    BrowserModule,
    HttpClientModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader) ,
        deps: [HttpClient],
      },
    }),
  ],
  declarations: [FooterComponent],
  providers: [WindowRefService],
  exports: [FooterComponent]
})
export class FooterModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: FooterModule,
      providers: [TranslateService]
    };
  }
}
```
app.module.ts
```
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';


import {AppComponent} from './app.component';
import {FooterModule} from 'lib-playground';
import {HttpClient} from '@angular/common/http';
import {TranslateHttpLoader} from '@ngx-translate/http-loader';
import {TranslateModule} from '@ngx-translate/core';

export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/', 'json');
}

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    FooterModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {
}
```

For the angular.io docs, which maybe helps: 
https://angular.io/guide/ngmodule#why-userservice-isnt-shared
https://angular.io/guide/ngmodule-faq#q-why-bad and onwards

**Comment by ocombe** [comment]
And if you think the ngx-translate doc isn't clear on the usage of shared modules, a PR would be nice! :-)

**Comment by dkabul** [comment]
@ocombe would love to help but need your guidance to make one.

**Comment by ocombe** [comment]
go to https://github.com/ngx-translate/core/blob/master/README.md click the edit button at the top, edit the doc, and then it will offer you to create a fork & a pull request

**Comment by dkabul** [comment]
@ocombe okay thanks. gonna do it after I finish todays obligations :)

**Comment by Abhishek-Kanitkar** [comment]
Dear @dkabul ,

Seems like you have found a solution to the problem.
I am also sailing in the same boat. 

I have created a component lib using ng-packagr in which I have ngx-translate.

I am also trying to into this component lib into a angular 4 client app & trying to provide translations in client app.

But when I include a component from a feature module in component lib into the client app (which is using ngx-translate as pipe), I get 
======================================
ERROR Error: StaticInjectorError[TranslateService]: 
  StaticInjectorError[TranslateService]: 
    NullInjectorError: No provider for TranslateService!

======================================

In my feature module, I have done the forRoot method changes as prescribed by you above. But still get the same error.

What I must be missing ?

I really need your help in this.

Can you please post a link to repo where this working ? 

Thanks a lot in advance !

**Comment by dkabul** [comment]
Hi @Abhishek-Kanitkar 

in your export module class forRoot() method, you need to put TranslateService as provider. 

```
export class FooterModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: FooterModule,
      providers: [TranslateService]
    };
  }
```

I havent got the time to build a repo for it. But Ill remind myself to make one.

**Comment by ovione** [comment]
hi 

**this is not working for me as @Abhishek-Kanitkar  proposed ** 
 
I have tried forRoot (like in this example) and forChild and none is givin my the transaltions.
What is given is the key without a translation.
I also tried providers: **[TranslateService, TranslateStore]** and **providers: [TranslateService]** but the same.
**So its not working**

Here is my library module 
```
@NgModule({
    imports: [
      CommonModule,
      HttpClientModule,
      TranslateModule.forRoot({
        loader: { provide: TranslateLoader, useFactory: HttpLoaderFactory, deps: [ HttpClient ] },
        missingTranslationHandler: { provide: MissingTranslationHandler, useClass: TranslateMissingTranslationHandler },
      })
    ],
    declarations: [TranslateComponent],
    exports: [TranslateComponent]
})
export class TranslateLibModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: TranslateLibModule,
      providers: [TranslateService, TranslateStore]
    };
  }
}
```

Here is my client module

```
@NgModule({
  imports:      [
    CommonModule,
    HttpClientModule,
    BrowserAnimationsModule,
    RouterModule,
    TranslateModule.forRoot({
      loader: { provide: TranslateLoader, useFactory: HttpLoaderFactory, deps: [ HttpClient ] },
      missingTranslationHandler: { provide: MissingTranslationHandler, useClass: TranslateMissingTranslationHandler },
    }),
TranslateLibModule.forRoot(),
```

**Comment by dkabul** [comment]
Hi @ovione 

about the .json translation file: I still put it on the app side, since the app on runtime still refers /assets into my app. So I suppose the next step is to try the app side loader to point into the node_modules /assets directory. This thing still bothers me.
 
other thing is: refering to https://github.com/ngx-translate/http-loader, if you use HttpLoaderFactory, the translation file should be put in the /assets/i18n/en.json. Did you try to put it under /src/assets/i18n/en.json maybe?

in your client module you dont need to put TranslateModule.forRoot(...) anymore. it should only pull TranslateModule from your TranslateLibModule

**Comment by Abhishek-Kanitkar** [comment]
Dear @dkabul  & @ocombe ,

I am also now facing same problem as @ovione . I don't get any translations. Only the translation keys are shown. Can someone please please throw some light on this ?

Really interested in getting a solution for this. Please help !

**Comment by dkabul** [comment]
Hi @Abhishek-Kanitkar @ovione, 

I opened a playground https://github.com/dkabul/translate-packagr-playground. Maybe you would find it useful

**Comment by Abhishek-Kanitkar** [comment]
Thanks for the efforts @dkabul  !!! But did you actually run the new-playground project to see the translations from de.json ? When I followed all the steps I got some error related to Zone. 

Can you please check once again whether following is true in playground ?

1) Ngx-translate is used in lib-playground
2) The components from lib-playground, when rendered in new-playground, render with translations from new-playground.

Can you please please help in this ? Seems like we are almost close to solution but some small things are missing & blocking us.

**Comment by Abhishek-Kanitkar** [comment]
@ovione @dkabul @ocombe 

After many many trials, it seems that translations simply don't get applied to components from component library that are used in a new application. Only components from new application get translated but not the ones from component library. Very frustrating !!!

**Comment by dkabul** [comment]
@Abhishek-Kanitkar I did try to start it and it renders. It could be that I missed something. 

yes, ngx-translate is used in lib-playground, and the components `FooterComponent` is the one which have the translated string. 

Can you tell me which step youve done?

**Comment by Abhishek-Kanitkar** [comment]
@dkabul 

I will let you know exact steps I followed in sometime.
But more importantly, you don't seem to have used (any) translations in new-playground project that may override the ones in lib-playground. 

Can you please add that too ?

Thats where the issue is I think !

**Comment by dkabul** [comment]
@Abhishek-Kanitkar I think that the issue. 

I let the angular-cli pull the translation file from the library module. As soon as a new file in client module exist, the old is being overriden. 

I still dont know how to put together 2 json files over angular cli in assets. The quickest fix is to build a job which puts these two file together and deploy it in your client module under ´assets\i18n\*.json`. 

Do you maybe have an idea?

**Comment by Abhishek-Kanitkar** [comment]
Dear @dkabul ,

Thanks for your continued support  :+1: 

Ok I have got the new-playground running now !  :)  
In order to have translations in new playground, I will follow same steps, as mentioned on Ngx-translate git page right ?

Any special steps/ changes I need to do to ensure that I can also translate footer component from new playground ?

**Comment by Abhishek-Kanitkar** [comment]
@dkabul 

Can you please add translations to new playground that override the footer component translations ?

Actually I am having issue with that. de.json file gets loaded twice & both times it's from lib-playground only.  Sad thing ! Please help !

**Comment by dkabul** [comment]
Hi @Abhishek-Kanitkar about those issue please read [comment](https://github.com/ngx-translate/core/issues/730#issuecomment-347814489) and refer to this [issue](https://github.com/ngx-translate/core/issues/735)

**Comment by Abhishek-Kanitkar** [comment]
@dkabul  But the problem I am facing is following
If I have same translation key for same language in new-playground (as in lib-playground) still the .json file from new-playground is not loaded & doesn't override translation at all.

Can you please throw some light on to it ?

In your playground git repo, can you please add a translations file & load it to override footer component translation ? That will really help me. I am not looking for comment mentioned by you above.

**Comment by dkabul** [comment]
@Abhishek-Kanitkar please look into your .angular-cli.json and check if your new-playground assets file is loaded. As soon as putting the right json under 'assets/i18n/de.json and defining assets in your angular-cli, your translation file would be overriden

**Comment by Abhishek-Kanitkar** [comment]
Dear @dkabul , @ovione , @ocombe ,

Please please help me !

I really like Ngx-translate. But my below requirement is not getting fulfilled properly.

Following is the problem I am facing

1) I have created a component library using ng-packagr
2) I am using components from this library into another angular cli application by doing 'npm install' to include my library
3) My requirement is that components in the library should be internationalization supported.
4) If I include any translations in my angular cli app, then those should get applied to the components from library.
5) I really need exact help to achieve this. Please provide exact code to do this.

Playground created by @dkabul  is not adding translations in new-playground app that can get applied to footer component. Feeling very low because it's not working !

Please please please help me  !!!!!

**Comment by ovione** [comment]
hi  @dkabul , @ovione , @ocombe ,

I see have the same problem as @Abhishek-Kanitkar.
When I see the [playgound](https://github.com/dkabul/translate-packagr-playground) of @dkabul I notice that this is not solving the problem.
Why ?
because the assets files are in the library and not in the client application.
Why I need that ?

**because its up to the client to provide the assets files. (not the library).**
**The library should not contain any assets.**
If we can solve this problem then the library could be used by multiple clients and each client can decide which languages its provides translations for.

For example one client could use the library and translate it to english and french, another client could translate it to german and italian.

That means that the assets files should be in the client and not in the library for this to make sense.
and this is not the case until now.

:)

**Comment by Abhishek-Kanitkar** [comment]
Dear @ocombe , @dkabul ,

Can you please help @ovione & me in above mentioned scenario ? 
I will be grateful if you can provide concrete solution to what @ovione & I have mentioned above.

Please help us !!!!!!!!

**Comment by dkabul** [comment]
Hi @Abhishek-Kanitkar @ovione,

as I said, if you want to put it on the client side (new-playground), the only suggestion I can give right now is to create your translation json file under src -> assets -> i18n on the client side. 

The next step is to modify the .angular-cli.json in the client side and put this "assets" under apps.assets so it will look like this:
 ```
"apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
       "assets",
        { "glob": "**/*", "input": "../node_modules/lib-playground/src/assets/i18n", "output": "./assets/i18n/" },
        "favicon.ico"
      ],
]
```
Then you need to restart your app.

The issue with 2 translation file: e.g. en.json in client and library and merging this file together, you need to[ write a small script](https://github.com/ngx-translate/core/issues/735) file. Otherwise the en.json from the library is overriden with the client en.json file.

**Comment by Abhishek-Kanitkar** [comment]
Hi @dkabul ,

I just now tried to do 'exactly' what you have mentioned above in comment using playground repo.

But the en.json file is NOT getting overriden with client en.json file.

Can you please make it working in playground repo ?

Can you please add de.json to new-playground in repo & check whether it overrites or not ?

I think it's not working ! Again feeling sad because of this.

Can you please help us ?

**Comment by Abhishek-Kanitkar** [comment]
Opps my bad this time !!!  I forgot to add "assets" into assets array of .angular-cli.json.

Thanks a lot @dkabul !

It's missing in playground repo too !

**Comment by Abhishek-Kanitkar** [comment]
Dear @dkabul ,

One more questions !

Lets say I have multiple modules such as FooterModule in my lib-playground.

In that case how to avoid repeat declaration of forRoot() method for each such module ?

Do you think Sharedmodule will help here ?

**Comment by Abhishek-Kanitkar** [comment]
Hey @dkabul

Can you please help us with this last thing asked above ?

Please Please! 

@ovione, @ocombe

**Comment by Abhishek-Kanitkar** [comment]
@dkabul  Please help !

**Comment by Arikael** [comment]
https://github.com/dherges/ng-packagr/issues/259 solved the issue for me

**Comment by ghiscoding** [comment]
@Arikael thanks for sharing, I was also pulling my hair on this one and your solution works :)

**Comment by ovione** [comment]
yes I tested it and this sis the correct solution :)

**Comment by DenisVuyka** [comment]
None of the suggestions work for SharedModule approach (using 8.0.0 and 9.0.2).  Using 'forChild' in the shared lib and 'forRoot' in the main app - same exception for TranslateService. Adding TranslateService to the lib providers causes exception for TranslateStore (not exported at all so far)

**Comment by SaturnTeam** [comment]
For Angular v5, please use the 2.0.0 release candidates of ng-packagr
