### ISSUE TITLE
Broken rxjs typings after v8 -> v9 upgrade

### ISSUE THREAD

**Issue by sinedied** [ngx-translate/core#734]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
An error occurs during build after @ngx-translate/core v8 -> v9 upgrade (no error with version @8):
```
ERROR in src/app/core/authentication/authentication.service.ts(46,23): error TS2339: Property 'of' does not exist on type 'typeof Observable'.
src/app/core/authentication/authentication.service.ts(56,23): error TS2339: Property 'of' does not exist on type 'typeof Observable'.
src/app/home/quote.service.ts(25,37): error TS2339: Property 'of' does not exist on type 'typeof Observable'.
```
`Observable.of` is still referenced in the `rxjs@5.5.2` docs, and the project was properly migrated to use lettable operators.

The same project, with the same rxjs version and the same code works using `@ngx-translate/core@8`. The error does not even occurs in file where ngx-translate is used, so it must be due to some import side-effect.

**Expected/desired behavior**
The project works as intended after version @9 upgrade.

**Reproduction of the problem**
1. Clone this project: https://github.com/ngx-rocket/starter-kit
2. `npm install`
3. Upgrade @ngx-translate/core `npm i @ngx-translate/core@latest`
4. `npm run build`

Error occurs (no error with version @8)
```
ERROR in src/app/core/authentication/authentication.service.ts(46,23): error TS2339: Property 'of' does not exist on type 'typeof Observable'.
src/app/core/authentication/authentication.service.ts(56,23): error TS2339: Property 'of' does not exist on type 'typeof Observable'.
src/app/home/quote.service.ts(25,37): error TS2339: Property 'of' does not exist on type 'typeof Observable'.
```

**What is the expected behavior?**
The project works as intended after version @9 upgrade.

**Please tell us about your environment:**
* node@8.9.1
* npm@5.5.1
* rxjs@5.5.2
* **ngx-translate version:** 9.0.1
* **Angular version:** 5.0.3
* **Browser:** [all]

**Comment by sinedied** [comment]
After investigation, it seems that I needed to update my `of` usage by adding `import { of } from 'rxjs/observable/of';`.

`@ngx-translate` actually revealed the issue that was hidden by the fact that the v8 patched the operators, making my code work 😝 

Sorry for the noise.

**Comment by EthanYueZhao** [comment]
I use this import 'rxjs/add/observable/of';
