### ISSUE TITLE
Working with large and multiple language files

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ngx-translate/core#735]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[X] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

I would like to ask if there is an efficient way to work with multiple languages (JSON) files for ngx-translate. 

As our projects get larger, we have difficulties keeping all the languages up-to-date and on the same level. For example, it would be helpful to have all translations side-by-side so you wouldn't need to search the same key in all files when editing.

How do you handle this issue? Can you recommend a tool for that, or would it be helpful to write one?

**Comment by tommueller** [comment]
I use a little script build around https://www.npmjs.com/package/merge-json
It is very simple, but I can post it tomorrow if you need some inspiration. The pitfall is, that the languages are outsourced to a separate repository, which makes maintaining easy, but requires some additional steps in the workflow to get changes into the actual app ...

**Comment by supertorpe** [comment]
There is a tool called [babeledit](https://www.codeandweb.com/babeledit/download) that serves exactly what you need

**Comment by andreas-aeschlimann** [comment]
@supertorpe you seriously made my day! We considered developing exactly something like that.

**Comment by ocombe** [comment]
There was a link to this editor on the main website, but not on the docs here, I added it

**Comment by andreas-aeschlimann** [comment]
@ocombe thanks, I didn't see that back then. Helps a lot!

**Comment by fkirc** [comment]
I wrote the new tool `attranslate` as an alternative to `babeledit`: https://github.com/fkirc/attranslate
In contrast to `babeledit`, `attranslate` operates directly on translation-files in a surgical way.
