### ISSUE TITLE
Access translate from .ts file (Angular2)

### ISSUE THREAD

**Issue by amrut123456789** [ngx-translate/core#738]
how to access translate pipe from .ts file in angular2
Please provide with import statements required for this.

**Comment by alexdragneel** [comment]
I have the same question because i want to display in alertCtrl a message that depends on the language.
I can get language in the .ts and display the right message but i search another better way.

**Comment by jmruiz6** [comment]
this.translateService.get('DASHBOARD_TITLE')
      .subscribe(value => {
          this.dashboardTitle = value;
        }
      );

**Comment by tatsujb** [comment]
@sundaramkumar  the above does not work for me : 

(picture of the app displaying the notification with "notification.updateGroups.GRP_ADDORUPDATE_000.body" instead of the retrieved value)




@jmruiz6 your solution is async I need a sync solution. 

@ngehlert, @ocombe  how do I solve this ?

here's my code : 
```
  LoginErrorMessage(){
    const myConf = {...conf};
    myConf.timeout = 3500;
    const body = this.translate.instant('notification.login.defaultError.body');
    const title = this.translate.instant('notification.login.defaultError.title');
    this.snotifyService.error(body, title, myConf);
  }
```

fr.json :

json```
{
"notifications" : {
    "login":{
      "defaultError":{
        "title":"Connexion Échoué",
        "body":"La connexion a échoué pour une raison inconnue.",
        "config":{
          "timeout":null
        }
      },
   }
}
```

I'm using the snotify library for notifications, any ideas?

**Comment by ngehlert** [comment]
@tatsujb what is your error, i don't quite get it. if you don't receive a translation well probably your file is not loaded

> instant(key: string|Array<string>, interpolateParams?: Object): string|Object: Gets the instant translated value of a key (or an array of keys). /!\ This method is synchronous and the default file loader is asynchronous. You are responsible for knowing when your translations have been loaded and it is safe to use this method. If you are not sure then you should use the get method instead.

**Comment by ncrehman** [comment]
> const title = this.translate.instant('notification.login.defaultError.title');

Thank you

**Comment by Melissa-Lima** [comment]
@tatsujb I know it's late but in your json file it's wrote "notifications", not "notification".
You forgot the 's' haha.
