### ISSUE TITLE
Version mismatch :  found version 4, expected 3

### ISSUE THREAD

**Issue by ikramcheb** [ngx-translate/core#739]
**I'm submitting a ...**  (check one with "x")
```
[+ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
With >> ng serve command, the translation works perfectly but 
When I run
 >> ng build 
or
>> ng build --aot
I have this error 
ERROR in Metadata version mismatch for module  ../node_modules/@ngx-translate/core/core.d.ts, found version 4, expected 3

**Expected/desired behavior**

* **ngx-translate version:** 9.0.1

* **Angular version:** 4.4.6
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ocombe** [comment]
ngx translate v9+ requires Angular 5, as it is explained in the changelog and in the peers dependencies.

**Comment by alexndreazevedo** [comment]
The documentation says: `NB: if you're still on Angular <4.3, please use Http from @angular/http with http-loader@0.1.0.`.

What is the reason for this sentence if the library no longer supports Angular 4? It's really confusing.

Also, there is no backward compatibility with version `4.4`, which remains the stable one. The `@ngx-translate v8.0.0` was supposed to be compatible with version 4, but the version `8.0.0` still breaking the build. There is no solution if we should stick to version 4 for stability reasons?

The Angular dev team plan to release the next stable version only in March/April 2018: [RELEASE SCHEDULE - Tentative schedule after september 2017](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md#tentative-schedule-after-september-2017). Until that moment, the LTS version still the version 4, which I'm using for stability reasons.

Hence, I kindly ask you @ocombe, why the support to version 4 was dropped in favor an officially unstable version of Angular?

_NB: Please, don't take me wrong. The library all you have done is really cool. Keep in mind I'm not criticizing what you have done. I'm only arguing about the stability of supported versions._

**Comment by ocombe** [comment]
The last version compatible with Angular v4 should be v7.2.2.

The reason why I dropped support for version 4 is simple: this project is not paid and I don't want to bother with supporting multiple versions of the library. I'll keep it working with the current version of Angular.

If your company depends on the library and wants to keep it working with v4, you can either do a PR to add a new branch that supports the old versions, or fork the project and release an alternative version, or hire me to do it.

**Comment by alexndreazevedo** [comment]
Thanks for your quick and friendly answer, @ocombe.

I've suspected that version `7.2.2` would be a proper one. It's completely understandable if you lack contributors. Let's do it together!

Although the company doesn't depend on your library, I would be glad to have you joining the company. Let me know and I refer you to the recruitment process that includes a full relocation package and visa sponsorship.

Cheers,
