### ISSUE TITLE
Actually, what are all the Languages that have been supported by the ng2-translate.?

### ISSUE THREAD

**Issue by VigneshSAN** [ngx-translate/core#741]
I need to translate English to All Indian Languages. So, I tried Tamil and Hindi Language but it falls on fail. So please tell me the languages that have been supported by this plugin.?

**Comment by sam-lex** [comment]
Supports all languages, but you need to provide your own translations in `lang.json`

for example:  
`en.json`

```json
{
  "hello": "Hello!"
}
```

and spanish: `es.json`:
```json
{
  "hello": "Hola!"
}
```
