### ISSUE TITLE
ngx-translate core 9.0.1 is 100kb bigger than 8.0.0

### ISSUE THREAD

**Issue by peterpeterparker** [ngx-translate/core#742]
**I'm submitting a ...**  (check one with "x")
[X ] feature request

**Current behavior**

I had a comparison of my bundle size with `source-map-explorer` using version `9.0.1` and `8.0.0` and I noticed that the library gained 100kb. 

**Expected/desired behavior**

First, could someone confirm that it gained weight because it's the inverse of what was expecting, according the release notes of v9.0.0 (https://github.com/ngx-translate/core/releases/tag/v9.0.0).

The, if yes, since bigger the app is, slower the boot is (specially in case of a mobile app), it would be good to shrink the bundle size respectively to spare these extra 100kb. 

**Reproduction of the problem**

Compare v8.0.0 to v9.0.1

* **Angular and Ionic**

"angular/core": "^5.0.0",
"ionic-angular": "^3.9.2"
 
* **Screenshots**

    ionic serve
    cd www/build
    source-map-explorer vendor.js vendor.js.map

v8.0.0

<img width="1235" alt="capture d ecran 2017-12-01 a 07 10 29" src="https://user-images.githubusercontent.com/16886711/33470070-c4329d5e-d666-11e7-9a8e-a6fc5727cf0c.png">

v9.0.1

<img width="1240" alt="capture d ecran 2017-12-01 a 07 11 03" src="https://user-images.githubusercontent.com/16886711/33470081-d7c8997c-d666-11e7-8e48-80f5d9bf4064.png">

**Comment by peterpeterparker** [comment]
I'm wrong. This size is the size before treeshaking and all other improvements using a `--prod` build would bring. I compared the size of the `vendor.js` v8.0.0 vs v9.0.1, it look like it only gained 18kb

      ionic cordova build ios --prod
      cd www/build
      ls -ltr vendor.js

v.8.0.0

     895408  1 déc 07:25 vendor.js

v9.0.1

      914290  1 déc 07:32 vendor.js

I could live with that ;)

**Comment by ocombe** [comment]
Since there was no code added between both versions (only packaging changes), it should be the same size or less (which was the point of the new build).
I'm not sure how ionic builds the code, but with the cli there is a significant size reduction, and the umd bundles are a lot smaller too

**Comment by peterpeterparker** [comment]
@ocombe thx for the feedback, understood. 

like I said, once I had run the build with all option, the size difference wasn't that significant anymore, therefore I closed the issue. Sorry for having open it in the first place and thx again for the great library!

**Comment by ocombe** [comment]
No problem, if there was a real issue I would have been glad to know about it!
