### ISSUE TITLE
Multiple translations require nested calls

### ISSUE THREAD

**Issue by Mihai238** [ngx-translate/core#743]
**I'm submitting a ...**
```
[ ] bug report
[X] support request
[ ] feature request
```

**Current behavior**
```
this.translate.get('DATA.X').subscribe(t1 => {
    this.translate.get('DATA.Y').subscribe(t2 => {
      // here I can use both translations: t1 and t2
    })
});
```

**Expected/desired behavior**
Several nested blocks often lead to unreadable code.
Is there any other way to perform multiple translations without using nested `subscribe` calls?

**Please tell us about your environment:**
* **ngx-translate version:** 8.0.0
* **Angular version:** 4.4.6

**Comment by ocombe** [comment]
You can pass an array of strings instead of a single key
