### ISSUE TITLE
The pipe 'translate' could not be found 

### ISSUE THREAD

**Issue by ltoshev** [ngx-translate/core#745]
The pipe 'translate' could not be found ("offerClicked(true)">
                                <span>
                                    {{[ERROR ->] 'HOME.SALESPITCHBAR.BUTTON_BUY_TEXT' | translate }}
                                </span>
      "): ng:///SharedModule/TopbarComponent.html@32:38

```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

For some reason the translate is not working in my new component. I have followed the guide on the start page in git hub and the module was working on my main app.component. Why does it not work on the this new component I have?

* **Angular version:** 5.0

**Comment by ssuperczynski** [comment]
If anyone has this error:
You need to add `TranslateModule` to each module where you use translation
