### ISSUE TITLE
Could you follow the Angular naming convention?

### ISSUE THREAD

**Issue by Slevender** [ngx-translate/core#748]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
The internationalization (i18n) library for Angular 2+.

**Expected/desired behavior**
The internationalization (i18n) library for Angular.

**Reproduction of the problem**
The naming is explained in this blog post: http://angularjs.blogspot.com.ee/2016/12/ok-let-me-explain-its-going-to-be.html

**Comment by ocombe** [comment]
I changed it in the readme not long ago, but forgot the github header. Thanks for the reminder.

**Comment by Slevender** [comment]
And the website? http://www.ngx-translate.com/

**Comment by ocombe** [comment]
done

**Comment by Slevender** [comment]
And the npm site :D ? https://www.npmjs.com/package/@ngx-translate/core

**Comment by ocombe** [comment]
I don't have any control over this. I guess that It'll be updated at the next release.
