### ISSUE TITLE
How to catch malformed JSON lang file when loading.

### ISSUE THREAD

**Issue by Harlok** [ngx-translate/core#751]
If I write a malformed en.json file by adding a comma at the wrong place, when I run my app, I get a very generic error log: [09:54:31]  console.error: ERROR [object Object] from somewhere within the library.

I have tried the following:

```
this.translate.use('en')
            .subscribe((response)=>{
              console.log("response: " + response);
            },(error)=>{
              console.log("error: " + error);
            })
```
The Error section never triggers when attempting to load the malformed JSON.  Where can I put a catcher to detect that mistake?

I'm using:
    "@ngx-translate/core": "^9.0.1",
    "@ngx-translate/http-loader": "^2.0.0",

**Comment by stevengunneweg** [comment]
I would also expect a descriptive error in my console when the JSON is malformed. Currently we get no indication of what goes wrong. A missing comma in our translation file cost us time to debug than we'd like to admit.

**Comment by CodeAndWeb** [comment]
The best place to catch an invalid json file is creating your own `TranslateLoader` and handle the error there. 

The default implementation is quite simple: https://github.com/ngx-translate/http-loader/blob/master/src/http-loader.ts

    public getTranslation(lang: string): any {
        return this.http.get(`${this.prefix}${lang}${this.suffix}`);
    }

... or make sure to only work with valid json files... [BE](https://www.codeandweb.com/babeledit) might help you. ;)
