### ISSUE TITLE
json files not loaded in dev environment, only prod.

### ISSUE THREAD

**Issue by zladuric** [ngx-translate/core#755]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

An app built by `ng build` (with dev environment) will not load i18n translations from json files.

More specific, when I ng serve my app, my translations are not loaded at all, and no activities in network tab. When I ng serve -e prod, translations are loaded.

The differences between serving in prod or dev environment:

jsons are not loaded. In prod I see requests to i18n/de.json request. In dev, no request.
Translation is, obviously, not done in dev.
There are no errors in browser console whatsoever.

What am I missing?

Angular 5.1, ng-cli 1.6, ngx-translate 9.0.1.

**Expected/desired behavior**

I expected there'd be no difference between dev and prod module. And I need dev for some other, env-specific purposes.

**Reproduction of the problem**

> If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:XXwyUYS6ZL7qVD9I2l0g

This plunkr doesn't work for me. Here's the rough outline of what I'm doing.

```
// app.component
// ...
constructor (private translateService: TranslateService) {
    translate.setDefaultLang('en-us');
    translate.use('en-us');
}

// app.module
// ...
function createTranslateLoader(http: HttpClient) {
    return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}
@NgModule({
    // ...
    imports: [
        // ...
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: (createTranslateLoader),
                deps: [HttpClient]
            }
        }),
  // ...
```

**What is the expected behavior?**

The app should load json files regardless of environment.

**What is the motivation / use case for changing the behavior?**

The behaviour seems broken.

**Please tell us about your environment:**

* **ngx-translate version:** 9.0.1

* **Angular version:** 5.1.0
 
* **Browser:** Chrome 63.0.3239.84 (latest), IE 11 latest, Edge latest

Windows.

**Comment by ac3ju** [comment]
Same issue, but it works in dev and not in prod for me ...

**Comment by kgish** [comment]
Same issue, dev ok and prod nok.

**Comment by CodeAndWeb** [comment]
Sorry - can't reproduce the issue. The code in this demo app is almost identical.
Can you try the demo project form here: https://github.com/CodeAndWeb/ngx-translate-demo ?

**Comment by zladuric** [comment]
Oh, no problem, I forgot about this issue. I don't remember how I fixed it, but I don't have the problem any more. Thanks.
