### ISSUE TITLE
How to get some "Translations Ready" event? And why you made 'loadingTranslation' and 'pending' properties privat?!?

### ISSUE THREAD

**Issue by antonpegov** [ngx-translate/core#757]
The problem is my service calls TranslationService to early - before translation file is loaded with HTTP request. So I need some observable to tell me when translation is loaded and ready. But you hide all properties that I can use...

**Comment by antonpegov** [comment]
Sorry, now I find it out how to manage it - 
` this.$translate.getTranslation(this.$translate.currentLang).subscribe(translation => {
 == do what you whant here ==
}`

**Comment by kevinrigot** [comment]
Hi, 
I have the same issue. When I use your solution I see 2 http requests which is not desirable. Have you found another solution since then?

Thanks,
Kevin

**Comment by slzr** [comment]
the solution of @antonpegov works perfectly, but yes, two http requests are made, and the solution of @kevinrigot gives error `Cannot read property 'subscribe' of undefined` 😞
