### ISSUE TITLE
Does not work examples

### ISSUE THREAD

**Issue by splincode** [ngx-translate/core#759]
Does not work:
https://plnkr.co/edit/XXwyUYS6ZL7qVD9I2l0g?p=preview

Please, usage https://stackblitz.com/

**Comment by Form1ca** [comment]
http://prntscr.com/hu7rmm

**Comment by alexndreazevedo** [comment]
The declaration of rxjs operators isn't working on the current plunkr example.

You may comment the code on `config.js:39` or use https://plnkr.co/edit/L2X3To.

cc: @ocombe

**Comment by ocombe** [comment]
@splincode I'd like to use stackblitz, but they don't support loading locale files yet (files that come from the project), which means that I can't make a good demo that use the http loader...

That being said I've updated the plunkr this morning, and now it works.
