### ISSUE TITLE
Does not work custom loader

### ISSUE THREAD

**Issue by splincode** [ngx-translate/core#760]
https://stackblitz.com/edit/angular-2owzjd?file=app/app.component.html

I return the data, but in the template they are displayed not processed

![image](https://user-images.githubusercontent.com/12021443/34353370-bfb57a40-ea38-11e7-8a4f-455982cd87e6.png)

**Comment by alexndreazevedo** [comment]
You are missing the `import 'rxjs/add/observable/of'` at `app.module.ts` and must define a language on `app.component.ts` by using `translate.use(LANG)` or `translate.setDefaultLang(LANG)`.

**Comment by splincode** [comment]
I do not understand

**Comment by alexndreazevedo** [comment]
Please, read the [README.md](https://github.com/ngx-translate/core/blob/master/README.md#usage) again if you didn't catch it.

The translations must have a corresponding language defined by one of those methods:
```typescript
this.translateService.setDefaultLang('<your_lang_here>')
this.translateService.use('<your_lang_here>')
```

In addition, your code is missing the method `Observable.of`.

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/34738638-b58d0bac-f58a-11e7-9e86-9e295fc647d8.png)

**Comment by splincode** [comment]
But how does he understand that you need to choose English?

![image](https://user-images.githubusercontent.com/12021443/34738737-0e0ae9ca-f58b-11e7-80fe-07feddf0b130.png)

![image](https://user-images.githubusercontent.com/12021443/34738746-16b5c2d4-f58b-11e7-95cb-7ad5693bc39e.png)

**Comment by alexndreazevedo** [comment]
It only retrieve the language from loader if you run `TranslationService.getTranslation()`. It doesn't happen automatically. You must use `TranslationService.use()` or `TranslationService.setDefaultLang()` it retrieves the language from loaders. 

Check [lib/src/translate.service.ts:263](https://github.com/ngx-translate/core/blob/master/lib/src/translate.service.ts#L263). If it still unclear, sorry but I can't help you more.

**Comment by splincode** [comment]
I still do not understand how it extracts the language from the bootloader, if I can specify any language

**Comment by alexndreazevedo** [comment]
You can specify any language: `TranslationService.setDefaultLang('yellow submarine')`

The responsible for matching the language with translations is your loader:

[lib/src/translate.loader.ts:14](https://github.com/ngx-translate/core/blob/master/lib/src/translate.loader.ts#L14)
```typescript
export class WhiteUnicornLoader extends TranslateLoader {
  public getTranslation(lang: string): Observable<any> {
    switch(lang) {
      case 'white unicorn':
        return Observable.of({ 'ROCK_BAND': 'White Unicorn' });
      case 'yellow submarine':
        return Observable.of({ 'ROCK_BAND': 'Beatles' });
  }
}
```

**Comment by splincode** [comment]
Add this to the documentation (readme.md)
