### ISSUE TITLE
 Field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by brevleq** [ngx-translate/core#761]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I'm compiling my Ionic Application to production and I'm receiving the following error:

@ ./src/app/main.ts,./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@ngx-translate/core/src/translate.store' in '/home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/src/app'
resolve '@ngx-translate/core/src/translate.store' in '/home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/src/app'
Parsed request is a module
using description file: /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/package.json (relative path: ./src/app)
Field 'browser' doesn't contain a valid alias configuration
after using description file: /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/package.json (relative path: ./src/app)
resolve as module
  looking for modules in /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/node_modules
    using description file: /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/package.json (relative path: ./node_modules)
      Field 'browser' doesn't contain a valid alias configuration
    after using description file: /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/package.json (relative path: ./node_modules)
      using description file: /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/node_modules/@ngx-translate/core/package.json (relative path: ./src/translate.store)
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/node_modules/@ngx-translate/core/src/translate.store doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
          /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/node_modules/@ngx-translate/core/src/translate.store.ts doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/node_modules/@ngx-translate/core/src/translate.store.js doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/node_modules/@ngx-translate/core/src/translate.store.json doesn't exist
        as directory
          /home/hudson/projetos/brazil-cartoon/brazil-cartoon-app/node_modules/@ngx-translate/core/src/translate.store doesn't exist

**Expected/desired behavior**

Compile without error

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:XXwyUYS6ZL7qVD9I2l0g

**What is the expected behavior?**

I expected the compilation works successfully

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-translate version:** 9.0.2

* **Angular version:** 5.0.1
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by xrobert35** [comment]
Temporary solution : 
I had the same problem with angular 5. It worked for me with the core in version 8.0.0

**Comment by ocombe** [comment]
Are you trying to import from `@ngx-translate/core/src/translate.store` instead of `@ngx-translate/core` ?

**Comment by brevleq** [comment]
As workaround I decided add the git repository as dependency instead of default npm package:
https://stackoverflow.com/questions/48059417/ionic-in-production-field-browser-doesnt-contain-a-valid-alias-configuratio

**Comment by ocombe** [comment]
That's not the good solution. The solution is to import from `@ngx-translate/core` instead, everything is exported from there. The other files are just typescript definition files, that's why it doesn't work.

**Comment by lucasvst** [comment]
Maybe is a bug in code generator. I found this on 'core/core.d.ts':

```
/**
 * Generated bundle index. Do not edit.
 */
export * from './index';
export { TranslateStore as ɵa } from './src/translate.store';
```

Workaround:

```
import { ɵa as TranslateStore } from '@ngx-translate/core';
```

I dont know where this code is generated, sorry :/

**Comment by ocombe** [comment]
Hmm I just checked and the store is not exported in index.ts, that's why. But you shouldn't need to use it, why do you want to import it?

**Comment by lucasvst** [comment]
I need to provide it to my SharedModule. If not, I receive:

```
Unhandled Promise rejection: StaticInjectorError(AppModule)[TranslateService -> TranslateStore]: 
  StaticInjectorError(Platform: core)[TranslateService -> TranslateStore]: 
    NullInjectorError: No provider for TranslateStore! ; Zone: <root> ; Task: Promise.then ; Value: Error: StaticInjectorError(AppModule)[TranslateService -> TranslateStore]: 
  StaticInjectorError(Platform: core)[TranslateService -> TranslateStore]: 
    NullInjectorError: No provider for TranslateStore!
```

**Comment by guilhermejcgois** [comment]
Some updates about that? We're having trouble too

**Comment by danday74** [comment]
unit tests failing because I cant import this.

import { TranslateStore } from '@ngx-translate/core'

gives ... no exported member TranslateStore

**Comment by zglou** [comment]
We had this "Can't resolve '@ngx-translate/core/src/translate.store'" problem on a project and it turned out that the problem came from a translate pipe wrongly formatted  ( placeholder="{{'placeholder' | translate}}" instead of   placeholder="'placeholder' | translate" ), hope it helps someone
