### ISSUE TITLE
ngx-translate pipe not working

### ISSUE THREAD

**Issue by lucassklp** [ngx-translate/core#762]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I got a en.json same with folowing statement:
`
{
    "cancel":"Cancel request"
}
`
It loads properly on the browser as images shows:
![image](https://user-images.githubusercontent.com/5818762/34529913-9e75efec-f094-11e7-8b5d-43b113e8a5fb.png)

The app.module is right here:

`export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, "/assets/i18n/" , ".json");
}
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    HttpModule,
    HttpClientModule,
    TranslateModule.forRoot({
      loader: {
          provide: TranslateLoader,
          useFactory: (HttpLoaderFactory),
          deps: [Http]
      }
    }),
...

export class AppModule {
  constructor(private translate: TranslateService) {
    translate.setDefaultLang('en');
    translate.use('en');
  }`

My HTML is:

`<app-global-loading></app-global-loading>

<app-navbar></app-navbar>

<button (click)="load()">{{ "cancel" | translate }}</button>
{{ 'cancel' | translate }}
<div>
    <spotlight>
    </spotlight>
</div>`

And the output is:
![image](https://user-images.githubusercontent.com/5818762/34529600-b50dc0dc-f093-11e7-96aa-ba0e9126caa7.png)

**Expected/desired behavior**
The button and the label must be "'Cancel Request', not 'cancel'".

**Reproduction of the problem**
The source code can be found at:
https://github.com/lucassklp/front-end-architecture

**Please tell us about your environment:**
- Angular CLI 1.6.3;
- Windows 10;
- Angular v5.0

* **ngx-translate version:** 9.0.2

* **Angular version:** 5.0.0
 
* **Browser:** [all]

**Comment by alexndreazevedo** [comment]
You are using `Http` instead `HttpClient` on `TranslateModule.forRoot()`:
```typescript
TranslateModule.forRoot({
  loader: {
    provide: TranslateLoader,
    useFactory: HttpLoaderFactory,
    deps: [Http] // Here comes HttpClient instead Http
  }
}),
```
