### ISSUE TITLE
Merge translations not working with ngx-translate-messageformat-compiler

### ISSUE THREAD

**Issue by lihanyu23** [ngx-translate/core#764]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

When using ngx-translate-messageformat-compiler, settings manually translations with 'shouldMerge' option will result in losing all translation values.

**Expected/desired behavior**

Should work the same as default compiler.

**Reproduction of the problem**

http://plnkr.co/edit/2qwydW

Merging translations using "setTranslation" method of TranslateService will cause removal of all translation values.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

Be able to use messageformat's pluralization feature combined with lazy-loading translation.

**Please tell us about your environment:**

* **ngx-translate version:** 9.0.2

* **Angular version:** 5.1.x
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by alexndreazevedo** [comment]
**Diagnose:**

1.  `TranslateMessageFormatCompiler.compileTranslations()` returns a non-valid JSON, an object notation with functions as value;
1.  [https://github.com/ngx-translate/core/blob/master/lib/src/translate.service.ts#L289](https://github.com/ngx-translate/core/blob/master/lib/src/translate.service.ts#L289) invokes `mergeDeep` from `lib/util.js`;
1.  The `mergeDeep` cleans the object notation (non-valid JSON) to an empty object `{}` at line [https://github.com/ngx-translate/core/blob/master/lib/src/util.ts#L65](https://github.com/ngx-translate/core/blob/master/lib/src/util.ts#L65);
1.  The algorithm keeps merging the empty object and the translations aren't available.

**Possible solutions:**

-  Reimplement the `mergeDeep` to consider also the non-valid JSON by removing the `JSON.parse` and `JSON.stringify`.
-  Replace the `mergeDeep` with `lodash`, for instance.

_NB: Keep into consideration that `JSON.parse` should return `Uncaught SyntaxError` if isn't enclosed into a `try..catch` block._

**Comment by lihanyu23** [comment]
@TakuyaAbe thank you for the commit.

Isn't it better to use '**lodash-es**' since it's more in the es6 way to import `merge` ? Like this:

`import merge from 'lodash-es/merge';`

**Comment by alexndreazevedo** [comment]
It's a possibility. You may implement the changes and submit the PR. The repo's owner shall evaluate.

**Comment by lihanyu23** [comment]
Since we don't want to add new dependency to the lib, we have to reimplement `mergeDeep` to handle the case.

Just want to know why [mergeDeep](https://github.com/ngx-translate/core/blob/45f1f6ea6759eea0f0312bdec6ea21743d55dd40/lib/src/util.ts#L63) cleans that object notation with
`target = JSON.parse(JSON.stringify(target));`
`source = JSON.parse(JSON.stringify(source));`

By removing that the issue can be solved.

**Comment by ocombe** [comment]
Probably to clean it, I'm not sure actually, I took that function in the AngularJS codebase :D

**Comment by alexndreazevedo** [comment]
Let's just try removing the `JSON.parse(JSON.stringify(...))`. It seems that the only problem is with this JSON normalization. There is no need to clean up both objects.
