### ISSUE TITLE
How to use translate service into service

### ISSUE THREAD

**Issue by lippomano** [ngx-translate/core#766]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```
In my application when I catch an error I call a service that shows a modal with the error,
so I need to call the translate service into my alert service, is it possible?
(it is a service so I don't have the related module to import translateModule)

* **"@ngx-translate/core": "^8.0.0",

* **Angular version:** 4.4.4

**Comment by kamil-zielinski** [comment]
@lippomano How did you solve it?

**Comment by teslim2903** [comment]
@lippomano How did you solve it?

**Comment by teslim2903** [comment]
@kamil-zielinski i found the issue, you can use suscribe, directly in your function . see exemple 
`async  presentAlertErreur() {

    this.translateService.get('GENERAL.erreur_generale').subscribe((text:string) => {
      this.messageErreur = text;
    });

    this.translateService.get('BOUTTON.fermer').subscribe((text:string) => {
      this.fermer = text;
    });

    this.translateService.get('LOGIN.erreur').subscribe((text:string) => {
      this.titre = text;
    });

    const alert = await this.alertCtrl.create({
      header: this.titre,
      message: this.messageErreur,
      buttons: [this.fermer]
    });
    return await alert.present();
  }`
