### ISSUE TITLE
localizedDate with other lang not working for angular 5

### ISSUE THREAD

**Issue by dsatpute** [ngx-translate/core#771]
translate:{ date: today | localizedDate }

import { DatePipe } from '@angular/common';
import { Pipe, PipeTransform } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

@Pipe({
  name: 'localizedDate',
  pure: false
})
export class LocalizedDatePipe implements PipeTransform {

  constructor(private translateService: TranslateService) {
  }

  transform(value: any, pattern: string = 'mediumDate'): any {
    const datePipe: DatePipe = new DatePipe(this.translateService.currentLang);
    return datePipe.transform(value, pattern);
  }

}

**Comment by consigliory** [comment]
+1

**Comment by xTaz1** [comment]
Are you sure that the current lang was defined ?

**Comment by dsatpute** [comment]
Yes in components I have already defined. It is working with angular 4.3.3 with http but in angular 5.0.0 HttpClient with not working. Ngx-translate using 7.2.2 release.. Any mistakes.

**Comment by ocombe** [comment]
The mistake is to use v7.2.2. This lib is compatible with Angular 5 starting from v8.0.0

**Comment by xTaz1** [comment]
Could you check it like this `console.log(this.translateService.currentLang)` ?

**Comment by dsatpute** [comment]
Ocombe by using v8.0.0 language changing the text now for other languages
 thank you.. but I am facing new problem with   custom  localizedDate pipe I have given code above also facing MissingTranslationHandler not worked.

**Comment by dsatpute** [comment]
For MissingTranslationHandler functionality already available in  v8.0.0 release or I need to create custom MissingTranslationHandler

**Comment by ocombe** [comment]
It's available, and yes you need to create a custom one, there is no handler by default.
