### ISSUE TITLE
Unable to load default language on page load

### ISSUE THREAD

**Issue by ajay2515** [ngx-translate/core#772]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

login page loads without translating. eg login.title 

**Expected/desired behavior**
page should load with one default translation eg login should appear instead of login.title

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

i have loader in app module
 TranslateHttpLoader(httpClient, "./assets/i18n/", ".json");

 imports: [
    NgbModule.forRoot(),
    BrowserModule, AppRouting, FormsModule, HttpModule, ReactiveFormsModule,
    HttpClientModule, NvD3Module, AngularFontAwesomeModule, HeaderModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpClient]
      }
    })
  ]

in login component

constructor
{ translate.setDefaultLang('en');
    translate.use('en'); }

lang change method
 changeSelectedLang = function (lang) {
    this.selectedlang = lang;

    this.langCollapsed = false;
    this.translate.use(lang.shortname);
  };

html
{{ 'LOGIN.TITLE' | translate }}
* **ngx-translate version:** x.x.x

* **Angular version:** 4.x.x
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by CodeAndWeb** [comment]
Sorry - for the late answer... but it's really hard to know what's going wrong from looking at your snippets.
If the issue still persists: Can you please create a small sample project?
