### ISSUE TITLE
How to add translate key to json file?

### ISSUE THREAD

**Issue by Bevis-Liao** [ngx-translate/core#775]
I am use ngx-translate in aungular project. This component so fast and amazing. But when i want to add the new thranslate key to local json file (eg: en.json) use ' this.translate.setTranslation('en', { a : 2 }); ', but no effect the "en.json"  file. So how can i do it. Thanks.

**Comment by ocombe** [comment]
Hello, sorry but a javascript library will never edit a file on your computer/server (unless you're using electron or something like that).
Edit the json file yourself instead of using `setTranslation`.
