### ISSUE TITLE
Angular translate boolean parameter

### ISSUE THREAD

**Issue by pierre03** [ngx-translate/core#778]
I want to translate a boolean parameter to different language, but it doesn't work

**Current behavior**
I have in my html:
` {{object.enabled | translate}}`

and in the fr.json, i have this:
```
{
"true": "Oui",
"false": "false",
}
```
But it doesn't work, error about the key.
Can somebody show me how to translate a boolean into i18n language, please?

**Expected/desired behavior**

Take into account the translations for all parameters into the same i18n file.

**What is the expected behavior?**

Show "Oui" ou "Non" in french, or other languages.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Angular 5

* **ngx-translate version:** 8.0.0

* **Angular version:** 5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Iv3li0s** [comment]
Convert to string before translate work
`{{object.enabled.toString() | translate}}
`
