### ISSUE TITLE
HTML doesn't compile when inserted as params

### ISSUE THREAD

**Issue by Sjerd** [ngx-translate/core#779]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
If i insert parameters to a pipe that contain html. the html doesn't get compiled 

HTML: 
```{{ 'auth.create-account' | translate:link }}```
typescript:
```  
public link = {
    start: '<a [routerLink]="[\'/auth/login\']">',
    end: '</a>'
  };
```
current output: 
```
<a [routerLink]="['/auth/login']">Click here</a> to create one! (this isn't compiled it displays it)
```
![image](https://user-images.githubusercontent.com/7803118/35333850-9105e196-0110-11e8-8690-69ab219996d6.png)

**Expected/desired behavior**
compiled html with a clickable link 

**Reproduction of the problem**
Insert HTML tags as params.

**What is the expected behavior?**
The HTML to be compiled like raw HTML does

**What is the motivation / use case for changing the behavior?**
Translators not being able to mess it up by changing the link values.

**Please tell us about your environment:**
NPM 5.6.0
Typescript ^2.6.1
* **ngx-translate version:** x.x.x
^9.1.1
* **Angular version:** 2.x.x
 ^5.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome XX

**Comment by ocombe** [comment]
You need to use [innerHTML] to bind html to elements. But it will only work with regular html. There is no "compile" function in Angular right now, so it will not work with directives, components and pipes.
This might change is such a compile function was to be available in the framework.

**Comment by El-Tee-E** [comment]
We have the same issue as @ocombe -  the innerhtml does not work in IE11:

shows a translated text but with the html as text, not rendered html. Also for some reason it shows the text twice. 

Ex.
```

"title": "Hello from this <strong>world</strong>"

{{'title' | translate}}

```
Result in IE 11: 

`Hello from this <strong>world</strong>Hello from this <strong>world</strong>
`

Expected result (and result in other - not crappy - browsers): 

Hello from this **world**

We are experiencing this bug in our ng4.1 project.
Worse part is that stats show IE 11 is 2nd most used browser by our users.

Will this issue be addressed  (or is there a workaround)?
