### ISSUE TITLE
use different directories for translation files

### ISSUE THREAD

**Issue by KNeela** [ngx-translate/core#781]
I'm using ngx-translate to translate buttons, headers, ... in my app and this works fine. My translation files are in the **/assets/i18n/** folder.

Now I have mockdata which I also have to translate, but my mockdata is in another directory -> **/assets/data/**

To load my json translations files from the **i18n** folder I use:

```
export function setTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}
```
but now I also want to load the files from the **data** directory.

How can I achieve that?

* **ngx-translate version:** 8.0.0

* **Angular version:** 4.4.3

**Comment by Iv3li0s** [comment]
Hey,
Solution here : [ issues 199]( https://github.com/ngx-translate/core/issues/199#issuecomment-339084987)

**Comment by KNeela** [comment]
@Iv3li0s Hi, thanks for your answer.
I tried this code, but I think I'm doing something wrong.
Can you take a look at my plunker I made?
https://plnkr.co/edit/K2dZuYAREvOA48sm66N9?p=info

**Comment by KNeela** [comment]
@Iv3li0s I guess I've edited my post at the same time as you posted the answer.
I've found the problem and was able to solve it. Now I have another problem which you can see above your last anwer

**Comment by Iv3li0s** [comment]
In plunker the "root file" is not the same as a classic angular app
You must add "src"
` {prefix: './assets/i18n/', suffix: '.json'}` besome 
` {prefix: './src/assets/i18n/', suffix: '.json'}`

**Comment by KNeela** [comment]
@Iv3li0s I solved the problem which I had in plunker.

Now my problem is this one:

In my data directory I have the following files:

en.json

[
  {
    "id": 1,
    "colorname": "blue"
  },
  {
    "id": 2,
    "colorname": "yellow"
  }
]
de.json

[
  {
    "id": 1,
    "colorname": "blau"
  },
  {
    "id": 2,
    "colorname": "gelb"
  }
]
I want these object properties to be translated. I tried to loop through the array with *ngFor and translate them but it doesnt work.

<li *ngFor="let color of colors">
   <a>{{color.colorname | translate}}</a>
</li>
I get no error but it also won't translate. I just get the string "color.colorname" as an output on my page instead of the real color name like "blue" or "blau"
