### ISSUE TITLE
How to change the json file (keys and values) without having to re-compile the application ?

### ISSUE THREAD

**Issue by SELKHENIFER** [ngx-translate/core#784]
Hello there, 

I'v just installed the ngx-translate module, it's working, my question is : after I deploy my application, how can I change the json files keys and values, without having to re-compile and re-déploy again.

Per example : 
My current en.json file : 
{
    "hello": "Hello World"
}
I have this  : <div>{{"hello" | translate}}</div>$

After deploying my app; I would like to change "Hello World" to "Good Morning" without re-compiling and re-deploying !

Thank you !

**Comment by ali-idrizi** [comment]
The JSON files don't actually compile, all you need to do is find them in your assets directory and change them. After you run `ng build` it should be located at `/dist/assets/i18n/en.json`.
