### ISSUE TITLE
Ability to break up json files into multiple json files feature request.

### ISSUE THREAD

**Issue by javaspeak** [ngx-translate/core#785]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
It seems like: 
   
   TranslateHttpLoader(http, './assets/i18n/', '.json');

matches one filename stem:

     e.g.  it matches en.json or fr.json e.t.c

**Expected/desired behavior**
As the application gets bigger it would be great to have separate json files for different functions.

For example:

     header_en.json
     header_fr.json
     login_en.json
     login_fr.json

Maybe support for wild cards would be great

     TranslateHttpLoader(http, './assets/i18n/*', '.json');

Maybe it is possible do this with a custom loader but am a beginner -the task is too hard for me.  If anyone could code this I would use it and be very happy.  It is good if this functionality becomes part of the API.

One of the reasons for breaking out into multiple files is to avoid code versioning conflicts and make the internationalization more maintainable.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:01UjWY3TKfP6pgwXKuEa

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-translate version:** x.x.x

* **Angular version:** 2.x.x
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jarodsmk** [comment]
Similar issue to:
https://github.com/ngx-translate/core/issues/199

?

**Comment by javaspeak** [comment]
@jarodsmk thank you

**Comment by lgh2016** [comment]
@jarodsmk thank you in angular 11 if works
