### ISSUE TITLE
getLangs() does not modify after resetLang()

### ISSUE THREAD

**Issue by ronen1malka** [ngx-translate/core#791]
**I'm submitting a ...**  
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
After removing a lang with `resetLang()` the removed lang is still in the list of `getLangs()`

**Expected/desired behavior**
The removed lang should not appear in the getLangs() array,

**Reproduction of the problem**
See following plunker:
[http://plnkr.co/edit/8OS7zsGMm1S20UPtikGD?p=preview](http://plnkr.co/edit/8OS7zsGMm1S20UPtikGD?p=preview)

**What is the expected behavior?**
Expected behaviour is that lang will be dropped from list.

* **ngx-translate version:** 5.2.0

* **Angular version:** 9.0.2

**Comment by CodeAndWeb** [comment]
`resetLang()` resets the internal translation caches. It's not a remove language function.
