### ISSUE TITLE
TypeError: __webpack_require__.e is not a function

### ISSUE THREAD

**Issue by bjornharvold** [ngx-translate/core#797]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
ng:///AppModule/AppComponent_Host.ngfactory.js:5 ERROR TypeError: __webpack_require__.e is not a function
    at webpackAsyncContext (eval at ./src/assets/i18n lazy recursive ^\.\/.*\.json$ (main.bundle.js:1350), <anonymous>:39:29)
    at WebpackTranslateLoader.getTranslation (webpack-internal:///./src/app/app.module.ts:76)
    at TranslateService.getTranslation (webpack-internal:///./node_modules/@ngx-translate/core/@ngx-translate/core.es5.js:3196)
    at TranslateService.retrieveTranslations (webpack-internal:///./node_modules/@ngx-translate/core/@ngx-translate/core.es5.js:3182)
    at TranslateService.setDefaultLang (webpack-internal:///./node_modules/@ngx-translate/core/@ngx-translate/core.es5.js:3123)

**Expected/desired behavior**
App should load

**Reproduction of the problem**
I update my Angular app to Angular CLI 1.7.0 and Angular 5.2.5. I can no longer start the app. 

**What is the expected behavior?**
App should load

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Angular CLI: 1.7.0
Node: 9.4.0
OS: darwin x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.2
webpack: 3.11.0

* **ngx-translate version:** x.x.x
v9.1.1

* **Angular version:** 2.x.x
 5.2.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
ALL

**Comment by bjornharvold** [comment]
This was an issue with Typescript 2.7.2. Reverting back to 2.6.2 fixed it.

**Comment by AhmetFUsta** [comment]
> 
> 
> This was an issue with Typescript 2.7.2. Reverting back to 2.6.2 fixed it.

I downgraded from 2.7.2 to 2.6.2 for other reasons and that's when this issue showed up for me.

**Comment by pabloleone** [comment]
I can confirm the same. I got this error when trying to use the CLI approach described in here https://github.com/ngx-translate/http-loader

I just downgraded to 2.6.2 and it's now solved!
