### ISSUE TITLE
Adding comment for translator

### ISSUE THREAD

**Issue by IterationCorp** [ngx-translate/core#798]
Hello,

Can we add a comment for the translator somewhere that will be stored in the JSON file but not printed on the html page ?

For exemple this is confusing:
{{ 'BOOK' | translate }}
Is this a "book" or to "book" something? (making a booking)

I would like to add comment on the file that can be seen on BabelEdit or oneskyapp.com but not displayed on my app. 

Thanks

**Comment by CodeAndWeb** [comment]
I agree that comments are important for the translator. But I would keep these comments out of the source. They will bloat your code twice times: The comments are part of your templates/code and JSONs.

Workaround:
- You could use an unused language for these comments
- As you just mentioned [BabelEdit](https://www.codeandweb.com/babeledit): You can add comments there

![Comment field](https://user-images.githubusercontent.com/716009/37979659-6b420c6e-31e9-11e8-9c66-6027f970fc32.png)
