### ISSUE TITLE
publish readme.md

### ISSUE THREAD

**Issue by scttcper** [ngx-translate/core#799]
the npm readme is out of date because it isn't being copied to the published directory used by ng-packagr.

Can see there's no readme in the latest version https://registry.npmjs.org/@ngx-translate/core/-/core-9.1.1.tgz

this is also why it isn't available on https://preview.npmjs.com/package/@ngx-translate/core

**Comment by scttcper** [comment]
I use something like https://github.com/TypeCtrl/ngx-headroom/blob/master/build.ts in my libs

**Comment by ocombe** [comment]
Fixed, thanks!
