### ISSUE TITLE
getting translations from a database

### ISSUE THREAD

**Issue by phsims** [ngx-translate/core#803]
We have a large database (pouchDB) full of translations each languages translations is held in its own db.  Can I use ngx-translate to get the translations directly from the db?

**Comment by raugaral** [comment]
I'm in the same point. Have you found any solution?

**Comment by CodeAndWeb** [comment]
Sure. You can create a custom loader and register it with ngx-translate:

```
export class MyLoader implements TranslateLoader {
  getTranslation(lang: string): Observable<any> {
      ... your code that returns an Observable containing the translations ....
  }
}
```
