### ISSUE TITLE
Documentation on how to setup translation for e2e.

### ISSUE THREAD

**Issue by un33k** [ngx-translate/core#807]
```
[ x] enhancement 
```

**Current behavior**
Translation works when running the app or unit tests. However, it doesn't load when running the e2e test.

**Expected/desired behavior**
It would be great to add some documentation on how config e2e so translation loads that work.

**Reproduction of the problem**
Just run `ng e2e` where `page.navigateTo();` navigates to a page that has `{{'SOMETHING'|translate}}

**What is the expected behavior?**
Having sample code or example on e2e setup.

**What is the motivation / use case for changing the behavior?**
e2e fails when app enables translation.

**Please tell us about your environment:**
Chrome
```
Angular CLI: 6.0.0-beta.4
Node: 9.6.1
OS: darwin x64
Angular: 6.0.0-beta.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cli: 6.0.0-beta.4
@angular-devkit/build-optimizer: 0.4.3
@angular-devkit/core: 0.4.3
@angular-devkit/schematics: 0.4.3
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.4
@schematics/angular: 0.4.3
@schematics/package-update: 0.4.3
typescript: 2.6.2
webpack: 4.0.1
```
* **ngx-translate version:** x.x.x
```
@ngx-translate/core": "^9.1.1",
@ngx-translate/http-loader": "^2.0.1",
```

**Comment by daniel-mueller-me** [comment]
@un33k Have you already found a solution?

**Comment by un33k** [comment]
Yes. Compiled all json files into a single object in a TS file that gets compiled in. Wrote a loader for pulling the ts file instead.

**Comment by arturhun** [comment]
Assuming by the label **Status: Solved**, the requested enhancement _Documentation on how to setup translation for e2e_ is available somewhere. Where can one find it? :)

**Comment by un33k** [comment]
@arturhun you can look at [@nwx/i18n](https://github.com/neekware/nwx-i18n) which is a wrapper module around ngx-translate. 

The custom loader for testing is found [here](https://github.com/neekware/nwx-i18n/blob/master/apps/web/src/app/home/home.component.spec.ts).

Cache busting logic is found [here](https://github.com/neekware/nwx-i18n/blob/master/pkgs/i18n/src/i18n.module.ts#L27)

Hope this helps.

**Comment by kimdah3** [comment]
@un33k would you mind sharing code on your solution? Still can't figure out how to use it in e2e testing. The links you share looks like normal unit tests.

**Comment by un33k** [comment]
Nothing special for e2e except that you need to use fakeAsync() or the good old timeout to allow time for the new language to load up.  [here](https://github.com/neekware/nwx-i18n/blob/master/apps/web/e2e/src/app.e2e-spec.ts) is the e2e test for this module.
