### ISSUE TITLE
Directive do not translate

### ISSUE THREAD

**Issue by xeewi** [ngx-translate/core#808]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

When i'm using translate directive, text don't translate, key still here

```
// en.json
{
  "key": "en-value"
}

// fr.json
{
  "key": "fr-value"
}

// page.html
<p translate>key</p>

// result 
key

// use translate.use('fr') in ts file
// result
key

```

**Expected/desired behavior**

```
// en.json
{
  "key": "en-value"
}

// fr.json
{
  "key": "fr-value"
}

// page.html
<p translate>key</p>

// result 
en-value

// use translate.use('fr') in ts file
// resultf
fr-value

```

**Reproduction of the problem**

I don't really know how to reproduce this problem, I just installed ngx-translate on my Angular project like it's say on the Getting Started

**What is the motivation / use case for changing the behavior?**
Just want to translate using directive, and string between tag as key (like described on the readme)

**Please tell us about your environment:**

* **ngx-translate version:** 9.1.1

* **Angular version:** 5.0.3
 
* **Browser:** [all]

**Comment by maxfahl** [comment]
I'm experiencing the same issue. Everything worked great until I upgraded from Angular 4.x to 5.2.8. I'm currently on @ngx-translate/core 9.1.1 and @ngx-translate/http-loader 2.0.1 using the translate pipe and not the directive.

**Comment by maxfahl** [comment]
I was having a different problem, the translate pipe is working as intended.

**Comment by CodeAndWeb** [comment]
Sorry - I can't reproduce this. I've been working through [my tutorial](https://www.codeandweb.cawwork/babeledit/tutorials/how-to-translate-your-angular-app-with-ngx-translate) but everything works like it should.

From what you've added here it's hard to tell what's now working in your case...
