### ISSUE TITLE
Inversed translate

### ISSUE THREAD

**Issue by jevilla94** [ngx-translate/core#809]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[X] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Currently, I have translated all content of my ngx-admin. But I have values that are gotten by a database and a service.

**Expected/desired behavior**
I need translate these values, search the specific key in the json file and whit this can get the translated value

**Reproduction of the problem**
I get the value "car" of my database to my select (for example). In my json file have "{"VE.CAR": "car"}" and "{"VE.CAR": "auto"}". I need receive this key ("VE.CAR") while use the value "car" and can translate to "auto" when the language is changed

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-translate version:** 9.1.1

* **Angular version:** 5.1.3
 
* **Browser:** [all ]

**Comment by CodeAndWeb** [comment]
Thanks for your feature request. This is an interesting idea, but I don't see many people who might have a use for it. This makes it hard for us to increase the complexity of the library.

In your case would be the easiest way to create a hash from the translations and perform the search manually. Or maybe it's an option to store the keys in the database?
