### ISSUE TITLE
Handle missing translation key and value separately

### ISSUE THREAD

**Issue by DanygNet** [ngx-translate/core#810]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
When using a MissingTranslationHandler the handle() function is called

- When the translation key is missing
- When the translation key is present, but the value is null/undefined

**Expected/desired behavior**

It would be nice if we could separate those two cases so you can handle them individually.

**Comment by CodeAndWeb** [comment]
Thanks for your feature request. 

What exactly is the use case for this?
Why would you treat a "missing" differently from "null"?

**Comment by DanygNet** [comment]
I have my translations stored in key-value table in a database.

If the translation key is missing I would like to perform a web request to my server that adds the key to the table.

If it is exists, but the value is null/undefined, I just want to return the translation key.

**Comment by CodeAndWeb** [comment]
A simple solution for you is the following:
Make your server request. If it comes back with a miss (null/undefined) store the key as translation.

**Comment by DanygNet** [comment]
This is the exact thing I want to avoid - to limit the amount of requests to the server, I only want to make the server request if absolutely necessary (when the translation doesn't exist)

**Comment by CodeAndWeb** [comment]
So you have a file with some of the translations? But if the translation is missing in the file you make the request?
