### ISSUE TITLE
translate.use not working

### ISSUE THREAD

**Issue by mu250234** [ngx-translate/core#811]
this.translate.use(this.languageInUse.language).subscribe(() => {
      console.info(`Successfully initialized language.'`, this.languageInUse.language);
    }, err => {
      console.error(`Problem with  language initialization.'`);
    });

i got console success message but pages are not translated. and there is no http calls hapening at network tab.
///////// app.module.ts
export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}
///////////
always taking default language set at app.component.ts

any help???

**Comment by CodeAndWeb** [comment]
Sorry - I can't reproduce this.

The code looks good (except for the wrong quote marks) - but it's hard to tell without seeing more of your project.

Here's a simple working demo project: https://github.com/CodeAndWeb/ngx-translate-demo
