### ISSUE TITLE
How to pass interpolateParams for instant method with Array<string> syntax?

### ISSUE THREAD

**Issue by shravansofts** [ngx-translate/core#814]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
How to pass interpolateParams when using instant with Array<string>?
Ex: translate.instant(["key1", "key2", "key3"]);

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:01UjWY3TKfP6pgwXKuEa

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-translate version:** 9.1.1

* **Angular version:** 2.x.x
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by CodeAndWeb** [comment]
The `instant` method applies the same set parameter set to all keys. You can't specify a separate set for each key.

You can either put all your parameters in 1 object - or call `instant` multiple times with smaller sets.

**Comment by shravansofts** [comment]
Thanks for the confirmation.
