### ISSUE TITLE
Update to support rxjs 6.0

### ISSUE THREAD

**Issue by mhosman** [ngx-translate/core#816]
This is a forced requirement in new Angular >= 6.0 rc0

**Comment by ocombe** [comment]
Actually it just need to support rxjs 5.6+, there's a document coming up soon that explains that.
I'll make the update once ngpackagr is updated to support the new Angular package format, it will probably be updated this weekend

**Comment by alvachien** [comment]
Have some issues here. As the the new material2 6.0 beta package requires angular 6.0 rc, and angular 6.0 rc requires rxjs6.0 beta.

When all beta packages installed, the project will failed at compile:
ERROR in node_modules/@ngx-translate/core/src/translate.directive.d.ts(2,10): error TS2305: Module '"C:/Users/XXX/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/@ngx-translate/core/src/translate.loader.d.ts(1,10): error TS2305: Module '"C:/Users/XXX/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngx-translate/core/src/translate.service.d.ts(2,10): error TS2305: Module '"C:/Users/XXX/node_modules/rxjs/Observable"' has no exported member 'Observable'.

**Comment by ocombe** [comment]
Version 10.0.0 has been released with support for Angular 6 and RxJS 6, can you try and tell me if it works for you?

**Comment by alvachien** [comment]
@ocombe Thanks so much for the next release.
It works! There is no more error now. Thanks!

**Comment by mhosman** [comment]
Thanks for the release!!! I don't know why but since I upgraded I get Http failure response for http://localhost:4200/assets/i18n/en.json: 404 Not Found

**Comment by mhosman** [comment]
Sorry, the 404 Not found is a problem with the Angular-Cli 6 RC01 and RC02, not a problem with this library.
