### ISSUE TITLE
Translation not working on a basic Nativescript angular-cli project

### ISSUE THREAD

**Issue by mozi22** [ngx-translate/core#831]
**I'm submitting a ...**
```
support request 
```

**Current behavior**
Translation not working in a basic angular-cli based Nativescript project.

**Expected/desired behavior**
Translation should work

**Reproduction of the problem**
You can find the minimum project in [this repo](https://github.com/mozi22/ngrx-translate-test).

**Please tell us about your environment:**
Mac OS 10.12.6

**Comment by CodeAndWeb** [comment]
Please remove "ng2-translate": "^5.0.0", from your package.json.
`ng serve` does also not work because of missing dependencies.

**Comment by mozi22** [comment]
Hi, thanks for getting back. The problem still persists. Even after removing the ng2-translate. Could you please point me to a minimum example project where ngx-translate is working ?. What I've noticed is that the problem lies in the ngx-translate/http-loader. If I change the version of it to 0.1.0 than it works fine. but it doesn't work for v2.0.0. Do you have an y idea why this is happening ? Should I post it in the ngx-translate/http-loader forum ?

**Comment by CodeAndWeb** [comment]
Please

1) Describe the issues that you have in detail - with error messages, whatever. "Translation not working in a basic angular-cli based Nativescript project." is not helpful
2) Get the git example in a state where it can be checked out and startable with `yarn install` and `ng serve`

**Comment by mozi22** [comment]
Here are the steps I took to generate the problem.

1) Followed [this tutorial](https://docs.nativescript.org/tutorial/ng-chapter-1) to create a basic nativescript + angular app.

2) Included the following packages in the parent package.json 

```
"@ngx-translate/core": "9.0.0",
"@ngx-translate/http-loader": "2.0.0",
```
3) Add the en.json and de.json file in the `app/assets/i18n` folder of the project. They look like this.

**de.json**
```
{
  "HELLO": "wie gehts"
}
```
**en.json**
```
{
  "HELLO": "whats up"
}

```
4) Add the following label instead of apple image as shown in the tutorial.
`
<Label [text]="'HELLO' | translate"></Label>
`

5) My `app.module.ts` looks like this.
```

import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";

import { AppComponent } from "./app.component";

import {HttpClientModule, HttpClient} from '@angular/common/http';
import {TranslateModule, TranslateLoader} from '@ngx-translate/core';
import {TranslateHttpLoader} from '@ngx-translate/http-loader';

export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}


@NgModule({
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  imports: [
		NativeScriptModule,
	    HttpClientModule,
	    TranslateModule.forRoot({
	        loader: {
	            provide: TranslateLoader,
	            useFactory: (HttpLoaderFactory),
	            deps: [HttpClient]
	        }
	    })  
    ],
  schemas: [NO_ERRORS_SCHEMA],
})
export class AppModule {}

```

6) Run the project using `tns run ios` after `npm i`.

**Comment by mozi22** [comment]
no problem thanks.

**Comment by renestalder** [comment]
Did you found a solution, @mozi22? I just wonder, I upgraded from version 5 to version 9 with the migration guide. Everything seems in place, but I only get empty outputs.

**Comment by ocombe** [comment]
Xplat will generate a CLI project that includes nativescript with ngx-translate, you could check it out: https://nstudio.io/xplat/

**Comment by mozi22** [comment]
couldn't find the solution. I had to try a separate way
