### ISSUE TITLE
Support for webpack 4.0

### ISSUE THREAD

**Issue by Santhosh25** [ngx-translate/core#833]
I'm trying to implement the translate in Angular 6.0.0-rc.1 version, it unable to load the {lang}.json file.
It throws 404 error. 

Latest version of ngx-translate support webpack 4.0 and above version ?

Can you please help me to resolve this issue?

**Comment by CodeAndWeb** [comment]
Please provide a simple demo of the problem - e.g. on github.
We really don't have the resources to try to reproduce the issue with this vague description.

**Comment by ocombe** [comment]
There are multiple issues dealing with the way to setup the path to load the assets with CLI projects, a quick search should be enough for you to find the solution.
