### ISSUE TITLE
How to translate words in the component(.ts) file??

### ISSUE THREAD

**Issue by sarath3940** [ngx-translate/core#835]
**I'm submitting a ...** 
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
   At present I am using the translation in ".html" file. But, now I have to use the translation in "Component(.ts)" file as well.

**Expected/desired behavior**
  I want to translate the value which is mentioned in the component(.ts).

**What is the expected behavior?**
  Should translate in component.

**Please tell us about your environment: Angular 5, type Script

* **ngx-translate version:** 9.1.1

* **Angular version:** 5
 
* **Browser:** [Chrome XX | Mobile Chrome XX ]

I want to translate the word "View".

![feature](https://user-images.githubusercontent.com/37688535/39172614-e4a9a990-47bf-11e8-992e-3b1678e7f25f.png)

**Comment by cristianmartinez** [comment]
Hi @sarath3940, I think you can use `TranslateService.instant('VIEW_KEY')` where VIEW_KEY is the token on your translation file.

**Comment by CodeAndWeb** [comment]
You have basically 3 choices

1. If you are absolutely sure that your translation files are already loaded and you don't want to update the translations automatically if a language changes use `translate.instant('ID')`
2. If you are not sure about the loading state but you don't need updates on language changes use `translate.get('ID')`. It gives you an observable that returns the translation once it's loaded and terminates the observable.
3. If you want constant updates (e.g. when a language changes) use `translate.stream('ID')` - it returns an observable that emits translation updates. Make sure to dispose the observable if you don't need it anymore.

This assumes that you've injected `TranslationService` as `translate` in your component.

E.g.

    export class AppComponent {
	    constructor(translate: TranslateService) {
	    	translate.get('hello.world').subscribe((text:string) => {console.log(text});
	    }
	}

**Comment by bmorozco** [comment]
We can use TranslateService.
E.g: `` export class AppComponent {
    constructor(translate: TranslateService) {
    }

print() {
console.log(this.translate.instant('hello.world'));
}
}``

Where 'hello.world' is a key in your file for the change of language

**Comment by bmorozco** [comment]
### We can use TranslateService
`` export class AppComponent {
constructor(translate: TranslateService) {
}

print() {
console.log(this.translate.instant('hello.world'));
}
}``

Where 'hello.world' is a key in your file for the change of language

**Comment by rabindranathforcast** [comment]
@bmorozco @CodeAndWeb i am trying both approach but i didn't get something good, i am doing something like this

asume translate as TranslateService and definition of json files for translates in this examples

file inside assets/i18n/en.json

```
"loginModule": {
        "messageNotifiLogin": {
            "loginSuccess": "User successfuly",
            "loginFailure": "User incorrect, check your credentials"
        }
    }
```

firts approach

in constructor
```
constructor (
     console.log(this.translate.instant('loginModule.messageNotififLogin.loginSucess'));
)
```
With firts one i just see loginModule.messageNotififLogin.loginSucess (not the content, that should be --> "User successfuly" )


Second approach direct with messageNotifLogin in single method call into ngOnInit

```
/**
   * LoadTextNotififBar
   */
  public LoadTextNotififBar() {
    this.translate.get('loginModule.messageNotififLogin.loginSucess').subscribe( (text: string) => {
      console.log(text);
      this.messageNotifNoLogin = text;
    });
  } 
```

i see the same result with both approches

![image](https://user-images.githubusercontent.com/52291139/61554069-1047cc80-aa2a-11e9-86af-67612f63f0b4.png)

sorry for my bad english...
Angular Version 7
Angular Cli 7.1.2
ngx-translate/core:  11.0.1
ngx-translate/http-loader: 4.0.0

any suggestions?

**Comment by vrushabh583** [comment]
you need to add your json data in en-us.json  file also , add it and try

**Comment by rabindranathforcast** [comment]
@vrushabh583 i already have those files but didn't work.. am i missing something?

**Comment by SuzannaWentzel** [comment]
I think it isn't working since you use 'loginSuccess' as a key in your JSON file, but in your code you are using 'loginSucess' (notice the amount of 'c's). You can change that and see whether that was the problem

**Comment by rabindranathforcast** [comment]
@SuzannaWentzel thx that amount of C and i write one F more into the keys 

this works now
```
this.translate.get('loginModule.messageNotifiLogin.loginFailure').subscribe( (text: string) => {
      this.messageNotifNoLogin = text;
    });
```

and  this option into ts.file

```
this.translate.instant('loginModule.messageNotifiLogin.loginSuccess') 
```
Both solutions works...thx

**Comment by garigordon** [comment]
Thanks
It is works - this.translate.instant('TEXT')

**Comment by vivmaniaa** [comment]
wow! thanks translate.stream('ID') worked for me thank you so much!!

**Comment by OusamaELIDRISSI** [comment]
> Hi @sarath3940, I think you can use `TranslateService.instant('VIEW_KEY')` where VIEW_KEY is the token on your translation file.

Thank you it works perfectly.

**Comment by praveenkumar-r** [comment]
Using Translate.stream before language files are getting loaded. And am getting following exception You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
Is it possible to use Translate.stream without this issue

**Comment by jack1ripper** [comment]
as we know ,in HTML file, we can use pipe to pass variable like this , so that different language can turn into inversion,
how can I make it in ts file.

` <div class="condition">{{ 'canUseTreshold' | translate: { restrictionAmount: item.threshold } }}</div>`

**here is my ts code:**
`
`${this.translate.instant('full')}${item.thresholdStr}${this.translate.instant('deliveryFeeDiscount')}${idx !== discountList.length - 1 ? '、' : ''}`;
`

**Comment by IkramiAswan** [comment]
> You have basically 3 choices
> 
> 1. If you are absolutely sure that your translation files are already loaded and you don't want to update the translations automatically if a language changes use `translate.instant('ID')`
> 2. If you are not sure about the loading state but you don't need updates on language changes use `translate.get('ID')`. It gives you an observable that returns the translation once it's loaded and terminates the observable.
> 3. If you want constant updates (e.g. when a language changes) use `translate.stream('ID')` - it returns an observable that emits translation updates. Make sure to dispose the observable if you don't need it anymore.
> 
> This assumes that you've injected `TranslationService` as `translate` in your component.
> 
> E.g.
> 
> ```
> export class AppComponent {
>     constructor(translate: TranslateService) {
>     	translate.get('hello.world').subscribe((text:string) => {console.log(text});
>     }
> }
> ```
> 
> You'll have to assign the translation to your data array from within the `subscribe`

Hi, I use this.translate.stream('KEY') and this.translate.get('KEY') but it returns the string of "[object Object]. Is there any way I can solve this?

**Comment by CodeAndWeb** [comment]
@IkramiAswan How does your .json file look like?
