### ISSUE TITLE
.json files path is incorrect after build prod

### ISSUE THREAD

**Issue by Ahmed-sa3d** [ngx-translate/core#837]
after build my app with ng build --prod --base-href "http://localhost:8080/angularspringbe" -d "/angulaspringbe/resources" --output-hashing none

every thnig is well but .json i18n files path is incorrect 
![capture](https://user-images.githubusercontent.com/38682139/39281782-add15178-4906-11e8-88b2-69cb28591ec7.PNG)
it's should be http://localhost:8080/angularspringbe/resources/i18n/en.json

this my angular-cli app
"apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico",
        "./angularspringbe/resources/assets" 
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ]

**Comment by CodeAndWeb** [comment]
You can set the paths in the constructor of the `TranslateHttpLoader`:

    export function createTranslateLoader(http: HttpClient) {
        return new TranslateHttpLoader(http, './assets/i18n/', '.json');
    }

**Comment by Ahmed-sa3d** [comment]
Thanks @CodeAndWeb you saved my time

**Comment by maiconfang** [comment]
Muito obrigado o meu também ^^ @CodeAndWeb
