### ISSUE TITLE
building prod issue

### ISSUE THREAD

**Issue by gbarrionuevo** [ngx-translate/core#841]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
It says λ rror during apps copy: No app builds found after ngx cordova:build

**Expected/desired behavior**
it should compile prod version

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example,
please provide the steps to reproduce and if possible a minimal demo of the problem via https://stackblitz.com/ or https://plnkr.co.
You can use this template as a starting point: https://stackblitz.com/github/ngx-translate/example

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-translate version:** 10.x.x

* **Angular version:** 6.x.x
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ocombe** [comment]
If you want any help with your issue, you need to give more details. You haven't even taken the time to fill the template message correctly.
