### ISSUE TITLE
breaking changes from 9 to 10 not documented

### ISSUE THREAD

**Issue by geetee24** [ngx-translate/core#844]
## Current behavior

can you please document what has changed in the api from 9 to 10 and 2 to 3

## Environment

<pre><code>
ngx-translate version: X.Y.Z
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ocombe** [comment]
All changes are documented here: https://github.com/ngx-translate/core/releases
