### ISSUE TITLE
Include translation file into main bundle (cache busting)

### ISSUE THREAD

**Issue by MartinMa** [ngx-translate/core#848]
I wonder what might be the best approach to **include** the **primary language** into the **main bundle** (e.g. main.hash.js).

Because of cache issues, I don't want to use the http loader. Because I can't guarantee that the language files (e.g. en.json) will be re-downloaded on every update.

That's because I'm using the WebpackTranslateLoader as stated on https://github.com/ngx-translate/http-loader#angular-cliwebpack-translateloader-example

Now, every language file is packed into its own chunk-bundle (like 2.308821959c3aab964278.chunk.js). But I'd like to include the primary language into the main bundle. It shouldn't be necessary to perform an additional http request in this case.

What can I do about this? Implement my own loader? Do I need to put my language json object into its own TypeScript file and export it?

**Comment by ocombe** [comment]
You can use `setTranslations` to add translations manually without using a loader, the loader will not be called because it'll detect those translations as loaded
https://github.com/ngx-translate/core#3-define-the-translations

in your code, just require the json translations and they will be bundled by webpack

**Comment by MartinMa** [comment]
Thanks @ocombe, that worked like a charm.

Anyone else looking for an example. In this case `de` is the primary language.

Before:
```TypeScript
export class AppComponent {
  constructor(translate: TranslateService) {
    translate.addLangs(['de', 'en']);
    translate.setDefaultLang('de');

    const browserLang = translate.getBrowserLang();
    translate.use(browserLang.match(/de|en/) ? browserLang : 'de');
  }
}
```

After:
```TypeScript
export class AppComponent {
  constructor(translate: TranslateService) {
    translate.addLangs(['de', 'en']);
    translate.setDefaultLang('de');

    translate.setTranslation('de', require('../assets/i18n/de.json'));

    const browserLang = translate.getBrowserLang();
    translate.use(browserLang.match(/de|en/) ? browserLang : 'de');
  }
}
```

**Comment by Ismaestro** [comment]
My solution:

```
const languages = ['es', 'en'];
this.translateService.addLangs(languages);
this.translateService.setDefaultLang('es');

for (const lang of languages) {
    this.translateService.setTranslation(lang, require('../assets/i18n/' + lang + '.json'));
}

const browserLang = this.translateService.getBrowserLang();
this.translateService.use(languages.includes(browserLang) ? browserLang : 'es');
```

**Comment by daaain** [comment]
What I noticed is that if I call `setDefaultLang` first then I'll always see a an XHR request (for that language file), but calling `setTranslation` first there isn't one (as expected).

**Comment by GursimranjeetSingh** [comment]
Thanks @ocombe, You are a life saver to me
