### ISSUE TITLE
On language change, instant still returns previous language values

### ISSUE THREAD

**Issue by coingod** [ngx-translate/core#866]
## Context
Our Application currently supports 2 languages, German and English. German is default language.
Users are able to switch language in Profile Settings, this triggers an API call to update the profile which returns the new User data with the current language, we then reset the language using `use`.

99% of our App uses the pipe method to translate everything, this works perfect.
We have a special case for our dropdown with a list of countries, since we want to sort this list Alphabetically and this depends on the current language. 
We have a special component for this dropdown. It's subscribed to the `onLangChange` event, to know when the language is switched, and updates the country list when triggered. This involves manually translating each country using `instant`, once the translated list is ready we can sort it Alphabetically using simple `localeCompare` (This is why we need a Sync method for translations). 
When the component is created it updates the list aswell.

**app.component.ts**
```javascript
    constructor(private _translate: TranslateService) {
        _translate.setDefaultLang('de');
        _translate.use('de');
    }
```

**country.component.ts**
```javascript
    // Array of Country objects, Country.value is the translate key
    countries: Country[] = [];

    constructor(private _translateService: TranslateService) {
        // Generate country list on start up
        this.updateCountries();

        // Regenerate country list on language change
        this._onLangChange = this._translateService.onLangChange.subscribe((event: LangChangeEvent) => {
            this.updateCountries();
        });
    }

    private updateCountries() {
        // We get all the countries with their translation key
        let allCountries = COUNTRIES;
        // This returns the correct language!
        let lang = this._translateService.currentLang;
        // Translate all countries
        allCountries.forEach(country => {
            country.value = this._translateService.instant(country.value);
        }); 
        // Sort the new list
        this.countries = allCountries.sort(function (a, b) {
            return a.value.localeCompare(b.value, lang);
        });
    }
```

**users.service.ts** (simplified)
```javascript
    private doGetUserData() {
        // fetch logged in.. user info
        return this._http.get(USER_API_BASE_URL + '/user')
            .map(res => {
                let user = new User(res);
                // set locale
                if (null !== user.locale) {
                    this._translateService.use(user.locale);
                } else {
                    this._translateService.use('de');
                }
                this.setUser(user);
                return user;
            })
            .catch(error => {
                this.logout();
                return ServerUtil.handleOtherError(error);
            });
    }
```
## Current behavior
When the country component is displayed for the first time, it generates the list in the current language and sorted. (Good)
Refreshing the App generates the list in the current language. (Good)
When the user switches to a different language, the list is updated but the translations are the same. (Bad)
Going to a different page, and back to the country list still shows old translations. (Bad)

## Expected behavior
When the user switches to a different language, the list is updated with the new translations.
Going to a different page, and back to the country list still shows the new translations.

## Environment
ngx-translate version: 9.0.2
Angular version: 5.1.2

I had a look at other issues and it seems that since `use `works Async, calling `instant `may not work correctly if the language is not yet loaded. But I think the point of using `OnLangChange `is to be sure that the langauge files have been loaded, and then I should be able to call `instant`. 
I tried using `get `just to see if the translation part was working but it isn't.
I even tried to reset the same language again using `use `and then subscribe to it to execute `updateCountries`, also didn't work.
Any help would be appreciated. Thank you in advance.

**Comment by MartinMa** [comment]
You can try to call `_changeDetectorRef.detectChanges()` manually to see if it fixes your problem. Like this:
```TypeScript
import { ChangeDetectorRef, Component } from '@angular/core';
import { TranslateService, LangChangeEvent } from '@ngx-translate/core';

@Component({
  selector: 'foo',
  templateUrl: 'foo.component.html'
})
export class FooComponent {
  public currentLang: string;

  constructor(private _changeDetectorRef: ChangeDetectorRef, public translate: TranslateService) {
    this.currentLang = translate.currentLang;

    translate.onLangChange.subscribe((event: LangChangeEvent) => {
      this.currentLang = event.lang;
      // TODO This as a workaround.
      this._changeDetectorRef.detectChanges();
    });
  }
}
```
This helped me working around a similar issue.

On the other hand, it would be helpful if you could provide a working example to reproduce your issue.
You can take the official StackBlitz example as a starting point: https://stackblitz.com/github/ngx-translate/example

**Comment by coingod** [comment]
I fixed the issue. It was actually related to this line:
`let allCountries = COUNTRIES;`
My _COUNTRIES_ list was being overwritten by the changes in _allCountries_, replacing all the Translation Keys with translated strings. So the next time it tried to read the keys, they were not there. Silly mistake.

Fixed via Deep Cloning of the array:
`let allCountries = JSON.parse(JSON.stringify(COUNTRIES));`
