### ISSUE TITLE
Function calls are not supported in decorators but 'TranslateModule' was called

### ISSUE THREAD

**Issue by wisespace-io** [ngx-translate/core#878]
## Current behavior
After migrate to Angular 6.0.8 and ngx-translate 10.0.2 I get the error: Function calls are not supported in decorators but 'TranslateModule' was called.

I am using ngx-translate in a library. The only way of build the library now is if I don't call TranslateModule.forRoot()

    @NgModule({
        imports: [
            BrowserModule,
            TranslateModule.forRoot() // Error happens here, need to remove the forRoot()
        ],
        bootstrap: [AppComponent]
    })
    export class AppModule { }

## Environment

ngx-translate version: 10.0.2
Angular version: 6.0.8
Node version: 10.5.0
ng-packagr: 2.4.2

**Comment by IhorShmidt** [comment]
Have the same issue, but I need to call "forRoot" method to use a loader, any ideas?

**Comment by wisespace-io** [comment]
It seems that it was caused by ng-packagr, I upgraded and now everything works fine.

**Comment by broweratcognitecdotcom** [comment]
I'm not using ng-packagr. I am still getting this error. Please reopen as ng-packagr is probably not the problem. I'm using "@ngx-translate/core": "10.0.2". I am calling forChild() since this is a lib.

**Comment by kwiesmueller** [comment]
Same here,
after the upgrade to Angular6 I get this error and really don't know why.

**Comment by rasmusvhansen** [comment]
Same here. I spent a few hours trying to solve with no luck...

**Comment by artemverbo** [comment]
+1 to @wisespace-io, I'm upgrading a codebase from Angular 5.x to 6.x and had this error until upgraded ng-packagr from 2.4 to 4.2

**Comment by BChoubey-git** [comment]
I have started to face this error, while migrating from angular 5 to angular 7. Any solution to this please?

**Comment by waseemdev** [comment]
I encountered the same issue and I solved it by moving `TranslateModule.forChild()` outside the `@NgModule`:
```js
export const translateModule = TranslateModule.forChild();
@NgModule({
  imports: [..., translateModule]
});
```

**Comment by rbalet** [comment]
A bit complex to say, but the error still happen in angular 10 library component that import another component that already had imported the `translateModule`.

The fix from @waseemdev seems to fix the problem, even if I'm not sure about the negative effect of exporting TranslateModule this way.

**Comment by telran** [comment]
@ocombe
This issue was not fixed. It is already available in the last versions (ng 10 + ngx-translate 13). Please reopen it.

**Comment by linnilsupak** [comment]
I found this problem too (ng 10 + ngx-translate 13)

**Comment by kruzaandrei** [comment]
Still nothing.. ng 11 + ngx-translate 13
