### ISSUE TITLE
how translate title route with ngx-translate

### ISSUE THREAD

**Issue by lordatef** [ngx-translate/core#894]
Hello, 
Angular 5,
"@ngx-translate/core": "^9.1.1"

Im asking how to translate route title in routingModule?
`
export const appRoutes: Routes = [
....
  {
  path: '',
  component: SampleComponent,
  children: [
  { path: 'Sample',
    component: InformationsComponent,
    data: { title: "{{'xxxx.yyyy.title' | translate}}" }

  }]
....,`

I try to inject TranslateService and using translate.get()... but doesnt works too
anyone has an idea about this please?

**Comment by adelloste** [comment]
Hi @lordatef 
you can use another approach to translate the title. In your route, you can set the key that you want to translate:
```
{
    path: '',
    component: SampleComponent,
    children: [
      { 
        path: 'Sample',
        component: InformationsComponent,
        data: { 
          title: "xxxx.yyyy.title"
        }
      }
    ]
  }
```
after, as you can see in the [angular doc](https://v5.angular.io/guide/set-document-title), you can inject the **Title** service into your component so you can translate the key and set the title. For example, in your component, you can do it:
```
public constructor(
    private titleService: Title,
    private route: ActivatedRoute,
    private translate: TranslateService
  ) {
    this.titleService.setTitle(
      translate.instant(this.route.snapshot.data['title']);
    );
}
```
Remember that **.instant** is synchronous, if your loader is async then you need to wait until the lang files have been loaded to get translations. If it's async, you can use **.get** which return an observable.

**Comment by wklq** [comment]
what is titleService?

**Comment by lordatef** [comment]
@adelloste it works! thak you for this solution

**Comment by sebastianmusial** [comment]
Here you can find simple package: https://github.com/ng-sm/title
