### ISSUE TITLE
ion-select option not translate

### ISSUE THREAD

**Issue by xuelabi123** [ngx-translate/core#896]
## Current behavior

when page loaded, the element dose'nt translate,it show like this "Select.Value"

## Expected behavior

it should be current selected

## How do you think that we should fix this?

I'm not sure it should be a bug or not,but I can't fingure out this problem now,if someone can help me?

## Environment

<pre><code>
ngx-translate version: X.Y.Z
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version Galaxy S5
- [ ] Chrome (iOS) version Iphone
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.0 
- Platform: mac 

Others:

</code></pre>
## Here my code
`<ion-select [(ngModel)]="show" (ionChange)="setView()" okText="确定" cancelText="取消">
			    <ion-option value="0">{{'Home.merge'|translate}}</ion-option>
			    <ion-option value="1">{{'Home.source'|translate}}</ion-option>
		    </ion-select>`
## result
![wx20180719-184736](https://user-images.githubusercontent.com/16874935/42938259-41fc179c-8b84-11e8-8ce1-9b7e7658545e.png)

**Comment by smallg** [comment]
@xuelabi123 how to fix it?
