### ISSUE TITLE
Is it possible to translate a translateParam value?

### ISSUE THREAD

**Issue by super-jb** [ngx-translate/core#899]
I haven't seen any examples. 

Imagine I have a form with some fields that are validated. All the form names and validations should be translated. My validation messages are very generic and only thing that changes is the name of the field being validated:

**en.json:**
  "authenticate": {
    "email": "Email",
    "password": "Password",
    "validations": {
      "required" : "{{value}} is required",
    }
  }

I want to inject a translatable value into "authenticate.validations.required" so I don't have to create a new "Required" message and translate it for each form field (there will be many across multiple forms).

So, in this case, I'd like to do something like:
{{ 'authenticate.validations.required' | translate:{ 'value' : **[insert translation here]** } }}

If this is possible, could you provide an example?
If not, shall I request it as a new feature?

Thanks in advance,
**JB**

**Comment by 1antares1** [comment]
I also try to do the same with a dynamic required message.

Example: _The field: '{{value}}' is required, in html._
But I already have the ID of the Field in Translations. Why retype it in HTML?

Maybe have the possibility, perhaps it is that I don't find i. Meanwhile, it's necessary to search for 2 times from the component.

**Comment by super-jb** [comment]
@1antares1, MUCHAS GRACIAS! THANK YOU SO MUCH!
Actually an easy solution but agree there should be something more straightforward then invoking the translation multiple times

**Comment by werad** [comment]
try this: 
<span [innerHTML]="'ID.KEY' | translate:{pramKey: paramValue}"></span>

**Comment by MonikaBozhinova** [comment]
You can use the TranslatePipe again to translate the translateParam value. In your case:
{{ 'authenticate.validations.required' | translate: { 'value' : 'authenticate.email' | translate } }}
