### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) URL: http://localhost:4200/assets/i18n/null.json

### ISSUE THREAD

**Issue by M-S** [ngx-translate/core#910]
`Failed to load resource: the server responded with a status of 404 (Not Found) URL: http://localhost:4200/assets/i18n/null.json
`
I am getting the above error each time on initial load after the default language file en.json is loaded.
It is trying to load null.json and returns a 404 status. What can be the reason to this?? 

<img width="287" alt="screen shot 2018-08-23 at 10 29 12" src="https://user-images.githubusercontent.com/13430853/44514071-664bad00-a6bf-11e8-8c93-66cb35eb9b92.png">

I use the following versions
```
"@ngx-translate/core": "^7.2.2",
 "@ngx-translate/http-loader": "^0.1.0",
"@angular/core": "^4.0.1",
```
This is my app.component.ts file
```
import { Component} from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import {ErrorLog} from './helpers/errorLog';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  constructor(private translate: TranslateService) {
    translate.setDefaultLang('en');
    translate.use('en');
  }


  switchLanguage(language: string) {
      this.translate.use(language);
  }

}
```

app.module.ts contains 

```
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateService } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
```

```
export function HttpLoaderFactory(http: Http) {
    return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

```

```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    .........,
    .........,
    TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: HttpLoaderFactory,
                deps: [Http]
            }
        }),
   
  ],
```

**Comment by M-S** [comment]
This issue no longer exists, there was a parsing issue in the component that tried to fetch the saved language settings, and returned null instead of string, that is why it tried to load null.json

**Comment by benag** [comment]
Did you solved this? i have the same thing
