### ISSUE TITLE
ng2 translate doesn't change options value inside multiselect checkbox list

### ISSUE THREAD

**Issue by usmanahmed061** [ngx-translate/core#915]
I am working on angular 2 application , cannot migrate it to angular 4>. In this application i am stuck at a point where i need to translate the option values inside a multi-select checkbox list. I have tried to use get method and also subscribed it to trigger on change but values doesn't get updated.

If i use translate pipe it show me blank area.

Multiselect plugin used is from bootstrap.

**Comment by usmanahmed061** [comment]
@ease below is the HTML and Typescript code

`<div class="col-md-6">
                                            <div class="multi-select-full" [class.padding-r0]="getCurrentLang == 'ar'" [dir]="getCurrentLang == 'ar' ? 'rtl' : 'ltr'">
                                                <span class="status-dd">
                                                    <select #statusFilter id="statusFilter" class="multiselect" multiple="multiple">
                                                        <option [value]="status.Id" *ngFor="let status of statusLookup">{{status.Name}}</option>
                                                    </select>
                                                </span>
                                            </div>
                                        </div>`

**OnInit** hook in Angular

` this.statusLookup = [];
            var lookup1 = new LookUp();
            var lookup2 = new LookUp();
            lookup1.Id = '0130002';
            lookup1.Name = 'Open';
            lookup1.IsChecked = true;
            lookup2.Id = '0130003';
            lookup2.Name = 'Closed';
            this.statusLookup.push(lookup1);
            this.statusLookup.push(lookup2);`

than **AfterViewInit** hook

`let allTranslatedVal = 'All';
        $(this.statusFilter.nativeElement).multiselect({
            numberDisplayed: 1,
            nonSelectedText: allTranslatedVal,
            allSelectedText: allTranslatedVal,
            selectAllNumber: false
        })
            .on('change', (e: any) => {
                this.statusFilterChanged();
            })
            .on('blur', (e: any) => {
                this.statusFilterChanged();
            });
        $('#statusFilter').multiselect('select', this.statusLookup[0].Id);`

Above is the all flow to bind values to Multiselect, Now what i am trying is to change the values that are pushed in **statusLookup** to what the language is selected for user.

For that i have made an Observable which listen to language change.

` this.userProfileService.getLangObservable.subscribe(
                val => {
                   
                    this.translate.get('Open').subscribe(
                        val => {
                            thisRef.statusLookup.find(x => x.Id == '0130002').Name = val;
                        }
                    )

                    this.translate.get('Closed').subscribe(
                        val => {
                            thisRef.statusLookup.find(x => x.Id == '0130003').Name = val;
                            this.configureStatusDD(); // This function is same as code written in **AfterViewInit**
                        }
                    )
                })`

I hope this helps you to understand my issue.

Thanks

**Comment by usmanahmed061** [comment]
Sorry my bad , Issue was because of Multiselect not because of ng2 translate. 

Thanks

**Comment by ease** [comment]
Good, great to hear that.
