### ISSUE TITLE
How can I translate input data of Angularfire2 Firestore ? ngx-translate

### ISSUE THREAD

**Issue by Omar-Qalei** [ngx-translate/core#931]
get title of  Firestore I wanna translate title such as {{'item.title' | translate}}

`<div>{{item.title}}</div>
`

**Comment by Mr-Eluzive** [comment]
I've already answered here:  
https://stackoverflow.com/questions/52595659/how-can-i-translate-text-input-in-angularfire2-firestore-use-ngx-translate/52596303#52596303

But also like I've mentioned, I had created a repo here:
https://github.com/Mr-Eluzive/angularfire-ngx-translate-example 

So if nobody has nothing against it, maybe we should add this piece of information to `ngx-translate`? `firestore-example`, like `ionic-example`. Or maybe I should create PR with `FIRESTORE_EXAMPLE.md` like it has been done with `FIREBASE_EXAMPLE.md`.  
What do you think guys?
