### ISSUE TITLE
ngx-translate in *ngfor not working

### ISSUE THREAD

**Issue by adeojoemmanuel** [ngx-translate/core#938]
I have this code
`        <div *ngFor="let service of services">`
`
              <span><img  [src]="service.imgPath" alt="{{ service.name }}"/></span>`
              `<h4>{{ service.name}}</h4>`
              `<p>{{ service.desc }}</p> 
`   </div>`
         

How can I do translation of each service that have 3 parameters

In regular case I use {{ 'something' | translate  }} , where "something" is placed in .json file

    "something" : "translation"

So how can a use it in state of ngFor? It read me an object from .json, but not array of objects that what I need in my case
## Environment

<pre><code>
ngx-translate version: 10.0.2
Angular version: 4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by Mr-Eluzive** [comment]
Why can't you use it in this way:  
```html
<div *ngFor="let service of services">
  <span><img [src]="service.imgPath" alt="{{ service.name }}"/></span>
  <h4>{{ service.name | translate}}</h4>
  <p>{{ service.desc | translate}}</p>
</div>
```
It should be done like this so what's the problem?

**Comment by adeojoemmanuel** [comment]
i got an issue stating that translate cant take in object

**Comment by Mr-Eluzive** [comment]
Ok, could you share with my some bigger part of the code please? Maybe on stackblitz. Because I don't even know what is under the `service` properties etc.

**Comment by hijoncon** [comment]
You can compose in your component example

list = ['ROOT.LEVEL', 'ROOT.LEVEL', 'ROOT.LEVEL']

ng iterate that in your ngFor

**Comment by kumaresan-subramani** [comment]
i am also having the same problem any solution available?

https://github.com/ngx-translate/core/issues/1011

**Comment by swapnilvaidankar** [comment]
Same problem I'm facing. Tried using i18n attribute however whole problem stuck when we comes to ngFor loop. Internationalization works better when texts are static.  Any solution you guys found it?
