### ISSUE TITLE
How can I translate array use Firestore ?

### ISSUE THREAD

**Issue by Omar-Qalei** [ngx-translate/core#940]
https://scontent.famm6-1.fna.fbcdn.net/v/t1.0-9/43408566_745185042485132_7887417855229034496_o.jpg?_nc_cat=103&oh=4e170024ef5d08e10d566f0540ff2051&oe=5C1D3034

**Ts**
```
links = [
    { path: 'Home', label: 'Home' },
    { path: 'Rent', label: 'For Rent' },
    { path: 'Sale', label: 'For Sale' },
    { path: 'AddAds', label: 'Add Ads' },
    { path: 'contactUs', label: 'Contact us' },
    {path: 'Messages' , label: 'Messages'},
    { path: 'About', label: 'About Us' },
  ];
```
**HTML5**
```
<span *ngFor="let link of links;let i=index;">
 <a mat-tab-link [routerLink]="link.path" routerLinkActive #rla="routerLinkActive" [active]="rla.isActive">
  <span translate>links.label</span></a>
 </span>
```

Output: 

`objectObject`

**Comment by Mr-Eluzive** [comment]
Firestore is not for translate anything.  
If you still use my solution for translations then it's not for this use case. Why can't you just define translations in language document? For what purpose is this array?

**Comment by Mr-Eluzive** [comment]
Yeah like I said. But also I have asked why did you define this in that way??  
If you put these labels just into `translates` collection then it should works just fine.  
If you really, really want to put these into array to keep things clear in your database you have to modify my solution or extends `translate` pipe / service / directive. But if I can I would advice you just use some namespace pattern like this:  
![zrzut ekranu 2018-10-08 o 15 04 51](https://user-images.githubusercontent.com/9000139/46610639-92a27800-cb0b-11e8-964a-5abdcdafc801.png)

**Comment by Omar-Qalei** [comment]
How can I show that in HTML5 ?

**Comment by Mr-Eluzive** [comment]
Replace string values in your `links ` array will be enough.  
```ts
const links = [
    { path: 'Home', label: 'LINKS_NAV.HOME' },
    { path: 'Rent', label: 'LINKS_NAV.FOR_RENT' },
    { path: 'Sale', label: 'LINKS_NAV.FOR_SALE' },
    // etc.
  ];
```
