### ISSUE TITLE
When passing a parameter through interpolation in a retrieved translation from a resource file translation fails

### ISSUE THREAD

**Issue by Pieter-1337** [ngx-translate/core#943]
## Current behavior
in .resx file:
key = text1 , value = `'<p>hi {{firstName}}</p>'`

in TS file 1:
```
Class X 
{
 firstName: string;
}
```

```
Class Y{
firstName: string = 'John Doe';

Get the translation => this.translationService.Get( ['text1'], { firstName = this.firstName} );

Insert the translation in an object of class X
.....
{
 firstName: translations['text1'];
}

}
```

in HTML file
`<div [innerHTML="X?.firstName"]></div>`

Output: Hi {{firstName}}

## Expected behavior
Output: Hi John Doe

## How do you think that we should fix this?
Handlebars parameter should get converted to it's value?

**Comment by Mr-Eluzive** [comment]
Can you share some stackblitz snippet? Because to be honest I don't really understand neither your code nor problem. For me interpolation works just fine. You can checkout my example on stackblitz right [here](https://stackblitz.com/github/Mr-Eluzive/ngx-translate-interpolation-example)
