### ISSUE TITLE
ERROR 404 trying to load the translations in Angular 6 and NS 4.2

### ISSUE THREAD

**Issue by hackerunet** [ngx-translate/core#947]
Sorry to reopen this, I'm using angular 6 and I have this issue, this is the output error, also if I change the json files url to something like './json/ I receive a no protocol error.
```
"@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
```

```
JS:   "name": "HttpErrorResponse",
JS:   "message": "Http failure response for (unknown url): 0 Unknown Error",
JS:   "error": {
JS:     "originalStack": "Error: java.net.MalformedURLException: no protocol: ./i18n/pt.json\n 
```

```
Successfully synced application com.domain.mob on device emulator-5554.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR {
JS:   "headers": {
JS:     "normalizedNames": {},
JS:     "lazyUpdate": null,
JS:     "headers": {}
JS:   },
JS:   "status": 404,
JS:   "statusText": "ERROR",
JS:   "url": "/data/data/com.domain.mob/files/app/i18n/pt.json",
JS:   "ok": false,
JS:   "name": "HttpErrorResponse",
JS:   "message": "Http failure response for /data/data/com.domain.mob/files/app/i18n/pt.json: 404 ERROR",
JS:   "error": "Not Found"
JS: }
JS: ERROR {
JS:   "headers": {
JS:     "normalizedNames": {},
JS:     "lazyUpdate": null,
JS:     "headers": {}
JS:   },
JS:   "status": 404,
JS:   "statusText": "ERROR",
JS:   "url": "/data/data/com.domain.mob/files/app/i18n/pt.json",
JS:   "ok": false,
JS:   "name": "HttpErrorResponse",
JS:   "message": "Http failure response for /data/data/com.domain.mob/files/app/i18n/pt.json: 404 ERROR",
JS:   "error": "Not Found"
JS: }
```
My NS project doesn't have the structure sugested to place something in assets, I don't have that folder and If I place my json files in /app/i18n I get this error, or in /i18n/ I also got this error, my NS version is 4.2 and rxjs is also 6
this is my app.module.ts
```
import { NgModule, NgModuleFactoryLoader, NO_ERRORS_SCHEMA } from "@angular/core";
import {BrowserModule} from '@angular/platform-browser';
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { NativeScriptUISideDrawerModule } from "nativescript-ui-sidedrawer/angular";
import { NativeScriptHttpClientModule } from "nativescript-angular/http-client";
import { NativeScriptFormsModule } from "nativescript-angular/forms";
import { HttpClientModule, HttpClient, HTTP_INTERCEPTORS } from "@angular/common/http";
import { AuthenticationInterceptor } from "./shared/interceptors/authentication.interceptor";
import {TranslateModule, TranslateLoader} from '@ngx-translate/core';
import {TranslateHttpLoader} from '@ngx-translate/http-loader';

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

import { LoginComponent } from "./login/login.component";
import { MenuComponent } from "./menu/menu.component";

import { UtilsService } from "~/shared/services/utils.service";
import { APIService } from "~/core/api.service";
import { Configuration } from "~/core/configuration";
// AoT requires an exported function for factories
export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(http, "/i18n/", ".json");
}
// Maps
@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        AppRoutingModule,
        BrowserModule,
        HttpClientModule,
        NativeScriptModule,
        NativeScriptFormsModule,
        NativeScriptUISideDrawerModule,
        NativeScriptHttpClientModule,
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: HttpLoaderFactory,
                deps: [HttpClient]
            }
        })
    ],
    declarations: [
        AppComponent, LoginComponent, MenuComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ],
    providers: [UtilsService, Configuration, APIService, {
        provide: HTTP_INTERCEPTORS,
        useClass: AuthenticationInterceptor,
        multi: true
    }]
})
export class AppModule { }
```
I'm a desperate man!!  
this is my tsconfig.json file:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "app/*"
            ],
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

**Comment by hackerunet** [comment]
Simple solution, webpack copy:
```
new CopyWebpackPlugin([
                {
                    from: 'app/i18n',
                    to: `${dist}/i18n`,
                    context: projectRoot
                },
            ]),
```

**Comment by weijyewang** [comment]
@hackerunet did it work after `tns build` with `--bundle --env.uglify --env.aot `. Mine is not working for android (i did not test on IOS), the text printed out in the UI is the variables instead of the value of the variables as defined in the json.

**Comment by alereisan** [comment]
@weijyewang same here..

**Comment by alereisan** [comment]
I got it working following this inputs:
https://discourse.nativescript.org/t/ngx-translate-nativescript-angular-application/4096/7

**Comment by anmolkrai** [comment]
This really worked for me. This is how we can keep our json files in customize path as follows-
 **return new TranslateHttpLoader(http, "src/_ui/custom/my-app/dist/assets/i18n/",  ".json");**

And in angular.json file we can ask compiler to check assets for our custom path as well-

 "assets": [
              "src/favicon.ico",
              "src/assets",
              **"src/_ui/custom/my-app/dist/assets"**
            ],

Thanks Bro **Alessandro Santamaria ** and **hackerunet** for sharing.

**Comment by parthdevloper** [comment]
> This really worked for me. This is how we can keep our json files in customize path as follows-
> **return new TranslateHttpLoader(http, "src/_ui/custom/my-app/dist/assets/i18n/", ".json");**
> 
> And in angular.json file we can ask compiler to check assets for our custom path as well-
> 
> "assets": [
> "src/favicon.ico",
> "src/assets",
> **"src/_ui/custom/my-app/dist/assets"**
> ],
> 
> Thanks Bro **Alessandro Santamaria** and **hackerunet** for sharing.
Thank You @anmolkrai , Your solution worked for me : -


![image](https://user-images.githubusercontent.com/58413215/79205842-1903ec80-7e5c-11ea-810c-ab81a255277a.png)


With **your solution I added my asset pathj to `angular.json`**
 Like this: 
![image](https://user-images.githubusercontent.com/58413215/79206033-61230f00-7e5c-11ea-8002-9de4b667807a.png)


Now Working absolutely fine. Thanks..
~ Cheers

**Comment by gayatri-kadam** [comment]
I am using Angular 13 and getting the same error mentioned by @hackerunet. When I was using Nativescript 6 it worked fine but when I migrated my project to Nativescript 8 I got this error. I don't have an asset folder in my project, the i18n folder is placed inside "app" folder. Also, in NS8 the webpack 5 is used so I had to add this:

webpack.Utils.addCopyRule(
		{
            from:'src/app/i18n',
            to : 'C:/Users/gkadam/Documents/myproject/src/app/i18n',
            context : projectRoot
        }
    )

Am I missing anything?

**Comment by pap5508** [comment]
@gayatri-kadam : 
add translation file en.json or any other languge translation file in 
`app/assets/i18n` 

webpack.config.js 
add following : 
`webpack.Utils.addCopyRule("assets/i18n/*");`

set Default language in App.component.ts : 
`this.translate.setDefaultLang("en");`

you can iniatialize Translate loader in App.module.ts 
`// for AoT compilation
export function translateLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, "/assets/i18n/", ".json");
}

imports: [
TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (translateLoaderFactory),
        deps: [HttpClient]
      }
    })]
`

`ns clean` and rerun the project.
