### ISSUE TITLE
Ngx translate with shared/lazy loading modules

### ISSUE THREAD

**Issue by Ruud-cb** [ngx-translate/core#966]
I have tried leaving a question open on [stackoverflow](https://stackoverflow.com/questions/53413612/ngx-translate-with-shared-lazy-loading-modules) but unfortunately no answer so far.

I do not call it a bug yet, I am not sure if this is by design or not.

Probably one of the most common questions, while the [documentation][1] and some [other questions][2] I found try to clear up things for me, yet I am still not sure how to fix this.

So this is my structure:

[![enter image description here][3]][3]

- App module is of course the main module that is bootstrapped
- Countryselector module: takes care of loading the default country(based on IP) and takes care of deciding what language to use based on the browser. It basically is the core functionality of deciding what country/language is used + it contains a dropdown for a user to change the country/language. 
- Checkout module, selection module, payment module are all lazy-loaded with routing.

**AppModule**

    export function HttpLoaderFactory(http: HttpClient) {
      return new TranslateHttpLoader(http);
    }
    
    @NgModule({
      declarations: [
        AppComponent
      ],
      imports: [
        HttpClientModule,
        BrowserModule,
        AppRoutingModule,
        ContrySelectorModule,
        TranslateModule.forRoot({
          loader: {
            provide: TranslateLoader,
            useFactory: HttpLoaderFactory,
            deps: [HttpClient]
          }
        })
      ],
      export class AppModule { }

**CountrySelectorModule**

    @NgModule({
      declarations: [CountryselectorComponent],
      imports: [
        CommonModule,
        TranslateModule.forRoot({
          loader: {
            provide: TranslateLoader,
            useFactory: HttpLoaderFactory,
            deps: [HttpClient]
          }
        })
      ],
      exports: [
        CountryselectorComponent
      ]
    })
    export class ContrySelectorModule { }

**Selection module:**

    @NgModule({
      declarations: [SelectionComponent],
      imports: [
        CommonModule,
        SelectionRoutingModule,
        UspblockModule,
        TranslateModule.forChild({//or forRoot, no idea how to configure this
          loader: {
            provide: TranslateLoader,
            useFactory: HttpLoaderFactory,
            deps: [HttpClient]
          }})
      ],
    })
    export class SelectionModule { }

Now the problem is that I don't want to do the language configuration again within the lazy-loaded modules, because the country selector module already takes care of this. I am not sure now how to correctly configure the lazy-loaded modules (and actually not sure if countrySelectorModule is done correctly). Using the [standard github documentation][1] I was not able to pull this off. I've tried messing around with `.forChild()` but no luck so far.

Do I need a share module? Do I need to import countrySelectorModule everywhere (not preferred)? Custom loader? t.b.h. I have no idea and the documentation is a bit short for more advanced scenarios.

  [1]: https://github.com/ngx-translate/core#1-import-the-translatemodule
  [2]: https://stackoverflow.com/questions/50992232/ngx-translate-not-showing-any-text-in-lazy-loaded-module
  [3]: https://i.stack.imgur.com/M8aN9.png

**Comment by luiscla27** [comment]
It is an issue,

A couple of days ago i've faced the same issue for another Angular Library ([igniteui](https://github.com/IgniteUI/igniteui-angular/issues/3026)), 

The problem can be solved by removing the `forRoot()` implementation and using the recently introduced `providedIn `property of the `@Injectable` decorator, in short `TranslateModule.forRoot()` will be deprecated.

This would be breaking-change so it requires someone to dedicate at least a full day to migrate the implementation, this is what the [Angular 6 documentation](https://angular.io/guide/singleton-services) says:

> Beginning with Angular 6.0, the preferred way to create a singleton services is to specify on the service that it should be provided in the application root. This is done by setting providedIn to root on the service's @Injectable decorator:

**Comment by luiscla27** [comment]
this issue is duplicated [here ](https://github.com/ngx-translate/core/issues/425)

**Comment by Ruud-cb** [comment]
Closed since [this solution](https://stackoverflow.com/a/53483123/2901207) solved my issue, credits go to one of the [replies](https://github.com/ngx-translate/core/issues/425#issuecomment-467418951) in the issue that @luiscla27 mentioned.
