### ISSUE TITLE
Translate Partial Loader?

### ISSUE THREAD

**Issue by datazen** [ngx-translate/core#977]
I have an older AngularJS project that uses the older ng-translate that I am updating to newer Angular 7 using ngx-translate however I do not see clearly where I can accomplish the same with the newer version.

Our app loads venue types on login.   I need to be able to load language translations depending on venue type and also load the common core defines.   With ng-translate in the AngularJs 1.x app.js, I used:

```
    $translateProvider.useLoader('$translatePartialLoader', {
        urlTemplate: 'translate/{part}/{lang}.json'
    });

    $translatePartialLoaderProvider.addPart('venue/all');

    $translateProvider.preferredLanguage('en');
    $translateProvider.useSanitizeValueStrategy('escape');
```
I could insert the type through interpolation and this would load the corresponding defines.

How to accomplish this with the newer ngx-translate?  I tried nesting the defines and accessing via interpolation but since is text, all I get is the raw variable text and not the define.

For example I cannot
```
var type = 'restaurant';
<div>Role: {{ 'type.role' | translate }}</div>
```
as this outputs type.role as text instead of the define.

Do I need to use a Custom Loader or a plugin like ngx-translate-multi-http-loader ?  Can you possibly provide an example?

Thanks in advance and thanks for the great product.

**Comment by datazen** [comment]
I have solved the issue.  ty.

**Comment by nfgaetest** [comment]
I have the same issue.
How did you solve this?

**Comment by voverc-providers** [comment]
i also have the issue, could you provide the solution?

**Comment by datazen** [comment]
Solved by:

var type = 'restaurant';
<div>Role: {{ type + '.role' | translate }}</div>
