### ISSUE TITLE
Can not able to use translate pipe in component

### ISSUE THREAD

**Issue by nachiketsalvi** [ngx-translate/core#987]
I am using localisation for my project. I that i have header component which takes name of header as input and display it as application header.I am wanted to translate header.
 
I have imported  translate module in app.module.ts and set default language in app.component.ts
I have json file is i18n folder.

Here is code 
--Code inside page --
label: string= 'HOME'
<header-component [name]="label"></header-component>

--code inside header component--
@input name = '';
<ion-header>
<button><span>{{ 'label' | translate }}</span></button></ion-header>

**Comment by nevadascout** [comment]
Are you getting an error message? What happens when you serve app and view it in a webpage?

**Comment by nachiketsalvi** [comment]
When i serve the app it shows error: pipe translate could not be found in header component.

**Comment by EnricoVogt** [comment]
Is your header-component of a shared-module or its located in the app-module?

**Comment by nachiketsalvi** [comment]
yes

**Comment by nachiketsalvi** [comment]
Found Solution so closing this issue.
Solution is get translation for word in side constructor and the passed it to the component.

code(public translation: TranslationService){
this.translatin.get(['word']).subscribe(translation=>{

this.translatedWord =  translation.word
})
}
