### ISSUE TITLE
Contents in [innerHTML]  over writing existing inner content 

### ISSUE THREAD

**Issue by eldhotkuriakose** [ngx-translate/core#994]
## Current behaviour
```//"foo":"<span>this is my translation </span>"```
```<div class='myclass'  [innerHTML]=''`foo` | translate''>  <b>this is my existing content</b> </div>```

results : this is my translation

## Expected behaviour

results : this is my translation this is my existing content

**Comment by djleonskennedy** [comment]
@eldhotkuriakose Dude! are you seriously ?! :) Learn angular first
